### PR TITLE
qPrefFacebook, ready

### PR DESCRIPTION
**Pull request by janiversen**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ x] Code cleanup
- [ ] Builds system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

next in the qPref series

Second commit is correcting a name in qml
Rest is qPrefFacebook
removed SAVE_FACEBOOK_CREDENTIALS

### CODE REVIEW

**Comment by janiversen** [comment]
@dirkhh thi is right now low priority due to the qPrefCloudStorage problem, but can you please point me where the facebook settings are stored and loaded ? it does not happen in SettingsObjectWrapper nor can I find it in desktop-widgets/plugins/facebook. Thanks in advance for a code pointer.

**Comment by dirkhh** [comment]
I think this is a trick question :-)
We decided very intentionally to NOT persistently store the FB credentials because of fear of other apps being able to abuse them for spamming purposes - and Subsurface getting blamed for that.
So we use the settings in memory (and that's in `desktop-widgets/plugins/facebook/facebookconnectwidget.cpp`), but we don't store this to disk.
Is that what you are asking about, or am I misunderstanding your question?

**Comment by dirkhh** [comment]
Yes, I'm ok with removing this. The code was written and then simply commented out at first when we decided to not save to disk after all.

**Comment by dirkhh** [comment]
The intro message for the PR doesn't seem to be correct anymore. No biggie.
The commits add the `SAVE_FACEBOOK_CREDENTIALS` handling and then remove it again. One could easily reduce the commit count and simplify this series by refactoring things so that this never gets added in the first place.
I don't want to bog you down with mechanics like this - would you like me to do the refactoring for you?
Other than this, this looks ok

**Comment by janiversen** [comment]
Reduced the commits, hope travis is ok with the changes,

btw every day is DM day until september 2nd, but some days are more fun than others.

**Comment by dirkhh** [comment]
Thanks for updating. Travis is happy, I am happy.

**Pull request merged**
