### PR TITLE
Dive picture handling: Re enable multi select, improve mouse events

### LINKED ISSUE #368: Add pictures to dive feature issues - Context menue and mouse events
Tested the really nice "picture" feature for the first time and stumbled across a couple of issues and bugs. I'm briefly going to list them here now also as a reminder for me. I can provide more details on request. I will also try to fix some of the items but with my limited experience... well you know...
- Mouse actions are pretty fragile mainly under Windows. E.g. the context menue doesn't open reliably on right-click into the picture "box". On Linux this works better. Also it is not 100% clear what actions should happen on different mouse actions. E.g. double-right-click does open a picture (as well as double-left-click). This doesn't feel correct.
- Selecting single/multiple pictures doesn't work.
- Right-click on a picture in profiles opens the picture (as well as left-click). This doesn't feel correct.
- In the context menu which opens under Linux and sometimes under Windows for right-click in the picture box, none of the four menu entries does work. This is also the case under Linux.

### PR DESCRIPTION
**Pull request by sfuchs79**
### Describe the pull request:

- [x] Bug fix
- [x] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Some improvements for the dive picture tab and dive pictures in profile:
- Bugfix mouse event in profile: Only Left-click will open picture
- Bugfix mouse events in picture tab:
  - Re-enable context menu (Windows bug mainly)
  - Re-enable multi select
  - Only double-left-click will open picture

Smaller size for pixmap of picture during drag&drop.

### Related issues:

Closes #368

### CODE REVIEW

**Comment by sfuchs79** [comment]
I forgot to mention:
I'm also still unhappy with the (standard?!) multi select behavior of the QListView used for the pictures. Honestly it sucks.
I would like to have the kind of standard behavior where selecting a different item w/o pressing control deselects the old selected items and where I have to hold ctrl or shift do do an multi select. And if I click into an empty space all items should be deselected. In fact our dive list table has this selection mode.
Any Qt genius can fix this? @tcanabrava

**Comment by sfuchs79** [comment]
@tcanabrava 
Fixed the selection mode thing - man, that was much easier than expected...
Will push another commit.

**Comment by sfuchs79** [comment]
Ok, the Alt modifier is a bad idea for Linux. Because there Alt+left-click is catched by the window manager to move the application window...

**Comment by atdotde** [comment]
Stupid question: What can I do with multiple selected images? Can I drag and drop more than one at once or delete those?

**Comment by sfuchs79** [comment]
Found a way to make this work really nicely w/o the Alt key modifier.
Tested it on Windows and Linux. Maybe a test on MacOS would be nice. @atdotde could you quickly test this please?

**Comment by atdotde** [comment]
What am I supposed to look at? Selection works (with multiple images), double click works (but opens only picture under pointer), so does drag&drop.

**Comment by sfuchs79** [comment]
Drag&drop: Only one at a time
Delete: All selected

Did you test already with the fix?

W/o the fix under Windows this didn't work well. Context menu didn't open. Multi select didn't work correctly...

**Comment by sfuchs79** [comment]
I have one additional idea here: Would it be nicer to have the pixmap for drag&drop much smaller, same size as the resulting, non-zoomed pixmaps in the profile? Would be maybe more intuitive then, that one can drop them only there... I'll show you how I think it could look like later...

**Review by dirkhh — APPROVED** [review]
This looks reasonable, but I haven't tested it. IF we want this in 4.7.5 then we should merge today and ask for testing on the mailing list...
I know that @sfuchs79 would really like this in 4.7.5 - any other opinions?

**Comment by atdotde** [comment]
Looks good.

**Pull request merged**
