### PR TITLE
iOS: BLE fixes

### PR DESCRIPTION
**Pull request by mfbernardes**
### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Fix BLE on iOS.

### Changes made:

1) Save BT DeviceInfo for all devices discovered
2) Check for UUID in order to enable bluetooth_mode (even though only bluetooth is supported I kept a check).

### Mentions:

@dirkhh

### CODE REVIEW

**Review by mturkia — APPROVED** [review]
LGTM (assuming it works :D)

**Comment by mfbernardes** [comment]
I tested on iOS 11.1.2 with a Perdix AI.

Even though the code should not affect other platforms, I checked it doesn't break anything on MacOS.

I don't have access to Windows or Android.

**Comment by dirkhh** [comment]
This looks excellent. Thank you @mfbernardes 
Welcome to being a Subsurface developer!
If there is any way I can bribe you into helping me with overall iOS development...
The GPS code. I know this should work. I never got it to work and gave up. But I'm sure I just did something stupid... please?

**Comment by mfbernardes** [comment]
I intend to get more active on the development. Help with iOS is something I can do.

I just sent a PR for the GPS code as well.

**Comment by dirkhh** [comment]
I cannot tell you how happy I am to hear about both of these statements.
Projects like this live and breath by the developers they can attract. Almost all of the developers are predominantly working on Linux. We have one other active Mac developer (@atdotde) and no one else who works on iOS - so that has been all me... and as the main maintainer, I have way too many other things I need to work on, so iOS has always been the step child :-(

Thank you so much.

**Comment by mturkia** [comment]
Great, I think this works for me. At least I got some communication going between iPhone and Perdix AI. Too bad there are no new dives to download.

What is problematic is that the dropdown list only shows the LE:{UUID} and no real information about what might be the DC and what might be something else. Any chance to get something more informational there? (There is something in parentheses, but I only see the opening '(', nothing from the content)

**Comment by mfbernardes** [comment]
I’m working on a new ConnectionListModel that will allow us to display a Name while keeping track of the actual data.

This will make things more user friendly.

—
Murillo

**Comment by dirkhh** [comment]
Yes, I noticed that in testing. And I noticed that I get the three vendors (Suunto, Shearwater, Scubapro), but only for Shearwater I get dive computer models. And of course we are also missing the OSTC models that are BLE. The latter is an omission. The former I'm staring at the code to understand...

**Pull request merged**
