### PR TITLE
[snap] add removable-media plug

### PR DESCRIPTION
**Pull request by Saviq**
### Describe the pull request:
- [x] Build system change

### Pull request long description:
This optionally allows accessing data in /media/ folders, if the user
issues:

snap connect subsurface:removable-media

https://docs.snapcraft.io/removable-media-interface
### Changes made:
1) add `removable-media` as a snap plug

### Release note:
With the snap, you can now use locations in `/media`, `/mnt` and `/run/media` for your dive logs, provided you issue `snap connect subsurface:removable-media` to allow this, first.

### Documentation change:
With the snap, use `snap connect subsurface:removable-media` to allow access to locations in `/media`, `/mnt` and `/run/media`.

### CODE REVIEW

**Comment by bstoeger** [comment]
I'm not even exactly sure what snap is (a software distribution method?). But would this warant a CHANGELOG.md entry?

**Comment by Saviq** [comment]
Hi @bstoeger yes it's a package format: https://snapcraft.io/

I've now added a `CHANGELOG.md` entry.

**Comment by bstoeger** [comment]
> I've now added a CHANGELOG.md entry.

Thanks. But it seems that you haven't pushed your changes. :)

**Comment by Saviq** [comment]
> Thanks. But it seems that you haven't pushed your changes. :)

D'uh, fixed now :)

**Comment by bstoeger** [comment]
Good, let's commit. Not sure if this part:
> snap connect subsurface:removable-media

Warrants a documentation change?

**Comment by Saviq** [comment]
There's unfortunately zero mention of the snap in any current documentation or website, I know @dirkhh  wanted to find some time to have a play with it. In any case, I left what changes could be made to documentation and release notes in the description above.

**Pull request merged**
