### PR TITLE
Configure DC dialog: Change order of DCs and correct names

### PR DESCRIPTION
**Pull request by sfuchs79**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

In the configure dive computer dialog change the order of the DCs
(all HW first, then Suunto) and correct the names of some HW DCs
(make them the same as in the "download from DC selection list").

### CODE REVIEW

**Comment by sfuchs79** [comment]
Ups, that's more tricky to change than I expected... still working on it.

**Comment by sfuchs79** [comment]
Now it should work. Tested it with my old OSTC 2N.
Plus found some more small items to fix (translations, button update).

There is one question open on my side: The "OSTC Plus" is not listed in configure DC dialog. Is it really NOT supported or is it supported and we should add it? If we can add it, which category - OSTC 2/3 or OSTC 4?

**Comment by glance-** [comment]
As far as I've can guess, OSTC Plus is based on the ostc3-platform, not the ostc4-platform.

**Comment by sfuchs79** [comment]
Added the "OSTC Plus" to the list of supported DCs for configuration. This is just a UI text update, no functional update and it is untested.

**Review by neolit123 — APPROVED** [review]

**Comment by atdotde** [comment]
Looks good.

**Pull request merged**
