### PR TITLE
Add ATM pressure, altitude and SAC values to diveplan

### PR DESCRIPTION
**Pull request by sfuchs79**
Print the altitude used for calculation into the resulting diveplan.
There is one drawback in this implementation: Altitude will be recalculated from surface pressure and therefore may differ slightly from altitude entered in the UI.

Signed-off-by: Stefan Fuchs <sfuchs@gmx.de>

### CODE REVIEW

**Comment by sfuchs79** [comment]
Hi All,

this is a proposal for discussion from my side. I'm not sure if you like it or not, please tell me!
I'm also not sure if its good procedure to put the German translation into the pull request or if this should be handled seperately.

**Comment by atdotde** [comment]
I like the idea, but I also have a few comments:

You don't need the if, have a look at how get_depth_units() works (it provides you both with a number as well as a unit symbol to print).

Then, I would rather print the surface pressure (since that is the primary datum) and provide the (derived) altitude in parenthesis behind or with a slash (like we report the gas usage both as a volume and as a pressure difference).

Finally, please print this information below the actual dive plan, not above: The user will not use this information while planning (as that is visible from another place in the UI). The top lines are very precious in the dive plan as those are visible while planning (so the user sees consequences of changing parameters, waypoints etc).

**Comment by sfuchs79** [comment]
Hallo Robert! Thanks for the feedback. I agree with all your comments. I will work on this during the next days - I still need a long time for a few code lines plus testing ;-) 

Shall we maybe then even move the info about used algorithm (VPM-B, Bühlmann, etc.) below the runtime table? Only keep overall runtime at the top?

Also I plan to do an update to print input SAC values to the diveplan in a lean way like:
"Gas consumption (based on SAC 18l/min, 15l/min):"
What do you think about this?

Last item: Ok or not ok to submit the German translation with the pull request?

**Comment by atdotde** [comment]
I agree with also moving the model information on the bottom as well as adding the SAC rates. 

The translations are handled differently, though: Leave them for the moment. At some point, @dirkhh will upload all strings to Transiflex ( https://www.transifex.com , you might want to click an account there as well as ask to join language teams, maybe de_schwaebisch ) and then all translators work on all new strings at once.

**Comment by sfuchs79** [comment]
Updated as discussed for next review.
I'm not ready with testing yet but it would be great to already hear your feedback.
Please also tell me if the pull request itself with the two commits and changing forth and back the language file is ok or if I need to do this in a cleaner way!

**Comment by dirkhh** [comment]
So you change some translations and then remove that... of course the cleaner way would be to never change things in the first place, right?
So now we get into rewriting history. FUN. That's advanced git.
I can try to walk you through it - or I can just clean it up here when I apply your commits. Your call.
The second commit moves quite a bit of code around which makes it a bit harder to see what is actually being changed. Can you explain that a bit better?

**Comment by atdotde** [comment]
Besides Dirk's points this looks good to me. And the rewriting history part isn't that hard. 

git rebase -i

is what you want. With

git help rebase

you can learn about it (scroll to the "INTERACTIVE MODE" section).

**Comment by sfuchs79** [comment]
Hallo Dirk, hallo Robert,

about cleaning the pull request with "git rebase":
I'll sure will learn this as well but I'm still so slow... ;-) Maybe
this time Dirk can fix it?

Concerning translations:
This will bring some new/changed strings.

About status of the change:
I now checked it in windows build as well and found no issue. But you
still please need to review very carefully what comes from my side! :-)

About explaining the change:
I added the ATM pressure info and moved also the deco model info below
the runtime table. This is why so much is moved around. It's best to
look at the example below to see the change.

OLD output:

Subsurface Plan
basierend auf VPM-B bei +2 Konservatismus, effektive GF=21/66

Runtime: 44min

[...table...]
 
CND: 6%
OTU: 18


Gasverbrauch:
1989ℓ/121bar Luft (875ℓ/54bar im berechneten Aufstieg)


*NEW output:*

Subsurface Plan

Runtime: 44min

	
[...table...]


CND: 6%
OTU: 18


Deco model: VPM-B at +2 conservatism, effektive GF=21/66

ATM pressure: 1013mbar (0m)


Gasverbrauch:
1989ℓ/121bar Luft (875ℓ/54bar im berechneten Aufstieg)

**Comment by sfuchs79** [comment]
Rebase done.

I'm also now working on printing the SAC values to the diveplan in this way:
"Gas consumption (based on SAC 18|15l/min):"

I have the feeling I need to add this as a second commit to this branch/pull request. Otherwise there will be easily a merge conflict (it's same file and even very close lines). Is my understanding correct?

And one question mainly to Robert: Shall we print SAC values also for CCR mode? At the moment I only added it for OC and PSCR:
if (dive->dc.divemode == CCR)
		snprintf(temp, sz_temp, "%s", translate("gettextFromC", "Gas consumption (CCR legs excluded):"));
	else
		snprintf(temp, sz_temp, "%s %.*f|%.*f%s/min):", translate("gettextFromC", "Gas consumption (based on SAC"),
			sacdecimals, bottomsacvalue, sacdecimals, decosacvalue, sacunit);

**Comment by dirkhh** [comment]
Your second commit is missing an SOB line (should I add that for you?)

**Comment by sfuchs79** [comment]
Fixed, sorry. Still learning phase... :-)

**Comment by dirkhh** [comment]
Pulled. Then added a ton of whitespace fixes as planner.c got too ugly for words.
So please make sure you pull master so you work on top of what I have.

Thanks!

**Comment by sfuchs79** [comment]
Ups...
Recognized that printing the result doesn't look perfectly nice yet.
There are a few line breaks missing which are in fact there in UI both in planner window and dive notes.
How are the line breaks differently controled in UI and printing?

grafik

**Comment by dirkhh** [comment]
It might be better to ask that on the mailing list, not in the thread for your pull request on github.
I thought that both would respect a <br> in the string.
Can you point out specifically which line break that is shown in the planner window is missing when printing the plan? (again, please in an email to the mailing list)

**Pull request closed without merging**
