### PR TITLE
mobile: start cleanup icon directory

### PR DESCRIPTION
**Pull request by janiversen**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

sorted and cleaned mobile-resources.qrc without making functional changes.

Renamed 24px icons and updated the README.license

Decoupled mobile and desktop qrc files by removing ssrf.qrc from .pro
Copied references to missing am-widget icons from ssrf.qrc to mobile-components.qrc

### CODE REVIEW

**Comment by janiversen** [comment]
sorry about the extra commit, but doing rebase turned out to be too complicated.

**Review by dirkhh — CHANGES_REQUESTED** [review]
the second to last commit has a mangled SOB line :-/

**Comment by janiversen** [comment]
just tried to make a change, from my normal whitespace problems :-)

Updated, I hope this is what you meant.

**Review by dirkhh — APPROVED** [review]
variatio delectat
(as we say in Latin)

**Pull request merged**
