### PR TITLE
[RFC] Codingstyle: add comment on "auto".

### PR DESCRIPTION
**Pull request by bstoeger**
Signed-off-by: Berthold Stoeger <bstoeger@mail.tuwien.ac.at>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [x] Documentation change
- [ ] Language translation

### Pull request long description:

Add a paragraph on the use of `auto`, which might be somewhat controversial, therefore marked [RFC]. Note that "variable definition" might be somewhat more precise than "variable declaration".

The whole `CodingStyle.md` file needs a formatting-overhaul.

### CODE REVIEW

**Comment by dirkhh** [comment]
Those are great additions. No point in waiting for Travis

**Review by janiversen — COMMENTED** [review]
I  think line 140
auto = m_trackers...
is not correct.

ps. I agree with the use of auto, just want the line to be correct.

**Comment by janiversen** [comment]
Ups this was merged before my comment. Maybe a coorection later would be in order

**Comment by dirkhh** [comment]
Yep. Already pushed with credit to you

**Pull request merged**
