### PR TITLE
List Ubuntu 18.04 packages needed for build.

### PR DESCRIPTION
**Pull request by merinsky**
Signed-off-by: Martin Měřinský <mermar@centrum.cz>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [x ] Documentation change
- [ ] Language translation

### CODE REVIEW

**Review by neolit123 — APPROVED** [review]
i guess it's OK to have the specific packages for a specific distro version. any objections by others?

**Comment by mturkia** [comment]
I would say that this can be combined with Debian stretch. Thus less maintenance burden for the package list. As far as I know Stretch and 18.04 are built on same base. Thus we only would need to add the following packages to stretch and update header for that.

qtdeclarative5-dev
qtdeclarative5-private-dev

**Comment by dirkhh** [comment]
Yeah, I like to keep this as generic as possible
And since it seems reasonable to assume that people building from source will be on a fairly recent version of their distro of choice, we should simply make sure that the instructions are available for just that.

**Comment by neolit123** [comment]
@merinsky
as per the 2 comments above, could you modify your commit?

**Review by neolit123 — CHANGES_REQUESTED** [review]
unify debian / ubuntu.

**Comment by merinsky** [comment]
I compared packages lists, and they are different.
* Debian needs libqt5declarative5
* Ubuntu needs qtdeclarative5-dev qtdeclarative5-private-dev

So I sorted packages for easier future comparison and removed Ubuntu 16.10. Documentation for last stable (LTS) should be good enough.

**Comment by dirkhh** [comment]
I don't think that's the right direction to go.
People who want the latest packages can use the AppImage.
Distribution packages should - where possible - use the distro supplied versions.
We used to have to bring our own libgit2 because we relied on a feature that was missing in the version available on (at that time) any of the distros. But this should long be fixed - every distro that is still supported appears to have at least 0.24 which is new enough.
Qt 5.9.5 is definitely new enough for the desktop version. 5.7.1 isn't great for BLE, but should work otherwise.
Bringing newer Qt to a distro is really tricky - unless you do it the AppImage way.

**Comment by jbygdell** [comment]
It's a somewhat philosophical question, what are our stand on the software packaging strategies?
I'm all for the AppImage approach.

**Comment by merinsky** [comment]
Requested changes have been made, squashed and force pushed.

**Pull request closed without merging**
