### PR TITLE
[RFC] Profile: Fix leak in animation

### PR DESCRIPTION
**Pull request by bstoeger**
If animDelete() was called with prefs.animation_speed == 0, the
object would not be marked for deletion, as opposed to calling
with prefs.animation_speed != 0.

While touching this function, use the function-pointer version
of connect().

Signed-off-by: Berthold Stoeger <bstoeger@mail.tuwien.ac.at>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

A small leak-fix, though I'm not 100% sure about this one. I'm not happy about Qt's diffuse ownership model with owner-less objects that schedule themselves for deletion by the main-loop, etc.

### Changes made:

1) Schedule object for deletion, even if animation speed is set to 0 (=infinity).
2) Use the function-pointer version of `connect` for compile-time checking.

### CODE REVIEW

**Comment by neolit123** [comment]
re: RFC
the only comment i can make is that i don't like `deleteLater()`. i've gotten weird behavior out of it many times - maybe it was misused, maybe not.

if we can avoid it - great! if we can't and if you think this patch works, we should just merge it.

**Review by dirkhh — COMMENTED** [review]
Always happy to see conversions to the new `connect()` syntax.
I'll admit that `deleteLater()` makes me queasy as well, but if it's the right thing to do, then let's do it...

**Comment by bstoeger** [comment]
I used deleteLater() for reasons of symmetry. But of course, in the first if-branch it has to be used, because you can't connect to delete directly. I will try if a plain delete works as well.

**Comment by bstoeger** [comment]
According to my analysis, a plain `delete` is fine: the caller doesn't keep references to the deleted items. I could hit the delete by setting animation speed to 0 (strange value for what is actually infinity). No double-free detected.

I added a commit with a few minor coding-style fixes. The double/int compares made me itch. :-P Not perfectly happy about the `steps`/`stepsInRange` pair of variables, but I hope that from the code it is quite clear what they are.

**Comment by dirkhh** [comment]
Thanks - this looks good, including the cleanups!

**Pull request merged**
