### PR TITLE
[EXPERIMENTAL] dive master -> dive guide

### PR DESCRIPTION
**Pull request by bstoeger**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Since a user requests listing the "dive master" in the dive list (see #3382), I guess it is the right moment to change from master to guide, as discussed in #2879.

This is of course very dangerous as divemaster is used as a tag in the XML and git logs as well as in foreign formats.

Nevertheless, I would suggest to start the transition now, before this becomes a never-ending story.

I shortly tested the desktop version and it seemed to load/save the dive guide and statistics still work.

### CODE REVIEW

**Comment by dirkhh** [comment]
I am wondering about separating the UI side from the file format side.
I completely agree with the UI changes. 
But I worry about changing especially the git format.
Because if we write the new format to cloud storage, no old app can parse the data that was written to the cloud...
So I think the approach would be to add the ability to read `diveguide`, but to still write `divemaster`. And then in maybe a year switch things to write `diveguide`...
thoughts?

**Comment by bstoeger** [comment]
> So I think the approach would be to add the ability to read diveguide, but to still write divemaster. And then in maybe a year switch things to write diveguide...

That's what this PR attempts to do. It's very likely that I made a few errors here or there, of course.

**Comment by dirkhh** [comment]
> > So I think the approach would be to add the ability to read diveguide, but to still write divemaster. And then in maybe a year switch things to write diveguide...
> 
> That's what this PR attempts to do. It's very likely that I made a few errors here or there, of course.

Doing PR reviews at 4am maybe isn't super smart.
I have a couple of errands to run, but will come back to this later today (I hope).

**Comment by dirkhh** [comment]
merged via #3390

**Pull request closed without merging**
