### PR TITLE
[RFC] Bugfix icd prefs option

### PR DESCRIPTION
**Pull request by sfuchs79**
### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Two bugfixes for the ICD prefs option:
- Load prefs option correctly
- Apply ICD option correctly (this one maybe needs discussion)

### Mentions:

@atdotde

### CODE REVIEW

**Comment by dirkhh** [comment]
This looks obviously correct, but let's let Travis do its job... after that I think it's good to merge.

**Comment by sfuchs79** [comment]
Please wait with this one for @atdotde 
It was never 100% clear to me which part of the whole ICD thingy Robert wanted to switch off with the prefs option - the warning icons only, also the table in the notes, everything,...?

**Comment by atdotde** [comment]
Indeed, I wanted to turn of all ICD warnings (in particular since the criterium is not very well motivated).

BTW, at the boot dive show, Matthias of H&W promised to tell me about some other (hopefully better) criterium they build into their computers.

**Comment by atdotde** [comment]
And yes, looks good to me (I restarted the Android build that got somehow stuck).

**Pull request merged**
