### PR TITLE
FB redirect use https instead of http

### PR DESCRIPTION
**Pull request by atdotde**
When connecting to facebook, I get a warning that the connection
is not secure. It's a wild guess that this patch solves the
issue but I currenty cannot build with facebook support. So I cannot
check.

### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Mentions:

Could somebody please test this? Or build for Mac so I can test it? Thanks!

### CODE REVIEW

**Comment by atdotde** [comment]
Now with SOB

**Review by bstoeger — APPROVED** [review]
Looks obviously correct, but I can't test owing to a lack of FB account.

**Comment by dirkhh** [comment]
@atdotde webkit has become really easy - just get the latest release (5.212) from here https://download.qt.io/snapshots/ci/qtwebkit/5.212/latest/src/submodules/ and it should build and install without any problems. Takes a while, but other than that...

**Review by dirkhh — APPROVED** [review]
obviously correct

**Pull request merged**
