### PR TITLE
Refine code and behavior of #863: refresh location filter list if dive site was edited

### PR DESCRIPTION
**Pull request by bstoeger**
### Describe the pull request:

- [ ] Bug fix
- [x] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

This is a refinement of #863. The user visible change is that now the selection of an entry in the filter list is kept if the dive site is renamed.

### Changes made:
1) Simplify signal/slot handling. Instead of catching a signal in MainTab and calling MainWindow, directly connect the signal to MainWindow.
2) Tell the location filter that a dive site was renamed and take the necessary actions to keep the selection.
3) Optional (remove by removing 3rd commit): tell the location filter that a new dive site was added. If there was any filter selection also the new dive site will be selected.

I solved 2) and 3) by introducing new signal/slot combinations, since this seems to be the Qt-style. But I must say that I dont "get" this kind of programming. Intuitively, I would just introduce a method call where it is needed. I understand that the signal/slot way is more flexible and it's cool for widget libraries, where your users can't change the source. But it introduces an element of non-determinism/non-linearity that I find uncanny.

### Related issues:
Refines #863.

### Mentions:

@sfuchs79: If you find time, please let me know how this performs for your use-case.

### CODE REVIEW

**Comment by dirkhh** [comment]
From the vision when this was implemented, those two are actually quite different.
a) actually means that you enter a different dive site - think about having comments and descriptions in the dive site (not just GPS coordinates); changing things in the main tab will give you a different dive site
b) is the only way that I know to change the name of a dive site

As for the signal/slot mechanism vs. direct calls - I have the concerns with that. But based on our experience when we allowed random calling back and forth it turns out that signal/slot calls have helped us in quite a few cases to keep the code cleaner and more easily understood.
But you are right - this is not a perfect solution

**Comment by bstoeger** [comment]
> Was this done by intention?

Not really. As you and @dirkhh note, these are different code paths: a) Edits a dive (which therefore may not be shown for the current filter selection anymore). b) Edits a dive site.

> Could the idea also be applied to scenario a)?

In principle yes. But I think it should be done only in special cases. Suppose, for example, that you have the location filter
[x] Site 1 (10)
[ ] Site 2 (10)
and you change the dive site of one particular dive from Site 1 to Site 2. Would you really want to end up with
[x] Site 1 (9)
[x] Site 2 (11)
i.e. ten more dives in the list?

On the other hand, if a new dive-site is added (explicitly or implicitly by renaming) and there is already a selection in the filter, one could automatically select the new dive site as well. But I'm not sure if this behavior would be less surprising than the current one. Maybe we should just try out.

**Comment by sfuchs79** [comment]
@bstoeger 
I think exactly the approach you are describing may be really worthwhile trying - if it's not too much effort.
At the same moment I want to say that after the discussion it became clear to me that also the current implementation absolutely makes sense and it also would be ok to simply keep it as it is.

**Comment by bstoeger** [comment]
It's not too much effort, just a bit scary with all that signal/slot stuff. I attempted this with the 3rd commit in this PR. It worked in a small test.

**Comment by dirkhh** [comment]
This looks like an excellent solution. Let's merge it and see how people respond to it.
Great work, @bstoeger

**Pull request merged**
