### PR TITLE
Vpmbprofiletest

### PR DESCRIPTION
**Pull request by atdotde**
Add a test for the profile elements in VPMB mode.  

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [x] Build system change
- [ ] Documentation change
- [ ] Language translation

### CODE REVIEW

**Review by dirkhh — APPROVED** [review]
nothing in here strikes me as wrong, but I haven't used the planner in at least 5 years, I have never used VPM for anything... I feel like I have no idea, so I'm not sure I'm the best person to review this.
Generally I view Robert as the maintainer of all of the planner / deco code

**Comment by dirkhh** [comment]
What's going on with the GitHub actions? The openSUSE one was failing, but it looks like no actions ran on this PR???

**Comment by atdotde** [comment]
openSUSE was broken for quite a while. What I am more worried about is that TestProfile did not catch previous problems. My suspicion is that it did not properly run recently.

**Comment by dirkhh** [comment]
> openSUSE was broken for quite a while. What I am more worried about is that TestProfile did not catch previous problems. My suspicion is that it did not properly run recently.

my comment was about the fact that this PR has just one action, one check... not of the compile checks were triggered somehow.
And now I figured out why. This is a PR into @bstoeger 's branch, not into master!!!

**Comment by dirkhh** [comment]
What would be a good ReleaseNotes entry for this fix? I'm on the process of pulling this all together (as you can see in master)

**Comment by atdotde** [comment]
I don't think this needs an entry as this fixes a problem that was introduced after the last release.

**Comment by dirkhh** [comment]
perfect. thanks

**Pull request closed without merging**
