### PR TITLE
[RFC] Import: import Poseidon MkIV logs via DiveLogImportDialog

### PR DESCRIPTION
**Pull request by bstoeger**
Poseidon MkIV logs (.txt) were special cased in MainWindow.cpp,
which led to a user-interface inconsistency. In some cases
[user chooses ".txt" (non-Poseidon) and ".csv"], *two*
import-dialogs were shown.

Move handling of Poseidon MkIV logs into DiveLogImportDialog.
There are already other "special" cases handled in this dialog.

At the moment, this shows the first 10 depth-values, which is
kind of useless, as this will all be at surface level. We
might think about something more useful.

Signed-off-by: Berthold Stoeger <bstoeger@mail.tuwien.ac.at>

### Describe the pull request:

- [ ] Bug fix
- [x] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

This moves the handling of Poseidon logs into `DiveLogImportDialog` in an attempt to make the user-interface more consistent and also the code more consistent. This will ease the detangling of the import code (think undo, don't unnecessarily import dive-sites, remove divesite-uuids).

Currently, the display is quite useless (first 10 depth values); I'm all ears for other ideas.

### Changes made:

1) Move handling of Poseidon into `DiveLogImportDialog`
### Related issues:

None.
### Additional information:

None.
### Release note:

Will do if code is accepted.
### Documentation change:

Will check if code is accepted.
### Mentions:

@mturkia

### CODE REVIEW

**Review by mturkia — COMMENTED** [review]
Seems reasonable but I have not tested this yet. Also the Windows build seems to fail on missing library or something. (I don't see how this patch would cause the failure)

**Comment by dirkhh** [comment]
The Windows build is fixed in master.
But now we see the failed Max builds where autotools mis-recognizes available functions...
I'll try to remember how I fixed that locally...

**Comment by bstoeger** [comment]
> The Windows build is fixed in master.

I reckon that means that I should rebase this on master?

@mturkia: Could you please also check #1750? Sorry for being a nuisance, but I'm a bit nervous because my local branches diverge more and more from master.. :-P

**Comment by dirkhh** [comment]
I'm trying my fix for the Mac build error.

Having your branch diverge is not a good sign.
How much of this should be merged upstream?

**Comment by bstoeger** [comment]
Rebased on master, edited commit message (MkIV -> MkVI) and added two very minor commits.

The second commit is a minor code-cleanup, which boils down to taste. In my opinion, the resulting code is simpler (one constant less, no sentinel), but if you want to keep the old version, that's fine by me.

The third commit makes the import-dialog modal (according to @neolit123 this is already the case on Windows), which allows removal of the `deleteLater()` kludge.

Concerning diverging branches, what scares me most is how my own branches diverge. Notably import and undo both mess with dive-merging in a different way. This PR seems pretty low risk to me  (how many users actually import from this Poseidon thing?) and would allow progress on the import-branch. Having the latter upstream would allow me to unify the two diverging branches.

**Review by dirkhh — APPROVED** [review]
This looks fine.
We should try to get a Poseidon user to test this :-)

**Comment by mturkia** [comment]
I tested one of the MKVI sample logs that I have and the logs looked to be the same. This test was only visual, so not entirely sure the imports are identical. Having a Poseidon user to test it would be great, as he&she would actually know what is the original dive.

**Pull request merged**
