### PR TITLE
(2) Theme, last part (for now)

### PR DESCRIPTION
**Pull request by janiversen**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Remove subsurfaceTheme in main and activating theme interface.

Once this is merged, I will make a short break for several reasons:
- to give the project/you time to update the manual
- to make a Beta (and later a release) with the current changes
- give me time to synchronise all the recent changes with our version,
making future PR easier

I will of course handle any bugs, just point me to them.

@dirkhh if you think another approach is better, please let me know.

### CODE REVIEW

**Review by dirkhh — COMMENTED** [review]
this looks good (order seems wrong on GitHub again)

**Comment by janiversen** [comment]
@dirkhh please do not forget my comments, I would really like to know your opinion.

**Review by dirkhh — APPROVED** [review]
I am once again traveling today, continuing on too Germany.
I will try to get this merged later today - gotta head to the airport now.
In general I am ok with the idea of a brief pause in order to do a beta; I will need to play with this some more to make sure we haven't lost anything that used to work :-)

**Comment by janiversen** [comment]
Thanks for your comments. Looking at the 3 new PRs (from bstoeger) I look forward to see how you judge my review comments, I have really tried not to use a "bad" tone, but if this is a signal on what is acceptable tones, I need to take a much longer break in order not start responding in the same art.

**Comment by janiversen** [comment]
I assume this PR does not really make sense anymore. I will let the branch stay for a couple of days should I be wrong in my assumption.

It will very soon also be available on my official master along with the remainder of the missing settings and navigation functionality.

**Comment by dirkhh** [comment]
I have the branch locally and am planning to merge this after minor changes.

As I wrote in my long rant. I appreciate the changes that you bring and the progress that the app has made. I regret the cost that goes along with that.

**Comment by janiversen** [comment]
Then I can safely clean my branches.

When you talk about cost, quote “  I end up spending a LOT of time working with you on getting a lot of your changes merged” I am not sure you consider that it has been more than 300 commits during a couple of months, so the cost pr commit could be low or at least not higher than what I have observed happening with work from others.

“ only to be proven wrong yourself in the end”, I think this statement goes in both directions, at least I remember such situations as well. I just wonder why you tend to remember only all the bad things and forget you “countless” times have written you like a specific code part.

I do not want to be seen as a burden or causing a lot of time being wasted. Considering the situation and your arguments (especially about your time usage) it seems the right choice that I take a long break and stop causing fuzz in this project. 

I will continue working on our local fork, it needs to be repositioned so it “sits” safely on top of subsurface-master and not as now in parallel (with some very incompatible changes, due to different demands) This will allow the functions we have to be easy integrated into subsurface-mobile (my preference) if wanted.

when problems or bugs in parts of the code I have made arise, just mail me and I will be happy to supply a bug fix.

A big thanks to you for the time you have spend helping me integrate fundamental changes to the QML interface and make it better (although it will never be perfect or even just good). This includes all the review feedback you have provided, securing the code finally merged is at a higher level.

**Pull request closed without merging**
