### PR TITLE
solve #1631

### LINKED ISSUE #1631: iOS input problems
### Describe the issue:

- [ x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

Based on master I uploaded a debug version to my ipad, as usual it starts by asking me to input my cloud credentials.

I input email and password, but when pressing the connect button, I see the error message “please enter correct credentials” and then it jumps to an empty dive list.

Looking in the log I found this:
stale focus object QQuickTextField(0x1c0358050) , doing manual update
stale focus object QQuickTextField(0x1c0358260) , doing manual update
QPlatformInputContext::inputMethodAccepted() does not match actual focus object IM enablement!
"106.292: Switching to no cloud mode"

I have never seen inputMethodAccepted before so I suppose that is causing the fuzz.

It seems to be local to the cloud screen (manipulating the setting to have correct credentials) loads the dive log and everything seems to work.

### Operating system:

iOS newest

ipad

### Subsurface version:

master

### Steps to reproduce:

upload debug version to ios device
enter cloud credentials
press connect.

### Current behavior:

accept credentials and update settings.

### PR DESCRIPTION
**Pull request by janiversen**
When installing for the first time cloudCredentials needs to be added,
this commit a problem with updating them correctly

this problem was caused by
da6e8a4cd5d80a4288129bf44b1efad69de1704f

Signed-off-by: Jan Iversen <jani@apache.org>

### Describe the pull request:

- [x ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

solve #1631 (funny nobody noticed earlier).

### Documentation change:

fixes #1631

### CODE REVIEW

**Comment by janiversen** [comment]
qt56 fail is hardly my problem “git2.h missing”

**Comment by janiversen** [comment]
can someone please restart travis.

**Comment by dirkhh** [comment]
I think this is an OpenSUSE problem - something is wrong with libgit2 there - but I haven't had the time to check what it is

**Comment by janiversen** [comment]
Just to be sure, this PR solves a problem, with every new installation of the mobile version...if anybody right now compiles master for mobile/ios/android cannot fill in the cloud credentials form.

**Comment by dirkhh** [comment]
I have walked away from all the pref discussions for a bit.
Maybe next week I will feel like stepping into this again and figuring out what we should do there and how I will manage to achieve this goal.
Right now the thought of engaging makes me want to wash the windows or mow the lawn or do anything else that prevents me from having to work on Subsurface.

**Comment by dirkhh** [comment]
Oh, and mind you - there are about six people total who have ever built and installed from either of the mobile versions from source. Jan M, Jocke, Robert, Murillo, you, I. Maybe I'm missing a couple. None of them would be blocked by this.
And I haven't made new test builds in ages because of the Qt5.11 resource bundling problems, so I'm guessing everyone else might have the same problems.

**Comment by janiversen** [comment]
fair, then I will make my life easier and close these PR, allowing me to include them in my signal branch.....that way I save a lof of rebasing (right now I have 4 branches chained).

remark closing the issue does not prohibit anybody in adding comment or continuing discussions, nor does it mean that they are withdrawn forever....it is simply complicated to have PR serialized.

I do understand why you take a break from this unpleasant part, but please see it from my side as well, when (or if) you are ready to see such PRs again, then I will post my active work.

**Comment by janiversen** [comment]
Oh fogot, I have been doing test build since I returned to my mac, and it seems to work with Qt 5.11 (with my patch), at least I use ssrf daily, which I build on master+patch+my extensions

**Comment by dirkhh** [comment]
You deleted the branch, which prevents me from adding this.
You were correct, this one I should have merged.

**Comment by janiversen** [comment]
hmmm strange, you said you preferred washing windows to think about qPref (this PR is about qPref and qmlmanager) and stated that my issue did not block anybody, so it was clear that this one was not to be merged now. 

I normally delete unused branches, simply not to confuse myself.

If you want this PR, not just to let it hang around but to merge it, I will resubmit it, which is easier said than done, because now it needs to do some cherry picking.

**Comment by henrik242** [comment]
@janiversen You are pretty quick to close issues and remove PRs.  Leave them a little longer, and maybe magic will happen :)

**Comment by janiversen** [comment]
yes when being told, what @dirkhh wrote in the 2 PR, there was no sense in letting thrm hang around and complicate my life. Remember the other PR (which are related) has been hanging around for quite a while.

but anyway I offered, when I closed it, and after the comments, that I will resubmit what I have, when it is wanted.

**Comment by dirkhh** [comment]
I will admit that I didn't expect you to simply delete the branch, but it's ok.
I'll have to take a few hours to pry this all apart and clean it up for 4.8.2, I'll fix the bugs as I do that.

**Comment by janiversen** [comment]
Well it would not help me a lot if I left the branch open, then I would have left the PR open.

Ping me if you want help, I happen to have time until sunday. As I wrote I have the commit in another branch and csn isolate it again.

**Pull request closed without merging**
