### PR TITLE
[RFC] Enter offline mode if sync with cloud failed

### PR DESCRIPTION
**Pull request by bstoeger**
In case syncing with the online repository failed, enter offline mode.
This reflects the message sent to the user ("working with local copy").

Signed-off-by: Berthold Stoeger <bstoeger@mail.tuwien.ac.at>

### Describe the pull request:

- [ ] Bug fix
- [x] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Not sure about this one. Background: Apparently I am too stupid to compile a working libgit2 (to make cloud syncing work, I have to comment out the `git_config_delete_entry(conf, "http.proxy");` line, but that is a different story). Anyway, I was surprised that it tells me that I'm working with an offline copy and yet I'm in online mode. This commit switches to offline mode if syncing failed for whatever reason.

### CODE REVIEW

**Review by neolit123 — APPROVED** [review]

**Comment by neolit123** [comment]
requesting another review.

**Comment by janmulder** [comment]
@bstoeger: is this still relevant after #1010?

**Comment by bstoeger** [comment]
This is independent of #1010. The question is: if the user is told "Syncing failed. Working with offline copy." should the cloud be switched to offline mode? I feel this would be more consistent, since this is also done if the cloud served can't be reached. So it wouldn't be completely surprising behavior.

**Comment by janmulder** [comment]
Ok, just tested the current master (desktop application) without network. Red error shows that I cannot go online, but the menu en title bar both say offline.

So, this PR seems not very relevant, and already taken care off. That said, I'm happy to merge it, as it will not do any harm, but as you still say "RFC and not sure about this", I'm a little hesitant :-)

**Comment by bstoeger** [comment]
Indeed, but you tested a different failure mode. If there is no internet connection, this will be detected in `checkcloudconnection.cpp`. This PR handles the case where the cloud server can be reached but syncing failed. This can have numerous reasons, for example:
1) git server is down.
2) libgit2 is messed up (my case).
3) we're not talking to the cloud, but an arbitrary online git repository (that's the actually interesting case).

This commit would make the two failure modes consistent. So all in all, I'm ~80% convinced that it does the right thing.

**Pull request merged**
