### PR TITLE
[RFC] QML UI: switch editing back to comboBox

### PR DESCRIPTION
**Pull request by dirkhh**
The HintsTextEdit just doesn't feel natural and intuitive.

Signed-off-by: Dirk Hohndel <dirk@hohndel.org>

### Describe the pull request:

- [ ] Bug fix
- [x] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

I don't really like the HintsText - this feels much more intuitive to me

### Changes made:

Replace HintsTextEdit with ComboBox and adjust the rest of the code accordingly since they are not drop in replacements of each other

### Additional information:

This has only been lightly tested - I would like to get feedback from those of you working on QML code in the first place, but also from those actively using the dive edit

### Mentions:

@janmulder @jbygdell @notmart @mfbernardes

### CODE REVIEW

**Comment by jbygdell** [comment]
I'm getting lots of issues after this.
*  Loss of data: multiple buddies -> first buddy in the list when editing other things like pressures.
* keyboard visible but not edit button in divedisplay
* Last edited object remembered when reopening edit mode on a dive, also makes keyboard visible.
* No save button when selecting an object from the drop down lists.
* Scroll list interfering with drop down list activation, page moves instead of opening the drop down list.

**Comment by dirkhh** [comment]
@jbygdell thanks for testing and feedback

>Loss of data: multiple buddies -> first buddy in the list when editing other things like pressures.

I have not seen this. Need to make sure that my test data contain multiple buddies

>keyboard visible but not edit button in divedisplay

Also not run into that one - is this on the device? Android, I assume? Because of my recent work on iOS I had actually played with this on iOS :-)

>Last edited object remembered when reopening edit mode on a dive, also makes keyboard visible.

Yes, I noticed that one as well

>No save button when selecting an object from the drop down lists.

Can you elaborate on this? I have an issue where after a partial edit I cannot select the original value without first selecting something else. But I don't recall the save button disappearing.

>Scroll list interfering with drop down list activation, page moves instead of opening the drop down list.

Ah, my tests were not with my full data file but with a much smaller test set, so I didn't get into scrolling. Maybe that's why way-back-when we gave up on the combobox... :-(

I'll keep playing with it because I do find the current solution without different options being available to pick from rather... limited.

**Comment by jbygdell** [comment]
> Can you elaborate on this? I have an issue where after a partial edit I cannot select the original value without first selecting something else. But I don't recall the save button disappearing.

screenshot_20171208-123627
The Cylinder box is still in edit mode and you need to press it again or something else to get the keyboard up, so that it can be dismissed and the save button appear.

For the cylinders we can fix this by setting it to non editable, we can't edit cylinder specifications on mobile yet. The same happens for the other combo boxes as well.

**Comment by dirkhh** [comment]
Please give the changes that I just pushed a try.
This disables editing for cylinders and tries to act more naturally when picking an element from a list.

**Comment by jbygdell** [comment]
Well, it fixes that.

Still having an issue where the edit/delete icon are not visible but still available i.e tapping in the right spot will open edit mode or delete the dive.

The multi buddy issue I think I know what it is.
ComboBoxes can only have one selection, multiple entries can then not be matched to a single index so the lookup will return '-1'. When we save a dive with multiple buddies that have not been modified during this round of editing we pass '-1' to the next step which results in the first entry in the list being saved. It will not happen when you edit the buddy field as it then will add "buddy1, buddy2" as one entry to the list. We then split it into two entries before saving to disk.

**Comment by mfbernardes** [comment]
Just a quick look into this and noticed other issues:

1) When I add a new value for each of these fields, data is saved, displayed on the page with the profile graph, but if I go back and edit the dive the fields are empty. If I force close the app, reopen, then the fields will display correctly the data. But if a new value is entered, same thing again.

2) Cylinders list is empty the first time I open the app.

**Comment by dirkhh** [comment]
OK, so this seems to add a lot more problems than it fixes. Darn. Because visually I like this so much better. I'll keep playing with it - other help / suggestions always welcome.
I did notice that there was some oddity with adding new values and them not being added to the models - but that should be fixable. The multi-buddy thing likely just won't work, so that one needs to find a different solution.
The ActionButton not showing up is something I can't reproduce...

**Comment by jbygdell** [comment]
If these commits are added on top of current master, editing a dive with multiple buddies works fine.

**Comment by janmulder** [comment]
I tried to improve on this PR, and it seemed that I was able to get a more natural behavior on the combobox, so I got more and more optimistic on this. Until I put my changes on device ... The behavior on device is significantly different compared to mobile-on-desktop, and looking trough the log messages and some google-ling  I now believe that the plain QML combobox is more or less useless for longer lists, and definitely different on all our platforms. Obviously, happy to share my 2 (simple) commits.

In the process I found:  https://github.com/oKcerG/SortFilterProxyModel which might be useful but unsure how that stuff behaves on the different (iOs and Android) platforms.

**Comment by janmulder** [comment]
Ok, a bit of a side note, but I tried that SortFilterProxyModel stuff mentioned above. As expected, it does not work on simple QStringList(Model) stuff, which we use to populate Comboxes (and the HintsText). But it does work on models derived from QAbstractItemModel. So I tried a simple filter on the divelist, and that works perfectly (that is, the list is filtered, but the link to the details is broken, very likely due to some stupid assumption on indexes somewhere). So, @dirkhh, what is your opinion of including that repo (only 8 well written and documented files, under MIT license). A divelist filter would be a nice added functionality, especially as I'm very close to 1000 dives logged in Subsurface :-)

**Comment by dirkhh** [comment]
Replaced by #1152

**Pull request closed without merging**
