### PR TITLE
Bugfix dive mode drop-down, translation and planner notes

### PR DESCRIPTION
**Pull request by sfuchs79**
### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [x] Language translation

### Changes made:

Add three missing translations for divemode_text_ui in plannernotes.c 

In planner notes don't show dive mode for first data point.

Fix dive mode drop-down in planner for re-planned dive
Also populate the DiveTypeSelectionModel with values for re-planned dive.

### Mentions:

@atdotde @willemferguson

### CODE REVIEW

**Comment by dirkhh** [comment]
Hmm. The translations obviously won't happen for 4.8.1. The rest looks entirely harmless and straight forward, so I'm tempted to just take it (which is really stupid of me, isn't it?).
Thoughts on before / after 4.8.1?

**Comment by sfuchs79** [comment]
Both or for me. I don't think it's important that this goes into 4.8.1.

BTW: This is what Travis is busy with - sorry ;-)

**Comment by atdotde** [comment]
I support merging.

**Comment by dirkhh** [comment]
OK, would you mention this in CHANGELOG?

**Pull request merged**
