### PR TITLE
[RFC] Dive pictures: Make picture code more scalable

### PR DESCRIPTION
**Pull request by bstoeger**
To potentially conserve memory, don't keep copies of scaled thumbnails.
Scale the thumbnails on demand.

Signed-off-by: Berthold Stoeger <bstoeger@mail.tuwien.ac.at>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Currently, all thumbnails are loaded into memory on startup and are saved to disk on exit. For big divelogs this can amount to a substantial memory-consumption. Moreover, at least three references of the thumbnails of the currently selected dive(s) are kept by the application:
1) In `thumbnailCache` with maximum size.
2) In `DivePictureModel`, according to current `zoomLevel` (for photo-tab).
3) In `DivePictureModel`, default size for the profile plot.

This commit attempts to make the dive picture code more scalable, by loading thumbnails on demand. Since the thumbnails are loaded from disk, displaying thumbnails now takes longer than previously. Therefore, this is now done in a background thread to avoid blocking the UI. Switching between dives with many pictures should now be "snappier".

Currently, there is only a single background thread, i.e. all thumbnailing code is serialized. This can be configured owing to the use of a `QThreadPool`.

As an added bonus of the new code, when adding an image from a remote URL, the image is shown after loading without having to switch between dives.

### Changes made:

1) Store thumbnails in individual files
2) Convert old thumbnail hash to individual files
3) Load thumbnails on demand
4) Do thumbnail processing in background thread
5) Update thumbnails after download

### CODE REVIEW

**Comment by dirkhh** [comment]
This seems useful. It would be nice to get some actual data on memory saved vs. compute impact - but even without that I think I'm ok with this.
@atdotde - any comments?

**Comment by bstoeger** [comment]
> It would be nice to get some actual data on memory saved vs. compute impact 

Unfortunately, both of these are really hard to measure.

I added two commits implementing a more radical approach at conserving memory, which definitely *should* be measurable.

Currently, we load *all* thumbnails into memory on startup. Obviously this doesn't scale to @sfuchs79 style logs with thousands(?) of images. I was thinking about writing one hash file per dive, but this would mean doing some fancy locking, caching, etc.pp. So it occurred to me that the simplest thing will be simply writing a file per thumbnail. Let the people who are actually good at this stuff (OS developers) take care of all the complicated stuff.

This will currently make switching between dives somewhat slower, because the thumbnails are fetched from disk. But in my tests with 200 images/dive, this was still very bearable. In the future, I plan to do the fetching from disk without blocking the UI (see also #1151).

Going with this route, in a next step we can limit the number of pictures shown in the photo-tab to a sane value (if e.g. the user selects all dives at once) to avoid spikes in memory-use.

I also added a commit which converts the old hash to single files. I think we don't need to localize the corresponding ProgressDialog, since it will only be shown once.

There's one point which should be discussed: In the current implementation, the thumbnail-files are composed of an integer and an QImage. The integer is currently set to 0. I plan to use this to differentiate plain images from videos (again, see #1151).

@sfuchs79: Would you perhaps have time to give this a try?

**Comment by bstoeger** [comment]
Cherry-picked the appropriate commits from #1151. Memory consumption is reduced for me and interface is quite snappy. A perceived disadvantage might be that thumbnails are loaded incrementally.

Anyone willing to test?

**Comment by atdotde** [comment]
I haven't looked at the code but I can confirm this is nice and snappy (for the few pictures I have in my dives) and no obvious flaws.

**Comment by bstoeger** [comment]
Thanks. Are you fine with prepending an integer in the thumbnail files to indicate the media-type (picture/video)?

**Comment by atdotde** [comment]
Sure. Can you do it in a way that is backwards compatible? Or at least use a different file name?

**Comment by bstoeger** [comment]
The "new-style" thumbnails are saved in the folder ".suburface/thumbnails". Older versions will simply ignore the folder and recreate the thumbnails if needed. So switching between old and new versions should have no adverse effects, besides unnecessary thumbnail recalculations. But I have only tested old->new version, not the other direction.

**Comment by dirkhh** [comment]
The iOS build fails with QThreadPool not found. Hmm. That needs looking into.

What are the effects for someone who has existing cache (so the common "upgrade" scenario)?

**Comment by bstoeger** [comment]
> The iOS build fails with QThreadPool not found. Hmm. That needs looking into.

Mobile on desktop builds and runs for me - so not sure what I can do...?

> What are the effects for someone who has existing cache (so the common "upgrade" scenario)?

Commit dbf1cb993e3a0aad2eb20e7180bde083bd58c7a8 converts the big hash to individual files on startup. This should happen only once (except if the application does not close regularly, i.e. crash or termination by user).

**Comment by bstoeger** [comment]
PS: This still needs clip art placeholders for "Image loading" and "Image loading failed". Currently, I misuse random icons which look horrible owing to scaling. How can we proceed in this respect?

**Comment by dirkhh** [comment]
Getting better icons for something is always challenging. Google searches with license restrictions for scalable icons often help.
As for iOS failing - now that I had some sleep I'm thinking this is caused by the way I have minimized the size of the iOS Qt package, so I think you can ignore this - this is something that I need to fix.

**Comment by bstoeger** [comment]
To make the maximum thumbnail-size scalable, we need SVG icons. The filter-close icon, which I misuse for load-failed, is an SVG. I added a few lines to render it to the appropriate size. For the moment I think it is clear what the icon means, but ultimately, someone will have to find a proper icon.

The photo-icon was a PNG, so I imported a camera-icon from the KDE-breeze icon set, which is licensed under LGPL. Is that OK? It feels weird to import other people's work without asking them.

From an aesthetic point of view, this all "fits like a fist to the eye" to use a German idiom, but this is simply not something that I can take care of.

**Comment by dirkhh** [comment]
reusing icons from breeze is fine - we already do this for Subsurface-mobile
I'm not in love with simply copying them (instead of what we do in the mobile build), but it's not a licensing issue

**Comment by bstoeger** [comment]
> instead of what we do in the mobile build

I see the `scripts/mobilecomponents.sh` thing. But do we really want to add such build-complexities to the desktop version for a single icon? If there was a bigger standardization effort to breeze icons, then sure. But for one (hopefully temporary) icon?

**Comment by dirkhh** [comment]
> I see the scripts/mobilecomponents.sh thing. But do we really want to add such build-complexities to the desktop version for a single icon? If there was a bigger standardization effort to breeze icons, then sure. But for one (hopefully temporary) icon?

Clearly I am speaking in tongues these days.
No, we don't want to do that. All I am saying is that this is fine from a licensing point of view, that we already do it, but that I don't want the next person to turn around and copy all the mobile breeze icons into the sources as well.

**Comment by sfuchs79** [comment]
@bstoeger 
Sorry for not giving a feedback for such a long time.
I was today finally able to test this.
In short: This is a really nice implementation. Very good performance and finally solves my issues with missing thumbnails. It also works nicely with dives with large number of pictures (~100). I didn't see any unwanted behavior after some quick tests. Thumbs up and thanks from my side!

**Comment by sfuchs79** [comment]
So yes, I can confirm that this huge enhancement closes #1179

**Comment by bstoeger** [comment]
> So yes, I can confirm that this huge enhancement closes #1179

That's nice to hear, because I wouldn't have thought that it would fix the problem. There's still room for improvement, but let's see if this causes any problems in the wild first.

**Comment by dirkhh** [comment]
I've gone through a complete review. There are patterns in the code that I am not super familiar with, but I don't see anything WRONG per se. So I think the best bet is to merge it and move forward.

**Pull request merged**
