### PR TITLE
Mobile: fix editing of weight system

### PR DESCRIPTION
**Pull request by bstoeger**
### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Removal of MAX_WEIGHTSYSTEM made it impossible to edit the weight on mobile for dives that had no weightsystem set (e.g. newly created dives). This PR fixes this.

### Changes made:

1) Enable editing of weight for 0-weightsystem dives.
2) Add a new weightsystem for 0-weightsystem dives.

### CODE REVIEW

**Review by dirkhh — APPROVED** [review]
Thanks for fixing this one. Looks good

**Comment by bstoeger** [comment]
Should we use something different than the empty string as description?

**Comment by dirkhh** [comment]
> Should we use something different than the empty string as description?

we could do something like `tr("weight")`

**Comment by dirkhh** [comment]
Does that look right, @bstoeger ?
I'll merge locally if you approve (and if Travis likes it)

**Comment by dirkhh** [comment]
does this look better, @bstoeger ?

**Comment by bstoeger** [comment]
Yes, that looks reasonable to me.
Before commit, perhaps change to `qUtf8Printable` as the documentation sounds to me as if that was more secure: https://doc.qt.io/qt-5/qtglobal.html#qUtf8Printable
But I'm not sure if I read the documentation right.

**Comment by dirkhh** [comment]
We use `qPrintable` everywhere because we set Subsurface up to always use Utf8
```
void init_qt_late()
{
	QApplication *application = qApp;
	// tell Qt to use system proxies
	// note: on Linux, "system" == "environment variables"
	QNetworkProxyFactory::setUseSystemConfiguration(true);

	// Set the locale codec to UTF-8.
	// This makes QFile::encodeName() work on Windows and qPrintable() is equivalent to qUtf8Printable().
	QTextCodec::setCodecForLocale(QTextCodec::codecForMib(106));
```

**Comment by bstoeger** [comment]
Ah yes, I think it was even me who removed all the qUtf8Printable things. Heh.

**Comment by dirkhh** [comment]
merged manually

**Pull request closed without merging**
