### PR TITLE
Test for adding a picture with data after JFIF EOI to a dive

### PR DESCRIPTION
**Pull request by sfuchs79**
This has to be merged after @atdotde and my other updates for the picture handling!
A test for adding a JPEG with data after the JFIF EOI tag.

Two doubts/questions:
- Is it ok to move the (now two) test files to a new subfolder? I didn't want to have them in the root directory.
- Is it expected that the hash of the wreck.jpg changes when moving it to another folder...

Let's see what Travis says...

### CODE REVIEW

**Comment by sfuchs79** [comment]
Ah, for sure the Travis build fails because the bugfix for the Exif is not there yet...
I'm stupid... but that was also a good test in the other direction :-)

I'll wait for Robert to finalize the other thing together with him first...

**Comment by mturkia** [comment]
The image should remain identical when you move it around - same hash after the move. You should use "git mv wreck.jpg pictures/wreck.jpg" to move it. I wonder if it would be better to have the pictures under the dives directory. This is where we store the test dive logs, and these pictures can be considered as part of test logs.

**Comment by atdotde** [comment]
The whole point of the picture hash is that we can recognise images in other places in the file system. So, no, it does not change when you move it around or rename it, the hash is only about the file contents.

**Comment by dirkhh** [comment]
I'm a bit unclear if this is ready to merge or not

**Comment by sfuchs79** [comment]
I updated it just a few minutes ago:
- I was now able to move the wreck.jpg w/o accidently touching it by using "git mv" (Hooray! Thanks to Miika!). Hash is now unchanged.
- Also based on Miikas suggestion I moved the pictures under /dives/images

Travis here still fails because it needs the other changes you just merged a minute ago. It should be ok and ready now. Is there a trick to rerun Travis w/o changing anything?

**Comment by dirkhh** [comment]
Yes, when you click on the Details link, you can restart the build. Or at least I can (not sure what the permission situation is there...). I just restarted the test so I'll know if this passes before merging it :-)

**Pull request merged**
