### PR TITLE
Enable location on iOS

### PR DESCRIPTION
**Pull request by mfbernardes**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [x] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Add required Info.plist entry in order to use corelocation and enable GPS menu entry

### Documentation change:

Need to update mobile manual removing "Android only" references.

### Mentions:

@dirkhh

### CODE REVIEW

**Comment by mfbernardes** [comment]
Did the original code (without calling serviceEnable) work on Android?

If you have a better place to call serviceEnable() just let me know.

**Comment by dirkhh** [comment]
Yes, the current code works fine on Android... Many of us use Subsurface-mobile on Android for GPS tracking :-)
Is this all it took for you to get GPS to actually work?
The reason I'm asking is that I had it sort of working, but if the phone went to sleep (so if the phone is in your dive bag while you are on the boat) it wouldn't register any GPS locations, so what you had (with the service running) was basically useless...

**Comment by mfbernardes** [comment]
This was all I needed to do to get location enabled, ask user for permission and start receiving updates.

But if we want constant tracking, even in background, I need to at least change the Info.plist to Always.

I’ll update that and check it still gets updates when in background.

I never used the android version and didn’t fully check the code, so I still didn’t know the intended functionality.

—
Murillo

**Comment by dirkhh** [comment]
OK, I wait with pulling until you had a chance to update / test that. I just finally got the BLE fix into TestFlight... turn around time on Apple apps is not swift.
As to the intended functionality, there are basically two modes:
One allows you to mark your current location as a (usually named) dive spot. If you are at the dive site and want to just mark that spot, that's what you do.
The other mode is what (I think) most people use, it's certainly how I always use it. You turn on the location service and just let it run while you are on the dive boat. It keeps storing GPS fixes. After you downloaded your dives from your dive computer, you ask the app to match the dives to the right GPS fix and you automatically get the best (for some definition of best - there's a PR in flight right now to improve that) location for that dive added.
That's why we need the background mode. And that's what I failed to get to work - so I disabled it at all because it seemed very hard to explain to users that "half" of the GPS functionality was available :-(

**Comment by mfbernardes** [comment]
Cool, I’m also reading the manual to see what to expect.

I’ll be a bit busy these next days, but I’m working on it.

**Comment by dirkhh** [comment]
Trust me - I know way too much about "I'll be a bit busy"... BTW: which time zone are you in?

**Comment by mfbernardes** [comment]
Currently UTC+8, traveling in Philippines... but I’m not from this side of the world :)

**Comment by mfbernardes** [comment]
This is what it takes to get location updates even in background.

Also enables the GPS menu entry.

Tested on simulator and iPhone with iOS 11.1

**Comment by dirkhh** [comment]
That is embarrassingly simple - I will claim that maybe the fact that this works now is caused by fixes in Qt (I last tested this with 5.7). But anyway - thank you for looking into this and getting us back on track here.

**Comment by mfbernardes** [comment]
Yeah, simple... and simple is good.

Looks like background location was fixed on Qt 5.9

**Comment by dirkhh** [comment]
That would explain it :-)
I need to make a new TestFlight version available...

**Pull request merged**
