### PR TITLE
Issue 259 minimal pO2 threshold

### LINKED ISSUE #259: [Idea] minimal pO2 threshold
Currently, the program has maximum threshold values (in preferences, and for example used in the profile) for partial pressures that are too high.

Especially a low pO2 can be very dangerous, which is something that can occur very easily in pSCR diving due to the pO2 drop, and using incorrect gas in the shallow part of the dive. For example, the user manual shows a example of a pSCR dive using EAN30 all the way up to the surface, and given the default pSCR settings from Subsurface, this results in a pO2 < 0.15 bar from approx. 3m depth. Another example is the planner that shows a warning way too late. A plan with EAN30 shows a warning: low p02 of 0.05 at <end of dive>, with the last 20 minutes of the dive with pO2 < 0.15. I would say: do not try this at home.

All boils down to not having a minimal pO2 threshold value, and by consequence no proper feedback to the user for this danger.

Obviously, this is something related to technical diving wiith pSCRs or open circuit hypoxic gas diving, but as we are targeting this type of divers too, we can better do it right (oh oh, the DIR word :-)

### PR DESCRIPTION
**Pull request by janmulder**
These 2 commit do the following:
- add a minimal pO2 threshold value to the Preferences UI, in addition, changed some labels to make the minimum or maximum threshold more explicit. Obviously, low thresholds for pN2 or PHe are not applicable.
- adapted the p02 partial pressure graph to show the too low p02 parts also in red. As this code is used in the planner as well, also there is already some guidance  for too low p02.

What can still be done (and is not part of this pull request), is improving the text area of the planner to be more precise in low pO2 warnings (or just point to the graph, instead of trying to list all possible episodes of too low pO2). Maybe @atdotde is tempted to adapt the planner for this. 

For now: fixes #259

### CODE REVIEW

**Comment by janmulder** [comment]
Sorry, did not build the tests. Correcting this later today, just wait with merging for now.

**Comment by dirkhh** [comment]
This no longer applies cleanly... I would much prefer if you rebased it instead of me trying to get things right.

Thanks

**Comment by janmulder** [comment]
Rebase done.

**Comment by sfuchs79** [comment]
@janmulder 
Maybe it would be nicer to move the 3 fields for the maximum pressure for N2, He, O2 for MOD to the right in the UI window exactly below the maximum field for the O2 (where we now have minimum + maximum). What do you think?

**Comment by janmulder** [comment]
@sfuchs79: agree and new PR #291 made.

**Pull request merged**
