### PR TITLE
[do not merge, need rebase] (planner 5) add notes variables

### PR DESCRIPTION
**Pull request by janiversen**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

move handling of planning variables from desktop-widgets to plannerShared, to prepare for an identical use in QML.

creating the functions in plannerShared and using the new functions in desktop-widget are on purpose in separate commits.

creating the new functions are grouped in commits with similar functionality

** Warning ** this pr is based on #2467 and thus contains those commits

### CODE REVIEW

**Review by dirkhh — COMMENTED** [review]
same comments

**Comment by janiversen** [comment]
same answer, I will wait to see if you change opinion (not a demand) and if not close this series.

Interesting enough I got a comment on the first PR, that was positive. quote "and I think you're starting in the right end, by refactoring the current code to make the infrastructure available in the mobile apps"

**Comment by janiversen** [comment]
the Mac failure is in "set our Qt" and ends with
tar: Error opening archive: Unrecognized archive format
46
##[error]Process completed with exit code 1.

I believe that is not something caused by this PR.

**Comment by dirkhh** [comment]
> the Mac failure is in "set our Qt" and ends with
> tar: Error opening archive: Unrecognized archive format
> 46
> ##[error]Process completed with exit code 1.
> 
> I believe that is not something caused by this PR.

No. I think we are doing so many pushes to PRs and so many merges into master that we are bumping into limits of the free GitHub Actions (or are simply seeing random network failures cause build failures). But this clearly has nothing to do with your PR

**Comment by dirkhh** [comment]
> same answer, I will wait to see if you change opinion (not a demand) and if not close this series.
> 
> Interesting enough I got a comment on the first PR, that was positive. quote "and I think you're starting in the right end, by refactoring the current code to make the infrastructure available in the mobile apps"

And I COMPLETELY agree with that.
This is the problem of the way PR comments are written and then read.
I think you are absolutely doing it the right way.
Note that all of my comments were "comments" not "request changes" or "NAK".
I had / have questions about the code you ended up with. And you already answered some of them.
This is completely normal (IMHO) and the fact that I am not intimately familiar with the planner code is a big part of this.

**Comment by dirkhh** [comment]
manually merged

**Pull request closed without merging**
