### PR TITLE
profile-widget: update to not ruin fonts.

### PR DESCRIPTION
**Pull request by janiversen**
### Describe the pull request:

- [ x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Disabling print mode, for the profile in the mobile version, received some doubts, but 
was merged as "on trial".

This patch set print mode on, and only disables the loop where the print mode is used
to determine behaviour (not a nice mixture).

### CODE REVIEW

**Comment by dirkhh** [comment]
looks like this PR contains commits that were already merged. Could you create a clean PR, please?

**Comment by dirkhh** [comment]
(the actual change in the final commit looks reasonable)

**Comment by janiversen** [comment]
Ups, my only excuse is that I am a bit tired, started the day with a 38meter dive and after that a 20meter dive where one diver managed to run out of air. 

Anyhow pushed a clean version, sorry for the mistake.

**Comment by dirkhh** [comment]
Running out of air on a 20m dive? tsk tsk tsk... how long was the dive?

**Comment by janiversen** [comment]
56 minutes, I returned with half tank, but I guess he was nervous and cold (and forgot to check). Well it ended with no problems, just sharing

**Comment by janiversen** [comment]
thanks a lot, that merge just made my day extra special. 7 weeks and #20 not bad at all !!

I normally do not really care, but I read you message on IRC a couple of days ago :-)

Anyhow now that I start feeling at home in the qml/C++ code of the mobile ui, it is time for some heavier commits.

**Comment by janiversen** [comment]
using the official insight
https://github.com/Subsurface-divelog/subsurface/graphs/contributors

**Pull request merged**
