### PR TITLE
Maps for ios

### PR DESCRIPTION
**Pull request by dirkhh**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [x] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

This **should** make the maps work for iOS, but it doesn't, I get linker errors about a missing vtable which I can't make sense of.
### Changes made:

Seems straight forward - just add things to the build system (and add a missing QVariant include)

### Mentions:

@atdotde @mfbernardes

### CODE REVIEW

**Comment by mfbernardes** [comment]
Dirk,

map-widget/qmlmapwidgethelper.h and qt-models/maplocationmodel.h were not being moc'ed.

This fix the build:

```
diff --git a/packaging/ios/Subsurface-mobile/Subsurface-mobile.pro b/packaging/ios/Subsurface-mobile/Subsurface-mobile.pro
index 2e4e9166b..376ceedee 100644
--- a/packaging/ios/Subsurface-mobile/Subsurface-mobile.pro
+++ b/packaging/ios/Subsurface-mobile/Subsurface-mobile.pro
@@ -183,12 +183,14 @@ HEADERS += \
     ../../../core/subsurface-qt/SettingsObjectWrapper.h \
     ../../../mobile-widgets/qmlmanager.h \
     ../../../mobile-widgets/qmlprofile.h \
+    ../../../map-widget/qmlmapwidgethelper.h \
     ../../../qt-models/divelistmodel.h \
     ../../../qt-models/diveplotdatamodel.h \
     ../../../qt-models/gpslistmodel.h \
     ../../../qt-models/divelocationmodel.h \
     ../../../qt-models/completionmodels.h \
     ../../../qt-models/weigthsysteminfomodel.h \
+    ../../../qt-models/maplocationmodel.h \
     ../../../qt-models/diveimportedmodel.h \
     ../../../qt-models/messagehandlermodel.h \
     ../../../profile-widget/diveprofileitem.h \
```

... but the map doesn't work yet. The app log shows this:

```
INFO: MapWidget.qml: cannot find a plugin named: googlemaps
INFO: qrc:///qml/MapWidget.qml:24: Error: Cannot assign [undefined] to QDeclarativeGeoMapType*
```

**Comment by neolit123** [comment]
> ... but the map doesn't work yet. The app log shows this:

it's usually a matter of copying he `*googlemaps*.so` file to the correct location.
for Android we had to `qinstall ` it into the folder where the rest of the `geoservices` plugins are in the Qt folder:
```
QT_PLUGINS_PATH=`$QMAKE -query QT_INSTALL_PLUGINS`
GOOGLEMAPS_BIN=libqtgeoservices_googlemaps.so
$QMAKE -install qinstall -exe $GOOGLEMAPS_BIN $QT_PLUGINS_PATH/geoservices/$GOOGLEMAPS_BIN
```

the Android APK build process would pick it up.

`make install` didn't work for Android on the CI, so maybe it is not working here too?

**Comment by dirkhh** [comment]
Duh, that's what I was missing. The .h files 😕

Getting the mobile apps to find modules and plugins is always a problem; even more so on iOS. Now that you showed me how to fix the build problem, I'll play with that.

Thanks
-- 
from my phone.

**Comment by dirkhh** [comment]
>it's usually a matter of copying he `*googlemaps*.so` file to the
>correct location.

On iOS these are all static libs.
It's pretty much black magic to me.

>for Android we had to `qinstall ` it into the folder where the rest of
>the `geoservices` plugins are in the Qt folder:
>```
>QT_PLUGINS_PATH=`$QMAKE -query QT_INSTALL_PLUGINS`
>GOOGLEMAPS_BIN=libqtgeoservices_googlemaps.so
>$QMAKE -install qinstall -exe $GOOGLEMAPS_BIN
>$QT_PLUGINS_PATH/geoservices/$GOOGLEMAPS_BIN
>```

I'll play with that.

**Pull request closed without merging**
