### PR TITLE
For About UI window layout, use SetFixedSize.

### PR DESCRIPTION
**Pull request by merinsky**
Window is resized according to its content.
There is no need for user to resize this window.

### CODE REVIEW

**Comment by dirkhh** [comment]
What about super small screens (like 800x600)? I actually think the change is fine, but I wonder what the impact is, i.e., what's the advantage of disabling resize?

**Comment by merinsky** [comment]
User can size 'About Window' only up (make it bigger). It doesn't make sense to do it, because content stays unchanged. And user will certainly not do it on super small screens :-)

I tried several applications and 'About Window' is mainly unresizeable.

For super small screens, I would suggest to make logo in 'About Window' a little bit smaller and replace some buttons with hyperlinks.

**Comment by Ghalr** [comment]
Speaking about 'About Window' I would like to suggest few ideas:

- I'm agree it would be great to have hyperlinks instead of buttons and smaller icon:
http://imgur.com/a/IMCd6

- 2 ways to close 'About Window' : 'Close' button + X top button  
I suggest to click outside the window.

**Comment by dirkhh** [comment]
I'm ok with both suggested improvements.

**Pull request merged**
