### PR TITLE
Android: Improve build instructions

### PR DESCRIPTION
**Pull request by mikeller**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [x] Documentation change
- [ ] Language translation

### Pull request long description:

Improve the build instructions for Android. Provide a complete script for building in a re-usable container.
Also changed the Android packaging README to markdown.

### Changes made:

1. provide a complete script for building in a re-usable container;
2. changed the Android packaging README to markdown.

### CODE REVIEW

**Review by dirkhh — COMMENTED** [review]
doing the switch to markdown AND the content changes at the same time makes it a lot harder to review the changes :)
Having that as two commits would have been nice...

**Review by dirkhh — APPROVED** [review]
I am reasonably sure that this is correct. It's definitely no worse than what we have, actually much better.

**Comment by dirkhh** [comment]
I keep trying to remember to disable the 18.04 build... not all that useful anymore...

**Comment by mikeller** [comment]
> doing the switch to markdown AND the content changes at the same time makes it a lot harder to review the changes :) Having that as two commits would have been nice...

Apologies. For some reason I had assumed it was already markdown - probably because there aren't many non-markdown READMEs around these days. So I pushed my changes containing markdown first, and then had to rename (and further markdown-ise) the file to stop it from being displayed as 'text file with funny ticks' by GitHub...

**Pull request merged**
