### PR TITLE
AppImage: don't bundle our libdbus

### LINKED ISSUE #2370: Bluetooth doesn't work in the appimage
```
$ ./Subsurface.AppImage 
Cannot find a running Bluez. Please check the Bluez installation.
```
### Describe the issue:
- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
When running subsurface from the app image, bluetooth doesn't work.

### Operating system:
Tested on Ubuntu 18.04

### Subsurface version:
Tested with v4.9.3-304-g80f123ce2aac

### Steps to reproduce:
Start app image, Import from dive computer, Choose Bluetooth download mode.

### Current behavior:
Bluetooth doesn't work. "Not available"
Says `Cannot find a running Bluez. Please check the Bluez installation.` on commandline.

### Expected behavior:
I expect to see devices on the Discovered devices dialog.

### Additional information:
We get the dbus library from the applimage, and the compiled in default for the dbus socket points to `unix:path=/usr/local/var/run/dbus/system_bus_socket` . I don't know of a single system where that will be right. A better default would be /var/run/dbus/system_bus_socket.

Even when setting the env-var DBUS_SYSTEM_BUS_ADDRESS=/var/run/dbus/system_bus_socket it behaves the same way, but with strace I see some talk on dbus, but nothing about bluez. What else do Qt5Bluetooth need to talk to bluez?

### Mentions:
@probonopd

### PR DESCRIPTION
**Pull request by Subsurface-divelog**
### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Changes made:

simply delete the offending library before bundling

### Related issues:

Fixes: #2370

### Release note:

DONE

### Mentions:

@glance- can you please check that the resulting AppImage works for you?
Since this is a PR, you'll need to go to the Action for Linux Qt5.12 and download it from the Artifacts drop down in the upper right area of the page

### CODE REVIEW

**Comment by Subsurface-divelog** [comment]
Somehow the original PR refused to re-open, so here's a new one.
Assuming this build succeeds, same request for @glance- to try things out (as I don't have a laptop running Linux with me on this trip and can't seem to test this in a VM)

**Comment by Subsurface-divelog** [comment]
OK, the build worked - now someone needs to test it :-)

**Comment by glance-** [comment]
I can't figure out where the binaries produced ends up?

**Comment by dirkhh** [comment]
> I can't figure out where the binaries produced ends up?

Linus reports it doesn't work for him.. so I'm curious how this will work for you since you said earlier that just removing that library fixed it for you. He's on Fedora, though.

Anyway, in the big box that says "All checks have passed" there is a line "Linux Qt 5.12" (it's the second for me). Click on Details. That page in the upper right (above the black area) has a drop down "Artifacts". There you can download a zip file that contains the AppImage.

**Comment by dirkhh** [comment]
This direct link "might" work https://github.com/Subsurface-divelog/subsurface/suites/322614029/artifacts/395658
But the instructions above will always work

**Comment by glance-** [comment]
The libdbus binary is still there in the app image. I'd rather see that we removed our "home brew" libdbus entirely from the mix, and shipped with the one from trusty.

**Comment by linuxcrash** [comment]
If anyone creates the updated App Image, I will be more than happy to try it out as I'm running Fedora 31 and have the same bluetooth issue currently.

**Comment by dirkhh** [comment]
> If anyone creates the updated App Image, I will be more than happy to try it out as I'm running Fedora 31 and have the same bluetooth issue currently.
Hi @linuxcrash - sorry, this took a bit longer than I hoped. Can you try this AppImage?
https://github.com/Subsurface-divelog/subsurface/suites/344708805/artifacts/568615
(download the .zip, the AppImage is inside)

**Comment by linuxcrash** [comment]
@dirkhh I just run the linked Subsurface AppImage on a up to date Fedora 31 and indeed the bluetooth scan function works now fine and detects my Ration iX3M computer.
I also extracted the AppImage to double check that there is no libdbus.so in /usr/lib.

I guess with that  #2370 can be closed.

**Pull request merged**
