### PR TITLE
CICD: Move MacOS / iOS Build Qt Resources into GitHub.

### PR DESCRIPTION
**Pull request by mikeller**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [x] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Move the Qt resources required for the build for MacOS and iOS into
GitHub, into their own repositories. This removes the need to publish
them on an external file server and download them from there for every
build.
It will also make it easier for contributors to update these resources
if needed.

### Related issues:

https://github.com/subsurface/qt-mac
https://github.com/subsurface/qt-ios

### CODE REVIEW

**Comment by mikeller** [comment]
image

**Comment by dirkhh** [comment]
nice

**Comment by mikeller** [comment]
We could probably get more speed improvements by caching things like the google maps plugin or the 3rd party components, but they are downloaded and installed inside the build scripts, which will make it hard to make this depend on the outcome of the cache load.

**Comment by mikeller** [comment]
@dirkhh: I have thought about this a bit more. We could probably get completely off Backblaze, and avoid having to download this data from external at all if we put the prebuilt Qt components for the MacOS / iOS builds into a repository of their own, and consumed them in the same way that we are already consuming the Google maps plugin - there is no point in caching stuff that is already stored in GitHub.

**Comment by dirkhh** [comment]
IIRC the problem with that was that a build of these components isn't possible inside a GitHub Action (requires too much memory / too much time).
But of course we should be able to figure out how to simply upload the binary artifacts that are built elsewhere.

**Comment by mikeller** [comment]
My thoughts too - having these resources available in pre-built form in a local repository will be an effective way to keep them at hand for the MacOS based builds that need them.
If you create two repositories `qt-mac` and `qt-ios` or similar, and give me access I can get this set up.

**Comment by dirkhh** [comment]
> If you create two repositories `qt-mac` and `qt-ios` or similar, and give me access I can get this set up.

You should be able to that without my help. At least I'm 95% sure that I gave you the necessary permissions...

**Comment by mikeller** [comment]
@dirkhh: I have re-engineered this one to keep everything inside GitHub.

**Comment by mikeller** [comment]
Note that it now also publishes artifacts:
- MacOS .dmg for pull request builds;
- iOS simulator app for all builds.

**Review by dirkhh — APPROVED** [review]
Nice. And thank you for doing that!

**Pull request merged**
