### PR TITLE
std99 does not make sense for C++

### PR DESCRIPTION
**Pull request by atdotde**
... and makes Qt Creator fail to parse files.

Signed-off-by: Robert C. Helling <helling@atdotde.de>

### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [x] Build system change
- [ ] Documentation change
- [ ] Language translation

### CODE REVIEW

**Review by neolit123 — APPROVED** [review]
seems correct.
LGTM

**Review by dirkhh — APPROVED** [review]
Reading up on it, yes you are correct. I know that I was trying to fix a compile problem when adding those - it looks like I went overboard.

**Comment by dirkhh** [comment]
Let's wait for Travis, please.

**Review by bstoeger — APPROVED** [review]
If Travis is happy, so am I (not a compiler expert at all).

**Comment by bstoeger** [comment]
>  I know that I was trying to fix a compile problem when adding those - it looks like I went overboard.

That's actually a copy&paste error caused by me. Blame where blame is due. 😁

**Comment by bstoeger** [comment]
Since there seems to be unanimity - commit.

**Pull request merged**
