### PR TITLE
win32: optimize the console and logging logic

### PR DESCRIPTION
**Pull request by neolit123**
### Describe the pull request:

- [ ] Bug fix
- [x] Functional change
- [ ] New feature
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Currently one has to explicitly to use --win32console and/or
--win32log to enable a dedicated console (a console window
that opens next to the Subsurface window) or to enable file
logging on Win32.

This patch makes the following changes:
- removes the --win32* command line arguments
- removes the dedicated console window support
- if the app starts from a shortcut and not from a console, always
redirect stderr and stdout to _err & _out log files
- if the app starts from a console redirect stderr and stdout to that
console

Signed-off-by: Lubomir I. Ivanov <neolit123@gmail.com>

### Changes made:

see list above.

### Related issues:

none

### Additional information:

none

### Mentions:

@dirkhh

### CODE REVIEW

**Comment by dirkhh** [comment]
Thanks - this seems like a really good solution. Now we need to make sure that the qDebug() output also goes there. I think @tcanabrava explained this on the mailing list. Is that something you'll work on as well?
I think it makes sense to merge this one as is and look at that part as the next step.

**Comment by neolit123** [comment]
@dirkhh 
qDebug() already goes there from my tests.

**Comment by dirkhh** [comment]
Sorry, I must have misunderstood your comment on the mailing list.

> in the case of subsurface, the log file is created, with OK
> permissions, but remains empty.
> maybe Qt is doing something to prevent this - no idea.

That's why both @tcanabrava and I thought that maybe things were only working for the fprintf(stderr,...) statements and not for qDebug()

**Comment by neolit123** [comment]
@dirkhh 
yes, qDebug() / qWarning() are redirected appropriately to log files or to the console.

the quotation explains what happens when i try to write to a *single* log file. it doesn't work, as it seems Qt is doing something to prevent it. writing separate _out.log and _err.log files on the other hand works.

**Pull request merged**
