### PR TITLE
Git storage refactor

### PR DESCRIPTION
**Pull request by dirkhh**
Make it possible to use different cloud credentials in TestGitStorage - and then do that in our GitHub Actions.

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [X] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### CODE REVIEW

**Comment by neolit123** [comment]
the test and build workflow changes LGTM.

**Comment by dirkhh** [comment]
> the test and build workflow changes LGTM.

turns out they only LOOK good. :-(
Pull requests can't use the secrets. I knew that. DUH.
So this needs to be done differently.

**Comment by glance-** [comment]
A Idea on how to fix this is to test it against a local git repo, and point subsurface tests against a file:// url instead.

**Comment by dirkhh** [comment]
> A Idea on how to fix this is to test it against a local git repo, and point subsurface tests against a file:// url instead.

I fixed it by hard-coding credentials again. Oh well. Seems to work. And does exercise the live connection to the cloud storage server, which really is the point here.

**Pull request closed without merging**
