### PR TITLE
changing Android build to use get-dep-lib.sh

### PR DESCRIPTION
**Pull request by janiversen**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ x] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

This is the promised continuation of using get-dep-lib.sh in our different build.sh

Currently it is a test to see if travis are similar to my own environment.

### CODE REVIEW

**Comment by dirkhh** [comment]
We have a few people actively working on Android.
The old OpenSSL library is simply a matter of "treat assessment". The mobile app only connects to ONE site, one that I control, and that it has a hard coded certificate verification for.
As an attack vector I fail to see how this could be weaponized. Unless you consider ME the thread vector. In which case you have, err, other problems (since I build the binaries that we ship) :-)
That said, I'm happy to see newer versions used - it just never got high enough on my priority list.

**Review by dirkhh — CHANGES_REQUESTED** [review]
Excellent... but I'm a bit unhappy about the sequence of commits. The first one adds things that are removed / replaced in the third, and the second one calls a script with an argument that isn't added until the third one.
so... can we rebase this, squashing the first and third commit together into a new first one, followed by the current second commit?

**Comment by janiversen** [comment]
You wrote what I was just thinking :-) I am apart from security, just sensitive to issues of different versions, that means android could have errors that are solved elsewhere.

Anyhow I hope, me overloading travis and our GitHub is something positive. I have free cycles until end of June (then I will do PADI DM while I work as helper).

**Comment by janiversen** [comment]
I am perfectly OK with squashing commit 1 and 3, but to be honest that superseds my git knowledge. I have now tried 2 times, and end up with wrong commits. If you can do it, please do it.

**Comment by dirkhh** [comment]
YAY, learning opportunity!!!
```
git rebase -i HEAD~3
```
an editor with the three commits will open. Move the third line into second position. Replace the `pick` at the beginning with `s`. Save.
It will now squash the first and third commit and open an editor to edit / adjust the commit message (filled with the two commit messages concatenated).
Save
Done
Review in `git log` (or, nicer, `gitk` - but you need to install that which is a bit of a pain without Homebrew)
`git push -f` into the GitHub branch which will update this PR

**Comment by janiversen** [comment]
@dirkhh 
thanks for the lesson :-) 
"save" was not correct it was "squash", and it seems to do what you wanted.
I did not know you could move the lines, that was the solution.

Lets see if travis is still happy.

**Comment by janiversen** [comment]
@dirkhh seems travis is happy so now it is up to you.

**Comment by dirkhh** [comment]
I meant "save" as in save the edited file... I realize that "s" stands for "squash" :-)
Glad this worked for you. Git is an amazing tool. And the fun of using git to develop Subsurface on Linux is not lost on me (those are the three projects that Linus started...)

**Review by dirkhh — APPROVED** [review]

**Pull request merged**
