### PR TITLE
Core: don't remove dive from trip in add_dive_to_trip()

### PR DESCRIPTION
**Pull request by bstoeger**
All callers of add_dive_to_trip() work on freshly generated dives,
with one exception, that was redundant anyway. Therefore it is not
necessary to remove the dive from a potential previous trip. Move the
responsibility of removing the dive from a trip to the caller,
respectively remove the redundant call. Add a warning message in the
case that trip is set.

Background: On import (either download or file-import) we might not
want to add trips to the global trip-list. For example to enable undo
of import but more generally to detangle that data flow. Thus,
add_dive_to_trip() should not mingle with the global trip-list,
which it has to do if a trip is deleted because the old dive was
removed.

Analysis of the add_dive_to_trip() callers:

1) core/dive.c

pick_trip():
    called on freshly generated merged dive.

finish_split():
    called on two freshly generated split dives.

2) core/divelist.c

create_and_hookup_trip_from_dive():
    called on freshly downloaded dive in dive_cb().
    called on freshly downloaded dive in record_uemis_dive().

autogroup_dives():
    called on dive from get_dives_to_autogroup(), which only
    finds dives that are outside of trips.

combine_trips():
    unused - removed in sibling commit.

try_to_merge_into():
    this call was actually erroneous - dive was already added
    to trip in try_to_merge(). Remove call.

3) core/libdivecomputer.c

dive_cb():
    called on freshly downloaded dive.

4) core/uemis_downloader.c

record_uemis_dive():
    called on freshly downloaded dive.

5) core/load_git.c

create_new_dive():
    called on freshly allocated dive.

6) core/parse.c

dive_end():
    called on freshly parsed dive.

Signed-off-by: Berthold Stoeger <bstoeger@mail.tuwien.ac.at>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

This moves the responsibility of removing a dive from a trip from `add_dive_to_trip()` to the caller. Actually, this function was only called on non-trip dives anyway, so no change needed. Add a warning printf in case the function is called on a dive inside a trip.

While this may look like idle code-reshuffling, it does actually simplify the work-in-progress on dive-import. The problem with automatically removing the dive from the trip is that if the trip becomes empty it is deleted from the global trip-list. But we might not want to add all trips to the global trip-list. For example to make download/import undo-able.

### Changes made:

1) Don't remove dive from trip in add_dive_to_trip().

### CODE REVIEW

**Comment by bstoeger** [comment]
Another small disentanglement of the same flavor: Don't remove dive from trip in `unregister_dive()` as the direct callers of that function already did that.

**Comment by dirkhh** [comment]
The two Travis failures both seem to be network related. Restarting.

**Comment by bstoeger** [comment]
Travis-Mac really has an attitude at the moment. :-/

**Comment by atdotde** [comment]
It sees, for some reason, brew update kicks of a huge thing: I restarted your job which was hung on 

Migrating tap caskroom/cask to homebrew/cask

The restarted job gets past that stage but then appears to be downloading a million and one things from home-brew...

**Review by dirkhh — APPROVED** [review]
This does look sane.

**Pull request merged**
