### PR TITLE
Dive mode csv

### LINKED ISSUE #1588: Add "dive mode" field to CSV dive details export
### Describe the issue:

- [ ] Bug
- [ ] Change request
- [X ] New feature request
- [ ] Discussion request

### Issue long description:

Can we please add a "Dive mode" field to the CSV dive details export format?

### Additional information:

This will facilitate filtering the Subsurface data on external programs...

### PR DESCRIPTION
**Pull request by mturkia**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [x] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Add support for dive mode in CSV export and import

### Related issues:

Fixes #1588 

### Release note:

Added note

### CODE REVIEW

**Review by bstoeger — APPROVED** [review]
I haven't tested it - but code looks very reasonable, thanks!

**Comment by atdotde** [comment]
I have to admit, I cannot tell from looking at the code if it' done or not, but: dive mode should be a string not an int (if we intend to change the corresponding enum at some point).

**Comment by bstoeger** [comment]
> I have to admit, I cannot tell from looking at the code if it' done or not, but: dive mode should be a string not an int (if we intend to change the corresponding enum at some point).

Indeed, I missed that. The question then is: translated or not translated?

**Comment by mturkia** [comment]
The header line is translated, the actual dive mode value is stored as is. And this is a string in Subsurface XML format.

**Comment by atdotde** [comment]
Great, so let's merge

**Pull request merged**
