### PR TITLE
media: load metadata and thumbnails of raw pictures using libraw

### PR DESCRIPTION
**Pull request by mikeller**
The distinguished photographer shoots raw images. There is a
comprehensive library that can extract metadata and thumbnails
from these images. Let's use it if available.

Signed-off-by: Berthold Stoeger <bstoeger@mail.tuwien.ac.at>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### CODE REVIEW

**Comment by dirkhh** [comment]
oddly, PRs against branches don't trigger builds.
But you can easily create this locally, no need for the CI to do this.

**Comment by mikeller** [comment]
> oddly, PRs against branches don't trigger builds. But you can easily create this locally, no need for the CI to do this.

This is just how we've configured our CICD:

https://github.com/subsurface/subsurface/blob/1a3bc9bf7129af837b712fc9bb34bfa06a55dfa1/.github/workflows/linux-ubuntu-20.04-qt5-appimage.yml#L12-L13

I don't think there is any particular intent from our side behind this, but all examples for workflows I've ever seen are doing this.

**Comment by mikeller** [comment]
@dirkhh: Am I correct that it was the Windows build that failed when building `smtk2ssrf`? Because when running the docker based Windows build on this branch it all works fine.

**Comment by dirkhh** [comment]
I'm traveling in Europe... my recollection was that a couple of builds failed, but it's kinda simple... if all the builds pass for you, it works, if not, then, well...

**Comment by mikeller** [comment]
Then let's merge this and take it from there.

**Pull request merged**
