### PR TITLE
Add Cressi Leonardo to list of devices in Android

### LINKED ISSUE #1240: Can't select Cressi (Leonardo) on mobile beta - Android
Should there be an option for the Cressi Leonardo on the download screen?

I'm using a DiveMate fusion IR, was hoping to see if the FTDI would work but I can't select my model from the list.

I had a look on my windows laptop and it seems to use the FTDI in device manager, I wanted to use PortMon, following the instructions from libdivecomputer for the contribution section on transfer protocol but it didn't run in windows 10.

If there's anything I can try to capture on iOS or windows that might help get the fusion IR working in subsurface let me know, comfortable with command lines :)

### PR DESCRIPTION
**Pull request by StephenGoodall**
Adding Cressi Leonardo to the list of devices that can be selected
on Android devices.

Signed-off-by: Stephen Goodall <stephen.goodall88@googlemail.com>

### Describe the pull request:

- [ ] Bug fix
- [x] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:
Adding Cressi Leonardo to the list of devices selectable in Android, This now works when selecting FTDI on some devices.

### Changes made:
1) Add Cressi Leonardo to the downloadfromdcthread.cpp file

### Related issues:
Fixes #1240 

### Additional information:
This may also work for other Cressi Devices that use the FTDI chip but I only have the Leonardo to test it with.

### Release note:
Not sure if this is something that you want to include but a few have asked for it and I have now tested this based on the latest code. Would be great if someone else could try it out aswell (using the official cable) to confirm it works on a different Android device.
Mine was a OnePlus3 using the DiveMate device.

### Mentions:
@dirkhh

### CODE REVIEW

**Comment by dirkhh** [comment]
So this works with the official Cressi PC interface, without any other hardware?

**Comment by StephenGoodall** [comment]
I have only tested it with what I have which is the DiveMate and OTG adapter.
Hopefully another user can confirm for the official cable, possibly @elf128 but not sure what cables or adapter he has.
On the Google groups divinh also mentioned having the official cable so I've asked if they would be willing to test this version of the APK for us:
https://groups.google.com/forum/m/#!category-topic/subsurface-divelog/5hNvowAr0OQ

**Comment by StephenGoodall** [comment]
He may have a Giotto on a second read through.....I could add that to the list/PR aswell and rebuild the apk. Not sure how similar they are for the transfer but they use the same interface cable so should be the same chip?

**Comment by dirkhh** [comment]
OK, since apparently a number of people are trying to get this to work, I'll merge this. Worst case we need to carefully document that this doesn't work with all cables.

Thanks

**Comment by StephenGoodall** [comment]
Should we leave it as just the Leonardo for now and add future ones at a later date? Or add them all so people can try it for the Giotto/Edy/Drake/Newton on the beta version? I have no idea how the last 3 work so not sure if they use the FTDI stuff.

**Comment by dirkhh** [comment]
I don't either - this is a big part of what makes me so uncomfortable here... I have no access to any of these dive computers, I don't know how the download works, I don't know if they are using the same protocol, etc.
From looking at the sources it seems like Leonardo, Giotto, Newton, and Drake may use the same parser, but Edy is different. But I don't know if there are other differences.

**Comment by elf128** [comment]
Ok, finaly got some time to get into this. Sorry for delay.

First of all, thank you for making it happen.
Second, I don't have official cable.
Third, following text is not a request to change something. It's mostly to _leave a trace for the people who will follow my path_, so they can understand why certain things the way they are.

I'm having troubles building subsurface myself at the moment however, I grabbed test build with this changes and tried it.

There are multiple things about serial implementation in the subsurface. First, Stephen's fix is just tip of an iceberg. There is FTDI part of this issue.

I was wrong, VID:PID pair does matter for subsurface-mobile because of two reasons.
1) app declare support of certain VID:PID pairs. That's how you're getting a pop-up when you connect "right device". This is something which happened in parallel. Cressi interface have been added into this list long time ago, but there was a copy-paste error. That have been fixed in Jan.
This is where it is declared:  _subsurface/android/res/xml/device_filter.xml_ 
2) Serial implementation use FTDI library which open an interface based on VID:PID pair that's why, again, you need proper device declaration. But there's no connection between the interface you're choosing from the menu and device's PID.
This is where all this is happening: _subsurface/core/serial_ftdi.c_

There're couple of things to take away from it.

_First. VID has to be 403. ( which is FTDI )
It is a must. It's hard coded pretty much everywhere._ 

_Second. You need to have ANY PID from the list. The system doesn't care what DC you have chosen. As long as it's interface is FTDI it just goes through the list._

Here is the list of accepted PID from the code
`int accepted_pids[] = { 0x6001, 0x6010, 0x6011, // Suunto (Smart Interface), Heinrichs Weikamp`
`    0xF460, // Oceanic`
`    0xF680, // Suunto`
`    0x87D0, // Cressi (Leonardo)`
`};`

Bottom line, if you have Cressi Gioto, but you're using Suunto (Smart Interface) or your device pretend to be the one, you're good to go. 
Probably this is the reason, why Dive mate happen to work with this patch cause it's FTDI based ( VID is 403 ) and PID is one of the accepted.

So, I changed my device's FW  from this:
`usb 2-1.3.7: new full-speed USB device number 96 using ehci-pci`
`usb 2-1.3.7: New USB device found, idVendor=0483, idProduct=5740`
`usb 2-1.3.7: New USB device strings: Mfr=1, Product=2, SerialNumber=3`
`usb 2-1.3.7: Product: STM32 Virtual COM Port  `
`usb 2-1.3.7: Manufacturer: STMicroelectronics`
`usb 2-1.3.7: SerialNumber: 6D7042615251`
`cdc_acm 2-1.3.7:1.0: ttyACM0: USB ACM device`

to this:
`usb 2-1.3.7: new full-speed USB device number 97 using ehci-pci`
`usb 2-1.3.7: New USB device found, idVendor=0403, idProduct=87d0`
`usb 2-1.3.7: New USB device strings: Mfr=1, Product=2, SerialNumber=3`
`usb 2-1.3.7: Product: IRDA Virtual USART Port `
`usb 2-1.3.7: Manufacturer: FTDI'ish interface`
`usb 2-1.3.7: SerialNumber: 6D7042615251`
`cdc_acm 2-1.3.7:1.0: ttyACM0: USB ACM device`

So first part is working.  Now device connection bring a pop-up with offer to use Subsurface-mobile with the device.

Second part is not working yet.
Device is found and open correctly, but somebody have decided that before sending the data it's required to call ftdi_usb_reset and whole opening procedure is failing in case this function does not return a success.

Now, I don't want to argue about whether it's right or not to require this function to succeed. So we're not changing the code, but I have to change device to react like it is an FTDI chip to make Stephen's patch work.

I've got sources of FTDI and looked it up. It tries to send a control message to the chip and return error if usb device does not respond to it right. 

I can see this msg get to device and I can debug it, so I probably will make a hack to make ftdi_usb_reset() happy, but it will take some time.

I'll make an update when this will work.

Thanks

**Comment by StephenGoodall** [comment]
Perhaps the issue with the Giotto is that it may use a different driver to the Leonardo:
https://www.libdivecomputer.org/drivers.html

Suggests a "Prolific" driver for non-Leonardo Cressi devices rather than FTDI?

Perhaps selecting the Mares Nemo Sport option might work, looks to have the same VID/PID values.

DiveMate seems to emulate the VID/PID depending on which device you tell it you have. I'm at work now, but when I get home tonight I will have a play and see what it shows up as in the "USB Device Info" app after selecting the following Cressi Devices:
Cartesio
Leonardo - I know this is 0x0403/0x87D0
Giotto
Goa
Newton
Drake

I will get a screenshot from each in case it is useful for any future investigation - you might be able to use the information with your custom interface (changing your FW to match the values)

**Comment by glance-** [comment]
You don't choose device in the menu. The only thing you can choose at the moment is "FTDI", and it will try to find a approperate FTDI device to use.

Second, Don't try to impersionate a device that you're not.

You have hacked your device to show up as idVendor=0403, idProduct=87d0 , but its not a FTDI device. Its a USB ACM device, and thats a compleatly different protocol.

It shouldn't be that hard to write a serial thingie which talks USB ACM, its quite a simple protocol, but we don't have one at the moment.

And, no, Prolific is yet another protocol which we don't support in the mobile app.

**Comment by elf128** [comment]
Hey @StephenGoodall, Don't worry about those screenshots.
I can bet, Dive Mate is based on popular FT232 USB Serial converter. Which happen to have PID = x6001, which is in the list already. It doesn't emulate anything, it's just lucky coincidence.
Currently, subsurface-mobile support only ftdi. And, most likely, nobody will extend it. Especially with the latest tendency of moving toward BLE.
So, I would not bother even talking about native support of _____ ( insert you device here ). If somebody want to add support of cp210x they're most likely welcome to do it them self. _Code maintainers don't have hardware on hands and, which is more important, have bigger fish to fry._

And @glance, as of "Don't impersonate...", hmm, I would rather use "emulate" here. We're not just changing descriptors, right? The stuff I've throned in was just a starter.  
Look. FTDI, CP21, ACM... In a nutshell, they are all ridiculously similar. Transport is pretty much identical. There're some chip-specific control transfers, but wast majority is not even used. There's no point to implement everything. No flow control, predefined baud-rate and formats. As long as device feeding the data driver expect and reply within timeout limits - everybody happy. 

BTW, I'm not asking anybody to do it. Quite opposite. I'm trying to make my stuff working with a least disturbance to community.
I'm sorry if my post brought some confusion. If subsurface support ftdi — fine, good enough for me. I'm not asking to change anything. 
I'm glad my DC itself is unblocked, thank you again for that.

**Comment by elf128** [comment]
Small heads up.
Finally had a chance to implement all I said above on my hardware. Once I've resolved all ftdi issues, Subsurface start working with Cressi Leonardo without any issue.
@StephenGoodall  your fix is working. Thank you.

img_20180915_225654_hdr

img_20180915_225740_hdr

**Pull request merged**
