### PR TITLE
MXE: move the objcopy calls to cmakelists.txt

### PR DESCRIPTION
**Pull request by neolit123**
### Describe the pull request:

- [ ] Bug fix
- [x] Functional change
- [ ] New feature
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

follow up on #811.

The objcopy calls to strip the debug symbols out of
subsurface.exe need to happen before the installer is
created (staged).

**note: WIP! please, do not merge until we get this right.**

### Mentions:

@dirkhh @sfuchs79

### CODE REVIEW

**Comment by dirkhh** [comment]
This looks reasonable. Once the Travis run has finished, can you download the resulting build artifacts and check that this works as expected?

**Comment by neolit123** [comment]
`message(STATUS "Build type is 'RelWithDebInfo'. Creating debug symbols in a separate file.")`
is not even called for some reason...

**Comment by neolit123** [comment]
@dirkhh @sfuchs79 

got this working finally after a *few* iterations.
the `objcopy` commands are now called right after the `exe` is created.

**Comment by neolit123** [comment]
stats wise: the executable with the debug symbols inside the installer get compressed so well that the installer is not inflated that much. probably best to still ship the debug symbols separately.

**Comment by sfuchs79** [comment]
Works fine here as well - thanks!
I would say the config as it is now is the right one: Only put the exe w/o debug symbols in the installer.
It doesn't really happen so often that we need to ask a user to debug s.th., isn't it?

**Comment by neolit123** [comment]
thanks for testing. merging this, so that we move the debug symbols away from the installer.

**Pull request merged**
