### PR TITLE
Planner test, added last test of conversions

### PR DESCRIPTION
**Pull request by janiversen**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [x ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Added test of gas variables.

There is a problem with one of the test cases for decopo2. Bottompo2 contains exact the same
code and tests but do not have problems. This is something I will investigate a bit more.

### CODE REVIEW

**Review by dirkhh — APPROVED** [review]
as I look at that I realize that we don't appear to run `make check` as part of the GitHub Actions anymore. I need to fix that.

**Comment by janiversen** [comment]
I have noted that too. Remark the TestPlannerShared is only available in build-mobile (due to link problems in the desktop, commands references mainWindow::instance(), not the best separation backend/UI).

**Comment by dirkhh** [comment]
> I have noted that too. Remark the TestPlannerShared is only available in build-mobile (due to link problems in the desktop, commands references mainWindow::instance(), not the best separation backend/UI).

definitely something to fix at some point - I'll look into it.
In the meantime I'll make sure we test in both desktop and mobile builds.

**Comment by dirkhh** [comment]
That said, I have some tests failing right now :-/

**Comment by janiversen** [comment]
Yes because you have a bug fix PR outstanding #2476.

And as noted in the PR, I have a strange problem with decopo2 and some very specific values. I am right controlling the Qt sources to see how they do fuzzy double compare.

**Comment by janiversen** [comment]
Now all the new test cases works here. I will remove the //TEMP once I find out why
bottompo2 can test 1.1 but decopo2 cannot.

**Comment by dirkhh** [comment]
I have unrelated tests failing... e.g. `TestGitStorage` -- which is one that I __REALLY__ don't like to see failing...
I am not saying that this has anything to do with your code. Maybe I shouldn't have added that comment here and instead on my PR.
Please ignore

**Comment by janiversen** [comment]
@dirkhh interesting, when I do
cd build
make check
-- or --
cd build-mobile
make check

It builds the exe and then I get some strange errors:

[100%] Built target TestQML_autogen
[100%] Built target TestQML
make[3]: *** No rule to make target `../tests/if', needed by `tests/CMakeFiles/check'.  Stop.
make[2]: *** [tests/CMakeFiles/check.dir/all] Error 2
make[1]: *** [tests/CMakeFiles/check.dir/rule] Error 2
make: *** [check] Error 2


I do not know if it is related to your problem, but wanted to inform you.

**Review by dirkhh — APPROVED** [review]

**Pull request merged**
