### PR TITLE
[Build Fix] Remove non-trivial designated initializers

### PR DESCRIPTION
**Pull request by tcanabrava**
Some C++ compillers (like g++) don't have non-trivial
designated initializers, we can replace that with a lambda
with just a bit more verbosity in the code.

The actual error:
core/qtserialbluetooth.cpp:617:1: sorry, unimplemented:
non-trivial designated initializers not supported

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### CODE REVIEW

**Comment by neolit123** [comment]
hi, Tomaz.
i had the same error and Linus told me that i just need to update the libdc module.
`git submodule update`

if libdc is updated the initializers in `core/qtserialbluetooth.cpp` do have all struct elements and the order is correct too.
http://lists.subsurface-divelog.org/pipermail/subsurface/2018-March/031565.html

**Comment by tcanabrava** [comment]
Then a change in libdc could break it too, while with this patch things will always work.

**Comment by neolit123** [comment]
i guess that's true. i will leave it to @dirkhh to decide if he likes the lambda initializers.
the commit needs a `signed-of`, btw.
thanks.

**Comment by dirkhh** [comment]
There is a reason why libdc is now a submodule and tightly coupled with Subsurface. It's exactly so that we have matching versions at all times. Subsurface isn't designed to be built against anything but the included libdc - and the build scripts take care of that.

I don't think this PR solves anything that needs solving.

**Comment by bstoeger** [comment]
> There is a reason why libdc is now a submodule and tightly coupled with Subsurface.

Is there any advantage compared to just pulling it in completely? Because obviously, I'm too stupid for this submodule business: https://github.com/Subsurface-divelog/subsurface/pull/799

**Comment by neolit123** [comment]
you can add this as a file named `post-merge` in `.git/hooks`
```
#!/bin/sh
echo "[post-merge hook]"
git submodule update --init --recursive
```

works for `pull --rebase`, `pull`, `merge`. haven't tried everything.

**Comment by dirkhh** [comment]
> Is there any advantage compared to just pulling it in completely?

Yes, massive advantage. Because now Linus can manage this as if it was a branch of upstream libdc which gives him better tooling and less work when merging Jef's changes. Having this inside of Subsurface would make this a TON more complex and frustrating.

**Pull request closed without merging**
