### PR TITLE
More cicd experimentation

### PR DESCRIPTION
**Pull request by dirkhh**
### Describe the pull request:

- [x] Bug fix
- [x] Build system change

### Pull request long description:

I was way too optimistic when it comes to what is possible within the yaml syntax.
This isn't bash. So I undid a few "improvements" I tried.

### CODE REVIEW

**Review by mikeller — APPROVED** [review]

**Comment by dirkhh** [comment]
I'll rebase on top of latest master so I can merge this more easily.

**Comment by mikeller** [comment]
🤞

**Comment by dirkhh** [comment]
well, the posting of the release has worked... with the correct release number. So that's a good start.
Now lets see if the Windows and Android builds succeed.

**Comment by mikeller** [comment]
Now colour me stumped:

Why is `$GITHUB_WORKSPACE` evaluating to  `/__w/subsurface/subsurface/` in 
https://github.com/subsurface/subsurface/blob/506a96f1f6cbe4279ecfb44fca24f4d985bd571c/.github/workflows/android.yml#L63 ???

**Comment by dirkhh** [comment]
I have given up trying to understand the logic of what is where in GH actions

**Comment by mikeller** [comment]
I'll be doing some experimentation to get some empirical findings.

**Pull request merged**
