### PR TITLE
downloader: Fix typo in libdivecomputer include

### PR DESCRIPTION
**Pull request by henrik242**
Signed-off-by: Henrik Brautaset Aronsen <subsurface@henrik.synth.no>

### CODE REVIEW

**Comment by atdotde** [comment]
Obviously correct.

**Comment by atdotde** [comment]
Waiting for tests, will then merge.

**Comment by henrik242** [comment]
@atdotde Weird that this typo didn't cause a build failure, though.

**Comment by atdotde** [comment]
Nobody has yet created CI tasks for the downloader.

**Comment by dirkhh** [comment]
I created a PR to build the downloader in one of the CI builds.

**Pull request merged**
