### PR TITLE
Typo: UCT to UTC

### PR DESCRIPTION
**Pull request by mturkia**
Signed-off-by: Miika Turkia <miika.turkia@gmail.com>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [x] Language translation

### Pull request long description:

Fixing misspelled UTC

### CODE REVIEW

**Comment by PeterZaal** [comment]
Yes, I noticed the same incorrect spelling in the translations on Transifex. I guess this means this new string has to be pushed to Transifex also. But maybe/probably there are more strings updated elsewhere, so guess strings will be pushed to Transifex anyway shortly before release so translators can get everything updated to the latest.

**Comment by mturkia** [comment]
> Yes, I noticed the same incorrect spelling in the translations on Transifex. I guess this means this new string has to be pushed to Transifex also. But maybe/probably there are more strings updated elsewhere, so guess strings will be pushed to Transifex anyway shortly before release so translators can get everything updated to the latest.

Yep, this is how it is supposed to go. Dirk will need to push the new strings to Transifex, and pull translated strings before release.

**Comment by dirkhh** [comment]
While I know this, I keep stumbling over it...
https://en.wikipedia.org/wiki/Coordinated_Universal_Time#Etymology
Thanks and Ill push updated strings in a moment.
Historically we tended to always have a couple of late changes, usually only very few strings. Why would this release be any different :-)

**Comment by dirkhh** [comment]
The string is pushed - it was the only new string, and since it was trivial to do, I fixed it in all languages where it was already translated (and almost all of them had already used the correct abbreviation, anyway, so all I had to do was to fix the match).
I also fixed a couple of places where we had the same typo in code comments :-)

**Pull request merged**
