### PR TITLE
build system: try harder to checkout the right version

### PR DESCRIPTION
**Pull request by dirkhh**
And actually fail a build if that doesn't work.

Signed-off-by: Dirk Hohndel <dirk@hohndel.org>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [x] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

use `git checkout -f` to avoid the weird 'can't checkout your branch/tag' issue
and fail a Travis build if we indeed cannot checkout the branch/tag that we want

### Related issues:

#1928 

### Mentions:

@janmulder - do you want to merge this and rebase on top of it?

### CODE REVIEW

**Review by janmulder — COMMENTED** [review]
Not fully understand what you mean with merge and rebase.

We have to do some cleaning up. The dirkhh-libgit2-0.26.8 branch also contains relevant stuff , but not all is relevant I think. Lets first decide if we go to libgit2-0.26.8 or stick at 0.26.0 or ... even test some more to go to 0.27.X. This commit (try harder) is the right thing to do.

**Comment by dirkhh** [comment]
Sorry, I knew that today would be a "no Subsurface until very late" day. I'm traveling for work and was in meetings all day... What I meant was
- merge this one if you agree (I'll do that in a moment, based on your comment)
- then rebase your branch on this one and continue to see what we can figure out.

**Comment by janmulder** [comment]
Ok, rebased the dirkhh-libgit2-0.26.8 branch, stripped the install of libgit2-0.26.8 as the 0.26.0 will do at this point (so modified your commit), and reworded and squashed some things. Just see if you like it. All compiles now (not sure about the openSuse packaging, as said somewhere else). The coming days I'm more or less offline, so just continue as you see fit.

**Comment by dirkhh** [comment]
Thanks for that. I'll take a look at that branch.

**Pull request merged**
