### PR TITLE
Planner

### PR DESCRIPTION
**Pull request by atdotde**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

The regression variables should be part of the planner state held in struct planner_state. This adopts Bertholds changes to this.

### CODE REVIEW

**Comment by bstoeger** [comment]
I'm fine with this, but somehow the two branches conflict. I'm not well versed enough with git to understand what is going on.

**Review by bstoeger — APPROVED** [review]

**Comment by dirkhh** [comment]
So, what's the difference between this and #2211?

**Comment by bstoeger** [comment]
This does not introduce a `regression` structure, but puts the variables into the `deco_state` structure.

I could also imagine introducing a regression structure and put *that* into the deco_state structure.

**Comment by atdotde** [comment]
Dirk,

> On 8. Aug 2019, at 18:11, bstoeger <notifications@github.com> wrote:
> 
> This does not introduce a regression structure, but puts the variables into the deco_state structure.
> 
> I could also imagine introducing a regression structure and put that into the deco_state structure.
> 
> 
I fetched Bertholds’ branch and then rebased interactively changing one commit not to introduce a new structure but to integrate the variables in the existing deco_state struct. The later commits are adopted to this change but but changed otherwise. I would recommend to merge my version of this branch with master.

Best
Robert

**Comment by dirkhh** [comment]
Merged manually

**Pull request closed without merging**
