### PR TITLE
Bugfixes for reverse geo lookup

### PR DESCRIPTION
**Pull request by sfuchs79**
### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Reverse geo lookup string for http://api.geonames.org corrected.
Language selection should now work again with string "lang=xx".

In location information UI set reverse geo lookup button activ as soon as coordinates are available.

### CODE REVIEW

**Comment by dirkhh** [comment]
Do you want to update this based on the feedback by Guillaume on the mailing list?

**Comment by sfuchs79** [comment]
Yes, sure. Looking for a clever way to do it but I think I found one...
BTW: The Travis fail is not from me! :-)

**Comment by dirkhh** [comment]
No, Travis breakage is mine and I hope I just fixed it...

**Comment by sfuchs79** [comment]
Pushed an update.
Hope this works for every language string...

**Comment by sfuchs79** [comment]
BTW - two questions:
- The two other providers listed in the code (divelogs.de and open.mapquestapi.com) are not used at all?
- What functions do we have now (or should we have now) with the reverse geo lookup? Is it only retrieving the country name or does this do anything else? There is some code regarding the ocean name but I didn't figure out what this does.

**Comment by dirkhh** [comment]
This is one of the many features where we had great ideas and ran out of time and energy... and by 'we' as so often I mean 'I'. I'd love to see support for more providers!

Right now we get four levels of geo hierarchy (so down to the closest city) plus the ocean.
This is shown in Subsurface as 'tags' above the location :-)

**Comment by sfuchs79** [comment]
Ahhhh!! Then I found another bug... and maybe this will bring us closer to the crashes again:
The "tags" thing never worked here for me. What I get is this:
grafik

**Comment by dirkhh** [comment]
That can happen if the geo service failed.
This works right now when run in English (which, honestly, is the only thing I test...)

**Comment by sfuchs79** [comment]
Tested now when run in English with same result. Plus the geo lookup at least returns the country name which means it doesn't fail completely. Plus why is "tags:" printed there? ;-(

And also I have the info in my log file, e.g.:
grafik


But they are not displayed:
grafik

Some data going somewhere but not into the right place?

**Comment by dirkhh** [comment]
I'm about to go diving, so I won't be looking at this for a while. I'd love it if you could add some debug messages to figure out what's wrong... :-)

**Comment by sfuchs79** [comment]
Didn't want to hear to first part of what you are saying! :-)

Ok, regarding the issue: No real bug. Huge part of the problem sitting in front of the PC.
But room for improvement to make users like me happy... will sent a PR soon.

Improvements will include translation. But I can't get tr() function to work in divesite.cpp:
/home/stefan/Entwicklung/Subsurface/subsurface/core/divesite.cpp:19:101: error: 'tr' was not declared in this scope
    locationTag = QString("<small><small>") + tr("No dive site layout categories set in preferences!") + QString("</small></s
Help?

**Comment by sfuchs79** [comment]
I'm getting closer to find the source for the crashes:
grafik

**Comment by tcanabrava** [comment]
On Mon, Oct 16, 2017 at 3:26 PM, Stefan Fuchs <notifications@github.com>
wrote:

> Didn't want to hear to first part of what you are saying! :-)
>
> Ok, regarding the issue: No real bug. Huge part of the problem sitting in
> front of the PC.
> But room for improvement to make users like me happy... will sent a PR
> soon.
>
> Improvements will include translation. But I can't get tr() function to
> work in divesite.cpp:
> /home/stefan/Entwicklung/Subsurface/subsurface/core/divesite.cpp:19:101:
> error: 'tr' was not declared in this scope
> locationTag = QString("") + tr("No dive site layout categories set in
> preferences!") + QString("</s
>

try QObject::tr

Help?

**Comment by sfuchs79** [comment]
@tcanabrava Thanks! Together with a #include <QObject> at the right place this works. Hell, why are there 100 different calls to do the translations??? ;-)

**Comment by tcanabrava** [comment]
On Mon, Oct 16, 2017 at 3:56 PM, Stefan Fuchs <notifications@github.com>
wrote:

> @tcanabrava <https://github.com/tcanabrava> Thanks! Together with a
> #include at the right place this works. Hell, why are there 100 different
> calls to do the translations??? ;-)
>

Only one. the one that inhertis from QObject. the problem is that sometimes
we are not inheriting from it and still want to use the tr. :)

**Comment by sfuchs79** [comment]
Me understand nothing. Me being the contributor with worst C, C++, SW, whatever knowledge here!
But nevermind - it now works and sometimes I even add some value. :-)
And now I'm going to fix this stupid chrash...

**Comment by dirkhh** [comment]
You add a lot of value, @sfuchs79 
tr() is a call we get from Qt. Every class that is somehow derived from QObject has the tr() class. But when we write C++ functions (to get some of the advanced features C++ offers) that aren't part of a class, we need to tell the compiler where to get the function from...
Thanks for working on this!

**Pull request merged**
