### PR TITLE
Mobile: build system, new Kirigami SHA and ...

### PR DESCRIPTION
**Pull request by janmulder**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [x] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:
... fix of a resulting issue. While most new commits are QML improvements, there is a change in the Kirigami build related to static building (like we do), and Cmake restyles to make
things more Qt compliant.

As now, the (generated) qrc_kirigami.cpp is included from kirigamiplugin.cpp, for static builds, our build failed on double defined symbols. For details of the relevant Kirigami commit see 8c34dde11.

The fix on our side is simple. Do not add the resource at our end, as it is already on the Kirigami side.

Signed-off-by: Jan Mulder <jlmulder@xs4all.nl>

### CODE REVIEW

**Comment by janmulder** [comment]
Ok, this is valid fail on Travis, so rethinking about this one ...

**Comment by janmulder** [comment]
@dirkhh: it seems that newer Kirigami sha's will enable us to restyle our build (wrt. Kirigami). Currently, that is a somewhat weird process. Clone the Kirigami repo, checkout the SHA we like, and copy a bunch of files to our tree. This copy, I do not like, and we probably cloud compile Kirigami like we, do, for example, the googlemaps plugin or libdivecomputer. The copy, results in numerous re-compiles  as the Kirigami files (that basically never change, except for explicit SHA changes) are touched, for example when working in Qt Creator.

So, I'm tempted to modify this, but, that said, our set of build scripts is not the nicest piece of code, so I'm afraid to break things (or simply forget to also edit duplicate occurrences, like in the Travis scripts).

But ... is there another reason, I might not see at this point in time, for the way the Kirigami stuff is embedded in our build? Or is it just history from the early days of mobile development?

**Comment by dirkhh** [comment]
The genesis of this is kinda stupid. We used to keep the Kirigami source in our source repo. And then later we pulled from theirs, but in order not to have to make too many changes (or maybe because there was initially a build issue if this wasn't done this way - I'm not 100% sure) we did this copying thing.
I'm more then happy to consider a better way of building this. The challenge is that the builds for Android (cmake) and iOS (qmake) are very different and that it's easy to mess things up. But feel free to change things around - it does make more sense to build it by itself

**Comment by janmulder** [comment]
Hmm. Not sure about the isolated build of Kirigami. I have it locally working for Arch Linux and Android, but as Kirigami is tightly coupled with the KDE style build process, I needed to install the KDE ECM (https://github.com/KDE/extra-cmake-modules) stuff on my Linux Box. Ok, that is not a show stopper, but it means that every developer (not being involved in KDE stuff) has to install that too (as I do not think we should embed that ECM stuff in our repo, or pull it in dynamically during build). So that means adaptation on every platform we build on, like Travis or other external builders.

In addition, we do some hackish patching of Kirigami (hiding the action buttons with the keyboard open), which we obviously still could do when building as a separate library, but I feel this defies the logic of a separate build.

**Comment by dirkhh** [comment]
Yuck. Then no, let's not do that.

**Pull request closed without merging**
