### PR TITLE
Sensor index fixup

### PR DESCRIPTION
**Pull request by torvalds**
### Describe the pull request:

- [x] Bug fix
- [x] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

This fixes up the pressure sensor index code to not be quite so eager to get rid of pressures that it doesn't understand.

In particular, if for some reason a dive computer was saved with a pressure sensor index bigger than the number of cylinders, it now tries to fix up the situation by renumbering the indexes to a minimal set. And if even that doesn't then fit in the number of cylinders, we just accept the sensor data as-is rather than clear it.

The user can then add cylinders as needed, or whatever.

### CODE REVIEW

**Comment by torvalds** [comment]
Hmm. I have no idea why that "TestRenumber" fails on Ubuntu but not on Fedora (and not on my local Fedora/arm64 build).

Strange.

**Comment by torvalds** [comment]
Ahh. We have code that depends on the sensor index never being bigger than the number of cylinders.

Ugly, ugly.

**Review by 3kh0 — APPROVED** [review]
Looking good!

**Comment by dirkhh** [comment]
So, Linus, what's the status of this one?

**Comment by torvalds** [comment]
Ok, looking at it. That test-case ends up with insane samples that have "s->sensor[x]" value of 255.

And the reason turns out to be that @bstoeger commit 361678dcbe introduced sanitize_sensor_id(), which does

        return d && nr >= 0 && nr < d->cylinders.nr ? nr : NO_SENSOR;

but the type of that function is 'uint8_t'.  So it doesn't actually return NO_SENSOR (-1) like the comment says, but 255.

We ended up hiding that by then later doing "if we have a sensor index that is larger than number of cylinders, clear it", so this bug was hidden by that whole thing. And when I removed the clearing, that just uncovered this odd issue.

I'm not sure why that test-case triggers this odd problem (and nothing else does), and I'll have to figure out what the proper solution is, but at least I see why it happens.

**Comment by torvalds** [comment]
Oh, and that sanitize_sensor_id() was actually correct when introduced, but then @bstoeger commit 0c84f369c35b ("core: use int16_t for sensor-id") changed the type for the sensor index, but didn't fix this helper.

**Comment by torvalds** [comment]
Ok, I have force-pushed an updated version of this branch.

It takes a different approach to the sensor index thing - instead of renumbering sensors to fit in the cylinders, it will just add empty cylinders as required to make the sensor data fit. 

I verified with your Palau 2016 data that this simply creates a new cylinder for those dives with the Atomic Aquatics dive computer, and it now looks like you have two different cylinders when you look at those dives. So now if you want to fix that up, you'd have to do the sensor remapping first, and then delete the second cylinder.

That was not only the simpler fix, but also the safer one. We don't do any "let's just automatically renumber sensors", and we don't throw any data away.

Let's see if it passes the test-suite now.

**Comment by torvalds** [comment]
> Let's see if it passes the test-suite now.

So far so good, but it might be worth pointing out that this pull request has three commits, and two of them are basically just preparatory fixes that are only indirectly related. 

All the *meat* of the pull request is in that last commit, with the two first ones just fixing that sensor type confusion, and fixing up the order of the dive fixups.

It all looks "ObviouslyCorrect(tm)" to me, but hey, so did the previous version. It just happened to uncover preexisting issues that were hidden by the sensor clearing. This one feels much safer, but who knows what it might uncover.

**Review by dirkhh — APPROVED** [review]
I read the code. I ran it against my dive data (forcing saves so I see what it does).
It seems correct, and I like it MUCH better than the previous version. This seems logical and consistent.
I requested a review from @bstoeger as well as it touches his code :)

**Review by bstoeger — APPROVED** [review]
Not sure my comment is needed here.

The `uint` -> `int` change fixes an obvious oversight (and I find it slightly annoying that we didn't get a compiler warning here). As for the sensor thing I still don't understand the data structure and will never use this part of the code.

So fine with me.

**Pull request merged**
