### PR TITLE
[TRIVIAL] Cleanup: remove unused macro SURFACE_PRESSURE_STRING

### PR DESCRIPTION
**Pull request by bstoeger**
The last user was removed in c3f07b9f81f09421a92d42d1b98e7c984b75e20d.

Signed-off-by: Berthold Stoeger <bstoeger@mail.tuwien.ac.at>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Trivial cleanup, see commit message.

### CODE REVIEW

**Comment by bstoeger** [comment]
@dirkhh: Any idea what is going on with the Qt5.6 build?

**Comment by dirkhh** [comment]
> @dirkhh: Any idea what is going on with the Qt5.6 build?

It seems that there were some issues with SUSE's infrastructure for updating that openSUSE version used in that particular build - I restarted it (just as I did on the other PR where the restart worked).
BTW: I am 99% sure that you can restart builds as well, @bstoeger ... and if you can't, we need to fix that

**Review by dirkhh — APPROVED** [review]
Just waiting for that final Travis build to go green. Not that it really seems worth it, now that I think about it... actually, no, I'll just merge.

**Comment by bstoeger** [comment]
> I am 99% sure that you can restart builds as well

I restarted it numerous times - it always hung. ☹️

**Comment by dirkhh** [comment]
> I restarted it numerous times - it always hung. ☹️

And at some point we may need to change distros if that's an ongoing issue. There are a couple on Qt 5.6, I think. After all, that's one of the Qt LTS releases.

**Pull request merged**
