### PR TITLE
Elevate "can't write hashes" message from debug to warning level

### PR DESCRIPTION
**Pull request by bstoeger**
I never realized that my hashes weren't written, because it only
outputs a debug instead of a warning message.

Signed-off-by: Berthold Stoeger <bstoeger@mail.tuwien.ac.at>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### CODE REVIEW

**Comment by sfuchs79** [comment]
Stupid question about this change:
Shall the qWarning be displayed in the UI? If yes can this ever work because maybe the whole UI is already destroyed when then hashes are written to disk?

**Comment by bstoeger** [comment]
qWarning() only writes to the console.
write_hashes() is called in the destructor of MainWindow(), so in principle the UI is still alive and you can show message boxes, etc. But calling UI stuff in a destructor of a QObject sounds like a very bad idea. Destructors are special and should only free resources. The reason being that you have a semi-destructed object in your object tree. 

One could for example move the write_hashes() call to after qApp->exec(). This would make more sense than a destructor. And one could create a MessageBox there. But in the end it's such a peculiar case that I wonder if it's worthwhile to show this message to non-developers?

**Comment by dirkhh** [comment]
I think the reason for having it in the destructor was to catch more ways in which the app could exec. But there's no reason why we can't make a "first attempt" to save in qApp->exec() and set a flag when things were successfully saved (and then try as last resort in the destructor).
@atdotde what do you think?

**Comment by bstoeger** [comment]
Can the hashes change without calling qApp->exec(), i.e. without user interaction? Then yes, placing it in run_ui() would be a bad idea. exit_ui() could be an alternative.

**Comment by atdotde** [comment]
The hashes are (potentially) modified upon loading images. I don't see how that could happen without there being a main window. Saving the thumbnails is just for performance (spend a but more at startup time and have them ready when navigating the dive list). The image hashes are necessary for the "find the images by hash sum rather than path" functionality. 

I put the write hashes code in the main window destructor since that seemed to be a natural place for something that needed to be done upon  closing the application. I am agnostic about the exact placement. And I don't know if we need to raise this warning at the UI level given that we don't lose a lot of functionality and that fixing potential problems is very likely beyond a UI user's ability (my guess would be permission problems except for disk full problems). And permission problems should only occur for users that circumvented the "don't run subsurface as root" start-up test. So I would say they are on their own and should be able to handle console output.

**Comment by bstoeger** [comment]
Ok, so one might argue that if the UI isn't started (-q option) there's no need to load/save hashes and one could  therefore move the read_hashes()/write_hashes() functions into the run_ui() function. But at the end of the day, this is such an obscure use case that the change isn't worth it. Let's just keep it the way it is - it does what it's supposed to do.

**Comment by bstoeger** [comment]
Ignore last comment - the whole point of the -q option is to measure startup time.

**Pull request merged**
