### PR TITLE
 Add Scubapro Aladin Sport Matrix to list of supported dive computers

### PR DESCRIPTION
**Pull request by bstoeger**
The protocol is essentially identical to the Scubapro G2.

Moreover, recognize Bluetooth devices advertised as "Aladin" as Aladin Sport Matrix.

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Documentation change
- [ ] Language translation

### CODE REVIEW

**Comment by dirkhh** [comment]
You can see that this pull request is problematic. It again includes an old commit that I already pulled, then it includes a merge (NO, really, don't do that, EVER). And then the one new commit.

Normally I'd ask you to re-do the pull request, but for now I'll just merge the one new commit manually.

**Comment by dirkhh** [comment]
No, I take it back. The commit is missing your "Signed-off-by"...
Also, the SuppoertedDivecomputers.txt file is automatically created from the src/descriptor.c file in libdivecomputer... so you'd have to add the additional name THERE to avoid it from being overwritten again (or change the scripts/parse-descriptor.pl file if this is something that can't be added in libdivecomputer).

**Comment by bstoeger** [comment]
Sigh - sorry. I noticed that, but was unable to reset the master branch and hoped that the problem would somehow fix itself. I simply don't understand git. :(

**Comment by dirkhh** [comment]
so the way you do it is simple...
check out a clean copy of master (if necessary, clone a new copy)
git checkout -b 'aladin'
make the changes you want
git commit -s -a
push that branch to gihub and create a pull request

**Pull request closed without merging**
