### PR TITLE
desktop: improve composition on TagWidgets

### PR DESCRIPTION
**Pull request by bstoeger**
The TagWidgets hook into the textChanged() signal to invoke
the word-completer. However, that signal is also emitted for
composition-keys, making composition impossible if the completer
decides that it should show some entries.

Instead, hook into the inputMethodEvent() function, where one
can test whether a real character was input.

Also, don't hook into cursorPositionChanged(), since that led
to an uncanny cascade of reparse() calls when editing text.

The UI experience is still rough as sometimes the completer
popup steals the focus and hinders further entry.

Also, this doesn't fix the location field, which is its own class.

Signed-off-by: Berthold Stoeger <bstoeger@mail.tuwien.ac.at>

### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Try to improve composition in the TagWidgets by not reacting to `textChanged` but to `inputMethodEvent`.

### Changes made:

1) Hook into `inputMethodEvent` instead of `textChanged`.
2) Don't listen to `cursorPositionChanged` signal.
3) Minot code cleanups.
### Related issues:

Fixes part of #1405.

Needs testing! The whole interaction with the completer is ominous.

### CODE REVIEW

**Comment by bstoeger** [comment]
OMG, this is so horrible. The popup opened by the completer by default does not have the `WA_InputMethodEnabled` set and therefore doesn't get these events. Thus, composition is broken as long as the popup is open.

Set the flag explicitly when starting completion.

@dirkhh: Could you perhaps check with your Qt contacts - I'm nearly certain that this is NOT how it should be done.

**Comment by dirkhh** [comment]
@thiagomacieira who should we poke for this?

**Review by dirkhh — APPROVED** [review]
That is... creative.
I have no idea how you managed to figure this out, but lo and behold. I can reproduce the problem, and the fix "fixes" it...

I do, however, agree, that this is not the prettiest of solutions.

**Comment by dirkhh** [comment]
I have tested this with two different Linux versions and it does seem to work reliably. So let's merge and see where this gets us.

**Comment by bstoeger** [comment]
Ooops. That might have been a bit premature. I think we're missing something fundamental. See upcoming PR.

**Comment by dirkhh** [comment]
most of the time I'm way too sluggish to respond. Here I happened to be at my computer, I tested it, so I went ahead...

There is no winning :)

**Comment by dirkhh** [comment]
do you want me to revert it?

**Pull request merged**
