### PR TITLE
Git storage fixes

### PR DESCRIPTION
**Pull request by dirkhh**
### Describe the pull request:

- [x] Bug fix
- [x] Functional change
- [ ] New feature
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

This PR mixes a few different changes:
a) add a bunch of debug information on which files are opened, which error git returns when the treebuilder fails
b) fix a bug where a local member variable hides the global 'verbose' variable
c) fix a bug that if you load from one git repo but store to a different git repo (specifically, cloud storage), the cached git objects per dive are invalid in the new repo and the treebuilder fails
d) adds a feature to correctly show the reason why cloud credentials weren't recognized (and especially don't confuse if the password was wrong or the PIN was wrong).

### Mentions:

@janmulder - you looked at the authentication code on the mobile side
@torvalds - can you check that I'm doing the right thing when I invalidate the caches?

### CODE REVIEW

**Comment by janmulder** [comment]
LGTM. 

I primarily focused on the PIN aspect. Did not create any new accounts, but used a existing account that is still in "PIN required" state. Both from the desktop as the mobile-on-desk (with hacked Qt 5.9.2). On mobile, switching between account is working as before. Did not test this on desktop. 

On both desktop as mobile, proper transfer of the new message "invalid PIN" to the UI is still to be done. But as this is not in the description, I assume that this is still on (somebody's) ever growing TBD list.

**Comment by dirkhh** [comment]
@janmulder this partially transfers the "invalid PIN" to the UI in that you still get the request to enter a PIN :-)
But I am indeed right now working on a complete change in how error messages are shown on the desktop (because hey, before .1 and .2 is the perfect time for a fundamental rewrite of something as fundamental as that... or in other words, if I really manage to stick to my "at least monthly release" goal, there will never be a good time to do this... YAY)

**Comment by torvalds** [comment]
So this is ok, but seems to be a workaround for something else not working right.

We actually _should_ use that "cached_ok" logic in "try_to_find_parent()", and it should get this right automatically. Basically, the logic should not be the name of the repository, but whether the repository we are saving to already has the commit that we already loaded.

Why isn't "try_to_find_parent()" working, I wonder? If you're saving to a new git repository, that function should have failed, and should have returned NULL, and "cached_ok" should be false (so that we don't use the git cached objects).

Because if the target repository *does*  contain the saved_git_id commit, then it should also contain all the dive objects!

**Comment by dirkhh** [comment]
Linus was ok with this one

**Pull request merged**
