### PR TITLE
core: remove qml ui properties

### PR DESCRIPTION
**Pull request by janiversen**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

downloadFromComputer contained qml properties which should not be in core and 
also not be compiled as part of the desktop.

The properties are added to qmlmanager

With the PR core is clean from qml properties.

### Changes made:

the commits are made in a sequence in order not to make a "Big Bang" change, but
show the logical change flow.

### CODE REVIEW

**Comment by dirkhh** [comment]
The reason for the old organization of the code was a desire to prevent qmlmanager from becoming too big and to keep the code local to where it was "logically connected". But I can see the logic that you are applying, so I'm ok with this.
Let's wait for Travis (but given the area where you made changes, I doubt it would catch breakage beyond simple compile issues). We don't test UI / functionality after all.

**Comment by janiversen** [comment]
I have tested it on my iPad over days, and also on my Mac due to the lack of functionality in mobile :-)

**Comment by janiversen** [comment]
@dirkh Qt55 with merge errors, I have no idea what is going on.

**Comment by dirkhh** [comment]
What the heck is wrong with the qt55 build. It just hangs when un-shallowing the git tree. That makes no bleeping sense. Restarting *again*

**Comment by janiversen** [comment]
updated my master, rebase in the branch and a push -f, because it seems that the Qt55 problem is merging this PR.

**Comment by dirkhh** [comment]
I can read and parse your words, but they make no sense to me. BTW, I'm on IRC if you want to chat, @janiversen

**Pull request merged**
