### PR TITLE
[MAP] Minor bug fix: don't show ugly "invalid dive site" message.

### PR DESCRIPTION
**Pull request by bstoeger**
### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Under not totally unlikely conditions, an ugly "invalid dive site" was shown to the user. Fix this. The code is horribly subtle, therefore add comments.

### Changes made:

1) Don't show ugly message.
### Additional information:

None.
### Release note:

Done.
### Documentation change:

No.

### CODE REVIEW

**Comment by dirkhh** [comment]
So I notice that we in two places return that INVALID_DIVE_SITE_NAME
is that an issue as well?

**Comment by bstoeger** [comment]
I'm not even sure if that is still active code..? When is `LocationInformationModel`  accessed with `Qt::EditRole`?

**Comment by dirkhh** [comment]
the Travis bug looks like memory corruption / out of bounds write.
I consider it rather unlikely that it's cause by this commit, but I think it's worth leaving it there so that maybe someone can take a look to see if they can reproduce it.

**Comment by bstoeger** [comment]
> the Travis bug looks like memory corruption / out of bounds write.

Can't reproduce in numerous runs and `valgrind` does not report any suspicious memory accesses:

```
$ valgrind --leak-check=full ./tests/TestQPrefDivePlanner
==18621== Memcheck, a memory error detector
==18621== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==18621== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==18621== Command: ./tests/TestQPrefDivePlanner
==18621== 
********* Start testing of TestQPrefDivePlanner *********
Config: Using QtTest library 5.9.5, Qt 5.9.5 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 7.3.0)
PASS   : TestQPrefDivePlanner::initTestCase()
PASS   : TestQPrefDivePlanner::test_struct_get()
PASS   : TestQPrefDivePlanner::test_set_struct()
PASS   : TestQPrefDivePlanner::test_set_load_struct()
PASS   : TestQPrefDivePlanner::test_struct_disk()
PASS   : TestQPrefDivePlanner::test_multiple()
PASS   : TestQPrefDivePlanner::test_oldPreferences()
PASS   : TestQPrefDivePlanner::test_signals()
PASS   : TestQPrefDivePlanner::cleanupTestCase()
Totals: 9 passed, 0 failed, 0 skipped, 0 blacklisted, 2801ms
********* Finished testing of TestQPrefDivePlanner *********
==18621== 
==18621== HEAP SUMMARY:
==18621==     in use at exit: 194,750 bytes in 632 blocks
==18621==   total heap usage: 220,340 allocs, 219,708 frees, 25,893,536 bytes allocated
==18621== 
==18621== 128 (16 direct, 112 indirect) bytes in 1 blocks are definitely lost in loss record 206 of 254
==18621==    at 0x4C3017F: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==18621==    by 0x15916D: TestQPrefDivePlanner::test_multiple() (testqPrefDivePlanner.cpp:317)
==18621==    by 0x867D062: QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const (in /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.9.5)
==18621==    by 0x81BB6F9: ??? (in /usr/lib/x86_64-linux-gnu/libQt5Test.so.5.9.5)
==18621==    by 0x81BC44F: ??? (in /usr/lib/x86_64-linux-gnu/libQt5Test.so.5.9.5)
==18621==    by 0x81BC9C0: ??? (in /usr/lib/x86_64-linux-gnu/libQt5Test.so.5.9.5)
==18621==    by 0x81BCF8A: QTest::qExec(QObject*, int, char**) (in /usr/lib/x86_64-linux-gnu/libQt5Test.so.5.9.5)
==18621==    by 0x157E1C: main (testqPrefDivePlanner.cpp:558)
==18621== 
==18621== 6,605 (232 direct, 6,373 indirect) bytes in 1 blocks are definitely lost in loss record 250 of 254
==18621==    at 0x4C31B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==18621==    by 0xC7B4B5F: ??? (in /lib/x86_64-linux-gnu/libdbus-1.so.3.19.4)
==18621==    by 0xC7BF31E: ??? (in /lib/x86_64-linux-gnu/libdbus-1.so.3.19.4)
==18621==    by 0xC7BF5C4: ??? (in /lib/x86_64-linux-gnu/libdbus-1.so.3.19.4)
==18621==    by 0xC7B2EEF: ??? (in /lib/x86_64-linux-gnu/libdbus-1.so.3.19.4)
==18621==    by 0xC79D114: ??? (in /lib/x86_64-linux-gnu/libdbus-1.so.3.19.4)
==18621==    by 0xC798A73: ??? (in /lib/x86_64-linux-gnu/libdbus-1.so.3.19.4)
==18621==    by 0x9A91CB0: ??? (in /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5.9.5)
==18621==    by 0x869C121: QObject::event(QEvent*) (in /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.9.5)
==18621==    by 0x866C990: QCoreApplication::notifyInternal2(QObject*, QEvent*) (in /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.9.5)
==18621==    by 0x866F11C: QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (in /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.9.5)
==18621==    by 0x86C62C2: ??? (in /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.9.5)
==18621== 
==18621== LEAK SUMMARY:
==18621==    definitely lost: 248 bytes in 2 blocks
==18621==    indirectly lost: 6,485 bytes in 37 blocks
==18621==      possibly lost: 0 bytes in 0 blocks
==18621==    still reachable: 188,017 bytes in 593 blocks
==18621==         suppressed: 0 bytes in 0 blocks
==18621== Reachable blocks (those to which a pointer was found) are not shown.
==18621== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==18621== 
==18621== For counts of detected and suppressed errors, rerun with: -v
==18621== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
```

**Comment by bstoeger** [comment]
I pushed an update cleaning up that model thing.
My theory is that this was in-progress work with the goal a common model shared by mobile and desktop. Sorry for destroying that - but since we want to change the dive-site handling anyway (pointers instead of uuid), clinging to this unfinished state is more burden than it has value. Let's do the refactoring first and then make it a nice common model.

I'm waiting with further cleanups to this code until I get a bigger map-related PR merged.

**Comment by dirkhh** [comment]
Mac build failed because it exceeded the 1hr limit. Strange. Restarted

**Comment by dirkhh** [comment]
manually merged

**Pull request closed without merging**
