### PR TITLE
Android build: buildtools version is automatically detected

### PR DESCRIPTION
**Pull request by janmulder**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [x] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:
With commit 0d8fc7ef970e of qt-android-cmake, the buildtools version is automatically detected. So do not try to pass it any more, as this breaks the build.

Signed-off-by: Jan Mulder <jlmulder@xs4all.nl>

### CODE REVIEW

**Comment by atdotde** [comment]
Hmm, not yet.

**Comment by janmulder** [comment]
And I know why .... we do not install the buildtools in the Travis process. So the new automatic detection fails on that. Previously, this install was done behind the scenes by Gradle, but now, no version is passed any more.

**Comment by janmulder** [comment]
Ok. Fixed. The first run failed, but that seemed a network hick-up and unrelated, so I restarted the Android build, and all good now. Lets wait for @dirkhh to merge this.

**Comment by atdotde** [comment]
LGTM

**Comment by dirkhh** [comment]
This looks reasonable (and Travis likes it)

**Review by dirkhh — APPROVED** [review]

**Pull request merged**
