### PR TITLE
[RFC] Presumably trivial dc cleanups

### PR DESCRIPTION
**Pull request by bstoeger**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

These are some idle cleanups. However, I'm not 100% sure about the last one. It seems that the divecomputer list is not accessed from mobile anyway, so it shouldn't matter..?

### Changes made:

1) Move function to appropriate translation unit
2) fix whitespace
3) clear divecomputer and model name lists automatically when clearing dive file data
### Release note:

No.
### Documentation change:

No.

### CODE REVIEW

**Comment by bstoeger** [comment]
TestParse fails for some reason - I will check that out tomorrow.

**Comment by bstoeger** [comment]
I see - comment in the tests says:
```
        /*
         * DC is not cleared from previous tests with the
         * clear_dive_file_data(), so we do have an additional DC nick
         * name field on the log.
         */
```
However, it doesn't say whether this is intended...?

**Review by dirkhh — APPROVED** [review]
Oh my. That's something that we wrote fairly early on (originally).
I have no recall if that was intentionally... maybe there was a use case where you'd do this to keep an existing nickname? Makes no sense to me...

**Comment by dirkhh** [comment]
after sleeping on it, I still can't figure out why this would be the wrong thing to do.
Let's merge.

**Comment by dirkhh** [comment]
(oh -- one thing I noticed... doing multiple merges back to back clearly gets us in trouble with the CI... the way we post releases isn't re-entrant and has several race conditions... a trivial way to avoid some of that is to wait between merges... not ideal... the other option would be to do all the merges manually / locally and doing one push at the end of a series of merges... which I think is what I may switch to)

**Pull request merged**
