### PR TITLE
QqPrefTechnicalDetails, one more in the series

### PR DESCRIPTION
**Pull request by janiversen**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Changes made:

commit 1 is a divePlanner cleanup
commit 2 and 3 is to clean a problem with Buehlmann 

### Mentions:

@atdotde commit 2 and 3 (remove buehlmann function) might interest you.

### CODE REVIEW

**Comment by atdotde** [comment]
fine with me.

**Comment by dirkhh** [comment]
> fine with me.

I think it's fair to say that it's NOT fine with Travis, though.

**Comment by dirkhh** [comment]
Joking aside, conceptually this is a continuation of the good work you've been doing.

**Comment by janiversen** [comment]
I an agree that travis is not happy, and with reason, the QCOMPARE macro works differently between versions....I solved that for another qPref class and will solve it here (however I am all for killing short in our code).

**Comment by janiversen** [comment]
travis is spinning, I did not cause that (I hope).

**Comment by janiversen** [comment]
and again today, github connect problem in 2 builds, that seems like a travis problem more than my code.

**Comment by dirkhh** [comment]
Yes, we've seen more of these issues than usual, I think.

**Pull request merged**
