### PR TITLE
Simple Mac OSX Dark Mode Fix

### PR DESCRIPTION
**Pull request by djunkins**
### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Small change to the Desktop tab widgets to fix two minor UI issues: 1) medium blue labels on the Dive Information tab were difficult to read in Mac OS X dark mode, and 2) the new device names tab was missing a label for the dive computer table which caused a default label of "GroupBox" to be displayed.

Medium blue labels in the Dive Information tab were inconsistent with the other tabs.

### Changes made:

1) removed the CSS_SET_HEADING_BLUE macro from TabDiveInformation.cpp
2) removed calls to the setStyleSheet(CSS_SET_HEADING_BLUE) method for the dive information labels
3) modified the CSSSetSmallLabel string to remove the 'color: mediumblue;' style directive for QLabels
4) added a "title" property to the table widget in TabDiveComputer.ui

### Related issues:

Does not fully address issue #3020 since it does not allow a user to toggle between dark and light modes

### CODE REVIEW

**Comment by djunkins** [comment]
Please don't merge the pull request yet -- just realized that the edit icon on the dive sites tab needs to be changed also.

**Comment by dirkhh** [comment]
That iOS build error was just bizarre. Let me restart that and see if it goes away.

**Review by dirkhh — COMMENTED** [review]
@willemferguson will be sad to see his blue text gone... 
But that's clearly the better choice over all. Is there a way to tell if we are in light or dark mode and to change colors depending on that? What happens with a running app when the user changes from light to dark or back?

**Comment by dirkhh** [comment]
> Please don't merge the pull request yet -- just realized that the edit icon on the dive sites tab needs to be changed also.

No problem. I really appreciate you working on this!!!

**Comment by djunkins** [comment]
@dirkhh From what I found, the Qt signal that is supposed to be sent when the mode changes from light to dark is broken, so it does not seem to be possible to explicitly set colors when the mode changes. Removing the explicit color definition was a simple fix, but I will continue to see if there is another way to handle this.

**Comment by dirkhh** [comment]
> @dirkhh From what I found, the Qt signal that is supposed to be sent when the mode changes from light to dark is broken, so it does not seem to be possible to explicitly set colors when the mode changes. Removing the explicit color definition was a simple fix, but I will continue to see if there is another way to handle this.

Do you have a link the the QT_BUG for that?

**Comment by djunkins** [comment]
> Do you have a link the the QT_BUG for that?

No, I have not found the QT_BUG yet. I saw a reference to the issue on another site when I was trying to figure out the best way to address the issue. I will continue to research whether it is still an issue and whether we can catch the signal when the mode changes so we can optimize the style for each.

**Comment by djunkins** [comment]
Please review now. I think I've addressed the most pressing issues with dark mode (the labels on the information tab being unreadable and the edit icon on the dive sites tab being all black.)

Ultimately it will make sense to have two different palettes defined for light and dark mode, but that will take a lot more work including figuring out how to catch the signal when the mode changes.

**Review by dirkhh — APPROVED** [review]
I'll build locally and test in light and dark mode.
Once I've done that, I'll merge

**Comment by dirkhh** [comment]
OK, I still don't understand why someone would want to use dark mode... but that's just me being old.
It's really hard on my eyes - almost all of the web pages I go to are black on white. Qt Creator is black on white. Any pdf that I look at is black on white. So my eyes constantly have to switch between positive and negative which is hard on them.
So right now the occasional web page designed by a cool person that is white on black is odd to me - but everything else on my screen looks consistent.
That childish (or old-person) rant out of the way, your PR creates a significant improvement in dark mode. And Subsurface correctly switches between dark and light while running. So "well done".
I notice a couple more icons that aren't perfect, but I'll merge this as is and will leave you the picture below in case you want to do a separate PR to address those
Screen Shot 2020-10-29 at 2 56 24 PM

**Comment by djunkins** [comment]
I'll take a look and see if I can do further improvements on the icons. It also looks like some buttons change background color, but not the font color in dark mode -- they're legible, but not ideal. This PR should help with the worst issues with dark mode, though.

**Pull request merged**
