### PR TITLE
[do not merge, need rebase] (planner 3) add last planning variables

### PR DESCRIPTION
**Pull request by janiversen**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

move handling of planning variables from desktop-widgets to plannerShared, to prepare for an identical use in QML.

creating the functions in plannerShared and using the new functions in desktop-widget are on purpose in separate commits.

creating the new functions are grouped in commits with similar functionality

** Warning ** this pr is based on #2465 and thus contains those commits

### CODE REVIEW

**Review by dirkhh — COMMENTED** [review]
similar comment as before.
This seems like we are moving things around in odd and not particularly obvious ways.
If those variables are already in a different model, why do we need all these "proxy" getters and setters? Shouldn't we just access that different model? And if that's the wrong answer, then the explanation should be in the commit message.
The way this reads to me it's just not clear why we need all of these in the plannerShared class instead of just going to the class we get them from.

**Comment by janiversen** [comment]
Because I am trying to make a backend that hides the complexity of multiple models etc, that way the different models to not need to interface QML. The UI should not need to know how the classes are structured internally, the UI should have a simple consistent interface.

But I see what you mean, and following your argument through, there are no real reason for this backend (but please do not complain, when the QML interface gets even more complicated).

**Comment by dirkhh** [comment]
I don't think that was what I was suggesting.

**Comment by dirkhh** [comment]
I like the idea of having a shared backend. And having an structured, sane way to access things from QML.
My comments were about the code that ended up in that backend.
And if the answer is "this is done like that on the desktop side" then that's, err, odd, but clearly no longer an issue that you necessarily need to fix in this PR.
Let me finish my work on the other PR and I'll get back to this series and poke more at the desktop code to get myself comfortable with your solution.
So let's put this on hold (hopefully just an hour or three) and ignore my comments for now

**Comment by janiversen** [comment]
quote "And if the answer is "this is done like that on the desktop side" then that's, err, odd, but clearly no longer an issue that you necessarily need to fix in this PR."

yes the functions are 1-1 copies from the desktop code. A couple of function have had code copied from a couple of places in the desktop-widget. The only modification is pure naming like plannerModel-> (seeing it now I could of course have made a class variable with the same name).

**Comment by dirkhh** [comment]
... and power went out at my house.
Sending this from my phone so you don't wonder why I stopped working on the PRs
-- 
From my phone

**Comment by janiversen** [comment]
Christmas is time for candle light! and no I did not even notice nor am I assuming about how and when you work.

I would still like to know, how I can do branches on branches without the second branch including the commits from the first one when I push it.

**Comment by dirkhh** [comment]
manually merged

**Pull request closed without merging**
