### PR TITLE
readme: update workflow badge

### PR DESCRIPTION
**Pull request by xiongnemo**
Remove old Travis CI badge, use GitHub workflow status badge instead as now we use GitHub Action.

Signed-off-by: Nemo Xiong <xiongnemo@126.com>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [x] Documentation change
- [ ] Language translation

### Pull request long description:

Remove old Travis CI badge, use GitHub workflow status badge instead as now we use GitHub Action.

### Changes made:

Badges in readme file.

### Related issues:

None.

### Release note:

None.

### Documentation change:

None.

### CODE REVIEW

**Comment by dirkhh** [comment]
The DCO is a legal statement and as such requires your actual name.
I'm going out on a limb here, but Marshmallow Nemo doesn't appear to be a legal name in any country I'm aware of.

**Comment by xiongnemo** [comment]
> The DCO is a legal statement and as such requires your actual name.
> I'm going out on a limb here, but Marshmallow Nemo doesn't appear to be a legal name in any country I'm aware of.

Shall I just redo a commit with my actual name or just edit my pull request?

**Comment by dirkhh** [comment]
Sorry for the slow response, busy with my real job :-)
Ideally just force push an updated commit with your real name (and correct syntax) and that should be sufficient.
Something like
```
project-infrastructure: update workflow badges in README

Remove old Travis CI badge, use GitHub workflow status badge instead as now we use GitHub Action.

Signed-off-by: Your Name <xiongnemo@126.com>
```

Thanks!

**Comment by xiongnemo** [comment]
Pushed!
Kindly check whether I did everything right, and have a good day 😉

**Comment by dirkhh** [comment]
Yes, thank you, will merge soon

**Review by dirkhh — APPROVED** [review]
this looks good

**Pull request merged**
