### PR TITLE
Dive list: update trip headers on filter-finish

### PR DESCRIPTION
**Pull request by bstoeger**
On change of the filter, the headers of non-extended trips were not
updated. Therefore, on filter-finish-event loop over all trips
in DiveTripModel and signal data-changed.

Signed-off-by: Berthold Stoeger <bstoeger@mail.tuwien.ac.at>

### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Another fix for fallout from divelist changes: Trip headers were not updated if the trip was not expanded. Send data-changed events for all trips on filter-repopulation.

### Release note:

No - introduced during this release cycle.
### Documentation change:

No.

### CODE REVIEW

**Comment by bstoeger** [comment]
Pushed two more minor cleanup commits.

**Review by dirkhh — APPROVED** [review]
I love reading the code and learning from it :-)
This looks good to me.

**Comment by bstoeger** [comment]
Tried to unify the second commit (use `setCurrentIndex` instead of `selectDive`). TBH, the whole selection thing is a bit nebulous to me.

**Review by neolit123 — APPROVED** [review]
lgtm

**Pull request merged**
