### PR TITLE
iOS: update build.sh to share 3rd party with desktop

### PR DESCRIPTION
**Pull request by janiversen**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [x ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

make cold build of iOS and desktop faster

Remark this PR is a convenience if you build both desktop and iOS.

It also cleans the iOS directory to be easier to check visually
 
Important: once #1363 is merged, I will rebase this one, since both touches 
Subsurface-mobile.pro

### Changes made:

1) change iOS/build.sh to use <src>/* as destination for 3rd party sources
2) make generic build-ios dir
3) move lib*-build into build-ios 
4) move install-root-ARCH into build-ios

### CODE REVIEW

**Comment by janiversen** [comment]
This is clearly my fault, the travis script does a couple of things different, lets see how to get around that.

**Comment by janiversen** [comment]
@dirkhh Solved the travis problem, so now it is ready for review.

**Comment by dirkhh** [comment]
This looks reasonable.

**Comment by dirkhh** [comment]
It seems that GitHub is happy to rebase this all by itself, so no extra work needed for you now that #1363 is merged :-)

**Pull request merged**
