### PR TITLE
Desktop: Add Country to the Fields Indexed for Fulltext Search.

### LINKED ISSUE #4134: Search tool does not find the keywords in the "country" field
### Describe the issue:

- [ X] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

Search tool does not find the keywords in the "country" field.

### Operating system:

Windows 10 & Ubuntu 23.04

Computer

### Subsurface version:

6.0.50.51

Yes

Official

### Steps to reproduce:

Try to find a word in the "country" field. Subsurface give empty answer.

### Current behavior:

Try to find a word in the "country" field. Subsurface give empty answer.

### Expected behavior:

Subsurface should find the requested country

### Mentions:

Sans titre
Sans titre2

### PR DESCRIPTION
**Pull request by mikeller**
### Describe the pull request:

- [ ] Bug fix
- [x] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Add 'Country' to the fields that are indexed for fulltext search - this seems to be a quite intuitive choice as 'Country' is also a field that is available in the dive list view.

### Related issues:

Fixes #4134.

### Additional information:

image

### Release note:

desktop: add country to the fields indexed for full text search

### Mentions:

@OlivierV78

### CODE REVIEW

**Comment by OlivierV78** [comment]
Is it possible to fix it in the mobile app too ?

**Review by bstoeger — APPROVED** [review]
lgtm

**Comment by mikeller** [comment]
@OlivierV78:

> Is it possible to fix it in the mobile app too ?

It looks like you haven't even checked if this adds the same feature to the mobile version:

image

Since the desktop version and the mobile version share a lot of the code a lot of improvements apply to both of them.

**Comment by OlivierV78** [comment]
Yes thank you.
I didn't probably try the latest nightly buil, because before this It didn't work.

**Pull request merged**
