### PR TITLE
[TRIVIAL] mobile: remove DiveListSortModel::getFilterString()

### PR DESCRIPTION
**Pull request by bstoeger**
This member function was never used.

Signed-off-by: Berthold Stoeger <bstoeger@mail.tuwien.ac.at>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Trivial(?) code cleanup.

### CODE REVIEW

**Comment by dirkhh** [comment]
Given that you removed that model in our other branch, is it worth messing with it? This just makes merging harder...

**Review by dirkhh — COMMENTED** [review]
So this is obviously correct, but I wonder if we really want to add this noise if we are removing this model, anyway.

**Comment by bstoeger** [comment]
Yes - for itself it does more harm than good. However, I may need this for #2625, so let's move discussion there.

**Comment by bstoeger** [comment]
Included in #2625 - individual PR is pointless.

**Pull request closed without merging**
