### PR TITLE
App image combined

### PR DESCRIPTION
**Pull request by dirkhh**
### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

This is a combination of #2296 and #2298 by @buxtonpaul 
I updated the reference to the 0.7 docker image based on his code. The only reason I'm pushing them as a combined PR is so that we can test the resulting AppImage and make sure nothing got broken compared to Paul's testing.

### Mentions:

@buxtonpaul please take a look at the AppImage that is created as a result of the Travis run and make sure that it works for you

### CODE REVIEW

**Comment by buxtonpaul** [comment]
Hmm, I don't seem to be able to find the build.
The latest one Continuous in https://github.com/Subsurface-divelog/subsurface/releases looks to be the build after, which I don't think includes this patch.

**Comment by dirkhh** [comment]
Sorry - PR builds aren't populated back to the GitHub site. You need to look through the build log to find the transfer.sh address.
Please try this: https://transfer.sh/CF17k/Subsurface-4.9.3-71-g10d662aa52a8-x86_64.AppImage

**Comment by buxtonpaul** [comment]
Thanks, will have a look. It will be tomorrow before I can try it on my
creaky old work system :-)

**Comment by dirkhh** [comment]
Based on the positive feedback (and my own successful tests) I'll merge this.
THANKS @buxtonpaul  for figuring out the two fixes!

**Pull request merged**
