### PR TITLE
mobile: get dive event on profile.

### PR DESCRIPTION
**Pull request by janiversen**
print mode was used to limit the functionality of the profile,
when used in ssrf-mobile.

The effect is that DC events are displayed, but not selectable

Signed-off-by: Jan Iversen <jani@apache.org>

### Describe the pull request:

- [ ] Bug fix
- [x] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

When using your mobile to upload from DC, it is nice to see if there were critical events
in your dive.

This is the first step in making profile more mobile user friendly (zoom/move/tooltips is
on the drawing board).

### Changes made:

1) disabled print mode for profile in ssrf-mobile, no change for desktop

### CODE REVIEW

**Comment by neolit123** [comment]
i think we had a good reason to do that related to fonts:
9df3835035f016231d02e95968c02bd5f100ee1a

cc @dirkhh

**Comment by janiversen** [comment]
Tested on my Mac (ssrf-mobile), my iPad Pro and my little iPhone, no problems here...but do not know about android.

**Comment by dirkhh** [comment]
So this was in 9df3835035f016231d02e95968c02bd5f100ee1a and the logic was that we are just rendering the profile - you get no interactivity anyway - and that without this on many displays the font sizes were out of whack.
What additional capability do you think this will give us? The profile shown is currently not a live profile, it's just a pixmap of one...

**Comment by janiversen** [comment]
I was really just confused that doPrint was used in the widget to limit functionality, that looked very wrong.

I want to see the DC events, and then slowly add e.g. tooltips on the events.

If activating print is a problem then I will restore that and do a couple of if in the widget itself.

**Comment by dirkhh** [comment]
So let's talk a bit about the architecture here.
What you are seeing on the screen in Subsurface-mobile is NOT the widget. You are seeing the widget being printed to a pixmap, and that static pixmap is then scaled and shown on the QML page.
I understand that there is brand new code in Qt (I don't recall if this has landed in 5.10 or is scheduled for 5.11 - @tcanabrava might know) that would allow us to actually show the widget there - which will then give you the option for all the other cool things you want to do. But right now, I think our architecture doesn't allow for it.

**Comment by janiversen** [comment]
ok, but actually for now I have. what I wanted. You download your dc to your mobile and can imidiatly see if the dc have issued warnings



so lets see what the future brings.

but again if you worry abut the fonts I will change that back and do a couple of if instead.


Enviado desde mi iPad

**Comment by dirkhh** [comment]
Let's do this and see what breaks :-)

**Comment by dirkhh** [comment]
we can always revert it

**Comment by janiversen** [comment]
mail and dile does not work, lets try this

imagen png

**Pull request merged**
