### PR TITLE
mobile: call prefs.cancelCred... for Change button in Settings

### PR DESCRIPTION
**Pull request by janiversen**
change manage.cancelCred to prefs.cancelCred

Signed-off-by: Jan Iversen <jani@apache.org>

### Describe the pull request:

- [ x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

The squash of the commits in #1398 had something I did not anticipate (just shows every change needs a lot of testing).

Change manage.cancelCred... to prefs.cancelCreds....

### CODE REVIEW

**Comment by janiversen** [comment]
@mfbernardes can you please test this:
1) open settings
2) click on "Change"

**Comment by mfbernardes** [comment]
@janiversen Yep, I see the problem. Confirm the change takes you back to the cloud login page.

That page shows a "Starting..." message that seems spurious. Never seen it before, but if unrelated to your set of changes just leave at that for now.

**Comment by janiversen** [comment]
that should be unrelated to my changes. It is a text message from qmlmanager. After the release I will publish a PR that changes a lot of these things, so I agree lets leave it for now.

**Comment by dirkhh** [comment]
I had this fixed locally already. There is another similar bug. I thought I had pushed that - will need to see what happened. But yes, this is good - I'll either take this or close it - but after I come back from diving

**Comment by janiversen** [comment]
Have some nice diving. My change or your change does not really matter, important is to get the release as good as posible, so please do whatever is easiest for you.

**Comment by janiversen** [comment]
@dirkhh you closed this one, but when build the latest master (commit c64f421006a4ecefa5624c33f742eeeef1d47aa2 from sunday), I still have the problem ?

**Comment by dirkhh** [comment]
I don't think 

> the latest master (commit c64f421 from sunday)

means what you think it means... (sorry for misquoting the "Princes Bride").
But a quick check seems to show that that commit is quite a bit behind latest master:
```
$ git shortlog c64f421..HEAD
Berthold Stoeger (2):
      libdc interface: remove debug messages
      Update to CHANGELOG.md

Dirk Hohndel (15):
      Whitespace cleanup
      QML UI: update to newer Kirigami
      build-system: add another Kirigami hack
      QML UI: build our own icon and header for global drawer
      QML UI: show the cloud credentials in the global drawer banner
      Travis: build mobile on Linux with newer gcc
      Add CHANGELOG entry
      Switch mobile version to 2.1.0 in preparation for next release
      core: add free_samples helper
      QML UIL: fix more problems with members moving from manager to prefs
      QML UI: store nocloud data when adding cloud credentials
      Update CHANGELOG.md
      QML UI: improve banner in global drawer
      QML UI: ensure we track vendor/product for download
      QML UI: remove unused property

Linus Torvalds (2):
      qt-ble: improve responsiveness of waiting for bluetooth data
      qt-ble: purge pending read data when writing

Lubomir I. Ivanov (4):
      equipment: sanitize 'tank_info' loop limits
      equipment: sanitize 'ws_info' loop limits
      equipment: use MAX_TANK_INFO in equipment.c
      CHANGELOG.md: add note about fixing a MAX_TANK_INFO bug

Murillo Bernardes (1):
      mobile: use full icon path.

Stefan Fuchs (3):
      Use correct "tr" call for translating dive mode names
      Change from gettextFromC::instance()->tr() to gettextFromC::tr();
      In dive picture shift time dialog suppress double triggering of timeEdit

jan Iversen (4):
      mobile: revert e993d4f005e62c12765e2e45342ecf840476e3bf
      mobile: move call to savePreferences back to manager.
      core: use num in alloc_samples
      mobile: set alloc_samples to 0 when resetting.
```

I was pretty sure that latest master does indeed have this fixed:
```
$ git grep cancelCredentialsPinSetup
mobile-widgets/qml/CloudCredentials.qml:                                        prefs.cancelCredentialsPinSetup()
mobile-widgets/qml/Settings.qml:                                        prefs.cancelCredentialsPinSetup()
mobile-widgets/qmlprefs.cpp:void QMLPrefs::cancelCredentialsPinSetup()
mobile-widgets/qmlprefs.h:      void cancelCredentialsPinSetup();
```
So - what am I missing?

**Comment by janiversen** [comment]
You are not missing anything, my master decided to change origin, so a pull -r did not bring me the new commits, sorry about that.

**Pull request closed without merging**
