### PR TITLE
mobile: save changes from main event loop, not signal handler

### PR DESCRIPTION
**Pull request by bstoeger**
### Describe the pull request:

- [ ] Bug fix
- [x] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

This is my attempt at fixing #4119, see discussion there. I have no idea whether this is a good idea and what, if any, negative consequences this has. In light testing, it didn't crash anymore. I never understood the whole cloud thing, so beware!

### CODE REVIEW

**Review by mikeller — APPROVED** [review]
I am by no means a mobile Qt expert, but these changes look good to me - do you want me to test if this fixes the crashes, or have you been able to reproduce the problem reported in #4119?

**Comment by bstoeger** [comment]
For me this fixes the crashes. Confirmation would obviously be appreciated. Moreover, I cannot tell whether this opens up a different can of worms. I think only @dirkhh is fluent with the code in `qmlmanager.cpp`.

**Comment by dirkhh** [comment]
And I am traveling this weekend - will be back on the road in a few minutes...
I think moving this into the main loop is the right way to do it. The problem that I had with this in the past was that it froze the UI in some circumstances. but even that is better than simply crashing, so yeah, go for it.

**Comment by dirkhh** [comment]
minor oh-shit moment.
on a slow connection this could make the app completely freeze if this is in the main thread. But I guess the simple remedy is 'turn off autosave'.

**Comment by bstoeger** [comment]
But it currently *is* in the main thread. That's the whole reason for the crash: it runs the main loop while hanging in a signal handler of the main thread.

That said, I think this should be solved differently: Instead of a timer, send an signal with an `QueuedConnection`. Then the code will be executed once the signal handler returns to the main loop.

**Comment by bstoeger** [comment]
Ok - I changed the thing to use a signal instead of a timer. This should execute the saving from the main event loop and not cause any delay, because it is executed immediately after the signal handler returns. In other words, this should not give any user-visible changes (except hopefully the lack of crashing, obviously).

Please check.

**Comment by bstoeger** [comment]
@mikeller: Can you confirm that the new version fixes the problem(s)? I'm a bit apprehensive of this change.

**Comment by mikeller** [comment]
Apologies, still on my cave trip, so my fingers are a bit worn. 
I gave it a quick spin on android, and creating and adding to trips from the dive list menu does not seem to trigger crashes any more.

**Comment by bstoeger** [comment]
Thanks for checking. Let's merge and revert if it breaks more things than it fixes. 🤷

**Pull request merged**
