### PR TITLE
Generate AppImage for each git push on Travis CI

### LINKED ISSUE #769: Provide continuous builds from Travis CI as AppImage
### Describe the issue:

- [ ] Bug
- [ ] Change request
- [x] New feature request
- [ ] Discussion request

### Issue long description:
Currently each each `git push` triggers a [build on Travis CI](https://travis-ci.org/Subsurface-divelog/subsurface), but the build artifacts are thrown away. Instead, we could bundle them up as an [AppImage](https://appimage.org/) and provide them for download, hence allowing for easy testing of the very latest continuous builds on local machines.

### Operating system:
The builds done on Travis CI in an Ubuntu trusty environments will run on most Linux distributions since 2014 when bundled as an AppImage.

### Subsurface version:
master

### Additional information:
https://plus.google.com/+DirkHohndel/posts/Vj2r74g3hBM
> screenshot_2017-11-04_13-59-20

__I am working on a pull request to implement this.__

### Mentions:
@dirkhh

### PR DESCRIPTION
**Pull request by probonopd**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [x] New feature
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:
This PR, when merged, will compile this application on [Travis CI](https://travis-ci.org/) upon each `git push`, and upload an [AppImage](http://appimage.org/) to a temporary download URL on transfer.sh (available for 14 days). The download URL is toward the end of each Travis CI build log of each build (see below for how to set up automatic uploading to your GitHub Releases page).

For this to work, you need to enable Travis CI for your repository as [described here](https://travis-ci.org/getting_started) __prior to merging this__, if you haven't already done so.

__Please note:__ Instead of storing AppImage builds temporarily for 14 days each on transfer.sh, you could use GitHub Releases to store the binaries permanently. This way, they would be visible on the Releases page of your project. This is what I recommend. See https://docs.travis-ci.com/user/deployment/releases/. If you want to do this for continuous builds, also see https://github.com/probonopd/uploadtool.

If you would like to see only one entry for the Pull Request in your project's history, then please enable [this GitHub functionality](https://help.github.com/articles/configuring-commit-squashing-for-pull-requests/) on your repo. It allows you to squash (combine) the commits when merging.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

### Changes made:
1) Build AppImage on Travis CI
2) Fix name in desktop file

### Related issues:
Closes #769

### Additional information:
A build can be tested at https://transfer.sh/YWxH0/Subsurface-git.21ac633-x86_64.AppImage

### Mentions:
@dirkhh

### CODE REVIEW

**Comment by probonopd** [comment]
Here is the URL to the AppImage built by this PR: https://travis-ci.org/Subsurface-divelog/subsurface/builds/297709527#L4165

**Comment by probonopd** [comment]
Once https://github.com/Subsurface-divelog/subsurface/pull/773 is merged, 

https://github.com/probonopd/subsurface/blob/21ac63382325dd6aeb7c646ea10b9ce5772772eb/.travis.yml#L58

can be removed.

**Comment by probonopd** [comment]
Very strange, but I think this PR is not responsible for the 1 check failing?

**Comment by dirkhh** [comment]
The tests use a single, shared resource (basically, a test account on our cloud storage infrastructure). So sometimes it happens that two people run the tests at the same time and just manage to step on each other. It's rare enough that I never bothered to fix it :-)
But no, I don't think you caused the failure.
Let me look through the changes and merge (assuming I don't stumble across anything nasty)

**Comment by dirkhh** [comment]
So this includes the stuff that I did to speed up testing - until I have QtWebKit figured out this makes sense, but I'll need to remember to undo that to make sure we test all the patterns we want to test in our builds.
Once I have that figured out I'll look into creating 'releases' here and using your uploadtool.
Thanks @probonopd

**Comment by probonopd** [comment]
> Once I have that figured out I'll look into creating 'releases' here and using your uploadtool.
Thanks @probonopd

Be sure to also upload the `*.AppImage.zsync` file which will enable delta binary updates with [AppImageUpdate](https://github.com/AppImage/AppImageUpdate).

**Comment by dirkhh** [comment]
You're ahead of me - I haven't even LOOKED at this...
I still want the AppImage to support FB and printing!

**Comment by probonopd** [comment]
> You're ahead of me - I haven't even LOOKED at this...
I still want the AppImage to support FB and printing!

That's `build.sh` stuff so I won't interfere with it :-)

**Comment by dirkhh** [comment]
No, it's Travis / Qt / dependencies stuff. But yes, I get your point, this isn't really about creating an AppImage, instead it's about having the right content FOR the AppImage :-)

**Comment by dirkhh** [comment]
I may need your help once I have this all assembled the way I want it to then get the release right :-)
I hope it's ok if I just @-tag you @probonopd if I get stuck...

**Comment by probonopd** [comment]
Always happy to be tagged! Looking forward to seeing "continuous" on GitHub Releases, along with a zsync file :-)

**Comment by probonopd** [comment]
Added to https://github.com/probonopd/linuxdeployqt/blob/master/README.md#projects-using-linuxdeployqt

**Comment by probonopd** [comment]
Quite a difference, going from [300 lines of code](https://github.com/AppImage/AppImages/blob/ac116c5814c00d044be04eb92270b23675778bdb/recipes/subsurface/Recipe) to just one fifth :-)

**Comment by dirkhh** [comment]
I'll celebrate if I can generate fully functional AppImages again. I think I'm getting closer, though :-)

**Comment by dirkhh** [comment]
If I understand correctly what you are doing with the uploadtool you are creating a 'fake' tag **_continuous_** and you create a release for that tag every time something is pushed...
Is there anything special I need to do to get a release with a 'real' tag published (and NOT deleted)?

**Comment by probonopd** [comment]
Well, for that it's much easier and you won't even need uploadtool:
https://docs.travis-ci.com/user/deployment/releases/

**Comment by dirkhh** [comment]
Woot - I have a fully functional AppImage (on Ubuntu - still have the OpenSSL problems on Arch).
I still have a test failing because we now link against QtWebKit in TestPreferences and it can't find it's platform plugin in the Travis environment.
Almost there...

**Comment by dirkhh** [comment]
> On Nov 5, 2017, at 2:52 PM, probonopd <notifications@github.com> wrote:
> 
> Once I have that figured out I'll look into creating 'releases' here and using your uploadtool.
> Thanks @probonopd <https://github.com/probonopd>
> Be sure to also upload the *.AppImage.zsync file.' which will enable delta binary updates with AppImageUpdate <https://github.com/AppImage/AppImageUpdate>.
> 

OK, HELP. Which `.zsync` file? I don' t think I see that.

Also, is it normal that the build log doesn't include the running of the `uploadtool`?

**Comment by probonopd** [comment]
> OK, HELP. Which `.zsync` file? I don' t think I see that.

Bear with me, we need to change something on our end. Will let you know when done.

> Also, is it normal that the build log doesn't include the running of the `upload tool`?

It should and it does, at the end of https://travis-ci.org/Subsurface-divelog/subsurface/builds/297815003 (the JSON stuff)

**Pull request merged**
