### PR TITLE
In strings change tank to cylinder and start lower case in parenthesis

### PR DESCRIPTION
**Pull request by sfuchs79**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [x] Language translation

### Pull request long description:

Change the word "tank" to "cylinder" or "cyl." in two occurences.
Start with lower case letter inside a parenthesis.

### CODE REVIEW

**Review by neolit123 — APPROVED** [review]
lgtm

@dirkhh please, have a look.

**Comment by neolit123** [comment]
@sfuchs79 i think this should be two separate patches:
- one for tank->cyl
- one for the lower case

**Comment by sfuchs79** [comment]
@neolit123 
Agree. Done.
Now need to go to bed... :-)
Happy to see PR for map improvements but my tests will need to wait for tomorrow...

**Review by dirkhh — APPROVED** [review]
string changes... looks good to me

**Pull request merged**
