### PR TITLE
Desktop: enable clearing of dive site

### LINKED ISSUE #2148: Bug: not possible to unset location
### Describe the issue:
- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
Once filled, it's not possible to make the location blank (unset) again.

### Operating system:
Linux en_GB on a laptop

### Subsurface version:
4.8.4-663-g5c1446a87acb

### Steps to reproduce:
1) Create a new entry
2) Go into the "Location" field
3) Set a dive location
4) Delete the dive location
5) Save changes

### Current behavior:
The set dive location is still shown even after the field was cleared

### Expected behavior:
The location is blank (as is currently happening in 4.8.6).

### PR DESCRIPTION
**Pull request by bstoeger**
### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

This hopefully enables the clearing of dive sites by connecting to the appropriate signal and recognizing the empty string as "no dive site". The whole thing is scary an I am certainly not a UI programmer and never will be.

### Changes made:

1) Connect the editingFinished signal of the location edit to the locationSelected slot.
2) When the text is empty return no-dive site instead of newly added dive site.

### Related issues:

(Hopefully) fixes #2148

### Release note:

No, bug not in release.

### Documentation change:

No.
### Mentions:

@kittykat

### CODE REVIEW

**Comment by bstoeger** [comment]
UI feels clunky and I wonder if we should add a "clear dive site" option to either the drop-down menu or as a separate button.

**Review by dirkhh — APPROVED** [review]
The field was indeed used in the old code (I am fairly certain, because I remember working on fixing bugs in this code), but the much improved new code apparently doesn't use it.
The code looks good. The UI issue is interesting - I think clearing out the name is a natural way to do this. why do you think that's weird?

**Comment by bstoeger** [comment]
The way this interacts with focus seems a bit weird to me. For example when TABing I suddenly land in the dive list. But at least it fixes the problem for now.

**Comment by dirkhh** [comment]
I have tabbing issues with the notes tab in master. The tab order in Qt is correct, yet it does strange things there as well, including sometimes landing me on the dive list.

This needs some more analysis
-- 
From my phone

**Pull request merged**
