### PR TITLE
Fix CCR setpoint display bug

### PR DESCRIPTION
**Pull request by willemferguson**
1) The connection for the display of CCR-setpoint o2SetpointGasItem
   was erroneous, being connected to partialpressuregasSettings. It
   is now correctly connected to technicalDetailsSettings.
2) The colour of the setpoint graph is changed from PO2_ALERT (red) to
   an orange colour in order to show setpoint in red only when it
   exceeds 1.6. This emphasises the visibility of red parts of the
   gas pressure graphs whenever gas limits are exceeed.

Signed-off-by: Willem Ferguson <willemferguson@zoology.up.ac.za>

### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Mentions:

@glance- @atdotde

### CODE REVIEW

**Comment by willemferguson** [comment]
@neolit123, please explain?

**Comment by neolit123** [comment]
@willemferguson i don't know what to explain?
waiting on the mentioned for reviews.

**Review by neolit123 — APPROVED** [review]
@glance- @atdotde any comments before merging this?

**Comment by dirkhh** [comment]
I honestly have no opinion. Not something I'll ever use.

**Review by atdotde — APPROVED** [review]
Looks good

**Pull request merged**
