### PR TITLE
desktop-main.cpp: further improve the GL version detection

### PR DESCRIPTION
**Pull request by neolit123**
First, attempt to use glGetString(GL_VERSION), which works
on legacy profiles but has to be parsed (unsafe and vendor specific?).
If the above fails attempt to use the newer version API from
glGetIntegerv().

If both fail, fall back to a software renderer or exit.

If GLES is detected from glGetString() (for some odd reason -
e.g. emulated driver) show a warning and return early as we don't
handle it's versioning.

Signed-off-by: Lubomir I. Ivanov <neolit123@gmail.com>

### Describe the pull request:

- [ ] Bug fix
- [x] Functional change
- [ ] New feature
- [ ] Documentation change
- [ ] Language translation

### CODE REVIEW

**Comment by mfbernardes** [comment]
On my system verMinor ends out being reported as 0, even though the reported string is "2.1 INTEL-10.28.26" or "2.1 NVIDIA-10.24.28 355.11.10.10.10.160".

After taking a look I found out ((verFloat - verMajor) * 10.f) ends up being 0.999999 instead of 1. With the cast it turns out as 0.

This makes it revert to software rendering even with the OpenGL 2.1 supported.

Tested on an old but trustworthy MacBook Pro retina, running MacOS 10.13.

**Comment by neolit123** [comment]
@mfbernardes 

this can be fixed easily.
are these the actual strings that `glGetString(GL_VERSION)` report?
```
2.1 INTEL-10.28.26
2.1 NVIDIA-10.24.28 355.11.10.10.10.160
```

is the word `OpenGL` even missing in them?

**Comment by mfbernardes** [comment]
@neolit123 These are the actual strings as they are reported. I just printed verChar.

No OpenGL word anywhere.

**Comment by neolit123** [comment]
@mfbernardes 
ok, thanks.
i will fix this in a new PR and send you a mention (@) soon so that you can confirm that it works again for you (assuming that you can build locally).

**Comment by dirkhh** [comment]
fascinating... the rounding is obviously easy to fix (use IS_FP_SAME)

**Comment by mfbernardes** [comment]
@neolit123 Cool. Yes I can build from source locally.

**Pull request merged**
