### PR TITLE
snap: fix and refresh the snap job

### PR DESCRIPTION
**Pull request by Saviq**
### Describe the pull request:
- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [x] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:
This fixes the Linux-Snap CI job by using the Canonical `build-snap` action I maintain, rather than spelling out all the steps. The `ubuntu-latest` move to 22.04 broke some things.

While there, I also cleared up some warnings related to deprecated GitHub Actions usage (e.g. `set-output=`).

### Changes made:
1) use [`canonical/actions/build-snap`](https://github.com/canonical/actions/tree/main/build-snap) action
2) make the `.ccache` folder now that `ccache --max-size` doesn't
2) refresh `checkout` and `cache` actions for [GitHub deprecation](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
3) use simpler `version: git` stanza

### More information
A move to `base: core22` will be the next step I'll work on.

### Mentions:
@dirkhh this will fix Snap CI

### CODE REVIEW

**Comment by dirkhh** [comment]
@Saviq thanks for submitting this!
Subsurface is requiring DCO for our code (which is why the test currently shows failed).
Is this something that you could either do yourself and force push, or alternatively, would you state here that I have your permission to add the DCO for you?

**Comment by Saviq** [comment]
@dirkhh I'll never learn, will I?

Done. :)

**Comment by dirkhh** [comment]
> @dirkhh I'll never learn, will I?

The number of times that I have made the exact same mistake. Even when I have scripts that should help me not make them... it's human nature (check the archive for "the update service gives the wrong version" after I made a release, for example).

The DCO passes, now we have other build issues. what the heck???

**Comment by dirkhh** [comment]
yeah, these look like internal system issues at GitHub.. they are 500 server errors when trying to download components / sources. I kicked all three to rerun.

**Comment by Saviq** [comment]
> yeah, these look like internal system issues at GitHub.. they are 500 server errors when trying to download components / sources. I kicked all three to rerun.

Yeah GH is having a bad day today.

**Comment by dirkhh** [comment]
> Yeah GH is having a bad day today.

clearly. but the builds all passed (even though the Qt6 one is still stuck). I'll merge this.

Thanks for your help - as always. Much appreciated.

**Pull request merged**
