### PR TITLE
Allow rudimentary ordering of the bar charts

### PR DESCRIPTION
**Pull request by bstoeger**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [x] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

This was requested on the mailing list, when introducing the statistics module: allow sorting of bar charts by count. In the case of value-based charts, this sorts by value and by count.

The UI is inconsistent, since here the allowed options are based on the chart and not vice-versa. I found the other way round a bit confusing. YMMV.

The good thing about this is that it provides a rather obvious differentiation between histograms and categorical charts. That caused some confusion in the past.

For stacked/grouped bar charts, we might think about sorting on the second variable. However, the result might be extremely confusing.

The layout of the mobile version is funky in wide mode. Beware.

### Changes made:

1) Add rudimentary sorting of bar charts.
2) Add support on mobile.

### Release note:

Done.

### Documentation change:

Still has to be done. Could be a good way to clarify the dichotomy categorical charts / histograms.

### Mentions:

@willemferguson

### CODE REVIEW

**Comment by willemferguson** [comment]
It looks perfect to me, using my dive log as a test case. Thank you, Berthold. I will update the user manual.

**Comment by willemferguson** [comment]
I need to mention that testing was using the desktop version of Subsurface

**Comment by dirkhh** [comment]
So, err... I finally got around to build this and I can't figure out how to use it. Where exactly does that sort show up?
I tried both desktop and mobile and am feeling a bit... lame to ask this...
On mobile I at least see the sort field - except that I can't figure out how to create a graph where the sort is enabled.
On desktop I don't even see a sort UI...
What am I missing? Yes, I tried `make clean` in case something wasn't rebuilt... do I need to be more aggressive than that?

**Comment by bstoeger** [comment]
You have to switch from a histogram to a categorical bar chart. A histogram can't be sorted: the axis is interpreted in a continuous (so far linear) way.

Yes, that will have to be explained in the documentation.

An alternative UI would let the user decide the sorting before selecting the chart and then not show charts with a continuous x-axis. However, I found that confusing. YMMV.

**Comment by dirkhh** [comment]
Yeah, this does look reasonable to me. Documentation is key, as always.
But approved from my perspective.

**Review by dirkhh — APPROVED** [review]

**Pull request merged**
