### PR TITLE
Add tests to read/write "file://..." style local git repositories

### PR DESCRIPTION
**Pull request by bstoeger**
Requested-by: Dirk Hohndel <dirk@hohndel.org>

Signed-off-by: Berthold Stoeger <bstoeger@mail.tuwien.ac.at>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

When testing local git storage, also test "file://..." style URLs. Requested by @dirkhh in #901.
Note that I currently get 4/7 FAILs for tests/TestGitStorage.

### CODE REVIEW

**Comment by dirkhh** [comment]
So the tests on the pull request past. What fails for you when you do it?

**Comment by bstoeger** [comment]
With current master I get:
```
~/src/subsurface/build$ ./tests/TestGitStorage
********* Start testing of TestGitStorage *********
Config: Using QtTest library 5.9.1, Qt 5.9.1 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 7.2.0)
PASS   : TestGitStorage::initTestCase()
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102003.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102032.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102039.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102084.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102098.jpg
PASS   : TestGitStorage::testGitStorageLocal(ASCII path)
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102003.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102032.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102039.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102084.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102098.jpg
PASS   : TestGitStorage::testGitStorageLocal(Non ASCII path)
error message was Malformed URL
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102003.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102032.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102039.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102084.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102098.jpg
PASS   : TestGitStorage::testGitStorageCloud()
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102003.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102032.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102039.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102084.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102098.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102003.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102032.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102039.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102084.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102098.jpg
error message was Malformed URL
FAIL!  : TestGitStorage::testGitStorageCloudOfflineSync() Compared values are not the same
   Actual   (readin) : "<divelog program='subsurface' version='3'>\n<settings>\n<divecomputerid model='Aeris A300CS' deviceid='2b012345' serial='035025'/>\n<divecomputerid model='Heinrichs Weikamp OSTC 3' deviceid='4ee3d5e1' nickname='Heinrichs Weikamp OSTC 3 (4ee3d5e1"...
   Expected (written): "<divelog program='subsurface' version='3'>\n<settings>\n<divecomputerid model='Aeris A300CS' deviceid='2b012345' serial='035025'/>\n<divecomputerid model='Heinrichs Weikamp OSTC 3' deviceid='4ee3d5e1' nickname='Heinrichs Weikamp OSTC 3 (4ee3d5e1"...
   Loc: [/home/bs/src/subsurface/tests/testgitstorage.cpp(171)]
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102003.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102032.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102039.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102084.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102098.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102003.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102032.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102039.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102084.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102098.jpg
FAIL!  : TestGitStorage::testGitStorageCloudMerge() Compared values are not the same
   Actual   (readin) : "<divelog program='subsurface' version='3'>\n<settings>\n<divecomputerid model='Aeris A300CS' deviceid='2b012345' serial='035025'/>\n<divecomputerid model='Heinrichs Weikamp OSTC 3' deviceid='4ee3d5e1' nickname='Heinrichs Weikamp OSTC 3 (4ee3d5e1"...
   Expected (written): "<divelog program='subsurface' version='3'>\n<settings>\n<divecomputerid model='Aeris A300CS' deviceid='2b012345' serial='035025'/>\n<divecomputerid model='Heinrichs Weikamp OSTC 3' deviceid='4ee3d5e1' nickname='Heinrichs Weikamp OSTC 3 (4ee3d5e1"...
   Loc: [/home/bs/src/subsurface/tests/testgitstorage.cpp(218)]
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102003.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102032.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102039.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102084.jpg
didn't find picture entry for /home/hohndel/subsurface/dives/images/PA102098.jpg
error message was Malformed URL
FAIL!  : TestGitStorage::testGitStorageCloudMerge2() 'dive != NULL' returned FALSE. ()
   Loc: [/home/bs/src/subsurface/tests/testgitstorage.cpp(248)]                                                                                                                                
FAIL!  : TestGitStorage::testGitStorageCloudMerge3() 'dive != 0' returned FALSE. ()                                                                                                            
   Loc: [/home/bs/src/subsurface/tests/testgitstorage.cpp(288)]                                                                                                                                
PASS   : TestGitStorage::cleanupTestCase()                                                                                                                                                     
Totals: 5 passed, 4 failed, 0 skipped, 0 blacklisted, 27081ms                                                                                                                                  
********* Finished testing of TestGitStorage *********
```
Should I investigate further (at the earliest tomorrow)?

**Comment by dirkhh** [comment]
That's odd. There is a "Malformed URL" in the middle there, so that's interesting.
That comes neither from Subsurface nor from libgit2... so I wonder what's going on there :-(

**Comment by bstoeger** [comment]
Actually, if I read it correctly, it does come out of libgit2. More precisely, in `create_local_repo()` [core/git-access.c] the call to `git_clone()` with parameters `remote="https://cloud.subsurface-divelog.org/git/ssrftest@hohndel.org"` and `localdir="/home/bs/.subsurface/cloudstorage/22c28ecd9cb677aa"` gives an error condition with `giterr_last()->message` set to `"Malformed URL"`.

But the call to `create_and_push_remote()` later on seems to work. So perhaps the problem is that the local copy is always recreated? Perhaps it doesn't like the '@'? I will investigate tomorrow, now I really have to do something different... :/

**Comment by dirkhh** [comment]
Which version of libgit2 are you using (that's not in the -v verbose output)?
Because my sources of 0.26.0 don't appear to have that string...

**Comment by bstoeger** [comment]
The version that comes with Kubuntu:
built with libgit2 0.24.6

They changed the message to lower case in this commit, that's probably why you don't find it: https://github.com/libgit2/libgit2/commit/909d5494368a00809bc42f4780e86f4dd66e4422

**Comment by bstoeger** [comment]
Ok, even normal cloud access does not work on my local build. But it *does* work with the executable found in the repository `ppa:subsurface/subsurface`.

It turns out that whereas my version is dynamically linked to the system libraries (0.24.6):
```
$ ~/src/subsurface/build/subsurface -v
Subsurface v4.7.4-234-gf764276c7efd,
built with libdivecomputer v0.6.0-devel-Subsurface-branch (7de3a549ee588fef4702ee9d894e390aca43950d)
built with Qt Version 5.9.1, runtime from Qt Version 5.9.1
built with libgit2 0.24.6
$ ldd ~/src/subsurface/build/subsurface|grep git
        libgit2.so.24 => /usr/lib/x86_64-linux-gnu/libgit2.so.24 (0x00007f74158c9000)
$ objdump -T ~/src/subsurface/build/subsurface |grep git_clone
0000000000000000      DF *UND*  0000000000000000              git_clone
```
The version in the officially repository is statically linked against a different version (0.24.4):
```
$ /usr/bin/subsurface -v
Subsurface v4.7.4,
built with libdivecomputer v0.6.0-devel-Subsurface-branch (7de3a549ee588fef4702ee9d894e390aca43950d)
built with Qt Version 5.9.1, runtime from Qt Version 5.9.1
built with libgit2 0.24.5
$ ldd /usr/bin/subsurface|grep git
$ objdump -T /usr/bin/subsurface |grep git_clone
00000000003c5a50 g    DF .text  00000000000000e8  Base        git_clone_init_options
00000000003c5280 g    DF .text  00000000000007c7  Base        git_clone
00000000003c51d0 g    DF .text  00000000000000a7  Base        git_clone__should_clone_local
```
Seems like something is wrong with the Ubuntu version of libgit2. This makes testing any cloud feature impossible for me at the moment. :(

**Comment by bstoeger** [comment]
Alright, built against a freshly checked out libgit2 0.26.0. Now the tests pass (except when they don't - but this seems to be timing related).
`Totals: 11 passed, 0 failed, 0 skipped, 0 blacklisted, 119832ms`

But please do not commit yet - the file:// test does not do what it is supposed to do - it creates a directory "file:", which is not what it's supposed to do.

**Comment by bstoeger** [comment]
> But please do not commit yet - the file:// test does not do what it is supposed to do - it creates a directory "file:", which is not what it's supposed to do.

False alarm... Apparently that was an artifact of a previous test. To avoid such ambiguities, the test now uses "file://" on save and no "file://" on read and vice-versa. Also, it uses different directory names for the different tests. From my point of view, this can be committed.

`Totals: 13 passed, 0 failed, 0 skipped, 0 blacklisted, 79500ms`

**Pull request merged**
