### PR TITLE
Csv

### PR DESCRIPTION
**Pull request by mturkia**
### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Adapt to having units in CSV header.
Add support for importing rating and visibility.

### CODE REVIEW

**Comment by janiversen** [comment]
I will test it, when it passes travis. Is the gps import format documented ? I have tried decimal and regular coordinates, but with decimal only the first number was imported and wirh coordinates nothing was imported.

**Comment by neolit123** [comment]
the android CI started breaking near the license agreement for some reason.

**Review by neolit123 — APPROVED** [review]

**Comment by mturkia** [comment]
[Subsurface user manual](https://subsurface-divelog.org/documentation/subsurface-4-user-manual/#S_locations) documents the supported formats. I have not tested if these all truly work on CSV import, but at least "20.739097 -78.821311" is imported properly for me.

**Review by janiversen — APPROVED** [review]
Build and tested, works as requested. Thanks.

Hope it can get on master soon.

**Pull request merged**
