### PR TITLE
Build system cleanups

### PR DESCRIPTION
**Pull request by DerDakon**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [x] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:
Minor things I came across while debugging a strange behavior change when requiring new CMake versions.

### CODE REVIEW

**Comment by Subsurface-divelog** [comment]
This pull request **fixes 4 alerts** when merging 6f94e409e4f81b4ec3aa7f94fba5e99d43841231 into 5cd64d42e4980fc1b252ca14d4afa64b273f5154 - [view on LGTM.com](https://lgtm.com/projects/g/Subsurface-divelog/subsurface/rev/pr-bc9bcd38c5ac2594d6036de690cc1c6c3d593ff5)

**fixed alerts:**

* 4 for Missing variable declaration

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by dirkhh** [comment]
Ha. Thanks for looking into the LGTM alerts. I have commits that clean all of that up in a different branch... the much more interesting part is the C/C++ scanning. And that I am still struggling to get working. But I unintentionally enabled the LGTM bot already on the main repo.
I'm ok with keeping those fixes in your PR - just letting you know what's going on there.

**Review by dirkhh — APPROVED** [review]
Thanks for these cleanups. Much appreciated.

**Comment by DerDakon** [comment]
I have not managed to get that working for my repos either, it is AFAICT heavily struggling if you have some not-so-standard dependencies.

**Comment by dirkhh** [comment]
Yeah, that's my perception as well - but when it works it appears to be a great static analysis tool, so I'd love to see it work...
I'm now at a blocking point and have asked for help in their community board. It's a Saturday, so I'll give it a bit of time.

**Pull request merged**
