### PR TITLE
Bugfix: correct reserve gas handling

### PR DESCRIPTION
**Pull request by janiversen**
### Describe the pull request:

- [x ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Move UI scaling from desktop-widgets/diveplanner.cpp to backend-shared/plannershared.cpp

Correct DivePlannerSetup.qml to react on unit pressure change and update step/max.

### CODE REVIEW

**Comment by janiversen** [comment]
Am I really causing this:
Failed with bad exit code during 'Checkout' (lines of code: 122.9k estimated)

at least I have no idea what to do to solve it apart from restarting the build, which I will do.

**Comment by janiversen** [comment]
How strange, change a commit message and all is green.

**Comment by dirkhh** [comment]
Usually these are simply network issues that cause operations to fail

**Comment by janiversen** [comment]
Seems pointless to keep this open, when we have so big differences in opinion on the fundamentals.

**Pull request closed without merging**
