### PR TITLE
THIS IS A FAKE PULL REQUEST TO TEST uploadtool

### PR DESCRIPTION
**Pull request by dirkhh**
DO NOT MERGE

### CODE REVIEW

**Review by Subsurface-divelog — COMMENTED** [review]
Travis CI has created build artifacts for this PR here: 
This link will expire 14 days from now.

**Review by Subsurface-divelog — COMMENTED** [review]
Travis CI has created build artifacts for this PR here: 
This link will expire 14 days from now.

**Comment by dirkhh** [comment]
HRMPF

**Review by Subsurface-divelog — COMMENTED** [review]
Travis CI has created build artifacts for this PR here: https://transfer.sh/9iOoI/Subsurface-4.7.4-67-g53df773fbb9f-x86_64.AppImage
This link will expire 14 days from now.

**Review by Subsurface-divelog — COMMENTED** [review]
Travis CI has created build artifacts for this PR here: https://transfer.sh/NTRr3/Subsurface-4.7.4-67-g53df773fbb9f-x86_64.AppImage.zsync
This link will expire 14 days from now.

**Pull request closed without merging**
