### PR TITLE
solve error in qPrefLanguage and qPrefUpdateManager

### PR DESCRIPTION
**Pull request by janiversen**
### Describe the pull request:

- [ x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Changes made:

1) correct wrong naming of qPrefLanguage variables on disk
2) solve next_check problem when changing locale

### Mentions:

@dirkhh this PR conflicts with #1578 so please do not merge until I hve rebased after merge of #1578.

I still have to check what happens when upgrading from a version where next_check is a string.

### CODE REVIEW

**Comment by dirkhh** [comment]
This looks reasonable, but as requested I'll wait

**Comment by janiversen** [comment]
I needed to check a couple of thungs and decide whether or not to merge this PR with another.

@dirkhh this is ready to merge, when you are back from a hopefully relxing vacation, unless someone beats you in pressing the merge command.

**Comment by janiversen** [comment]
that seems not to be a problem with this PR, test gitcloudstorage ??

**Review by dirkhh — APPROVED** [review]
Thanks for fixing these!

**Comment by dirkhh** [comment]
The relaxing vacation ended with rushing home a day early to get out before hurricane Lane came in...

**Pull request merged**
