### PR TITLE
[do not merge, need rebase] (planner 1a) prepare to test plannerShared

### PR DESCRIPTION
**Pull request by janiversen**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [x ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

It is very important that the introduction of plannerShared do not change the behavior of the diveplanner, especially the variables (meters, liters etc) are important since they can cause 
severe problems (if the deco is not calculated correctly).

Create framework in tests to allow testing of backend-shared classes:
- add qt-models etc. to link
- secure it works for building desktop as well as mobile

Create framework for testing plannerShared
- add add class and integrate into test framework

Currently this test is only available for mobile builds (build-mobile/tests), due to commands
currently included e.g. mainWindow::instance().

This PR will fails in tests if merged before #2476 (which are made, due to errors found with help of these test cases).

### CODE REVIEW

**Comment by dirkhh** [comment]
this is obsolete now, correct?

**Comment by janiversen** [comment]
no this is tests for plannerShared and was not in the sequence planner 1-7

**Comment by janiversen** [comment]
the 3 top commits:
add framework
activate TestPlanner
add test cases

need to be nerged

**Comment by janiversen** [comment]
hmm I cannot reopen. will make a new PR.

**Comment by dirkhh** [comment]
my apologies for closing this prematurely

**Comment by janiversen** [comment]
No problem at all !!! I can sure understand you believed it to be part of series. You could now know that I made it after I saw the calculation problem.

But because these variables are very delicate, it is important they get well tested. And I hope @atdotde will help verify/extend the test cases as I submit them.

**Pull request closed without merging**
