### PR TITLE
Import: fix download into new trip

### PR DESCRIPTION
**Pull request by bstoeger**
### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

The recent undo-of-import changes were buggy when importing into a new trip:
1) The trip table was not passed correctly.
2) The process_imported_dives() logic was faulty.

Fix both. Add a unused-variable fix for good measure.

### Changes made:

1) Pass correct trip table to downloader.
2) Fix silly logic mistake in merge-trips loop.

### Related issues:

#1925 
#1904 

### Release note:

No.
### Documentation change:

No.
### Mentions:

@dirkhh @janmulder

### CODE REVIEW

**Review by dirkhh — APPROVED** [review]
LGTM

**Comment by bstoeger** [comment]
Factored out the merge-trip-into-existing-trips functionality to make the loop a bit more palatable.

But: I believe that the way we do this is wrong anyway, from a UI perspective. What happens is that "download into new trip" is performed during download. So consider the following situation:

1) User selects "download into new trip".
2) Downloads dives. Dives appear in the dialog and are added to a new trip.
3) Deselects "download into new trip".
4) Clicks "OK".

The *old* version of the "download into new trips" flag will be used, because all that was done during download time. Therefore I think that this logic should be moved from the download-code to the import-code, isn't it?

**Comment by dirkhh** [comment]
Linus doesn't do GitHub... I'll ask him to chime in. This was his code... :-)

**Comment by torvalds** [comment]
I think @bstoeger is right, it probably makes more sense to do as a import-time thing.

The only important part is that because the new dives are in a new trip, they shouldn't then be merged with any pre-existing dives. But yes, the "should trip be assigned" makes more sense at import time than download time.

**Comment by dirkhh** [comment]
@bstoeger your call if you want to merge as is or make it "more correct".
Linus and I are in Fiji with poor internet...

**Comment by bstoeger** [comment]
> Linus doesn't do GitHub... I'll ask him to chime in. This was his code... :-)

The garbage logic was mine.

I pushed the "move new-trip logic to import function" part on top. Now history is weird because the first fix adds a trip-table to the libdivecomputer state, which is then promptly removed.

Please don't commit yet - the code doesn't yet ensure to never merge dives if add-to-new-trip is set.

> Linus and I are in Fiji with poor internet...

That sounds like a cruel fate. :) Fiji is where I did my first dive ... spoiled forever. If only it weren't so hard to reach from Europe!

**Comment by bstoeger** [comment]
From my side this is ready (though additional testing can't hurt).

With create-new-trip and download-all-dives I was able to download the same dive into two trips. I guess that's how it's meant to be...

**Review by dirkhh — APPROVED** [review]
Reading through the code this looks very nice.
I appreciate all the cleanups that you do, @bstoeger

**Pull request merged**
