### PR TITLE
Add dive mode filtering

### PR DESCRIPTION
**Pull request by bstoeger**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [x] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Per request, add dive-mode filtering. The new filter widget is becoming slightly bloated.

### Changes made:

1) Add filter option for dive mode
2) set maximum time seven days in the future to avoid confusing behavior while testing: manually added dives don't show up.
### Related issues:

Implements #2329
### Release note:

Yes, should probably do.
### Documentation change:

Not sure?
### Mentions:

requested by @plxflx and @adamel

### CODE REVIEW

**Review by dirkhh — APPROVED** [review]
I will admit that I struggle with the filter widget and the insane complexity and user hostility that it provides.
And that's not the fault of this PR, but that's a failure of vision when we first engaged down this road.
I personally find it completely unusable and find that I have pretty much stopped using it because it's so confusing and complex.
But then, maybe I'm not the target audience, anyway.

**Comment by dirkhh** [comment]
In unrelated news, I'm on day three of trying to figure out a solution to the Android build failure.
What I have learned is that Qt 5.14 is a complete nonstarter for Android.
It breaks so many things it is truly stunning.
And cmake builds for Android with Qt 5.14 appear to work for no one. Even qmake builds seem to be very much hit and miss. So after wasting a day and a half in that direction, I'm now back to trying to get a clean 5.13.2 build going with a massively smaller docker image.

**Comment by bstoeger** [comment]
Idea: If we improve the fulltext search, I hope that we can cover >90% of the use cases just with that. Then show the rest only in an "advanced mode", sorted by relevance. This advanced mode will have to be moved out of its tiny quadrant though.

**Comment by adamel** [comment]
One thing that really annoys me with the search functionality is that the keyword search uses substring match so that when serching for "cave" it matches "cavern".

**Comment by bstoeger** [comment]
That should be fixed for a long time in master: you can change the search mode to "exact" on a field-by-field basis.

**Comment by dirkhh** [comment]
> Idea: If we improve the fulltext search, I hope that we can cover >90% of the use cases just with that. Then show the rest only in an "advanced mode", sorted by relevance. This advanced mode will have to be moved out of its tiny quadrant though.

I think that's a good next step direction.
I'm willing to merge this before 4.9.4 - was that your intention as well?

**Comment by bstoeger** [comment]
Yes, I think this is low-risk and doesn't make the UI worse than it already is.

**Pull request merged**
