### PR TITLE
User manual updates

### PR DESCRIPTION
**Pull request by dirkhh**
### Describe the pull request:

- [x] Documentation change

### Pull request long description:

@willemferguson did an amazing job in #3190 explaining not only the statistics UI, but a lot of the underlying concepts and thoughts. I took that PR as is to preserve the work he did, but wanted to add a few changes on top of that.

This PR has four distinct commits. 
- One to just update version numbers. 
- One to change the style, the tone to be more in line with the rest of what we did in the manual in the past. 'you' form, slightly more informal language, slightly more conversational - simply to seem more approachable. These two should be fairly non-controversial, I hope.

There are two commits I would love to see comments on:
- one changes the way the two variables are introduced. Instead of repeating the 'axis' concept already mentioned in the text before, I pulled in the terms 'base' and 'data' - yes, those aren't the _right_ terms, but they are the terms we are using later in the text and they are likely terms that are more approachable to our users
- the other changes a single word where I _think_ @willemferguson made a typo, but want him to please double check that my change is the right one. It changes the term `depth type` (which I believe isn't a thing) to `categorical type` (which I believe is what we are talking about here).

### Mentions
@willemferguson - please comment

### CODE REVIEW

**Comment by willemferguson** [comment]
Thumbs-up

**Comment by willemferguson** [comment]
Should I take the text about the stats tool after Dirk's last PR, reformat it and insert it in the mobile users manual?

**Comment by willemferguson** [comment]
It would need new screen shots.

**Comment by dirkhh** [comment]
> Should I take the text about the stats tool after Dirk's last PR, reformat it and insert it in the mobile users manual?

Well, the part about the filter needs to be dropped. But yes, that would be awesome. I can easily create screenshots.

**Pull request merged**
