### PR TITLE
Tiny UI changes to the dive list

### PR DESCRIPTION
**Pull request by bstoeger**
### Describe the pull request:

- [ ] Bug fix
- [x] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

A few tiny changes to the dive list on desktop. A cleanup and two UI changes.
### Changes made:

1) Remove an unused function
2) Make the sort order behave more idiomatically (switch to a default order when selecting a new column)
3) Show sort indicators

### Release note:

Could do for 2) and 3), even though these changes are trivial.
### Documentation change:

No.

### CODE REVIEW

**Review by dirkhh — APPROVED** [review]
This looks all reasonable (and should improve both the UI behavior and performance)

**Comment by sfuchs79** [comment]
@bstoeger 
One quick remark on this one:
I have doubts that the new sort indicator is pointing in the wrong direction after startup.
After startup I see this:
grafik
After clicking on "Nr." once I see this (# 182 is my first dive in this log!):
grafik
After again clicking on "Nr." I see this:
grafik

**Comment by sfuchs79** [comment]
BTW, one more question: Is current master intended to restore the dive list sort order from session to session? My Subsurface always starts up with the sort order setting shown in the first picture of my last post.

**Comment by dirkhh** [comment]
It currently doesn't remember sort order.
The arrows are confusing in your pictures, TBH

**Comment by bstoeger** [comment]
Yes, that's funky. On first click I see the arrow jump up-and-down. Perhaps this was the reason why the arrows were hidden in the first place?

I fear that today I will not find time to hunt this one down. The jumping seems to happen *after* `DiveListView::headerClicked()` returns somewhere in Qt's guts. In the worst case, let's disable the arrows again (i.e. revert e1cca876d33ec3951a582c02291fa9dff0d99a7b).

**Pull request merged**
