### PR TITLE
github: update PR template with 'documentation-change'

### PR DESCRIPTION
**Pull request by neolit123**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [x] New feature
- [ ] Code cleanup
- [ ] Build system change
- [x] Documentation change
- [ ] Language translation

### Pull request long description:

Add a 'Documentation change' section to the PR body.
This instructs the PR submitter to edit the section
with notes for the team editing the documentation.

If a PR has such notes, a maintainer should then
apply the needs-documentation-change label, so
that the documentation team can easily filter
such PRs by label.

### Mentions:

@mturkia @dirkhh @janmulder @atdotde @glance- 
please, merge after a review.

### CODE REVIEW

**Review by glance- — APPROVED** [review]

**Review by dirkhh — APPROVED** [review]
Looks good - let's get another couple of reviews from the maintainers so they see that they should add this label :-)

**Review by janmulder — COMMENTED** [review]
LGTM

**Comment by dirkhh** [comment]
Great idea, Lubomir.

**Comment by neolit123** [comment]
it was Miika:
https://github.com/Subsurface-divelog/subsurface/pull/818#pullrequestreview-77006249

**Pull request merged**
