### PR TITLE
Documentation: major update of NL user manual (and a 1 line fix in EN manual)

### PR DESCRIPTION
**Pull request by janmulder**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [x] Documentation change
- [ ] Language translation

### Pull request long description:

As the base EN user manual went forward, the NL translation was hardly updated for almost a year. Do I took all the changes over this period and corrected the NL translation accordingly. So, its synced and up-to-date to version 4.8.2 of the software (assuming the EN version is).

And a second commit does a 1 line fix in the EN manual.

### CODE REVIEW

**Comment by janmulder** [comment]
And we don't care about Travis here.

**Comment by dirkhh** [comment]
And here I was wondering how Travis managed to break this time :-)
Yes, this looks good.
I can update the online version of the user manual - the one bundled with the app won't change until 4.8.3, though.

**Comment by janmulder** [comment]
Yes, it was a lot more work than expected, so a was a little too late for 4.8.2. That's live :-)

**Comment by dirkhh** [comment]
If you had asked me to wait a day, I could have waited... :-/
Maybe we can ask the other maintainers of the user manual translations if they would update theirs as well and do a 4.8.3 once that's done.

**Comment by janmulder** [comment]
I did not want to stall the release process for this, and as I went commit by commit it was a little difficult to estimate progress. And yes, I think the other manual translations suffer more or less the same issue, so an update there (or at least verify) seems useful. If this justifies "a docs only" 4.8.3 release is up to you.

**Pull request merged**
