### PR TITLE
Implement height-to-pressure functions in planner

### PR DESCRIPTION
**Pull request by willemferguson**
The units.h file has two functions to convert atm pressure to mbar
and also to convert mbar to atm pressure. Implement these two
functions in the planner.

Signed-off-by: willemferguson <willemferguson@zoology.up.ac.za>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Mentions:

@atdotde

### CODE REVIEW

**Comment by atdotde** [comment]
Looks good. I restarted the Linux build as that likely Haida hiccup.

**Comment by bstoeger** [comment]
You deleted the dives/test40-42.xml file therefore the parsing test fails.

**Comment by atdotde** [comment]
Which poses the question: why does only the Linux build fail?!?

**Comment by bstoeger** [comment]
I believe the tests are only executed for Linux. At least when I break them, only the Linux build fails...

**Comment by willemferguson** [comment]
The test40-42.xml is perfect, the right version with the correct date in the proper directory, no problem, not deleted from the tree. What is my appropriate action now?

**Comment by bstoeger** [comment]
I will never understand git, but perhaps:
git add dives/test40-42.xml
git commit --amend
git push -f
???

**Comment by willemferguson** [comment]
Lets see if it will pass the parse test now...

**Comment by bstoeger** [comment]
Works now. All that casting makes me dizzy, but since @atdotde approves, let's commit.

**Pull request merged**
