### PR TITLE
Add support for the new Suunto D5

### PR DESCRIPTION
**Pull request by torvalds**
This is just a trivial update to recognize the BT name, and a
libdivecomputer submodule update to get the updates to libdivecomputer
to recognize the new USB IDs etc.

Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### CODE REVIEW

**Comment by torvalds** [comment]
Note: I've verified that the USB download works. I haven't gotten the BLE side to pair with my desktop, but I suspect it's the same thing that makes it very awkward with the EON Core and EON Steel too: those dive computers want to pair using a secure host key, and bluez doesn't support that by default (apparently it breaks some mice and keyboards).

That likely means that BLE is most useful on mobile. Big surprise.

**Comment by torvalds** [comment]
I take all the BLE comments back. I just tried again, and it worked. The D5 does *not* need any magic BLE setup, but I think my phone had paired with it because I tried to use the Suunto app.

So I had to do "forget mobile" on the D5, and then pair on the desktop, and it all seemed to work.

**Comment by torvalds** [comment]
I'm not sure why the "Analysis failed" thing is happening. Looking at the logs, it seems to have trouble fetching the libdivecomputer update, and says

  ERROR: Error searching for sub-modules
  > Missing unknown 1194585595f7a26f3ec7f96b5ad6e8f689a70258

but I've pushed out that commit to the upstream libdivecomputer repo.

It looks like it tries to get the libdivecomputer files from somewhere else. This was the first time I tried the libdivecomputer submodule update, and clearly I did something wrong.

**Comment by dirkhh** [comment]
I need to switch LGTM to use the GitHub app integration. No time to look into that right now.
I don't think you need to worry too much about it

/D

On May 16, 2019 2:59:57 PM PDT, Linus Torvalds <notifications@github.com> wrote:
>I'm not sure why the "Analysis failed" thing is happening. Looking at
>the logs, it seems to have trouble fetching the libdivecomputer update,
>and says
>
>  ERROR: Error searching for sub-modules
>  > Missing unknown 1194585595f7a26f3ec7f96b5ad6e8f689a70258
>
>but I've pushed out that commit to the upstream libdivecomputer repo.
>
>It looks like it tries to get the libdivecomputer files from somewhere
>else. This was the first time I tried the libdivecomputer submodule
>update, and clearly I did something wrong.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Subsurface-divelog/subsurface/pull/2095#issuecomment-493246650

-- 
From my phone

**Comment by bstoeger** [comment]
Travis is happy, therefore I think we can commit.

**Comment by rumplezZiI** [comment]
有点东西

**Pull request merged**
