### PR TITLE
Add Export divesites to mobile.

### PR DESCRIPTION
**Pull request by janiversen**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [x ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Found a way to bypass DiveFilter (which are not activated for mobile), using a C macro
for_each_dive_site

This PR extends the export functionality in #2396, with dive sites export.

### Changes made:

see commits

### Related issues:

sits on top of #2396, and need to be rebased when (if) #2396 is accepted.

### Documentation change:

Mobile doc. should be extended with the Export facility, including dive site export.

### CODE REVIEW

**Comment by dirkhh** [comment]
#2396 was merged.
But I don't like the filter hack. I would prefer to make sure we do this right in the context of the larger filter rework @bstoeger and I have been working on for a few weeks (but that I got completely sidetracked from for the last two weeks... so I need to reconnect on the status of that)

**Comment by janiversen** [comment]
Happy to use diveFilrer when available, that is the right thing to do.

**Comment by janiversen** [comment]
I had a second look, and I believe it is less a "hack" as you think, and I cannot see what I can do in this PR to change it 

The loop for_each_dive_site, is actively used several places in the code:
Please look at core/divesite.c (that is where I copied it from) line 21, 33, 44, 56, 70, 101, 311, 334

Apart from that in the code merged there are a number of for_each_dive, which surely also one day can be replaced by the new filter function.

The real "hack" is in core/divefilter.cpp line 5++, that is where it is accepted that mobile uses a different version (in this case in the divest) than the desktop.

Please advice which changes you expect me to make. Alternatively since there are many places still open to change, would it not be sensible to just count this as one more ?

**Review by dirkhh — APPROVED** [review]
It works. I'll merge it and when we redo filtering, we just need to make sure we don't break this one.

**Pull request merged**
