### PR TITLE
Consistently use the famous l for liters in info tab

### PR DESCRIPTION
**Pull request by sfuchs79**
### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

After complaining about not using the famous Subsurface "l"...

For salinity in info tab change the l character to the famous
Subsurface "l".

### CODE REVIEW

**Review by dirkhh — APPROVED** [review]
I'm not sure I'm thrilled with the tone in the commit message There's nothing infamous about this, and this is in no way a Subsurface specific symbol.
The goal is to improve readability and make the distinction between l and I and 1 easier. You'll admit that ℓ and I and 1 are easier to tell apart, right?

**Comment by sfuchs79** [comment]
Ah, my mistake... I do like the ℓ! Guess that goes back to my bad English language skills - was not aware of the fact that "infamous" has a negative touch...

**Comment by dirkhh** [comment]
Yes, this is an odd one. Merrian Webster has a nice entry about it:
https://www.merriam-webster.com/words-at-play/infamous-vs-famous
So yes, infamous has a STRONGLY negative connotation.

> infamous, on the other hand, has a negative set of meanings, such as “having a reputation of the worst kind”

**Comment by sfuchs79** [comment]
Yep, understood... different to using the German word "berüchtigt" in such a context which would be totally harmless, more kind of funny...
Did a quick update... already busy with messing up things by using setlocale()... ;-(

**Comment by neolit123** [comment]
my commit title would have been more boring:
`TabDiveInformation: use 'SCRIPT SMALL L'  for liters`

**Pull request merged**
