### PR TITLE
WIP - do not merge - trying to enable LGTM as automatic static analysis tool

### PR DESCRIPTION
**Pull request by Subsurface-divelog**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [x] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

fix a few of the JS warnings produced by LGTM
add a YAML file to correctly extract C/C++ build

### Additional information:

I'm using the branch / PR to test the YML file and get to the point where this actually works... please do NOT merge

### CODE REVIEW

**Comment by Subsurface-divelog** [comment]
This pull request **fixes 7 alerts** when merging c0f5180783afb4dd94b149fce9267a2097aeda56 into 5cd64d42e4980fc1b252ca14d4afa64b273f5154 - [view on LGTM.com](https://lgtm.com/projects/g/Subsurface-divelog/subsurface/rev/pr-15054b28086f035c3235dc8bfdabcc567e61a719)

**fixed alerts:**

* 4 for Missing variable declaration
* 2 for Unused variable, import, function or class
* 1 for Useless assignment to local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by s0** [comment]
Hey thanks for trying out LGTM!

I see that you're trying to get the C/C++ builds working, unfortunately this isn't something you can do and test in a pull request like this, we need to have the `.lgtm.yml` file in the main branch of your repo, and then you retry the build here: https://lgtm.com/projects/g/Subsurface-divelog/subsurface/logs/languages/lang:cpp

In the meantime, i've kicked off a manual attempt to build your C/C++ code from the admin panel using the `.lgtm.yml` config file in this pull request so we can test if it's working. I'll let you know what happens.

Cheers,
Sam.

**Comment by dirkhh** [comment]
Hi @samlanning 
Thanks for reaching out. I ended up creating a second repo where I can move ahead changes in the master branch. Our problem is that we need to run a shell script in order to build a submodule first.
Right now I'm trying to use the existing script, but I may end up having to write a little bootstrap.sh

I will admit that the documentation is a bit, err, thin :-)
But I'm hopeful that once I'm over that first hump this will be super useful!

**Comment by dirkhh** [comment]
OK, found one problem. LGTM checks out the sources into `/opt/src` - not `/opt/src/subsurface` - so the `subsurface` directory can't be found, which we assume to be there...
Not a big problem, but annoying

**Comment by s0** [comment]
> I will admit that the documentation is a bit, err, thin :-)
> But I'm hopeful that once I'm over that first hump this will be super useful!

Thanks for the feedback, i'll pass that along to the docs team.

> OK, found one problem. LGTM checks out the sources into /opt/src - not /opt/src/subsurface - so the subsurface directory can't be found, which we assume to be there...
> Not a big problem, but annoying

Okay sounds good. Let me know if you need any further assistance, testing this out i another repo sounds like a good thing to do in the meantime.

**Comment by dirkhh** [comment]
obsolete now

**Pull request closed without merging**
