### PR TITLE
Move function isobaric_counterdiffusion()

### PR DESCRIPTION
**Pull request by willemferguson**
Move the above function from plannernotes.c to dive.c so that
it is available to be called from the dive log part of the
software, and not only from the planner. The following was done:

1) Edit the comment above the code to make it more accurate
2) Move the structure icd_data to dive.h
3) Create an external reference in dive.h for the above function
4) Copy the body of isobaric_counterdiffusion() to dive.c

Signed-off-by: Willem Ferguson <willemferguson@zoology.up.ac.za>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Mentions:

@atdotde 
@neolit123 
@dirkhh

### CODE REVIEW

**Comment by neolit123** [comment]
shouldn't the move happen once we have actual use outside of `plannernotes.c`?

**Comment by willemferguson** [comment]
The decision is, of course, up to you. The reason for writing a separate function that does not depend on plannernotes.c is part of an understanding between myself and Robert who envisions that icd calculations needs to be incorporated in the gaschange functions in dive.c.

**Review by dirkhh — APPROVED** [review]
If this is indeed going to be called from the divelog side, this looks fine. @atdotde please review as well and merge if you approve

**Comment by atdotde** [comment]
Yes, I admit, I wanted this. So, let's merge.

**Pull request merged**
