### PR TITLE
Update .DEREK.yml

### PR DESCRIPTION
**Pull request by alexellis**
I'd like to test the Derek integration, but I'm not signing off this commit. So hopefully it will trigger the DCO check.

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [x] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

I'm testing the integration of a bot to help with DCO checking - with Dirk.

### Changes made:

Updated a YAML file

### Related issues:

n/a

### Additional information:

Do not merge.

### Mentions:

@dirkhh

### CODE REVIEW

**Comment by sfuchs79** [comment]
Out of curiosity: What is the bot doing to people not adding a SOB line?
Flame them? ;-)

**Comment by dirkhh** [comment]
See how polite Derek is? @alexellis wrote this for his OpenFaaS project, and it's very British and very understated (and very useful) :-)

**Comment by sfuchs79** [comment]
Ok, that answered my question. It (he/she?!) is quite polite :-)

**Comment by alexellis** [comment]
@sfuchs79 yes kind of 😄 but it's more than that - it also opens up some interesting possibilities around empowering contributors without write access. In effect Derek can delegate fine-grained permissions through the use of comments.

https://blog.alexellis.io/derek/

**Comment by alexellis** [comment]
(something that you’ll notice is the *convention over configuration* aspect of one thing -> the DCO comment added by Derek will point a hyperlink to CONTRIBUTING.md in the root of a repository. In theory this could be configured by .DEREK.yml in the future.)

**Comment by dirkhh** [comment]
Thankfully, we follow that convention.
But yes, it would make sense to make that configurable.

**Comment by sfuchs79** [comment]
But it LOOKS dangerous. It could LOOK a little bit nicer! ;-) Ok, I stop that now. But this is way funny.
And yes, I agree, it (the bot) is useful.

**Comment by alexellis** [comment]
Oh how careless of me.. I appear to have forgotten my sign-off.. I re-signed the commit and pushed it up again. Derek's now removed the no-dco label indicating it has passed at least that check-point.

**Comment by dirkhh** [comment]
This is awesome. Thanks for that cool service, @alexellis 
But I'm not sure you have contributed enough to Subsurface to be given maintainer rights here, so NAK on the PR :-)

**Comment by alexellis** [comment]
You can also try `Derek open` / `Derek close` or

`Derek close: NAK on the PR`

**Comment by dirkhh** [comment]
(and I totally agree with @sfuchs79 - the icon red eyes look scary... you need a friendlier avatar)

**Comment by alexellis** [comment]
If you're fed up you can try `Derek lock` and `Derek unlock` a little later

**Comment by dirkhh** [comment]
Derek open

**Comment by dirkhh** [comment]
Nope, still looks closed - what am I doing wrong here?

**Comment by alexellis** [comment]
It's `Derek reopen` - https://github.com/alexellis/derek#examples

**Comment by dirkhh** [comment]
Derek assign: @sfuchs79 
Derek reopen

**Comment by alexellis** [comment]
For the time being it's one comment at a time. "PRs welcome" as they say.

**Comment by dirkhh** [comment]
Derek assign : sfuchs79

**Comment by dirkhh** [comment]
Derek reopen

**Comment by dirkhh** [comment]
Derek assign: sfuchs79

**Comment by dirkhh** [comment]
@alexellis - where can I see what Derek makes of the comment, i.e. if there's a parse error or something?

**Comment by dirkhh** [comment]
ahh, Stefan isn't "special" enough.

**Comment by dirkhh** [comment]
Derek assign: Subsurface-divelog

**Comment by alexellis** [comment]
> If you have write access to a repository, you can assign issues and pull requests to yourself, collaborators on personal projects, or members of your organization with read permissions on the repository.

https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/

**Comment by dirkhh** [comment]
now that's better :-)

**Comment by dirkhh** [comment]
OK, I'll stop playing around now. Again, thanks @alexellis

**Comment by dirkhh** [comment]
Derek close

**Comment by alexellis** [comment]
There is only feedback for positive actions to prevent abuse - i.e. someone using up all the rate limit of the G/H API token

No problems - hope Derek becomes of use to you on Subsurface 🎉

**Pull request closed without merging**
