### PR TITLE
Make handling of booleans consistent in the preferences code

### PR DESCRIPTION
**Pull request by bstoeger**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

These two commits make the handling of booleans consistent on both sides, C and C++, of the preferences code. They turn a number of shorts into bools. The C++-side was rather consistent, with the exception of five settings. The C-side was just randomly bool and short. Nevertheless, the patch for the C++-side is distinctly more complex, since it has to handle setters, getters and signals.

### Changes made:

1) Turn the five settings
  showPo2
  showPn2
  showPhe
  saveUserIdLocal
  displayInvalidDives
into bools. This means adapting setters, getters, signals and tests.
2) Remove declaration of the unused set_save_userid_local() function.
3) Turn boolean settings in core/pref.h that were declared as short into bools.

### CODE REVIEW

**Review by neolit123 — APPROVED** [review]
looks good to me. thanks.

@tcanabrava pleas,e have a look if you have a minute.
the big question here was if the size of short and bool is different and if this change might break something in the settings.

**Comment by bstoeger** [comment]
@neolit123: note that this changes only the C++ part. So this is a different issue from the point raised on the mailing list. The C++-side is pretty consistently bool with the exception of these two. Therefore, I believe(!) that this commit is should be OK. Of course, it's always better if someone more familiar with the code has a look.

I guess I'm a bit too erratic at the moment.Sorry for the confusion...

**Comment by bstoeger** [comment]
I amended the commit to include the showPo2, showPn2 and showPhe settings, which I missed the first time around. Edited title and description accordingly.

**Comment by bstoeger** [comment]
Added a commit to also make the C-side of things consistently bool. Even though the commit looks more trivial, it makes me more queasy.

The commit made me resolve a conflict - please let me know if this is OK or if a rebase is preferred.

**Comment by neolit123** [comment]
hi, this branch has conflicts.

```
This branch cannot be rebased due to conflicts
Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch.
```

do a:
`git pull --rebase origin master`

in your branch you can resolve the conflicts.

**Comment by dirkhh** [comment]
In general I prefer it if you DON'T merge master into your branch.
And if GitHub tells you that your branch has conflicts, don't worry - I'll deal with that when I pull it. If I can't or if I have concerns, I may ASK you to  make changes, but unless I do, just keep going on the branch you are working on.

Looking at the changes this looks reasonable, but I haven't test compiled it or looked to see if it's complete. Is it at the stage where you'd like me to merge it? If yes, then I'll do that manually to see what's going on.

**Comment by bstoeger** [comment]
Oh, sorry... I didn't realize that the "Resolve conflicts" button would merge *all* changes from current master. I though it would only alter the few conflicting lines. So I reset back to before the merge.

Given that development is not tremendously fast - wouldn't it be easier for you if I just rebase to current master? Especially, given that the conflicting commits were both from me...

What I did for testing was building with and without this PR. Then toggled some chart flags, exited and started the other build. At least in these tests one build understood the settings written by the other. So it *looks* quite save and you can commit from my point of view. Of course, another set of eyes can never hurt.

**Comment by neolit123** [comment]
@bstoeger 

here is my workflow:
- master is conflicting with my branch from which i have a PR
- a checkout my branch locally with `git checkout the-branch`
- i do a `git pull --rebase origin master`
- it will tell me about the conflicts. i resolve the conflicts with a text editor.
- `git add -u` to add the changes
- `git --rebase continue` to continue the rebase
- `git push --force your-remote the-branch` will force push the changes to the remote branch
- the PR is now updated and not conflicting any more

**Comment by dirkhh** [comment]
@bstoeger there is no simple answer.
For people who are comfortable with git, what @neolit123 wrote is perfectly fine.
What I was trying to express is that for people who aren't comfortable with git it's ok to just ignore the conflicts and let me (or one of the other maintainers) deal with them.
We have no hard rule "you must do ABC" - we try to make it easy for the contributors (without creating a complete mess out of our git history). And the GitHub style merges of master can create a true mess with duplication of commits in your history that get really confusing...

**Comment by bstoeger** [comment]
Ok, thanks. So in the future I will try to "rebase". Currently, I'm doing this by creating a new branch and then cherry-picking from the other branch and finally renaming. Clumsy, but works. :)

**Pull request merged**
