### PR TITLE
GitHub Actions: run the tests

### PR DESCRIPTION
**Pull request by dirkhh**
We lost running the tests when migrating to GitHub Actions...

### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

running locally there are broken tests. so this needs fixing as part of this PR

### Changes made:

simply try to enable tests both in mobile and desktop context, both on Linux and Mac

### CODE REVIEW

**Comment by janiversen** [comment]
@dirkhh  did you find the problem ? I hope it was not one of my commits.

I still have the strange CMake error, so I must be doing something wrong.

**Comment by dirkhh** [comment]
> @dirkhh did you find the problem ? I hope it was not one of my commits.
> 
> I still have the strange CMake error, so I must be doing something wrong.

I just pushed the fix. Something I should have caught in review.
More sign that we need to get `make check` working again in our CI/CD pipeline.

**Comment by janiversen** [comment]
Just saw your commit, I do however wonder why it worked and generated the TestPlannerShared.

However many thanks for correcting my mistake.

**Comment by dirkhh** [comment]
@janiversen if I run this locally, I still get four tests that fail (macOS, Qt 5.14.0):
```
The following tests FAILED:
	 11 - TestGitStorage (Failed)
	 15 - TestPlannerShared (Failed)
	 17 - TestQPrefDisplay (Failed)
	 32 - TestQML (Failed)
```
I am working on the first one. I haven't looked at the second at all. I don't understand the QML one as it uses Qt internal functions in ways that I wasn't able to find documentation for. It fails for me with 
```
$ ./TestQML
The directory '/<...>/build-mobile/tests' does not contain any test files matching 'tst_*.qml'
```
which is a correct statement - but also not helpful :-)
I briefly looked at the display prefs but decided to push this as is and spend my time on the GitStorage one as that scares me the most.
If you have time, I'd appreciate your help with the QML one, and either of the other two...

**Comment by janiversen** [comment]
I will switch to bug fix mode right now:
let me handle 
15 - TestPlannerShared (Failed)
17 - TestQPrefDisplay (Failed)
32 - TestQML (Failed)

**Comment by janiversen** [comment]
Just need to generate desktop/mobile based on current subsurface-master, that will take a little bit.

**Comment by janiversen** [comment]
just test with newest subsurface-master and I see different failures:

desktop:
	 20 - TestQPrefLog (Failed)
	 21 - TestQPrefEquipment (Failed)
	 29 - TestQPrefUnits (Failed)
	 31 - TestQML (Failed)

Mobile:
	 11 - TestGitStorage (Failed)
	 15 - TestPlannerShared (Failed)
	 17 - TestQPrefDisplay (Failed)
	 21 - TestQPrefLog (Failed)
	 22 - TestQPrefEquipment (Failed)
	 30 - TestQPrefUnits (Failed)
	 32 - TestQML (Failed)

If you concentrate on the TestGit, I can work my way through the rest. I will submit a PR for each.

Workorder for me:
32 (+31), 30 (+29), 22 (+21), 20, 17, 15

**Comment by dirkhh** [comment]
please don't test with master, test with this branch. This branch has a few fixes that you list as still broken

the good news is that GitStorage has been broken for a while it seems. The bad news is that it has been broken for a while...

**Comment by janiversen** [comment]
I have just downloaded that branch and are building right now.

I really hope the problem with GitStorage are in the test cases and not the production code

**Comment by janiversen** [comment]
not sure how to send the commits to you, but I have just added a PR bugfix1 that fixes TestQPrefDisplay.

**Comment by janiversen** [comment]
TestQML is a bit special.

cd subsurface/tests
../build*/tests/TestQML

and then you will see the problem is that QtTest and QtQuick is not installed.

I will pinpoint where that happened (surely it is a CMakeFiles.txt problem).

**Comment by dirkhh** [comment]
you can simply point me to branches that you have with fixes - you don't even have to create PRs (but that doesn't hurt, either). Whatever works for you.

GitStorage is leading me down a major rat hole. None of this has anything to do with you :-)

**Comment by janiversen** [comment]
I am sorry to hear that....Before you asked for my help, I was playing with GitStorage, I want to combine the local storage (NOCLOUD) and cached storage (ONLINE) so switching between those are automatic, but it turns out to be quite a challenge. 

TestQML proves to be quite a challenge, it seems Qt have changed the test harness, and I believe I need to come up with a very changed version of testqml.

In order not to block you, I will make a bug fix that returns without actual testing, so nothing is blocked by this. I hope that is ok with you ?

Once all this is done, I would like (when you have time) to have a talk on how gitstorage works locally and as cached.

**Comment by janiversen** [comment]
please pick up bugfix2, and testqml will be quiet. I will provide a new testqml this year :-)

**Comment by janiversen** [comment]
please pickup bugfix3, and testplannershared will be quiet, it seems the current diveplanner is very metric focused, at least it missed psi implementation and a couple of other parts, I will implement the missing functionality in the new year.

I did make an issue earlier #2491, which I hope @atdotde will comment on when he has time.

It is very late here, so I am stopping, but let me know if there are anything more I can do to help.

**Comment by dirkhh** [comment]
thanks @janiversen for all the excellent work you put into this. Very Much Appreciated!!!

**Comment by dirkhh** [comment]
So it turns out that GitStorage has failed on Mac for a very long time and no one ever noticed. It works fine on Linux. I still don't quite understand __WHY__, though.
And both on Linux and Mac all the QPref tests fail in the GitHub actions - with basically no information that would tell me why/how they fail. That's frustrating.

**Comment by janiversen** [comment]
I have doing year ends cleaning in my notes etc. and found a note about "make check", which I had forgotten (actually when I worked on a solution allowing apple users to automatically sync between their devices using apple cloud, we stopped it because nobody knew if android had a similar facility).

After I upgraded to Catalina, GitStorage started failing and I considered if there was a general problem with git or just the tests. I did not report it at the time, because I was not connected to the project (apart from having forked and having made a lot of changes).

I have no idea how GitHub actions work (I did not know about the existence before I saw your PR), so I cannot give you any clues to why qPref* fails. TestQML is mostly when there are no qml files in the directory where it is started. 

I started looking at TestQML and TestPlannerShared as promised, but I saw you did not merge the 2 bug fixes, which would allow me to work independently.

**Comment by dirkhh** [comment]
I merged the bug fixes into this branch, didn't I?

**Comment by janiversen** [comment]
yes you did, I just saw the fixes as being independent, but I have enough other work to do.

**Comment by dirkhh** [comment]
good point

**Comment by dirkhh** [comment]
fixes are now in master

**Comment by janiversen** [comment]
thanks

**Comment by dirkhh** [comment]
OK, got it. Yikes.
The semantics of opening cloud storage with a cloud storage URL are different depending on whether you are in a mobile build or in a desktop build. That is crazy subtle and I need to spend a bit more time thinking about this. But right now TestGitStorage indeed fails in a mobile build but not in a desktop build because of that...

**Comment by dirkhh** [comment]
pushed fix into master, rebased this on top of master and force pushed.
Let's see how that goes :-)
I'm away from my computer for much of the rest of today.

**Pull request closed without merging**
