### PR TITLE
Update INSTALL for Raspberry Pi OS (64-bit)

### PR DESCRIPTION
**Pull request by captainjunk**

### CODE REVIEW

**Comment by captainjunk** [comment]
As noted in https://groups.google.com/g/subsurface-divelog/c/wp4JMa6xh7w/m/uRxQY9HqAgAJ?pli=1, updating install instructions for Raspberry Pi OS (64-bit).  Hopefully I'm doing this correctly.

**Review by dirkhh — CHANGES_REQUESTED** [review]
we usually request as "Signed-off-by" line in the commit messages as explained in 
https://github.com/subsurface/subsurface/blob/master/CONTRIBUTING.md

If that is more 'git magic' than you are comfortable with, you can also read through the meaning of adding such a line (there's a link in the document to explain what this implies) and ask me here to add that for you and I'll do that manually when merging...

I appreciate you taking the time to document this!

**Comment by dirkhh** [comment]
(since this only changes documentation there's no point in wasting cloud resources and running the build test workflows...)

**Comment by captainjunk** [comment]
Hey,
  Sorry for messing this up, this is my first time playing with git and
it's a bit different than what I'm used to.  Thanks for pointing me to the
CONTRIBUTING doc.  I saw the Checks tab and assumed that the code needed to
be signed off on by someone from the project, not me. Let me try to fix
this up.  Thanks and sorry for the bother.
-Capn

**Comment by dirkhh** [comment]
It's no bother at all.
I'm happy to help walk you through the process.

I'm really grateful that you are contributing to the project!

**Pull request closed without merging**
