### PR TITLE
Planner limit minimum GFlow to 10 and minimum GFhigh to 40

### LINKED ISSUE #774: Planner GF high < 35% possible in UI but not accepted, crash for very low values
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

Today in the planner the limits for GF low and GF high are for both 1%-150%.
a) I'm not sure if this really makes sense
b) If I decrease GF high below 35% via the combo box arrow buttons this is not reflected in the calculation
c) If I enter very low GF high (1-5%) via keyboard I create a freeze plus crash

### Operating system:

Win 10

### Subsurface version:

Latest Master

### Expected behavior:

Proposal:
Let's limit GF high (and GF low) directly in the UI file to different values than today.
I have no real proposal yet.
My OSTC seems to allow:
GF low 10...100%
GF high 60...100%

If someone says: "Let's have wider limits for testing/whatever" - Thats ok for me.

Maybe:
GF low 10...150%
GF high 35...150%
???

### PR DESCRIPTION
**Pull request by sfuchs79**
### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Planner limit minimum GFlow to 10 and minimum GFhigh to 40

### Related issues:

Closes #774 

### Mentions:

@RickMWalsh @atdotde

### CODE REVIEW

**Comment by dirkhh** [comment]
Oh look, "I randomly work"-bot is working :-)
This is of course a good thing to do. I wonder if there should be a comment about this in the documentation. I.e., should you add this to the ReleaseNotes and maybe even to the user manual?

**Comment by sfuchs79** [comment]
That's fair :-)
Will do this as soon as the kids are in bed...
BTW, stupid question: Should such release notes and user manual stuff always better go into a separate commit or in the same commit with the functional changes?

**Comment by janmulder** [comment]
And what about the limits on the GF values in the user preferences? Seems logical to me to have the same ranges on both sets.

**Comment by dirkhh** [comment]
Either is fine. They should be in the same PR, but having them in a separate commit might make things cleaner? I don't know and don't really care.

**Comment by sfuchs79** [comment]
@janmulder 
Sure you are right. Thanks for pointing me to that!
Kids, go to bed!!! I have work to do ;-)

**Comment by sfuchs79** [comment]
Ok:
- Release notes done (hopefully correct)
- In docu GFlow/high min/max limits not mentioned up to now. So I at the moment decided not to add it. Is it really needed? Yes, I'm lazy... ;-)
- Found s.th. else slightly off topic...

**Comment by dirkhh** [comment]
LGTM

**Pull request merged**
