### PR TITLE
Q_UNUSED changes -> no parameter name, where applicable in whole code base

### PR DESCRIPTION
**Pull request by janiversen**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Removed Q_UNUSED where it is posible to remove the parameter name instead.

When Q_UNUSED is conditional it is untouched.

The commits are grouped by directory, since doing a pr file commit seemed a bit heavy
(but can easily be split if so wished)

This is the first PR in a couple of PR´s, next one will convert (void)parm to UNUSED(parm)
(just need to find a safe place to define UNUSED)

### CODE REVIEW

**Comment by dirkhh** [comment]
That last one was a bit too aggressive... you removed the name of a parameter that's actually used, it seems :-)

**Comment by janiversen** [comment]
ups, but that is why I use travis :-)

**Comment by janiversen** [comment]
Heh problem was that Q_UNUSED was false :-) anyhow corrected.

**Comment by dirkhh** [comment]
Gotta love incorrect Q_UNUSED labels :-(
But yeah, Travis is awesome. Thanks for working on this. I love to see all the cleanup that you're doing!

**Comment by dirkhh** [comment]
Hu. There's something fishy with those two failed builds - they stalled when un-shallowing the git tree. WTH? I restarted them.

**Comment by janiversen** [comment]
it is travis figthing back because I request too many builds :-)

**Comment by dirkhh** [comment]
Ahh, good. That fixed the builds. Looking great, @janiversen

**Pull request merged**
