### PR TITLE
[WIP] mobile: update to latest Kirigami

### PR DESCRIPTION
**Pull request by mfbernardes**
Signed-off-by: Murillo Bernardes <mfbernardes@gmail.com>

### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Fix unaligned icon and other minor changes.

Tested on iOS. Need to be tested on android (it insists in not finding std{in, out, err} when I try to build).

### Additional information:

Kirigami now has two buttons (Back and Forward) on application header when more than one page is in the stack.

### CODE REVIEW

**Comment by janiversen** [comment]
Funny seems android have the same issue as desktop-mobile. iOS builds correctly for both device and simulator.

**Comment by mfbernardes** [comment]
It's the mix cmake and qmake.

There is still a dependency issue on linux though. I'm checking.

**Comment by neolit123** [comment]
the change seems OK, and all our Travis jobs are happy except the `linux2` job:
```
[ 92%] Building CXX object CMakeFiles/subsurface-mobile.dir/mobile-widgets/qml/kirigami/src/formlayoutattached.cpp.o
[ 93%] Building CXX object CMakeFiles/subsurface-mobile.dir/mobile-widgets/qml/kirigami/src/mnemonicattached.cpp.o
[ 93%] Building CXX object CMakeFiles/subsurface-mobile.dir/mobile-widgets/qml/kirigami/src/delegaterecycler.cpp.o
[ 94%] Building CXX object CMakeFiles/subsurface-mobile.dir/mobile-widgets/qml/kirigami/src/desktopicon.cpp.o
[ 94%] Building CXX object CMakeFiles/subsurface-mobile.dir/mobile-widgets/qml/kirigami/src/libkirigami/basictheme.cpp.o
[ 95%] Building CXX object CMakeFiles/subsurface-mobile.dir/mobile-widgets/qml/kirigami/src/libkirigami/kirigamipluginfactory.cpp.o
[ 95%] Building CXX object CMakeFiles/subsurface-mobile.dir/mobile-widgets/qml/kirigami/src/libkirigami/platformtheme.cpp.o
[ 96%] Building CXX object CMakeFiles/subsurface-mobile.dir/mobile-widgets/qml/kirigami/src/libkirigami/tabletmodewatcher.cpp.o
/home/travis/build/Subsurface-divelog/subsurface/mobile-widgets/qml/kirigami/src/libkirigami/tabletmodewatcher.cpp:25:41: fatal error: tabletmodemanager_interface.h: No such file or directory
 #include "tabletmodemanager_interface.h"
```

i haven't checked how this job is different to `linux`.
@dirkhh

**Comment by mfbernardes** [comment]
I'm aware. Kirigami added a KWin dependency on linux.

Just keep this on hold for now and I'll get it fixed upstream first.

**Comment by janiversen** [comment]
??? I thought you were experiment with the newest version, not only to solve this bug, but others as well.

I for one, would like that we use a more recent Kirigami.

**Comment by mfbernardes** [comment]
It's not way behind. It's literally HEAD^ as of now.

About Qt Creator... I never got it to work properly with Kirigami, but didn't really try that much.

**Pull request closed without merging**
