### PR TITLE
Release notes: Cleanup, pressure graphs, VPM-B ceiling

### PR DESCRIPTION
**Pull request by sfuchs79**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [x] Documentation change
- [ ] Language translation

### Changes made:

Recognized that I had to fix a mistake I did when updating the release notes and took the chance to also add two items where I somehow was involved.
BTW - one SOB related question:
Is it the correct thing that I add Ricks SOB if I bring here some content which comes from him. Clearly I also need to inform him @RickMWalsh 
Or is there another SOB-like line one adds in such a case?

### CODE REVIEW

**Comment by neolit123** [comment]
> BTW - one SOB related question:
Is it the correct thing that I add Ricks SOB if I bring here some content which comes from him. Clearly I also need to inform him @RickMWalsh
Or is there another SOB-like line one adds in such a case?

it's OK if you both SOB a patch, as long as both of you agree on the changes.
please, make the discussion public at the ML, so that we can see that Rick says "yes, i SOB this patch".

here is an example:
https://github.com/Subsurface-divelog/subsurface/commit/73814583258fd88078582043754dc5fa33861cbf

some suggestions at kernel.org:
https://www.kernel.org/doc/html/v4.12/process/submitting-patches.html#using-reported-by-tested-by-reviewed-by-suggested-by-and-fixes

**Comment by neolit123** [comment]
oh, so the commit in this PR itself has a SOB from Rick.
https://github.com/Subsurface-divelog/subsurface/pull/829/commits/f43e3a4bfa1a8102ea345bd17c80ac70db69bde0

in that case - questions:
- has Rick edited the ReleaseNotes or is he made functionality changes and you are editing the ReleaseNotes for him?
- is this commit a combination of your an his work?
- does he agree with his SOB being here?

**Comment by dirkhh** [comment]
Think of an SOB like a signature on a document.
So unless someone has given you clear instruction that they are ok with you adding their SOB, please don't do it.
For something like this commit, the SOB is for the change to the documentation. You did this, so only you should sign off on it. So please change the commit (unless in the meantime @RickMWalsh has agreed that he is happy to co-sign) :-)

**Review by dirkhh — CHANGES_REQUESTED** [review]
please change the SOB

**Comment by sfuchs79** [comment]
Ok, understood. That text on kernel.org sent by @neolit123 is good for learning this - thanks!
The reason I raised this point for this minor change is that the release notes text for the VPM-B stuff was proposed by Rick. I just copy&pasted it because I saw some other stuff I wanted to add to the release notes.
So maybe either a "Suggested-by:" or even nothing would be the right choice here. I like the "Suggested-by:" - that's nice in some way. Ok?
And we for sure wait for Ricks ok here - I guess @RickMWalsh does read Github notifications...

**Comment by neolit123** [comment]
@sfuchs79 

`Suggested-by:` is fine

**Comment by RickMWalsh** [comment]
Yes, I do read notifications, but not so much in the wee hours of Saturday morning Australian time. Thanks for adding this @sfuchs79. I'm happy with suggested by. Fine with my SOB too, but how it stands is great.

**Review by dirkhh — APPROVED** [review]

**Pull request merged**
