### PR TITLE
add documentation about experimental BTLE on Windows

### PR DESCRIPTION
**Pull request by neolit123**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [x] New feature
- [ ] Code cleanup
- [ ] Build system change
- [x] Documentation change
- [ ] Language translation

### Changes made:

- added change in user manual
- added change in change log

### Related issues:

NONE

### Additional information:

NONE

### Release note:

commit present.

### Documentation change:

commit present.

### Mentions:

@dirkhh @willemferguson

### CODE REVIEW

**Review by dirkhh — COMMENTED** [review]
Wouldn't it make sense to add the language you had in your email?
>- Make sure that your BTLE dive computer is paired in Control Panel.
>- If connectivity from Subsurface to the BTLE device fails, try unpairing and pairing again.

**Comment by neolit123** [comment]
> Make sure that your BTLE dive computer is paired in Control Panel.
> If connectivity from Subsurface to the BTLE device fails, try unpairing and pairing again.

this seems to be already present in the user manual.
should that be added in the changelog?

**Comment by dirkhh** [comment]
Oops. If that's already there, then clearly I haven't paid enough attention. My apologies

**Comment by neolit123** [comment]
> Oops. If that's already there, then clearly I haven't paid enough attention. My apologies

it seems to already include necessary steps and troubleshooting but if you think we can make more updates there?
it SGTM.

**Pull request merged**
