### PR TITLE
[WIP] Reworked #921 (QML UI: switch editing back to ComboBox)

### PR DESCRIPTION
**Pull request by jbygdell**
### Describe the pull request:

- [ ] Bug fix
- [x] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Changes made:

Reworked and rebased PR #921 since I can't push changes to that PR.
This also includes bugfixes related to editing dives with more than one buddy related to the original PR.

### Related issues:

#921 

### Mentions:

@dirkhh

### CODE REVIEW

**Comment by janmulder** [comment]
Tested (on device, with both a own build against Qt 5.10.1, and the Travis build).

1) The location field is not populated from the model (so also no hints from the model)
2) The combobox for buddy (and highly likely all comboboxes in this edit mode) open without a current item set. This is reasonable for comboboxes with only a few rows, but this is highly inconvenient for long lists of buddies or divesites, as the user has to scroll through a long list to select an adjacent buddy name.
3) It would be nice when there is a filter on the rows based on the already entered start string.
4) The auto completes seem case intensive. Due to my remark 2), an user will likely accept the auto complete proposed value, and then by consequence introduce a new buddy with different capitalization (jan vs. Jan).

So, I believe, not ready to be merged. And thats a pity as I like comboboxes better than the hintstexts.

**Comment by jbygdell** [comment]
> 1. The location field is not populated from the model (so also no hints from the model)

That's a regression that needs to be fixed

> 2. The combobox for buddy (and highly likely all comboboxes in this edit mode) open without a current item set. This is reasonable for comboboxes with only a few rows, but this is highly inconvenient for long lists of buddies or divesites, as the user has to scroll through a long list to select an adjacent buddy name.

This is due to not having set the combobox index, fixable, just need to add some magic when a dive has more than one buddy.

>  3. It would be nice when there is a filter on the rows based on the already entered start string.

This would then require us to set the combobox index value on the fly, might be doable.

> 4. The auto completes seem case intensive. Due to my remark 2), an user will likely accept the auto complete proposed value, and then by consequence introduce a new buddy with different capitalization (jan vs. Jan).

This is most likely Qt related. Might be possible to generate a workaround.

**Comment by jbygdell** [comment]
@janmulder care to test the latest fixes?
Should fix everything that is not related to Qt internals.

**Comment by jbygdell** [comment]
> 4. The auto completes seem case intensive. Due to my remark 2), an user will likely accept the auto complete proposed value, and then by consequence introduce a new buddy with different capitalization (jan vs. Jan).

I did some more testing of this and on my device the matching is case sensitive.

**Comment by janmulder** [comment]
Tested again:
1) Edit an existing dive, and change its location to a different location with an existing GPS location. Save the edit. Now, the new location is duplicated. 1 with GPS coordinate and a new one without GPS location. 
2) The auto complete is case insensitive for me. Tested both my own compile (Qt 5.10.1) and the Travis compile with 5.9.3. See mp4: 
[capital.mp4.gz](https://github.com/Subsurface-divelog/subsurface/files/1804234/capital.mp4.gz)
3) and what is more worrying (see also the mp4). Without hitting save or cancel, the edit mode is terminated as if it was cancelled. (the mp4 if from the Travis compile).

**Comment by jbygdell** [comment]
>1. Edit an existing dive, and change its location to a different location with an existing GPS location. Save the edit. Now, the new location is duplicated. 1 with GPS coordinate and a new one without GPS location.

That's how the underlying logic works, if you want to assign an existing divesite with GPS coordinates to a new dive both fields must be empty first.

>2. The auto complete is case insensitive for me. Tested both my own compile (Qt 5.10.1) and the Travis compile with 5.9.3.

We need more testers here to see if it is device dependent or where this comes from.

>4.

Never had that happen.

**Comment by dirkhh** [comment]
Usually the best way to get things tested is to add it to the beta release. We aren't really good at getting testing done based on pull requests.
Any concerns with adding this to master and pushing out a new Android Beta? I'd be ok with that.

**Comment by jbygdell** [comment]
@dirkhh no concerns from my side. I have tested this on two devices with different OS and the behaviour is as intended, i.e. case sensitive matching.

**Comment by dirkhh** [comment]
OK, so let's pull this, get it into people's hands and then respond to the feedback. Can you send me a couple of lines that I should put in the beta announcement on what specifically should be tested?

**Comment by jbygdell** [comment]
Primarily people should check that the auto-complete function works properly i.e. that the lookup is case sensitive. Qt by default performs an case sensitive exact match so it should not be an issue.
The lookup takes a second to perform so the best strategy is to type 2-4 characters and then pause for a second to let the lookup happen.

**Pull request merged**
