### PR TITLE
git: parse into arbitrary table

### PR DESCRIPTION
**Pull request by bstoeger**
### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

The `parse_file()` function had a very surprising behavior: If you pass a git repository-style filename it would parse into the global dive table, not the supplied table! Hard to pull of, but still a bug: import dives from a git repository -> disaster.

@dirkhh: This appears like the right thing to do. However, I have no idea if that now breaks the mergeLocalRepo thing - that should be tested.

### CODE REVIEW

**Review by dirkhh — COMMENTED** [review]
this looks right. But given how many things appear to be broken right now, I feel a bit adrift at sea.
I will need to test this, test the `invalid index` thing that I see, the crash that you see... not sure when I'll have the time to do all that

**Comment by bstoeger** [comment]
> I will need to test this

Yes.

> test the invalid index thing that I see

I know how to fix this. Just not today anymore.

> the crash that you see...

You do realize that that's fixed by #2680?

**Comment by dirkhh** [comment]
> > I will need to test this
> 
> Yes.
> 
> > test the invalid index thing that I see
> 
> I know how to fix this. Just not today anymore.

Of course. It's midnight
 
> > the crash that you see...
> 
> You do realize that that's fixed by #2680?

No I do not. I'm completely confused.

**Comment by bstoeger** [comment]
> No I do not. I'm completely confused.

See: https://github.com/Subsurface-divelog/subsurface/pull/2680#issuecomment-600330932
And: https://github.com/Subsurface-divelog/subsurface/pull/2680#issuecomment-600335593
:-D

**Pull request merged**
