### PR TITLE
WIP: Planner second minimum gas switch time for below 30m/100ft

### PR DESCRIPTION
**Pull request by sfuchs79**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [x] New feature
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Added a second minimum gas switch duration for gas switches below
30m/100ft.
This is needed because at this depth one doesn't want to prolong
gas switches where at the same moment for shallower switches one does.

Yeah, I once again have here a tiny, lovely, little new feature for the planner.
It is once again such a "please tell me if you like it or not - I won't be angry if we don't merge it into master" thing.
On the other hand the feature for sure is awesome! ;-)

After possible "yes" decision I will take care about release notes and docu.

### CODE REVIEW

**Comment by RickMWalsh** [comment]
Switching to deco gas deeper than 30m is something beyond my experience and training. Could you provide a reference/example where shorter gas switches (or presumably switching while ascending) is common practice?
Also, are there situations where deep gas switched occur, and where the deco stops for shallower switches wouldn't be longer than an acceptable minimum switch duration. E.g. is there a case that requires a gas switch at 36m (or whatever) but then the 21m deco stop (and gas switch) would be <2m if a minimum switch time weren't set.

**Comment by glance-** [comment]
I feel like the UI clutter for this is just more than the % on the deco schedule its worth.

In my experience and training deep gas switches are just as important to do in a effective and controlled manner as the shallower ones.
The deepest deco gases I've used have bin 21/35 @ 57m, and yea, you're in a hurry there, but if you where to screw it up and grab the 50/25 instead, your probably going to be experiencing some problems.

When punching in such a dive in the planner, just increasing all the gas switch times from 0 to 1 minute adds +3 minutes to the total runtime, which for this random sample started out at 171 minutes. Thats +2% which is just noise.
I even managed to produce a 40 min @ 70m profile with 3 deco gases, which pushing the current gas switch timer all the way to 9 minutes, just added 12 minutes to the total runtime.

So I'll need some convincing before seeing the need for another spinbox in the planner ui.

(I even missed that we had one to begin with)

**Comment by janmulder** [comment]
I'm also not very convinced about this new feature. Gas switches (deep or shallow) do hardly cost any time when doing it efficiently. Just prepare your new tank 1 stop below (you have to wait anyhow), and the switch is nothing more than team confirmation, and putting a different reg in your mouth at the actual switch depth. Even with relatively complex PSCR switchblock plugging and un-plugging, all this switching does not cost time, as you can do all this in parallel with a stop. 

So, really interested in a use case for this.

All this said, I never use the planner in real live.

**Comment by sfuchs79** [comment]
Here is the example:
[2_Min_Switch.zip](https://github.com/Subsurface-divelog/subsurface/files/1469842/2_Min_Switch.zip)

It is a rather simple 60m dive with 3 stages where you switch during ascent to Tx30/30 at 36m.

Any yes, you are right. If I apply a min. switch time of 5min for the 36m stop (which is the value I like to have for the 21m stop) then the whole dive is 3min longer...

Well, I'm going to cry now for a minute or so, then close the PR and continue doing more important stuff ;-)

**Comment by atdotde** [comment]
I thing there is a general opinion that this feature does not warrant adding to our already baroque planner UI.

**Pull request closed without merging**
