### PR TITLE
iOS: move get-dep-lib outside ARCH loop

### PR DESCRIPTION
**Pull request by janiversen**
Fetch all 3rd party libs before entering ARCH loop

Signed-off-by: Jan Iversen <jani@apache.org>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [x ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

no need to run get-dep-lib for each architecture

### Changes made:

1) see commit message.

### CODE REVIEW

**Comment by janiversen** [comment]
I start to think that Travis-linux do not like me :-(

failed in
10 - TestPicture (Failed)

and this PR is only about iOS.

**Comment by bstoeger** [comment]
This is probably my recent changes to the picture code. Linux builds twice and it could be that the hash-file has funny side-effects. I will try to investigate tonight.

**Comment by bstoeger** [comment]
It's not your commit - I can reproduce this with current master. Seems to be some multi-threading thing as it only happens occasionally.

**Comment by janiversen** [comment]
Thanks for the infirmation. Is it worth to restart the build (I do not have karma to dot it) ?

**Comment by bstoeger** [comment]
I understand the problem now - will see what I can do about it.

I don't think that it is necessary to restart the build as obviously all other platforms succeeded.

**Pull request merged**
