### PR TITLE
Factorcacheparallel

### PR DESCRIPTION
**Pull request by atdotde**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### CODE REVIEW

**Comment by neolit123** [comment]
looks like adding on top of the `CHANGELOG.md` still produced conflicts. not sure why as it worked in my tests...maybe something is confusing the `CHANGELOG.md -text merge=union` magic.

merging `master` into the branch is not a good idea, though. rebase is the correct solution.

**Comment by bstoeger** [comment]
I think the problem is a commit that did not only add a line, but *changed* a line (replaced '_' by '-').

**Comment by atdotde** [comment]
Here is how I got to this state: I added the Changelog commit. There, I saw that the old top message had a _ instead of a - so I changed that, too. That produced the conflict. So I changed it back to _ and --ammend'ed the last commit and force-pushed it (the result is 5795dc0). Then I clicked on the resolve conflict button, did the edit manually and that produced the merge commit (which only merges the CHANGELOG file).

Anyway, the resolution is probably trivial: Cherry pick cf213de and 220024e and manually adjust the CHANGELOG. Anything else is probably wasted energy.

**Comment by dirkhh** [comment]
I'll take care of it

**Pull request closed without merging**
