### PR TITLE
Cleanup: remove combine_trips() function

### PR DESCRIPTION
**Pull request by bstoeger**
In f427226b3b605523bc8285dbdaaa7f6993af6e6a a combine_trips_create()
function was introduced that combined trips without deleting the old
trips. This was necessary for making combine-trips function undo-able.

The old combine_trips() function is not used anymore. Therefore remove
it. Rename the combine_trips_create() function to combine_trips() as
no differentiation is needed anymore.

Signed-off-by: Berthold Stoeger <bstoeger@mail.tuwien.ac.at>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Trivial code cleanup / fix of an oversight: remove unused function.

### Changes made:

1) Remove unused `combine_trips()` function.
2) Rename `combine_trips_create()` to `combine_trips()`.
### Related issues:

None.
### Additional information:

None.
### Release note:

No.
### Documentation change:

No.

### CODE REVIEW

**Comment by bstoeger** [comment]
Added another unused-function removal: `remove_autogen_trips()`.

**Comment by bstoeger** [comment]
....and the `merge_two_dives()` function.

**Review by dirkhh — APPROVED** [review]
this all looks sane

**Comment by dirkhh** [comment]
Those Mac failures... this one ran out of time. Ignoring as it made it all the way to the install step

**Pull request merged**
