### PR TITLE
cmake: add the GCC_OPTIMIZATION_FLAGS variable

### PR DESCRIPTION
**Pull request by neolit123**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [x] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Instead of always adding -O2 for CMAKE_C_FLAGS_DEBUG and
CMAKE_CXX_FLAGS_DEBUG allow the user to pass a custom value
via GCC_OPTIMIZATION_FLAGS.

Passing -DGCC_OPTIMIZATION_FLAGS:STRING=-O0 would disable
all optimizations.

### Changes made:

- the default value is still `-O2`.
- adding `-DGCC_OPTIMIZATION_FLAGS:STRING=-O0` from the command line or using the GUI would disable the optimizations.

### Related issues:

This PR should replace PR:
https://github.com/Subsurface-divelog/subsurface/pull/1221

### Mentions:

@atdotde @bstoeger @dirkhh

### CODE REVIEW

**Comment by atdotde** [comment]
Of course, you are right. This shows up in ccmake. ACK.

**Comment by neolit123** [comment]
ok, i'm going to merge this for now. if someone thinks there is something wrong with the `CACHE` thing which i don't really understand please comment.

**Comment by bstoeger** [comment]
Should this perhaps be documented in the "Contributing" documentation?

**Comment by neolit123** [comment]
if someone has the time to do this please go ahead.

**Pull request merged**
