### PR TITLE
build-system: use common code to download tarballs

### PR DESCRIPTION
**Pull request by mfbernardes**
Signed-off-by: Murillo Bernardes <mfbernardes@gmail.com>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [x] Build system change
- [ ] Documentation change
- [ ] Language translation

### CODE REVIEW

**Comment by mfbernardes** [comment]
Open for comments. I think this is generic enough, but I might have missed something.

**Comment by mfbernardes** [comment]
@dirkhh Sure. Just pushed an update.

**Comment by janiversen** [comment]
@dirkhh see the comment on #1390, checking for the existence of tar file is less error prone, than having another file. I have documented below what I mean, so I will close my PR.

@mfbernardes I do it like this:
+if [[ "$BUILD" = *"libzip"* ]]; then
 +	if [[ ! -e libzip-${CURRENT_LIBZIP}.tar.xz || ! -d libzip ]]; then
 +		${CURL} https://subsurface-divelog.org/downloads/libzip-${CURRENT_LIBZIP}.tar.xz
 +		tar xJf libzip-${CURRENT_LIBZIP}.tar.xz
 +		mv libzip-${CURRENT_LIBZIP} libzip
 +	fi

**Comment by mfbernardes** [comment]
@janiversen This patch does check the tar file. If present it is not downloaded again.

I also chose to check if the final directory is from a known and expected version. If not, cleanup and unpack the known version.

Of course the first time it is run on an existing download it will trigger a new unpacking.

I have no love for this check. If just checking the presence of the tar file is prefered I can do just that, no problem.
@dirkhh comments?

**Comment by janiversen** [comment]
Sorry, I saw that what I meant (but did not write clearly) was exactly what you are asking @dirkh to comment :-) This would be the optimal solution for me, but your patch is fine as it is!

**Comment by dirkhh** [comment]
I think just testing for presence of the tar file is sufficient

**Comment by mfbernardes** [comment]
Updated to check just the tar file and Travis finished ok.

**Pull request merged**
