### PR TITLE
Printing: improve template management

### PR DESCRIPTION
**Pull request by neolit123**
### Describe the pull request:

- [ ] Bug fix
- [x] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

The changes bellow solve the issues discussed in #847 and #839.
From this point forward the bundled templates are read-only and they are handled by the application and us (the developers). The users need to make copies of the bundled templates (e.g. via Export) if they want to base their work on them.

The patch from @willemferguson to modify the `one dive` template is also included in this PR.

### Changes made:

- always copy the bundled templates to the user folder
- once the files are copied make them read-only
- improved edit / delete / import / export message handling
- prevent deletion of bundled templates
- prevent editing of bundled templates unless they are exported to a new file first
- prevent import / export to overwrite bundled/read-only templates
- backup existing templates if such are not read-only and create a UI dialog for them as a summary

### Related issues:

https://github.com/Subsurface-divelog/subsurface/issues/847

### Additional information:

- untested on OSX; tested on Linux and Windows.
- statistics templates have to be manually copied by the user in the `user-dir/statistics` folder. import / export is not supported for those.

### Release note:

```
- Printing: the bundled templates are now read-only and are always overwritten
  by the application. The first time the user runs this update, backup files
  of the previous templates would be created. (#847).
```

### Documentation change:

Partially explained in the release note above.
The user now has to always export or manually copy a template before editing, as the default templates
are now always read-only and are overwritten on startup. Also, look at `changes made` above.

### Mentions:

@dirkhh @willemferguson

### CODE REVIEW

**Review by dirkhh — CHANGES_REQUESTED** [review]
Overall this looks very good. I definitely like the direction we are going here.
A couple of the commit messages might need some grammar love :-)
My one concern is that this minor upgrade will simply over-write someone's painstakingly edited templates.
Would this logic make sense:
- if existing template is r/w, back it up, replace it with new one
- if existing template is r/o, just replace it
???

**Comment by neolit123** [comment]
> A couple of the commit messages might need some grammar love :-)

understood. will try to find which ones.

> My one concern is that this minor upgrade will simply over-write someone's painstakingly edited templates.
Would this logic make sense:

> - if existing template is r/w, back it up, replace it with new one
> - if existing template is r/o, just replace it

it seems like a good solution.

i think this logic will ensure that this one time before the templates become RO the user templates are backed up. but they need to be backed up in a new folder `backup` because the current implementation just reads any type of file from the path. maybe it should be limited to `.html`.

**Comment by neolit123** [comment]
PR updated.

**Comment by dirkhh** [comment]
This looks excellent. Thanks, @neolit123 
I haven't done extensive testing, but I think the best way to get this tested is to pull it into master and then once we have test builds talk about it on the mailing list and ask people to make sure it works as intended.
Right now I am **still** working on the Travis build issue - I'm making progress but still have at least one obstacle ahead of me... :-(
We'll need that part fixed before we reliably get working binaries in the continuous build, again.

**Comment by dirkhh** [comment]
I restarted builds now that they appear to a) complete again on master and b) fail when they don't complete

**Review by dirkhh — APPROVED** [review]

**Comment by dirkhh** [comment]
As usual, the ReleaseNotes cause a merge conflict. I'll fix that and merge manually.

**Pull request merged**
