### PR TITLE
Bugfix: correct ratings calculations in plannerShared

### PR DESCRIPTION
**Pull request by janiversen**
### Describe the pull request:

- [ x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Calculations were off by +- 1 due to rounding errors.

Error was found during implementation of automated test #2477

### CODE REVIEW

**Comment by dirkhh** [comment]
This raises questions that I would love for @atdotde to take a look.
It's a three-holiday-Christmas in Germany, so I don't know if he is online today (or if he is off for a few days just like a few of our other contributors)

**Comment by janiversen** [comment]
Yes I believe that is a good idea.

What I did, was to start the official subsurface desktop, and check the values in the plist.

the commits in #2484 (old #2477) contains a more detailed explanation.

I will btw continue to make test cases for the other plannerShared variables.

**Comment by dirkhh** [comment]
@atdotde seems to be out for the holidays. Let's just merge and clean up later.

**Comment by atdotde** [comment]
Sorry, I am late. As you guessed correctly I was on family hiatus. This looks good. Maybe  only more realistic values for the test velocities (10m/min, 6 m/min, 1m/min) would have been even better test values. But it's fine like this.

**Pull request merged**
