### PR TITLE
core: make qPref:cloud_status the only version of the enum

### PR DESCRIPTION
**Pull request by janiversen**
add enum to qPref and remove elsewhere
update source core to reference qPref.

the enum cannot be in pref.h because it is to be used in qml and Q_ENUM
need the enum to be defined as part of the class

Signed-off-by: Jan Iversen <jani@apache.org>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

This extends the release bug fix in #1462 and present a final solution.

cloud_storage is only defined in the qPref class, and referenced elsewhere.

I have an idea on how to make QML test cases as well, but will do that later in another PR.

### CODE REVIEW

**Comment by janiversen** [comment]
Let me deal with the conflict !

**Comment by janiversen** [comment]
Hmm seems there is an android travis problem, something with Qt login credentials, do not believe this is due to this PR ?

**Comment by dirkhh** [comment]
The code looks fine, I didn't see any other comments, so I assume this is good to merge?

**Comment by mfbernardes** [comment]
This breaks the "No cloud mode" button  for me

**Comment by janiversen** [comment]
Let me have a look again (I cannot load on my ipad using ssh, so I work blindfolded this week).

**Comment by mfbernardes** [comment]
@janiversen here it goes, running on the simulator.
[subsurface.log](https://github.com/Subsurface-divelog/subsurface/files/2171732/subsurface.log)

**Comment by janiversen** [comment]
@mfbernardes thanks a lot, I know what the problem is (last line in log), will make a push shortly

**Comment by janiversen** [comment]
@mfbernardes sorry to bother you, but working through ssh is a painful limitation, can I please ask you to test my push, I believe Qt made life difficult for me, but I am not sure. Please mail me the log again if it fails....and thanks for your patience.

**Comment by mfbernardes** [comment]
@janiversen Still doesn't work. 

This is not urgent, so I suggest you take your time to work on this with the proper resources.

**Comment by janiversen** [comment]
@mfbernardes thanks for taking the time, I am working on something that will secure us against this type of failures (QML interface broken), so I might just finish and submit that work first.

**Comment by janiversen** [comment]
Found the problem, there are severe restriction on type names in qml, and there was no check if qmlRegisterType succeeded.

**Comment by janiversen** [comment]
Just decided to test a bit more, think there are more problems.

**Comment by janiversen** [comment]
Now this PR is ready for reviewing.

@mfbernardes I have tested on my iPad, but it would be nice if you could also test it.

**Comment by dirkhh** [comment]
This looks good to me - but I'm knee deep in fighting with Travis over Qt 5.11.1 on Mac (it's amazing how much time one can waste with things that in hindsight are obvious) - so I haven't actually tried this.

**Comment by mfbernardes** [comment]
@janiversen I just tried. Works nicely now.

Looks good to me. Not a big deal but be68294a3 is unused and other than being in the same class, unrelated to the rest of the PR.

**Comment by janiversen** [comment]
Thanks for test, you could say the same about qPrefDisplay, but both are preparing for the next set of batches (and having an open discussion).

**Comment by dirkhh** [comment]
Thanks for the reviews and rework. This looks ready to go in.

**Pull request merged**
