### PR TITLE
Csv multitank

### LINKED ISSUE #2830: Issues with CSV summary dive details - multitank dives
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

When exporting summary dive details as csv, information on multiple tanks (if used) is not exported. Specifically, information regarding cylinders used (cylinder size, startpressure, endpressure, o2 and he) is only shown for the first cylinder on the equipment tab. 

### Operating system:

Arch Linux
en_US.UTF-8

### Subsurface version:

4.9.4

Compiled myself

gce-7cc7970540

### Steps to reproduce:

1) Select dives (in this case I've selected dives with more than one tank)
2) Select File/Export and then "CSV summary dive details". Check the selection button "Selected dives"
3) Open the exported csv file and verify the missing info

### Current behavior:

The file only shows information (cylinder size, startpressure, endpressure, o2 and he) for the first cylinder on the equipment tab

### Expected behavior:

Information on all used cylinders should be exported (including -- feature request -- "SAC" for each cylinder.

### PR DESCRIPTION
**Pull request by mturkia**
### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [x] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

The idea was to implement support multiple cylinders in CSV export and SubsurfaceCSV import. This will only be supported when choosing SubsurfaceCSV from the import menu. Implementing test case for this, was a deep rabbit hole with plenty of debugging and bugs to be fixed. And some of this shows in this PR.

### Changes made:

1) multi-cylinder support for CSV export
2) multi-cylinder support for Subsurface CSV import
3) Implement test case for this
4) Fix multiple bugs in Subsurface CSV import, partly related to recently added SAC and dive mode support and partly to bugs in e.g. unit conversion
5) Switch old CSV export-import-export test case to use single cylinder dive (multiple cylinders is not supported in this kind of import)
6) Trip support for exporting cylinder info

### Related issues:

Fixes #2830

### Release note:

I guess this could be mentioned. Will push changelog shortly

### CODE REVIEW

**Comment by dirkhh** [comment]
I'm guessing the failed tests are all simply a fall out of the cloud server disaster... since I foolishly think that that's finally (??) under control (??) I restarted the tests.

**Review by dirkhh — COMMENTED** [review]
Me reviewing xslt is like me proofreading the Arabic translation...
I guess I'll merge once the tests pass

**Comment by mturkia** [comment]
Seems that some builds still fail with the git test case
11/31 Test #11: TestGitStorage ...................***Failed 16.68 sec

That should be unrelated to my changes. I do have the same problem when
running the tests on my laptop.

**Comment by dirkhh** [comment]
OK, now that the backend is feeling better, the tests pass. Will merge locally to deal with the very obvious CHANGELOG merge.

**Pull request closed without merging**
