### PR TITLE
Various updates to flags on map

### PR DESCRIPTION
**Pull request by bstoeger**
### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

This is a partial fix for #2076, which tries to make the behavior of the map edit mode more consistent. Since we get spurious reload signals - these have to be disabled during edit mode.

The problem is that now it works as supposed and only dive sites of dives which are not filtered away are shown. That means that on the dive site tab only the selected dive sites are shown, which is less than optimal. We probably have to add two filter modes
1) show only dive sites of filtered dives
2) show all dive sites even though filtering is active
?
### Changes made:

1) Don't exit edit mode when reloading map
2) Don't reload map when in edit mode
### Related issues:

#2076
### Release note:

Bug not in release.
### Mentions:

@djunkins

### CODE REVIEW

**Comment by bstoeger** [comment]
First attempt at showing all dive sites in dive site mode.

I'd still like to have all other dive sites grayed-out when on the dive site tab.

**Comment by bstoeger** [comment]
Trying to detangle the whole dive-selection / site-selection mess and I have a feeling that I'm running in circles... ☹

User visible changes:
- Now multiple sites are highlighted on the map if multiple dives/sites are selected.
- You can move sites while on the dive-site-table screen.
- Tons of warnings spewed on the console:
```
"Passing incompatible arguments to C++ functions from JavaScript is dangerous and deprecated."
"This will throw a JavaScript TypeError in future releases of Qt!"
"Could not convert argument 0 at"
         "expression for source@qrc:/qml/MapWidget.qml:62"
```

I believe the last point is due to Qt not being smart enough to turn null-QVariants into null-pointers. We'll probably have to turn the strongly typed function into a weakly typed one taking a QVariant. And convert it in the function, because why easy and compile-time evaluated when you can make it hard and run-time evaluated. ☹

**Comment by bstoeger** [comment]
Fixed the warnings by turning a proper typed parameter into a `QVariant`.

@djunkins: If you find time, could you try out if this works for you?

**Comment by djunkins** [comment]
@bstoeger This seems to work to edit the dive site flag location from the dive sites tab with two caveats:

1) Once you click the edit button to edit the dive site fields you can no longer drag the flag to a new location on the map, including after you click the Done button to return to the dive site list. Only after you select another dive site and come back to the original site can you move the flag again.

2) Sites that don't have dives associated with them are still not working. They don't appear on the map and when selecting a site with no dives, you can not edit it's location on the map.

**Comment by bstoeger** [comment]
Sigh - this is so horrible. When clicking the edit button, we reload the map four (sic!) times:

1) Click on the edit button - Qt selects the corresponding row.
2) We instruct the filter to filter on a different dive site.
3) This changes the selection, because the old selection was unselected.
4) The changed selection reloads the map (I).
5) After the filter has done its thing, it sends a filter finished signal.
6) That reloads the map (II).
7) We get the the click and switch into dive-site-edit mode.
8) The dive site tab instructs the filter to filter on the dive site.
9) Filter does its thing, sends a filter-finished signal and reloads the map (III).
10) The dive site list gets its hide signal and stops edit mode.
11) Filter is reset and reloads the map (IV).

10 is the reason why flag dragging does not work anymore.
I will try to improve this mess, but not today.

**Comment by bstoeger** [comment]
Added reference-counting to filter's dive site mode. It's awful, but at least now switching from table to edit view and back should work.

I'll see what is wrong with 0-dives dive sites, but probably not today.

**Comment by djunkins** [comment]
This is working much better for sites that have at least 1 dive associated with them. Interestingly, when you select both a site with dives and one without dive, the map zooms and scrolls to include coverage for the site without dives even though there is no flag there.

**Comment by dirkhh** [comment]
It's so obvious that the original code was written by multiple people with non-identical vision for the code flow - and maybe non-optimal understanding of the underlying mechanics. I recognize some of the abominations that you removed as hacks I did to fix something that I didn't fully understand.
Thank you so much for digging in and cleaning this mess up.
I read through all the commits and can't find anything to bicker about. @djunkins obviously has a point with the dive sites with no dives - but I wonder if we should merge this now and deal with that issue in a follow on PR - in the past long running PRs that we didn't bring into master often turned into rather significant time sinks.
Your call, @bstoeger

**Comment by bstoeger** [comment]
Do not commit yet, please. I think the whole dive selection vs. dive site selection vs. filter vs. map thing is still fundamentally wrong. But currently I have no time to wrap my head around it...

**Comment by dirkhh** [comment]
Marked as `[WIP]` to document that this isn't ready for merge

**Comment by neolit123** [comment]
thank for working on this refactor. i went trough the commits and this seems good.

when the QML map code was created it was a direct port of the old Marble (map globe widget) and for a short period of time we were able to toggle between the two map widgets on compile time. their backends were very similar in terms of public methods and signal/slot connectivity.

the reload-on-anything logic felt wrong, but was cheap and didn't cause any trouble (back then), so i didn't bother changing it.

but seems like the filtering of dive-sites with the combination of dive edit opened the can of worms.

> We probably have to add two filter modes
> 1. show only dive sites of filtered dives
> 2. show all dive sites even though filtering is active

1 is more intuitive, but if it creates complications 2 is fine.
i wouldn't add both modes or a toggle between the two.

**Comment by bstoeger** [comment]
Added commits that at least show unused dive sites on the map when in edit mode.

Still very non-intuitive behavior. For example, editing the name of a dive site does not immediately update the name on the map.

Another problem: Selecting multiple dive sites whereby one has no GPS locations will put the flag of the latter at the old map position, but the map will zoom on the former.

**Comment by bstoeger** [comment]
Name is now updated on the map.

@djunkins: is this usable for you?

It still has some funky issues with undo, etc. But we can take care about them later...

**Comment by djunkins** [comment]
Sorry. I’ve been buried with my day job. I’ll try to build and test this tonight.

**Comment by djunkins** [comment]
@bstoeger This seems to be working well. So far I have not run into any issues with it not working as expected.

**Comment by bstoeger** [comment]
Thanks. There still are UI quirks, but I hope that they are acceptable for a first version. Therefore removing the WIP tag.

**Review by dirkhh — APPROVED** [review]
Great series. I would have merged as is... but the typo in the commit message bugs me.
Maybe the best way to deal with this is for me to merge it manually instead of waiting for @bstoeger to force push...

**Pull request closed without merging**
