### PR TITLE
map-widget: interaction improvements

### LINKED ISSUE #754: map-widget: improvements for editing markers
### Describe the issue:

- [x] Bug
- [x] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

**PART 1 (COMPLETED)**
I see two more improvements for the new map widget based on the latest changes already done there:
- Today we have the following behavior: Map zoomed in to dive site A. One creates/imports a new dive with empty dive site. Enter the dive site B for the new dive which is a new one. Edit the new dive site. Map stays zoomed in at dive site A. You have to zoom far out and grab the new marker at '0' position somewhere south of Ghana and drag it to the desired position for dive site B.
Minimum two possible ways to improve this: 1. Zoom out automatically in this case to "whole world" or 2. Create the new marker at dive site A location.
- If you create a new dive site or edit an existing one you can manually enter coordinates. But the marker in the map is today not moved to the entered coordinates immediately while you are still inside the edit dive site dialog. It's updated only after pressing "apply changes". If you need some fine tuning to the coordinates by moving the marker in the map after entering the coordinates you today need to reenter the edit dive site dialog.
Can we update the marker immediately after entering valid coordinates? One remark: Please NO keyboard tracking for the edit field for this feature! Update only after coordinates edit looses focus (pressing enter or clicking in other field).

**PART 2 (WIP)**
- What is a great "side effect" of the new strategy is the following: After creating a new dive site for a new dive if the user "accidentally" already moves the map to the right location before pressing the "edit dive site" button this work is not lost when pressing the dive site button because the marker is created at the current map center. Thats great. But currently there is the strong need to once grab the marker then to have the gps coordinates copied to the edit field and to have it saved. Why not immediately copy the initial coordinates once. Maybe the marker is already at the 100% exact position and the user just wants to press "apply".
- If you now enter coordinates directly by keyboard this is reflected immediately in the marker position. BUT the map is not following the marker. So very often the marker will be out of sight and you have to find it by zooming out. The map should follow the marker in this case while keeping the current zoom level.

### PR DESCRIPTION
**Pull request by neolit123**
### Describe the pull request:

- [x] Bug fix
- [x] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

These is a PR to make the `PART 2` additions from #754.

### Changes made:

1) move the map with the edited dive site
2) start dive site editing with coords pre-entered
3) use 'getter' function coordinate() for MapLocation
4) interrupt map animations on new interactions

### Related issues:

Fixes #754

### Additional information:

@sfuchs79 please, ACK/NAK this PR once you review the UX changes.

### Release note:

```
- map-widget: follow the newly entered coordinates on the map when the user
  is editing a dive site
- map-widget: prevent glitches when the user is interacting with the map
  while animations are in progress
```

### Documentation change:

none

### Mentions:

@dirkhh @sfuchs79

### CODE REVIEW

**Comment by dirkhh** [comment]
I have not tested this, but reading the code it looks fine. I will flat out admit that I don't think I understand what the first commit (eefc449) really does :-/

**Review by dirkhh — APPROVED** [review]

**Comment by neolit123** [comment]
> I will flat out admit that I don't think I understand what the first commit (eefc449) really does :-/

user enters new latitude, longitude and the marker moves to that location. with this patch, the map viewport moves too.

**Comment by neolit123** [comment]
looks like i'm able to make the app enter a busy state (infinite loop) if i enter some random coordinates (testing in decimal mode), but cannot reproduce this consistently. will debug tomorrow.

**Comment by sfuchs79** [comment]
@neolit123 
> - [...] But currently there is the strong need to once grab the marker then to have the gps coordinates copied to the edit field and to have it saved. Why not immediately copy the initial coordinates once. Maybe the marker is already at the 100% exact position and the user just wants to press "apply".

This part seems to be covered perfectly. After a few tests I would say you implemented this exactly according to my expectations. Thanks!

> - If you now enter coordinates directly by keyboard this is reflected immediately in the marker position. BUT the map is not following the marker. So very often the marker will be out of sight and you have to find it by zooming out. The map should follow the marker in this case while keeping the current zoom level.

With the implementation for this I still have some small doubts I would like to discuss with you:
- Is it really a good approach to have keyboard tracking enabled for the coordinates edit field? I ask this because: If you want to change a value like minutes or seconds e.g. from 49 to 50 you will - by keyboard - first delete the whole "49" and then enter "50" instead. And all the time while doing this the map will move.
- Could we do all this map movement COMPLETELY W/O changing the zoom level? I guess you also recognized that with this implementation if you quickly change around numbers in the coordinates edit field you can even end up with a different final zoom level compared to the starting zoom level. That's not nice. For this feature (other than for selecting different dives in the dive list) I would prefer that the map moves at very high speed to the new location w/o changing zoom. Question: Does the map even support this?



No freeze or other strange things detected on my side but I didn't spent more than 10 minutes on testing up to now.

**Comment by neolit123** [comment]
@sfuchs79 
thanks for testing,

i'm tempted to disable the update-coordinates-as-you-type feature and add a button that says `update` (coordinates), which is probably the better UX.
i confirm that something isn't right with the zooming out code, and also the freeze has to be investigated.

i will see how can i improve this later today.

**Comment by dirkhh** [comment]
@neolit123 @sfuchs79 thanks to both of you for working on this.
- I think move as you type won't be a great experience
- I suggest to move if the input field loses focus or if the user pushes a button to update
- alternatively you can get fancy and do something like "no key pressed in 2 seconds" as well :-)

- Once that is fixed, I assume that the zoom level change isn't that much of an issue anymore, but we'll have to see how that feels then.

**Comment by sfuchs79** [comment]
> I suggest to move if the input field loses focus or if the user pushes a button to update

My suggestion would be to first really try this very simple "loses focus" approach and let's check if we like it. Robert did this recently for some combo boxes in the planner (ascent and descent rate). The change is very simple, just look at https://github.com/Subsurface-divelog/subsurface/commit/030c094854aeab4aaade523d7126728d9ce98a5b

**Comment by neolit123** [comment]
i have updated the commits:
- user can now press enter or a flag button to update the coordinates
- fix for infinite loops
- QML cleanup
- zoom in/out i still happening when editing the coordinates by hand - i think this is the correct way to approach this.

**Comment by neolit123** [comment]
looks like i have a bit of a GIT issue locally. will find a fix first and update.
(done: had to reflog/undo a bit of a mess)

**Comment by sfuchs79** [comment]
From my point of view this map update works really nicely now.
Did some tests today and didn't see any malfunctions.

**Comment by dirkhh** [comment]
So where are we with this? Ready to merge?

**Comment by neolit123** [comment]
> So where are we with this? Ready to merge?

yes, maybe we can get more feedback from the mailing list.

**Pull request merged**
