### PR TITLE
[RFC] Add dive(s) to any trip

### PR DESCRIPTION
**Pull request by bstoeger**
### Describe the pull request:

- [x] Functional change
- [ ] Bug fix
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

A user requested on the mailing list that dives be added to any trip. Indeed, the restriction to add dives only to the trip above/below seems illogical. This adds the possibility to add dive(s) to any trip. The trip is selected in a new dialog.

### Changes made:

1) Add trip selection dialog.
2) Move trip header formatting to qt-helper.cpp so that code can be reused by the new dialog.
3) Add context menu to add dives to any trip.

### Additional information:

1) Mostly untested
2) I noticed that the add to trip above/below feature is currently broken: Remove a dive from the middle of the top-most trip. The context menu will feature a "add to trip above" entry even though there is *no* trip above.
3) The context menu is getting absurdly long - this is in need of a redesign.
### Release note:

Done.
### Documentation change:

Perhaps?
### Mentions:

@dirkhh, @willemferguson for possible documentation change...?

### CODE REVIEW

**Review by dirkhh — COMMENTED** [review]
this sounds logical - I need to play with the UI, though.

**Comment by dirkhh** [comment]
The UI isn't super slick, but, yeah, this is a start.
But, in my testing, I was able to reproduce this odd effect.
- dive list has a few trips, then one top level dive, a trip with one dive, another top level dive, more trips
- add these two top level dives to a trip
- undo
- now in the dive list the two top level dives are next to each other, and the trip that was between them is instead after them

**Comment by bstoeger** [comment]
Can you test whether this:
```
iff --git a/qt-models/divetripmodel.cpp b/qt-models/divetripmodel.cpp
index 539cf98ff..bc2c2ea46 100644
--- a/qt-models/divetripmodel.cpp
+++ b/qt-models/divetripmodel.cpp
@@ -1325,8 +1325,8 @@ void DiveTripModelTree::divesMovedBetweenTrips(dive_trip *from, dive_trip *to, b
 	// Cheating!
 	// Unfortunately, removing the dives means that their selection is lost.
 	// Thus, remember the selection and re-add it later.
-	divesAdded(to, createTo, dives);
 	divesDeletedInternal(from, deleteFrom, dives); // Use internal version to keep current dive
+	divesAdded(to, createTo, dives);
 }
 
 void DiveTripModelTree::divesTimeChanged(timestamp_t delta, const QVector<dive *> &dives)
```
fixes the problem?

Unrelated: The German translation is confused: "(1 Tauchgang(e))" vs. "(6 Tauchgäng(e))". Weird.

**Comment by willemferguson** [comment]
I will keep an eye on this with the view of documentation changes

**Comment by dirkhh** [comment]
> Unrelated: The German translation is confused: "(1 Tauchgang(e))" vs. "(6 Tauchgäng(e))". Weird.

Sweet.
That's verbatim in our translations. Oops.
```
        <translation><numerusform>(%n Tauchgang(e))</numerusform><numerusform>(%n Tauchgäng(e))</numerusform></translation>
```
looking through the various translations with `numerusform` I found a second one that's wrong. Will fix that one as well.

**Comment by dirkhh** [comment]
> Can you test whether this:
> 
> ```
> iff --git a/qt-models/divetripmodel.cpp b/qt-models/divetripmodel.cpp
> index 539cf98ff..bc2c2ea46 100644
> --- a/qt-models/divetripmodel.cpp
> +++ b/qt-models/divetripmodel.cpp
> @@ -1325,8 +1325,8 @@ void DiveTripModelTree::divesMovedBetweenTrips(dive_trip *from, dive_trip *to, b
>  	// Cheating!
>  	// Unfortunately, removing the dives means that their selection is lost.
>  	// Thus, remember the selection and re-add it later.
> -	divesAdded(to, createTo, dives);
>  	divesDeletedInternal(from, deleteFrom, dives); // Use internal version to keep current dive
> +	divesAdded(to, createTo, dives);
>  }
>  
>  void DiveTripModelTree::divesTimeChanged(timestamp_t delta, const QVector<dive *> &dives)
> ```
> 
> fixes the problem?
> 

It does fix the problem

**Comment by bstoeger** [comment]
Added fix and fixed CHANGELOG.md conflict.

Note that this is probably not the perfect fix. And it will probably be easiest to simply send two signals from the core (remove-dive/add-dive) instead of one (move-dive) to avoid sorting inconsistencies.

**Review by dirkhh — APPROVED** [review]
LGTM

**Comment by dirkhh** [comment]
You are of course encouraged to send a better fix in a future PR :-)

**Comment by dirkhh** [comment]
ignoring the GitStorage fail - there clearly is something odd happening on the backend. Which once again I cannot reproduce.
Oh how I love this test.

**Pull request merged**
