### PR TITLE
Filtering: Usability Improvements to Filter Constraints.

### PR DESCRIPTION
**Pull request by mikeller**
### Describe the pull request:

- [ ] Bug fix
- [x] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Some improvements.

### Changes made:

1. for constraints where the condition is applied to any one of a list of items, show the condition as 'any X';
2. when filtering for tags, do not include divemode as a 'tag' - this is hard to impossible for users to understand, and we do have a dedicated condition for the dive mode.

### Additional information:

image

### CODE REVIEW

**Comment by bstoeger** [comment]
fine with me.

@dirkhh: care to comment on this UI change?

**Review by bstoeger — APPROVED** [review]

**Comment by dirkhh** [comment]
I'm not sure I understand why calling this "any ... " is easier to understand. 
I would read it as "this triggers with any value"

It's a translation text change and I'd be concerned if the translators will know how to reflect the intention without more information.

So, I'm not against making improvements, but I worry about how this will play out for the user, especially the non-English users

**Comment by bstoeger** [comment]
We could do "person (any of)". Optionally, have "(any of)" as separate translation string and have it automatically added if an `any_of` flag is set in the type description?

**Comment by mikeller** [comment]
> I'm not sure I understand why calling this "any ... " is easier to understand. I would read it as "this triggers with any value"

This is just based on the observation that, when taken as natural language, the filter condition 'tags is starting with X' is clearly not correct in cases where it is not the first tag in the list that matches 'X':

image

> It's a translation text change and I'd be concerned if the translators will know how to reflect the intention without more information.

Yes, this will require the translators to get some context, either by checking in-app to see where this change is applying, or by being given cues (not sure if transifex supports this).

> We could do "person (any of)".

Yes, the '(any of)' is an alternative - but not sure if this wil make it easier for translators to grasp how it will be used without being provided with context.

> Optionally, have "(any of)" as separate translation string and have it automatically added if an `any_of` flag is set in the type description?

Unfortunately this will definitely break translations, or at least make them even more awkward, as in at least some of the languages where nouns have a gender the 'any' will have to follow the gender of the noun. (cf. 'ein' / 'eine' in German).

**Comment by bstoeger** [comment]
> Yes, this will require the translators to get some context, either by checking in-app to see where this change is applying, or by being given cues (not sure if transifex supports this).

Qt has //: comments for translators: https://doc.qt.io/qt-5/i18n-source-translation.html Not sure if this works for the QT_TRANSLATE_NOOP macros, though.

> Unfortunately this will definitely break translations, or at least make them even more awkward, as in at least some of the languages where nouns have a gender the 'any' will have to follow the gender of the noun. (cf. 'ein' / 'eine' in German).

Yes, the translators might have to be creative in that case. I think @atdotde is responsible for the German translation (I don't use it) - best to ask him about proper gendering.

PS: Perhaps we should expand the code to allow for any of / all of / none of searches...?

**Comment by mikeller** [comment]
> Yes, the translators might have to be creative in that case. I think @atdotde is responsible for the German translation (I don't use it) - best to ask him about proper gendering.

Or just leave it as the fixed expression for the handful of cases that we have. 😉

> PS: Perhaps we should expand the code to allow for any of / all of / none of searches...?

We already have 'is not' that can be used to compose a 'none', and users can add multiple conditions for the same 'any' element to get 'all of' semantics for multiple search terms.

**Pull request merged**
