### PR TITLE
Icons wip

### PR DESCRIPTION
**Pull request by merinsky**
### Describe the pull request:
- [ x] Functional change
- [ x] New feature
- [ x] Code cleanup

### Pull request long description:

* Icons were in several formats, and several sizes. It made them diffucult to work on. Now all icons are scalable. Bitmap icons can be fine-tuned for several sizes (but SVG works just fine for me). Scalable icons are also usable for HiDPI displays.

* Filenames were mess. Now all filenames follow one naming scheme.

* Some Subsurface icons were arranged to a theme, some not. Now all of them are. It makes it possible to use your current theme icons and improve yout GUI integration (or switch icons theme).

* Number of icon files has decreased. Icons have been deduplicated and unused icons were removed.

For graphics: SVG files are using correct 96 DPI. "Plain SVG" format is used. It makes files small. And there are less binary files in the repo.

### Changes made:

* While many icons have to be drawn from scratch (there weren't SVG), I tried to find better metaphors and improve icons readability. Please consider this a proposal. Once SVG icons are used, it would be much simpler to improve (redraw) icons. I'm open to suggestions.

* On several places, your GUI theme icons are used. I believe this is the way to go.

* I changed very slightly buttons order. I followed general rules:
  * Related items close to each other.
  * Most important and used items first.
  * Ceiling options are somehow likely to be found up.
  * Bottom options should be down (where one expects the bottom).
  Proposed order is:
  * Start with various ceilings.
  * Gas related items and partial pressures.
  * O2 limits us the most, then N2, He only TECs.
  * Divers body related items. Both are rates.
  * Depth limit related items are down (NDL is closely related to depth).
  * Graph related options last.

* If there is no graph to show. Scale background Subsurface logo.

* Filter show/hide icon changes according to the action it will perform.

### CODE REVIEW

**Comment by janiversen** [comment]
How about mobile-widgets/qml/icons could you please have a look, and if no changes are needed add it to a commit message.

**Comment by merinsky** [comment]
I'm not using Subsurface Mobile and have no QML knowledge. So I tried not to break Subsurface mobile or touch it in any way.

**Comment by janiversen** [comment]
lets make a deal, because I do not have your graphical experience. You do the icons, I then do the needed qml changes. Deal ?

In case yes, simple add a commit to this PR, and I will do another PR, asking @dirkhh to merge the 2 simultaniously.

**Comment by janiversen** [comment]
Just saw iOS is already broken, I can adjust that in a couple of hours.

**Comment by merinsky** [comment]
Unfortunatly, yes. Mobile version and some build/install scripts are broken. I tried to fix some problems. If you can help, it would be really great!

**Comment by janiversen** [comment]
I kniw the buil system so I will help you, but it will not be today.

ps. you have forgotten to sign your commit that is why the bot is unhappy

last in each commit needs to be like (of course changed to yours):
Signed-off-by: Jan Iversen <jani@apache.org>

**Comment by mfbernardes** [comment]
Maybe you could also could post screenshots showing the app with the new icons.

I took a quick look. The O2, H2, N2 icons seem harder to read than the originals.
screen shot 2018-06-01 at 21 51 16

Edit: ok, ok... I had not been able to read all my emails yet. I saw now the email with the images.

**Comment by janiversen** [comment]
all green, nice. I like the new icons, but honestly I am not a designer so I will leave decisions to others.

I have started a similar cleanup in mobile-widgets/qml/icons and hope to reuse your svg files. However I think there are still a number of png left e.g. in mapwidgets.

**Comment by dirkhh** [comment]
So I've held back commenting so far because I figured maybe I'll have to get used to them to appreciate the new icons. But... ummm. I honestly do not think that they are an improvement.

**Comment by merinsky** [comment]
Using GUI icons and adding only special ones is the correct way. I think good applications do it this way. I really don't want to use several different icons for "cleaning form", "removing list element" or "network settings", etc.

I don't stick to proposed icons. More important is to have one source format and size. Then you can ask icon makers for help. Or even arrange a competition. In current state, no one would do it, because current icons are a mess.

I'm offering to redraw or improve icons according to users wishes. Or make some small code tweaks.

If someone is wiling to cherry pick something, or base his work on this, I'm fine with it. I do not need credit. Other than that, this is take or leave (forever) work. Sorry.

**Comment by dirkhh** [comment]
> Other than that, this is take or leave (forever) work. Sorry.

If there was ever a comment that made me want to walk away from a submission, this one might be it. As a project, being told "take this or else" is not really interesting.

I will go through this huge pull request and cherry pick what I consider useful.
As far as being lectured what is "the correct way"? Err, yeah, I think I can do without that.

**Comment by tcanabrava** [comment]
It's strange to read " Please consider this a proposal." and "Take or leave (forever)" from the same contributor, but let's go:
The icons where initially SVG and we used them to load to memory and create pixmaps from that, this was slow and made subsurface took a few seconds more to show than it should, that's why we moved away from svg to png. Of course we could have kept the icons in svg mode but then another problem, the designer that did the icons used Illustrator and .ai files are a pain to open without it, also the svg export is still broken. So we accepted her submissions of icons in png and everyone was happy.
As for your icons, Some are better, some are not, and that's life. If you would like to keep contributing to subsurface, please be my guest as we miss designers, for real.

**Comment by merinsky** [comment]
> It's strange to read

You are taking my words out of context "I'm offering to ...", "Other than that".

> this was slow

I don't see any delay using SVG icons.

> we moved away from svg to png

It is not necessery to load SVG. I already wrote "Bitmap icons can be fine-tuned for several sizes". Have you ever looked into how icons are organized in some widely used projects?

> we could have kept the icons in svg mode but then another problem, the designer that did the icons used Illustrator and .ai files are a pain to open without it

Strange, I didn't use Illustrator at all. And there already are SVG icons in Subsurface.

Source format has to be SVG, if there is any intention to let someone work on the icons and be able to scale them for HiDPI displays.

> everyone was happy

Not me. Current icons are "organized" in a complete mess. Some are in theme, some are not. They are in several different formats and sizes. They are unresizable. Some icons are unreadable. Many icons make no sense - there is no way to figure out what action they are supposed to stand for. They are not using the same color palette and style. Subsurface is using it's own icons for actions widely used through the whole GUI.

> Some are better, some are not

As I wrote "consider this a proposal", "I'm open to suggestions."

So I really don't understand you.

The most important things in my patches are naming, deduplication, organization. I would love to let everybody use the icons he likes. But with current codebase, it's not possible.

My time is precious. There were no constructive criticism. I don't see any way how to split this work into smaller pieces.

**Comment by tcanabrava** [comment]
"Strange, I didn't use Illustrator at all."
The original icon designer, Luisa Pires, did. She did not want to learn another tool, some other icon designers did in svg. 

I agree with you that our icons needs a bit of push up.
I can try to do a "Theme Settings" for the icons and we can join together for packs, what you think?

**Comment by merinsky** [comment]
> I can try to do a "Theme Settings" for the icons and we can join together for packs, what you think?

@tcanabrava I don't understand what are you proposing.

What might be done is configurable usage of GUI theme icons, whrere feasible. While it doesn't make sence to me, i understood @dirkhh doesn't want to use his GUI icons and wants separate icons for Subsurface.

Changing themes (using different icon sets) was one of my aims. It could be done _after_ this work. Not before, becase current icons cannot be used. They are in many different sizes and formats. Some are in the theme, some are not. Not speaking about the naming mess. Someone would have to redraw, reorganize and rename current icons. And it probably wouldn't be me, becouse I find current icons unintuitive and unreadable.

Generally, I doubt there is any interest in my work. There wasn't any _constructive criticism_. And after the reactions above, I'm willing to spend much less time with Subsurface.

> I will go through this huge pull request and cherry pick what I consider useful.

Dirk probably didn't find anything usefull.

Right now, I'm rebasing my set of patches. It's not quite pleasant, but it works.

**Comment by neolit123** [comment]
closing due to inactivity.
please re-open if needed.

**Pull request closed without merging**
