### PR TITLE
Update the dive list context menu to reflect new media interface

### PR DESCRIPTION
**Pull request by willemferguson**
A minor change to the UI. The wording of the two items in the dive
list context menu "Load image(s) from file(s)" and "Load
image from web" are updated since we now deal with both images
and videos. So it becomes "Load media from file(s)".... etc.

Signed-off-by: willemferguson <willemferguson@zoology.up.ac.za>

### Describe the pull request:

- [ ] Bug fix
- [x] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### CODE REVIEW

**Comment by janmulder** [comment]
Please remove the change to `appdata/subsurface.appdata.xml` from this PR. Due to a recently introduced small bug in the build system, this change always show up.

**Comment by willemferguson** [comment]
Jan, I am clueless about this. How should I  remove the change(s) to appdata/subsurface.appdata.xml ?? The changes are contained in the commit that changes my repository. If I do git reset --hard HEAD^1 then the whole commit is removed. Please give me an idea? Kind regards, wf.

**Comment by janmulder** [comment]
I would do:

```
git checkout video2
git checkout appdata/subsurface.appdata.xml
git add appdata/subsurface.appdata.xml
git commit -s
git rebase -i master (and mark the new commit with "fix", instead of "pick")
git push  -f origin video2
```

**Comment by willemferguson** [comment]
~/src/subsurface$ git checkout appdata/subsurface.appdata.xml
~/src/subsurface$ git add appdata/subsurface.appdata.xml
~/src/subsurface$ git commit -s
On branch video2
nothing to commit, working tree clean
~/src/subsurface$ 

What does this mean???

**Comment by dirkhh** [comment]
I'll deal with it here - don't worry about it.

**Pull request closed without merging**
