### PR TITLE
Correct time bookkeeping when doing O2 breaks

### LINKED ISSUE #662: O2 breaks timing incorrect
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

In current master the O2 breaks timing is broken, maybe comming from this change:
515b7b5fea13762f8003963eca4c2a241c52dfb7

In 4.6.4 release this still looked good.

Ok example in 4.6.4:
grafik

NOT Ok in current master:
grafik

### Mentions:

@atdotde

### PR DESCRIPTION
**Pull request by atdotde**
These got mangled with previous changes to stop length determination.

I guess this
Fixes #662
but I am getting a bit tired. Please confirm @sfuchs79 

Signed-off-by: Robert C. Helling <helling@atdotde.de>

### Describe the pull request:

- [x ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Documentation change
- [ ] Language translation

### CODE REVIEW

**Comment by dirkhh** [comment]
Great work, @atdotde - you can tell how good you are if @mention-bot suggests that you should review your own PR...
Thanks for all the effort you are putting in. This really helps a lot.

**Comment by sfuchs79** [comment]
The results look much better but there are still some small concerns and questions from my side.
Sorry for the nitpicking but I think let's better do it perfectly and maybe even post 4.7 that in a hurry:

[air_breaks_test.zip](https://github.com/Subsurface-divelog/subsurface/files/1397599/air_breaks_test.zip)

1. Results with this fix vs. results 4.6.4
With an example dive (attached) the last stop w/o breaks is identical for current master plus this fix and 4.6.4:
6m | 33min | 136min | Oxygen
0m | 6min | 142min |  
Then with breaks in 4.6.4:
6m | 13min | 117min | Oxy
6m | 6min | 123min | (18/45)
6m | 12min | 135min | Oxy
6m | 6min | 141min | (18/45)
6m | 6min | 147min | Oxy
0m | 6min | 153min
And with breaks in "fix":
6m | 13min | 118min | Oxy
6m | 6min | 124min | (18/45)
6m | 12min | 136min | Oxy
6m | 6min | 142min | (18/45)
6m | 8min | 150min | Oxy
0m | 6min | 156min
So w/o break we have a stop time on Oxy of 33min. With 4.6.4 the total time on Oxy is reduced to 13+12+6=31min which takes into account that we also desaturate during the breaks. With "fix" we again have the full 13+12+8=33min Oxy stop. Also one can see that in the "fix" result the ceiling clears some minutes before the final ascend is started. So I think 4.6.4 uses the correct approach.

2. In 4.6.4 code before the changes there were two variables used for this function: "breaktime" and "o2time". Now in "fix" "o2time" is initialized a couple of times but not used a single time and also "breaktime" seems to be used in a different way. Maybe one or both variables can be completely removed now or maybe one needs to "activate" them again to achieve the perfect result.

3. In 4.6.4 the "minimum stop time" was somehow also used when the timing for the O2 breaks was calculated. I first was confused if this makes clearly sense but then I recognized that the code in 4.6.4 seems to be in a way that the "minimum stop time" has NO effect on the air breaks.
And exactly this is an issue we now seem to have with the "fix": In the fix if I change "minimum stop time" this has an undesired effect on the calculation of the air breaks. The interesting thing is that the error is max if I set "minimum stop time" to 0 and min if I set it to max value of 9min. The example above was done with 5min.

Example dive, min switch to 9min:
grafik

Example dive, min switch to 0min:
grafik

**Comment by atdotde** [comment]
Hi,

> On 19. Oct 2017, at 10:32, Stefan Fuchs <notifications@github.com> wrote:
> 
> So w/o break we have a stop time on Oxy of 33min. With 4.6.4 the total time on Oxy is reduced to 13+12+6=31min which takes into account that we also desaturate during the breaks. With "fix" we again have the full 13+12+8=33min Oxy stop. Also one can see that in the "fix" result the ceiling clears some minutes before the final ascend is started. So I think 4.6.4 uses the correct approach.

I agree there is still something borked with the O2 breaks. When you make a 60m dive on air (don’t ask) with O2 deco gas long enough, you can get a deco with breaks where the time on O2 (not counting the break time) is significantly longer than the 6m stop without breaks.

Will investigate this further.

Best
Robert

--
.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oO
Robert C. Helling     Elite Master Course Theoretical and Mathematical Physics
                      Scientific Coordinator
                      Ludwig Maximilians Universitaet Muenchen, Dept. Physik
                      Phone: +49 89 2180-4523  Theresienstr. 39, rm. B339
                      http://www.atdotde.de

Enhance your privacy, use cryptography! My PGP keys have fingerprints
A9D1 A01D 13A5 31FA 6515  BB44 0820 367C 36BC 0C1D    and
DCED 37B6 251C 7861 270D  5613 95C7 9D32 9A8D 9B8F

**Comment by dirkhh** [comment]
10 days... is this abandoned? :-)
(ridiculous comment... I'm sorry... should have just said PING?)

**Comment by atdotde** [comment]
These two should fix the remaining problems except for the unused variables. With this (and hopefully a check by @sfuchs79 that this is indeed the case) this should be ready to go for 4.7.2

**Comment by dirkhh** [comment]
Did I miss a comment on this from @sfuchs79 ? I am very worried about pulling this for 4.7.2... but then again... we'll do a 4.7.3...

**Comment by sfuchs79** [comment]
After one quick test this seems to be ok now.
I was a little bit confused at the first moment because when looking at the PR diff a recent change (already merged into master) done by me in the same file and area was missing. But then when looking at current master Roberts and my work was visible. How can this happen? Does this happen when a branch used for a PR was not rebased on master before doing the PR?

There is one thing now due to this overlap of two changes:
Robert introduced a "stopcylinder" and I once introduced a "breakfrom_cylinder" and both are now used in some specific way. But maybe we don't need both and could make the code look simpler if we remove one of both. Plus maybe we can finally remove the unused variables.

If you allow me to work on this I maybe tidy up this part in the next few days...

**Comment by dirkhh** [comment]
I decided to merge it. So please create a new PR that deals with any discrepancies you see

**Pull request merged**
