### PR TITLE
Fix MacOS build & update INSTALL.md

### PR DESCRIPTION
**Pull request by rmultan**
Fix build for Apple silicon Mac. Update INSTALL.md with relevant instructions.

### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [x] Documentation change
- [ ] Language translation

### Pull request long description:
Fix MacOS build for Apple silicon Macs and update build instructions for MacOS.

### Changes made:

1) Update libgit2 to current latest version
2) Update libcurl to current latest version
3) Switch MacOS build of libcurl to use openssl instead of darwinssl
4) Add entitlements-mac-dev.plist file to disable library validation for debug builds on MacOS

### Documentation change:

Update INSTALL.md with instructions to sign the app in order to run it locally.

### Mentions:

@mikeller follow up to this [comment](https://github.com/subsurface/subsurface/pull/4268#issuecomment-2247897181)

### CODE REVIEW

**Comment by mikeller** [comment]
@rmultan: Looks like this is breaking our android build - can you please have a look?

**Comment by rmultan** [comment]
@mikeller I will try to resolve it

**Comment by rmultan** [comment]
@mikeller Can you run builds? I think it should be fixed

**Comment by rmultan** [comment]
@mikeller @dirkhh Can one of you try to run builds to validate if I managed to fix the issue with android build?

**Comment by mikeller** [comment]
@rmultan: Apologies, I missed your prior comment. I am still getting used to the requirement for approval for CICD runs on pull requests from 'new' contributors.

**Comment by rafal-karhoo** [comment]
let me just verify the build on clean MacOS, so make sure that INSTALL.md covers everything required in order to build

**Comment by rmultan** [comment]
let me just verify the build on clean MacOS before merging to make sure that INSTALL.md covers everything required to build

**Comment by rmultan** [comment]
@mikeller all good now, please run builds

**Review by mikeller — APPROVED** [review]
Tested the android build. Good job on figuring this out, @rmultan!

**Pull request merged**
