### PR TITLE
fix site/location build issue

### PR DESCRIPTION
**Pull request by salvadorcunat**
[SmartTrak import]
We were assuming these tables were sorted with their indexes, but it
happens to be false, under some circustances at least, and results in merged or wrong locations/sites.

Simply check the index fixes the issue.

ATM I don't know what makes the index to be unsorted, may be a big number of dive sites, may be editing an old dive point ...

Reported-by: Andreas Hagberg <scubasoft@gmail.com>
Signed-off-by: Salvador Cuñat <salvador.cunat@gmail.com>

### Describe the pull request:

- [X] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Mentions:

@atdotde

### CODE REVIEW

**Comment by bstoeger** [comment]
Looks good to me in principle, but what happens if for some crazy reason the index is not found? Looks like an infinite loop to me.

I suggest that we try to handle that situation gracefully, as that shouldn't be too hard.

**Comment by salvadorcunat** [comment]
Hi @bstoeger .
You are right there would be an infinite loop. Take a look to the other patch I've just send.
Nevertheless, the only reasons I can think of for the failure would be a damaged db which should be catch by the previous smtk-open-table() call or a dive reffering to a non existent index which should be really weird as the .slg file would fail on the smarttrak application too.

**Comment by bstoeger** [comment]
> Nevertheless, the only reasons I can think of for the failure would be a damaged db which should be catch by the previous smtk-open-table() call or a dive reffering to a non existent index which should be really weird as the .slg file would fail on the smarttrak application too.

Sure, but since handling it is not hard, I think we should try it. Your patch leaks memory, but it's not terribly important as this is a "shouldn't happen" situation.

**Comment by atdotde** [comment]
I installed the original patch on the web service and this indeed fixes the reporter's problem.

**Comment by atdotde** [comment]
Restarted the Mac build.

**Pull request merged**
