### PR TITLE
Minor code hygiene: profile code

### PR DESCRIPTION
**Pull request by bstoeger**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

This is just minor code hygiene, see commit messages for details.

On a side note: The positioning of the profile seems broken to me. You can't use relative positioning for the axes! This will lead to either free space or cut-off axes on resizing. Matter of fact, when exporting the planned dive, depths > 100 m/ft are cut off for me. I believe that the whole idea of a fixed (100, 100) size is broken. I am *not* at all looking forward to fix this.
### Release note:

Nope.

### CODE REVIEW

**Review by dirkhh — APPROVED** [review]
I am 99% that the simple compare initially didn't work. I think there was an offset between the pointer values or something... if this works now, even better.
I like the DiveTextItem cleanup - and of course the header simplification

**Comment by bstoeger** [comment]
There *is* an offset. But the compare still works, because the compiler understands that this is the only way it can upcast (sidecast?) the pointer to be compatible. Unless something completely  different changed, this construct should always have worked (before Qt even existed).

Maybe you were just confused by the `printf` output with different values? For historical interest it might be interesting to check out the original version of the code, but I don't think it's worth the hassle. :-P

**Comment by bstoeger** [comment]
For illustration:
```
printf("%p %p\n", diveComputerText, (QGraphicsItem *)diveComputerText);
```
gives
```
0x55b4069a3d40 0x55b4069a3d50
```

This cast implicitly happens if you compare to `QGraphicsItem *`, so everything turns out fine.

**Comment by dirkhh** [comment]
I will never understand C++

**Pull request merged**
