### PR TITLE
Update divelist when changing units

### LINKED ISSUE #1591: Add unit selection preference to mobile app
### Describe the issue:
- [ ] Bug
- [ ] Change request
- [ x ] New feature request
- [ ] Discussion request

### Issue long description:
For reasons surpassing my personal understanding, my partner prefers Imperial units. And yet, the dive detail views in the mobile app only show the dive information in metric. Now, clearly metric is superior in virtually every way, but yet still I'd like to help those who have not yet transitioned their thinking.

### Operating system:
Android

### Subsurface version:
2.1.0(4.8.0.0)

### Steps to reproduce:
Open a dive in the mobile app
Try to see units in Imperial.

### Current behavior:
Only gloriously understandable metric units

### Expected behavior:
Confusing and nonsensical imperial units are displayed instead.

### Additional information:
I started digging through the code, but I'll have to admit I have some things to learn about QML+Android and could use some structural pointers.

### PR DESCRIPTION
**Pull request by jbygdell**
### Describe the pull request:

- [X] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

We need to explicitly refresh the divelist when switching between
metric and imperial unit systems. Or the changes will not be visible until
we restart the app or scroll outside of what's in the current cache.
This will update both the divelist view and the dive profiles to show the new units.

### Related issues:

Related to #1698 and properly Fixes #1591

### CODE REVIEW

**Comment by jbygdell** [comment]
Derek add label: ui-mobile

**Comment by dirkhh** [comment]
Cool - I'll test this soon...

**Comment by janmulder** [comment]
The divelist and details correctly change dynamically. 

The only thing that I've a little doubt ... should something change to the date format? I still see those M/d/YY US style dates when in metric.

**Comment by jbygdell** [comment]
@janmulder date format is not part of our unit structs, it is set via system locale.
as per units.h
```
#define SI_UNITS                                                                                           \
        {                                                                                                  \
	        .length = METERS, .volume = LITER, .pressure = BAR, .temperature = CELSIUS, .weight = KG,  \
		.vertical_speed_time = MINUTES, .duration_units = MIXED, .show_units_table = false              \
        }

#define IMPERIAL_UNITS                                                                                     \
        {                                                                                                  \
	        .length = FEET, .volume = CUFT, .pressure = PSI, .temperature = FAHRENHEIT, .weight = LBS, \
		.vertical_speed_time = MINUTES, .duration_units = MIXED, .show_units_table = false              \
        }
```

**Comment by dirkhh** [comment]
The short answer is "no they shouldn't"
The long answer is that our users won't rest until we have reimplemented every single thing that's in the desktop version in the mobile version.

**Comment by jbygdell** [comment]
Seems like Travis is a bit grumpy today.

**Comment by dirkhh** [comment]
travis is grumpy with the Subsurface website.
Apparently we are being targeted by someone who likes to take down the server.
Huge volume of requests coming in from thousands of IP addresses, all at the same time - resulting eventually in a server crash three times in the past 3 days

**Pull request merged**
