### PR TITLE
Make salinity data in the Information tab editable. (rebased / merged #2391)

### PR DESCRIPTION
**Pull request by dirkhh**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [x] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

mainly so that it's easier for @willemferguson to look into the issue mentioned in #2391

### CODE REVIEW

**Comment by willemferguson** [comment]
Please send me a sample (3-4 dives) of your dive log that I can play with??  You can anonimise it. I would like to see if it is repeatable on my system and track down the issue. The position of the headings is a rather easy thing to diagnose, a single statement in tabDiveInformation.cpp. Let's hope there is a simple explanation for it.

**Comment by willemferguson** [comment]
I made two changes: 1) Hardcode the vertical position of the QGroupBoxes in the Information tab (I suspect Qt's interpretation of the CSS em variable is not the same in all versions of Qt); 2) Make the default salinity saltwater, nor freshwater. However, this does NOT solve your problem of the code not seeing your dive computer-derived salinity. Having a small demo dive log of yours will really be helpful. I am not sure how to get the above changes into the rebased repository. Clearly another commit to #2391 is inappropriate.

**Comment by dirkhh** [comment]
> I am not sure how to get the above changes into the rebased repository. Clearly another commit to #2391 is inappropriate.

Feel free to just add commits there and I'll wrangle them into place.

As for a sample - this appears to happen with cloud repos (and local git repos), so I'm guessing it's an error in the `load-git` implementation. I'm traveling like mad again (returned from New York last night, heading to Tokyo tomorrow) - I will try to look into this "at some point" myself :-)

**Comment by willemferguson** [comment]
Well, it is either save-git that writes wrongly or load-git that parses incorrectly. I will have  a look-see and communicate if I find anything definite. I will then hold off with additional commit(s) until all issues are solved.

**Comment by willemferguson** [comment]
I did a code review and could not find any glaringly obvious coding problem. With respect to git access, I had a problems the last 2 weeks or so that I got a segmentation fault when accessing a git dive log. So I cannot access git dive logs with my branch **salinity1**. But the latest version of master accesses my git dive log well: I have no problems at all in reading the correct salinity from my git dive log. 

I pushed a branch called **salinity2** onto my private github repo. This is a rebuild, on top of the latest master (474fc72e32f), of the edit-salinity code. Please try this and see if it solves your problem? Also, see if this solves the problem with the alignment of the groupbox-headings in the Information tab??

**Comment by dirkhh** [comment]
I need to get back to this one as well, but I also have more than a dozen other PRs pending, so I'll try to get through a bunch of those, first. But yes, this is still on my todo list.

**Comment by dirkhh** [comment]
closing this as I'm about to create a new PR that tries to put these changes on top of current master

**Pull request closed without merging**
