### PR TITLE
Header refactor

### PR DESCRIPTION
**Pull request by dirkhh**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Baby step to shrink dive.h
I'm interested to hear what others think would be good logical ways to break things up.
I'm not convinced that this really is a compile time advantage, though.

### Changes made:

1) moved a couple of math macros and string inline functions into a separate header
2) dropped dive.h from the source files that didn't need it any more

### Release note:

Doesn't seem worse a mention in the Release note

### Mentions:

It would be nice if a couple of people take a look - if you think this is going the wrong way about it, happy to hear other ideas how to approach this.
@atdotde @mturkia @sfuchs79 @bstoeger @neolit123

### CODE REVIEW

**Review by neolit123 — APPROVED** [review]
the change looks good. :+1:

**Comment by bstoeger** [comment]
Perhaps use the opportunity to un-inline `includes_string_caseinsensitive()`? Looks a bit voluminous for an inlined function.

PS: This functions seems to have only one caller - you might even move it to `core/git-access.c`

**Comment by dirkhh** [comment]
Good idea @bstoeger - I'll do that

**Comment by dirkhh** [comment]
Any more comments? Otherwise I'll just merge it

**Pull request merged**
