### PR TITLE
CICD: Update the android Build Docker Image.

### PR DESCRIPTION
**Pull request by mikeller**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [x] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Update the android build docker image:
- rebase on ubuntu 22.04;
- add tooling required to sign APKs;
- changes to make the container re-usable;
- change to a multi-stage build to keep the image size smaller;
- generic improvements to the Dockerfile

Also update the example script for how to use the container.

### Additional information:

Since there is no offline installer available for Qt 5.15, the new docker container re-uses the Qt install from the existing 'subsurface/android-build-container:5.15.1' image, by using it as the first stage of the multi-stage build. In order to avoid overwriting this source image the new image is named 'android-build'.

### CODE REVIEW

**Review by dirkhh — APPROVED** [review]
this looks very clever. well done.
I'll approve but not merge so you can do this according to your needs.

**Comment by mikeller** [comment]
@dirkhh: If you are ok with the proposed approach I'll do up the action that builds and publishes the docker image, and we can use this to publish the new 'production' image.

**Comment by dirkhh** [comment]
Yes, that sounds great

**Comment by mikeller** [comment]
@dirkhh: This is ready now - once the CICD on it has run it might be good to add a description to https://hub.docker.com/repository/docker/subsurface/android-build/general, and update https://hub.docker.com/repository/docker/subsurface/android-build-container/general to tell users to use https://hub.docker.com/repository/docker/subsurface/android-build/general instead.

**Comment by dirkhh** [comment]
I wonder if the CICD has the necessary credentials to push to docker... 
But yeah, let's merge this and improve from there...

**Comment by dirkhh** [comment]
That's what I was worried about. I created a new access token and re-ran the workflow. Fingers-crossed.

**Pull request merged**
