### PR TITLE
Manual entry for export anonymization

### PR DESCRIPTION
**Pull request by atdotde**
This should be accompanied by an updated screen shot. I am looking at @willemferguson.

Signed-off-by: Robert C. Helling <helling@atdotde.de>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [x] Documentation change
- [ ] Language translation

### CODE REVIEW

**Comment by willemferguson** [comment]
There is a bug. See the attached image. There is a "Metric" pseudo-button overlapping with the Anonomise option.
bug

**Comment by janmulder** [comment]
Fixed in #1691

**Comment by willemferguson** [comment]
Image attached.
export_f20

**Comment by janmulder** [comment]
@willemferguson: no, this image is not correct. The metric button is a valid button, so needs to stay. In my PR, I just fixed the positions so that they lineup correctly.

**Comment by dirkhh** [comment]
darn - should have paid attention and merged this one before updating the HTML in the repo. Oh well.

**Pull request merged**
