### PR TITLE
Remove gps

### PR DESCRIPTION
**Pull request by dirkhh**
### Describe the pull request:

- [x] Functional change

### Pull request long description:

this may be going a bit too far... the ApplyGpsFixes interface might be useful in the future - including the related command stuff. So let's not merge this too aggressively :)

### Changes made:

- remove the GPS service and current position UI components
- remove the GPS fix list and UI components
- remove the qmlmanager interfaces used to implement all this
- remove the command to apply GPS fixes
- remove the GpsLocation class
- remove the related preferences

### Related issues:

#3227

### Additional information:

- This is pretty drastic. 
- We still need to remove the location related permissions and all the other Android and iOS build cruft around that.
- The location menu now is silly - needs to just become a map action
- And of course eventually we need a different way to import GPS data

### Release note:

TBD

### Documentation change:

TBD - lots of things to delete

### Mentions:

@willemferguson

### CODE REVIEW

**Review by bstoeger — COMMENTED** [review]
I have never used the mobile version[*] nor am I involved with Google's or Apple's appstore process. Therefore, I cannot make an informed judgement. The code deletion looks reasonable to me, from what I can tell.

[*] nor do I plan to: I use my phone as a phone with Google maps and my tablet as a notepad with Google maps and always have my laptop with me for anything else.

**Comment by dirkhh** [comment]
If we import GPS info from another app... Won't we need the apply gps fix stuff?

I wasn't sure if this was removing too much

**Comment by bstoeger** [comment]
Yes, I reckon it depends on how you want to implement the alternative.

1) As an independent feature that imports multiple dive locations (like now). Then it would make sense to keep the undo-command.

2) As part of the edit-dive screen. Then probably the editDive undo-command should be adapted.

3) In a completely different way.

It's really impossible for me to judge without knowing your "vision". Since I only have a small dive log, I'm perfectly fine with fetching the GPS locations from various online databases / sources. And really, I don't care about precision down to the meter or so.

**Comment by dirkhh** [comment]
My "vision". That made me snort.
As if my "vision" mattered. What matters is what people are willing to implement. And we have heard from a few people about importing gpx files - so that seems likely to be similar to what we have today.
So I think I convinced myself to drop the last few commits that deal with that...

**Pull request merged**
