### PR TITLE
Add snap packaging

### PR DESCRIPTION
**Pull request by Saviq**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [x] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

This adds [`snap`](https://snapcraft.io/) packaging to subsurface.

### Changes made:

1) added `snap/snapcraft.yaml`

### Additional information:

See [this forum post](https://forum.snapcraft.io/t/call-for-testing-subsurface/5249) for more information on where to get the snap.
The placement of `snapcraft.yaml` in a top-level `snap` directory is required to use [build.snapcraft.io](https://build.snapcraft.io) for automated builds and releases from the Git repository.
I will transfer ownership of the `subsurface` name in the [snap store](https://snapcraft.io/store) so you can set the builds up.

### Release note:

Subsurface is now also available as a snap (https://snapcraft.io/subsurface).
> the link above will start working once the snap is released in the `stable` channel

### Documentation change:

A mention of the snap should be added to the website.

### CODE REVIEW

**Comment by mturkia** [comment]
Cloud sync is not working for me. I wonder if libgit2 is too old. For some reason:
built with Qt Version 5.5.1, runtime from Qt Version 5.5.1
built with libgit2 0.24.0

The INSTALL states that 0.23 should suffice, but I am not certain if this is still the case. Also I am wondering, why you build with 0.26 but stage with 0.24. (I have no clue about snaps, but I would assume that libgit2-26 for staging is what you want.)

I am not sure if the Qt version is recent enough for some of the features to work...

**Comment by Saviq** [comment]
@mturkia 0.24 is the [latest in available in xenial](https://launchpad.net/ubuntu/+source/libgit2), why do you say I build against 0.26? I can pull 0.26 in if that can help cloud syncing.

@dirkhh I want to update to 18.04-based snap when that's supported, that would [give us Qt 5.9.5](https://launchpad.net/ubuntu/+source/qtbase-opensource-src) but continue to run on all the distros that snaps are supported on today.

**Comment by dirkhh** [comment]
You should be able to build under 18.04 (I haven't tried). It's our packaging that fails for it because of the missing headers and the restrictions of what we can do at build time.

**Comment by Saviq** [comment]
What I meant is for snaps based on 18.04 to be supported (it's almost there).

**Comment by mturkia** [comment]
I was thinking that libgit2-dev is 0.26 as that is the version in my system. But if you are building in xenial, then my comment is obviously incorrect.

**Comment by dirkhh** [comment]
So this has been abandoned it seems. Closing it for now, feel free to re-open once the resulting snap works.

**Comment by Saviq** [comment]
Hi @dirkhh - not abandoned at all, just I'm on holidays atm, will report back when I return. Thank you!

**Comment by Saviq** [comment]
@dirkhh @mturkia new PR: https://github.com/Subsurface-divelog/subsurface/pull/1374 - I've verified cloud syncing as well as USB/serial connection to my HelO2.

**Pull request closed without merging**
