### PR TITLE
Dive pictures: connect DivePictureModel signals in constructor

### LINKED ISSUE #1441: Deletion of images in profile not working on Windows
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

While trying to test Bluetooth on Windows I found a usability bug: Deleting images does only work sporadically in the profile plot. I can only guess that this has something to do with case insensitive filenames? It's difficult for me to debug as I have no build environment on Windows.

### Subsurface version:

Windows 7 Enterprise
Version 6.1 (Build 7601: Service Pack 1)

### Steps to reproduce:

Click on trashcan symbol.
### Current behavior:

Nothing.
### Expected behavior:

Picture gets deleted.

### PR DESCRIPTION
**Pull request by bstoeger**
The DivePictureModel signals were connected int the setProfileState()
function of ProfileWidget2. If this function was called repeatedly
(e.g. after adding a dive), multiple connections were made, which led
to multiply delivered signals. This in turn led to confusion, when
deleting pictures (i.e. multiple pictures were deleted).

Instead, connect once in ProfileWidget2's constructor. It is unclear
whether these signals should be disconnected temporarily if no pictures
are shown. In any case, the weren't, so this shouldn't introduce any
regression.

Fixes #1441

Signed-off-by: Berthold Stoeger <bstoeger@mail.tuwien.ac.at>

### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

This is an old problem, which was turned into an actual bug by my recent changes to `DivePictureModel`. I'm not sure, if the original code was intended that way. I.e. if the signals should be removed under certain conditions. I will make further experiments.

There is an unrelated bug which I introduced recently. Fix forthcoming.
### Changes made:

1) Move `connect()` calls.

### Related issues:

Fixes #1441 

### Release note:

Not needed - user visible bug introduced after last release.

### Documentation change:

Not needed.
### Mentions:

@tcanabrava: Please check, if this makes sense. I'm quite sure that at least it doesn't worsen things.

### CODE REVIEW

**Comment by dirkhh** [comment]
This also looks like it is intended for 4.8.0, correct?

**Comment by bstoeger** [comment]
This fixes a 4.8.0 showstopper (even more so than #1444), but pre-commit comment by @tcanabrava (and others) would be very welcome.

**Comment by dirkhh** [comment]
OK, I'll wait for @tcanabrava to take a look

**Comment by dirkhh** [comment]
THANKS, @tcanabrava

**Pull request merged**
