### PR TITLE
Fix loading bailout events

### LINKED ISSUE #2613: Divemode changes become bookmarks after saving and reopening
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

I manually added a bailout event to my last dive in subsurface. The icon on the profile is the little curved arrow with a line through it.

I saved, closed and reopened subsurface the icon for the bailout had disappeared and was replaced with a dive flag ('normal' bookmark with a note of 'OC @26:20')

This also applies if I switch to pSCR mode and then back to CCR mode.

### Operating system:

Windows 10, english uk

Shearwater petrel 2 (hardwired), firmware version 71

### Subsurface version:
subsurface  4.9.3
 Does the same happen on another Subsurface version? don't know 
 official release

### Steps to reproduce:
- Diving on CCR (Shearwater) in CCR mode
- During the dive I bailout and switch to BO mode on my computer.

1. When I import the dive into subsurface, I don't see the bailout event.
2. When I manually add a change divemode event (bailout to OC, back on CCR ) the event appears and looks fine and shows the OC divemode (bailout) icon. The Surface GF at end of the dive reflects the bailout accurately.
3. I save and quit.
4. When I open subsurface and look at the dive, I see a 'dive flag' bookmark in the profile, but no bailout icon. Further, the surface GF is calculated as if I had stayed on CCR through the whole dive
5. I remove the event (the note says 'OC @ [time]')
6. Repeat steps 2,3,4 - same result.

### Current behavior:
see description

### Expected behavior:
divemode change event persists as  between saves and affects tissue calculation (surface GF etc.)

### PR DESCRIPTION
**Pull request by atdotde**
The parsing of events mistakes the new divemode name
as the event name. Let's use the fact that dive modes
have distinct names from other events and simply
fix those events whose name matches a divemode.

Signed-off-by: Robert C. Helling <helling@atdotde.de>

### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

This is a bit of a hack since it relies on the "only one string per line" feature of git loading. But it is simple. If a dive mode name ends up as an event name, make that a mode change event and fix the value.

### Related issues:

Fixes #2613

### CODE REVIEW

**Comment by dirkhh** [comment]
Would you agree that it makes sense to use #2621 instead?
Also, would you review that one, please?

**Comment by atdotde** [comment]
Yes, #2621 attacks the problem at a more fundamental level. But this here might be "good enough".

**Comment by dirkhh** [comment]
You are correct that #2621 is more complex - but it also fixes a bigger problem and increases the likelihood that the next time we add things to the format we don't re-break things (knock wood).

My preference would be to go with that, TBH.

**Comment by atdotde** [comment]
Fine with me

**Pull request closed without merging**
