### PR TITLE
Tell mention-bot to mention @atdotde if planner/deco files touched

### PR DESCRIPTION
**Pull request by atdotde**
Signed-off-by: Robert C. Helling <helling@atdotde.de>

### CODE REVIEW

**Comment by glance-** [comment]
@mention-bot didn't like this config file: https://github.com/Subsurface-divelog/subsurface/pull/328#issuecomment-295866222

**Comment by glance-** [comment]
The whole content should probably be wrapped with {} , as a object .

**Comment by atdotde** [comment]
My impression is the @dirkhh already fixed this in 76975ed425e4772a55f3e2f19c8ab5a71c3ab742 .

**Comment by glance-** [comment]
Yepp.

**Pull request merged**
