### PR TITLE
Remove Facebook support

### PR DESCRIPTION
**Pull request by neolit123**
### Describe the pull request:

- [ ] Bug fix
- [x] Functional change
- [ ] New feature
- [x] Code cleanup
- [x] Build system change
- [x] Documentation change
- [ ] Language translation

### Pull request long description:

facebook: remove the feature from the code base

Remove from:
- unit tests
- desktop widgets
- preferences
- core intergration
- cmakefiles
- build scripts
- icons
- docs

Also remove the plugins and social network integration.

### Changes made:

see above.

### Related issues:

none for the removal

### Additional information:

- i will also close all existing open facebook issues in the tracker **(edit: done)**

### Release note:

added

### Documentation change:

- remove the facebook section from all the multi-language docs (TXT source),
- remove the images too.

### Mentions:

@dirkhh @willemferguson

### CODE REVIEW

**Comment by neolit123** [comment]
@willemferguson could you please check if i haven't broken the docs in any way?

you can pull this as a patch like so:
```
wget https://github.com/Subsurface-divelog/subsurface/pull/1958.diff
git apply 1958.diff
```

**Comment by dirkhh** [comment]
Interesting that all non Windows/Android builds failed. And equally interesting, I guess, that those completed, given that type of errors that I see in the other builds.
@neolit123 are you still working on this, or do you want me to fix the build errors so this can be merged?

**Comment by neolit123** [comment]
looks like the tests are failing at:
```
CMake Error at tests/CMakeLists.txt:44 (add_executable):
```

i will fix that and watch the build again.

**Comment by neolit123** [comment]
@dirkhh 
i have removed the WIP.

all tests pass except the Xcode ones with:
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```
possibly a temporary issue.

**Comment by dirkhh** [comment]
the iOS failure is that there's still a reference to the FB preferences in the qmake file:
```
packaging/ios/Subsurface-mobile.pro:    ../../core/settings/qPrefFacebook.cpp \
packaging/ios/Subsurface-mobile.pro:    ../../core/settings/qPrefFacebook.h \
```

And a quick `git grep -i facebook` shows a ton of hits in `.pot` files and translations (those are all fine), but it also shows me that we still refer to this in the FAQ (I'll fix that myself) and in a few other places in the code...

**Comment by dirkhh** [comment]
I also think that `core/isocialnetworkintegration.*` and references to it should be removed while we do this, right?

**Comment by dirkhh** [comment]
I'm pretty sure the same is true for `core/pluginmanager.*`

**Comment by neolit123** [comment]
> the iOS failure is that there's still a reference to the FB preferences in the qmake file:

ack.

> I also think that core/isocialnetworkintegration.* and references to it should be removed while we do 
this, right?

i left those and the plugin manager intentionally.
LMK if you want them removed.

**Comment by dirkhh** [comment]
Since this all came in when the FB support was added, it seems the right time to also remove them.

**Comment by neolit123** [comment]
all tests have passed.

**Review by dirkhh — APPROVED** [review]
This looks good. Thanks for taking care of that, Lubomir.

**Pull request merged**
