### PR TITLE
Updates for Android building with  Qt 5.12

### PR DESCRIPTION
**Pull request by dirkhh**
### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [x] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Lots of work to get Android to build with clang and latest NDK/SDK and Qt 5.12
In the process Arm64 builds were enabled, but the resulting binary still crashes when using Bluetooth

### Changes made:

1) switch to newer Android platform (which means this won't work on some of the oldest Android versions - we now require at least Android 5.0
2) switch to clang and work around numerous issues with that
3) add ability to build against arm64_v8a
4) hack around a build failure by patching NDK
5) introduce a Docker based build for Travis that makes it easier to reproduce the same builds locally and on Travis (and makes it easier to get all the required tools installed on Travis)
6) upgrade the cmake version in that Docker container to the latest to work around an odd build bug

### Release note:

Strangely, this doesn't seem to really need release notes... no one cares if this is 5.11 or 5.12

### Mentions:

@janmulder  thanks for all the work - is this ready to merge? armv7 works as before, I think...

### CODE REVIEW

**Comment by janmulder** [comment]
Yes, ready to merge (that Travis failure is a failing test, but still I restarted it).

**Comment by janmulder** [comment]
And it's a pity that the arm64 version is crashing on Bluetooth, as a small test on 2 identical phones, one with arm and one with arm64 shows a nice improvement in startup time. To read my 1060 dive logbook from the local cache on startup: 4.6 sec on arm64, 6.4 sec on arm. And obviously, we are talking debug builds here.

**Comment by dirkhh** [comment]
The push  completed Travis. Any concerns merging this, @janmulder ?

**Comment by dirkhh** [comment]
oops, my screen hadn't refreshed. Thanks. Merging

**Pull request merged**
