### PR TITLE
CHANGELOG: update with end-user relevant PR`s

### PR DESCRIPTION
**Pull request by janiversen**
Signed-off-by: Jan Iversen <jani@apache.org>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [x ] Documentation change
- [ ] Language translation

### Pull request long description:

Based on the dialog in #1388 I submit the end-user relevant PR I have made.

@dirkhh feel free to reduce/reword etc as you find needed.

### CODE REVIEW

**Comment by dirkhh** [comment]
That first line I don't understand:
> Mobile: Log is copied to clipboard (see about) to be pased in problem reports

Should this be something like

Mobile: Add button to About page to copy logs to clipboard; this makes it easier to provide the required information when reporting issues

**Comment by janiversen** [comment]
Sounds more english :-) I will correct it tomorrow

**Comment by janiversen** [comment]
changed

**Comment by dirkhh** [comment]
Well, sort of :-)
I obviously could just fix the missing '- ' -- or I can make you redo it. Decisions, decisions...
OK, I'll just take care of it myself

**Pull request closed without merging**
