### PR TITLE
Planner: Unify final ascent rates in plan() and fake_dc()

### PR DESCRIPTION
**Pull request by bstoeger**
When generating fake profiles for manually entered dives, fake_dc() and
plan() used different final ascent rates of 5 m/min and 4.5 m/min,
respectively. This led to dives that were 6 seconds longer than entered
by the user and to confusion. See #554.

Therefore, use the same ascent rate taken from the preferences field
flag.ascratelast6m in both cases.

Signed-off-by: Berthold Stoeger <bstoeger@mail.tuwien.ac.at>

### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

This (partially?) fixes the long-standing bug #554.
### Related issues:

#554 #1211

### CODE REVIEW

**Review by atdotde — COMMENTED** [review]
I totally agree that these should be unified. But 5m/min sounds like a strange value to me. Is there anybody diving like this? 6m/min is 1m/10s which is much easier to hold looking at the computer.

**Comment by bstoeger** [comment]
The whole logic seems broken to me. Depending on the value we set here, manually entered dives will change their duration. That seems unhealthy. Is the last sample not saved to disk or is it ignored?

**Comment by bstoeger** [comment]
What about using `prefs.ascratelast6m`?

**Comment by atdotde** [comment]
Let's use the pref.

**Comment by bstoeger** [comment]
Using preferences now - tested with a few dive durations, always got the same value out that I put in. Of course, already saved dives stay 6-seconds longer.

**Review by atdotde — APPROVED** [review]
LGTM

**Pull request merged**
