### PR TITLE
[DO NOT MERGE] Android build Qt5.12 beta 4, clang, arm64 architecture, NDK 18b

### PR DESCRIPTION
**Pull request by janmulder**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [x] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:
The first steps to build Subsurface-mobile using a much newer toolchain than we currently do for production. Read the individual commits. As Qt 5.12 is not released at point, anyone that wants to try this PR, needs to install this by hand. The wrapper script is **not** yet adapted, and the android build script does not check for Qt versions used etc.

There is 1 crash known in the arm64 build. See mailing list for more discussion on this. 

### Changes made:
See commits

### Related issues:
Well, as NDK is moving away from gcc in favor of clang, and Android will be requiring arm64 builds for all apps in the Play Store mid 2019, this will be a more or less forced change.

### Mentions:
Anyone that is brave enough to cross build for Android.

### CODE REVIEW

**Comment by dirkhh** [comment]
with 5.12 out and released we should revisit this...

**Comment by janmulder** [comment]
Agree. I think the first step is now to get things running on Travis. For that, the Qt  `android_armv7` and now also the `android_arm64_v8a` trees have to be put on `https://storage.googleapis.com/travis-cache` so that we can work on the wrapper script. Is that something you maintain?

**Comment by dirkhh** [comment]
yup it is. But I'm thinking that what I did with windows container build is actually MORE clever and I'm planning to slowly move everything in that direction. The logic there is that anyone can just run that container locally and deal with breakage.
(AND I don't need to pay for storage/bandwidth like I do on Google - not that the ~$3 a month are killing me or anything)

**Comment by dirkhh** [comment]
I have some time for cleanup work on Subsurface the next ten days. I'll add this to my list :-)

**Comment by janmulder** [comment]
In the meantime, I'm trying to get BT on Qt 5.12 working again (for Linux Desktop), but progress is slow. I'm getting to the point that I have to compile Qt from source to make more sense of the failures I'm seeing. I've a hard time believing that Qt shipped a 5.12 without working Bluetooth classic for one of the supported platforms ...

**Comment by dirkhh** [comment]
Have you asked @ablasche for help? He tends to be the best go-to person when it comes to BT and Qt

**Comment by janmulder** [comment]
No, not yet. Feels a little early.

**Comment by dirkhh** [comment]
CRUD. Upgrading Arch Linux got me Qt 5.12 and now I can't test what I'm working on with subsurface-mobile on desktop because... no BT :-(

**Comment by janmulder** [comment]
Yes, see also issue #1891.

**Pull request closed without merging**
