### PR TITLE
Filter: Update #1953: use combo-boxes

### PR DESCRIPTION
**Pull request by bstoeger**
### Describe the pull request:

- [ ] Bug fix
- [x] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

See #1953; replace button by combo-boxes.

### Changes made:

See #1953 

@dirkhh

### CODE REVIEW

**Comment by dirkhh** [comment]
Something odd happening with the commits there... looks like you just amended my commit and didn't change the author :-)
I'll try it in a minute.

**Comment by dirkhh** [comment]
The UI isn't ideal, but it has its advantages. It's visually clear that you can change the negation, it would indeed be easy to add "Any of". Etc. I won't claim that I love it, but I think it's a step in a good direction.
Would you like me to fix the authorship problem with that last commit and maybe clean up the spacing a tiny bit?

**Comment by dirkhh** [comment]
BTW... the way you laid out that grid for this UI is... interesting :-)
I actually added some markers to the code to try to make sense of it... there appear to be unused columns (I can't find anything at column 1 or 5) :-)
Not a big problem, I'll fix that once we agree on the rest of the UI.

**Comment by bstoeger** [comment]
> Would you like me to fix the authorship problem with that last commit and maybe clean up the spacing a tiny bit?

If you would do that - yes, please.

> BTW... the way you laid out that grid for this UI is... interesting :-)

It's tool generated with "Qt Creator". I get a headache from that XML-format.

**Comment by dirkhh** [comment]
I love having a GUI tool to build the UI. I hate the XML it products... And I usually end up hand editing it when I try to fix things. 🙄

I'll work on this in a few minutes

**Comment by dirkhh** [comment]
ok, pushed my cleanup back to my own branch (I know I can overwrite your, it just feels... wrong).
So back to #1953

**Pull request closed without merging**
