### PR TITLE
When finding deepest ceiling, do not round to multiples of 3m

### LINKED ISSUE #630: Deco ceiling calculation for EAN32 dive with 3m steps on/off - very strange results
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

Strange effect once again with deco ceiling calculation. This time visible outside the planner.
Example dive attached. If you for this example dive with EAN32 as bottom gas switch on/off 3m steps for deco ceiling calculation the overall ceiling result changes. This should not be the case because the 3m steps should only round up every ceiling to next 3m stop.
This issue is gone as soon as you change the bottom gas for the dive to s.th. other than EAN31-32.

Maybe linked to #601 

### Operating system:

Windows 10

### Subsurface version:

Latest master

### Additional information:

[EAN32_dive_deco_ceiling.zip](https://github.com/Subsurface-divelog/subsurface/files/1353675/EAN32_dive_deco_ceiling.zip)

### PR DESCRIPTION
**Pull request by atdotde**
Fixes #630

Signed-off-by: Robert C. Helling <helling@atdotde.de>

### Describe the pull request:

- [x ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Documentation change
- [ ] Language translation

### CODE REVIEW

**Comment by dirkhh** [comment]
That CI failure... could be something brought in by the latest Kirigami. I'll take a look

**Comment by dirkhh** [comment]
CI is fixed - who should review this? Or is there a test case?

**Comment by atdotde** [comment]
There is a discussion over at #630.

**Comment by neolit123** [comment]
lgtm

**Pull request merged**
