### PR TITLE
mobile: fix wrong coords when saving new location

### PR DESCRIPTION
**Pull request by mfbernardes**
This one place it was not being multiplied by 1000000,
as expected for degrees_t.

Signed-off-by: Murillo Bernardes <mfbernardes@gmail.com>

### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

As simple as the commit msg.

So what was supposed to be 48°45'N 8°56'E ended up as something like 0°00'00.162"N 0°00'00.083"W

### CODE REVIEW

**Comment by neolit123** [comment]
thanks for the fix - LGTM.
waiting on CI to finish.

**Comment by mfbernardes** [comment]
and then android build times out downloading qt :(

**Comment by neolit123** [comment]
@mfbernardes restarting the Android build.
our CI is pretty solid, i have to say.

the CI of some other, bigger projects fails like 9/10 times.

**Comment by dirkhh** [comment]
This qualifies for the OOPS award.
Thanks for the fix!

**Pull request merged**
