### PR TITLE
macOS: build against Qt 5.15.16

### PR DESCRIPTION
**Pull request by dirkhh**
With this we should be able to switch to a newer mac build VM.

### Describe the pull request:

- [x] Build system change

### CODE REVIEW

**Comment by dirkhh** [comment]
Ahh - looks like QtLinquist is missing from my Qt 5.15.16 build.
So I'll need to update that, again.

**Comment by dirkhh** [comment]
Woot - macOS builds -- I tested things and the binary seems to work. Since this seems like such a clear step forward (and obviously cannot impact anything else - see the diff) I'll merge this myself :)

**Comment by mikeller** [comment]
Thanks @dirkhh. 
The solution looks nice and clean.

**Comment by mikeller** [comment]
Oh wait - only now did I realise that you had to build and push Qt 5.15.16 into our `qt-mac` repository.
As a thought, when we are upgrading Qt for Mac / iOS, should we delete the old version? (Or delete the -2 version, or delete with a grace period, so that work in progress that is building againt a previous version isn't broken)?
The speedup for our CICD runs will likely be minimal, but in terms of GitHub resources it seems to be the right thing to do.

**Comment by dirkhh** [comment]
Yes, we should delete both of the old ones and force push to actually remove them from the repo as well. 
Since builds against the old one will fail, that seems fine. 

Otherwise (without the hard break thanks to GitHub) the "keep the last two" approach is of course better

**Pull request merged**
