### PR TITLE
mobile-widget/qml: correct syntax error in main.qml introduced in e63257f0e

### PR DESCRIPTION
**Pull request by janiversen**
default parameter values is not supported as this syntax was introduced
in ECMA-262 6th edition while QML only implements the fifth edition
(as of Qt 5.11).

remove default parameter and check for undefined instead.

Signed-off-by: Jan Iversen <jan@casacondor.com>

### Describe the pull request:

- [x ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### CODE REVIEW

**Review by dirkhh — APPROVED** [review]
I'm puzzled why this worked in my testing, then.
But hey, yeah, this of course is equivalent

**Comment by dirkhh** [comment]
What the actual heck.
I approved your PR. I'm waiting for the tests to complete before merging because that's the sane thing to do. And you close the PR and delete the branch.

Jan, you have serious issues. Please get help.

**Comment by janiversen** [comment]
Actually I did not delete anything, but I am updating Xcode, and all my git stuff went wild.

I will submit again, when Xcode is reinstalled.

**Comment by dirkhh** [comment]
This is what GitHub shows me. That you closed the PR and deleted the branch. That's what I responded to. If that's not what you did, then my apologies. To avoid treating you unfairly, I have deleted the comment.

Screen Shot 2019-11-11 at 11 14 42 AM

**Comment by janiversen** [comment]
branch is back, sorry for the inconvenience.

**Comment by janiversen** [comment]
ps. do not work with git while updating Xcode 👎

**Comment by janiversen** [comment]
Not sure if the correct thing is to reopen the pull request...but I assume it cannot hurt.

**Comment by dirkhh** [comment]
Simply for workflow reasons I usually let the Actions run through - because if I merge while the actions are running sometimes (but not always) the action is then reported as having failed... which results in a confusing email to the maintainers. So I'll get back to this PR when I have a break again this afternoon and merge once the CICD runs have completed.

**Pull request merged**
