### PR TITLE
Planner: Add option to treat O2 as narcotic

### PR DESCRIPTION
**Pull request by atdotde**
When computing the best mix for a target depth, for helium, one
can either require that the partial pressure of N2 is the same
as at the target depth or the partial pressure of N2 plus O2.

Signed-off-by: Robert C. Helling <helling@atdotde.de>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [x] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Related issues:

Fixes #23254

### Documentation change:

This adds a new checkbox to the planner that needs to mentioned in the user manual.

### CODE REVIEW

**Comment by atdotde** [comment]
Now with CHANGELOG and user manual entry.

**Review by dirkhh — APPROVED** [review]
Overall this looks reasonable. Did I misunderstand you regarding "edit user manual"?

**Comment by glance-** [comment]
For maximum feature creep, might one request the ability to set a maximum equivalent air density depth?

**Comment by atdotde** [comment]
I added text to the user manual explaining this feature. Since it changed the UI we might need a new screen shot.

**Pull request merged**
