### PR TITLE
Add preferences for unit selection on mobile.

### LINKED ISSUE #1591: Add unit selection preference to mobile app
### Describe the issue:
- [ ] Bug
- [ ] Change request
- [ x ] New feature request
- [ ] Discussion request

### Issue long description:
For reasons surpassing my personal understanding, my partner prefers Imperial units. And yet, the dive detail views in the mobile app only show the dive information in metric. Now, clearly metric is superior in virtually every way, but yet still I'd like to help those who have not yet transitioned their thinking.

### Operating system:
Android

### Subsurface version:
2.1.0(4.8.0.0)

### Steps to reproduce:
Open a dive in the mobile app
Try to see units in Imperial.

### Current behavior:
Only gloriously understandable metric units

### Expected behavior:
Confusing and nonsensical imperial units are displayed instead.

### Additional information:
I started digging through the code, but I'll have to admit I have some things to learn about QML+Android and could use some structural pointers.

### PR DESCRIPTION
**Pull request by jbygdell**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [X] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

This is the first part of a planned addition of  settings to Subsurface-mobile.
This on enables the user to change the unit system used, independently of 
what is set by system locale.

### Changes made:

1) Added unit selection to settings page
2) Fix various issues related to preference choice vs. locale when
starting the app.

### Related issues:

Fixes #1591

### CODE REVIEW

**Comment by dirkhh** [comment]
I created the 2.1.2 release builds for Android and iOS today - sent them both out to testers for a quick smoke test and then plan to publish in a few hours. So this is exactly the right timing for new features...

**Comment by dirkhh** [comment]
The code seems to make sense. Some of the commit messages might benefit from editing.
Would you like me to try and clean them up as I merge this, @jbygdell

**Comment by jbygdell** [comment]
@dirkhh go ahead.

**Comment by dirkhh** [comment]
Sorry to be so slow here - battling other bugs and re-submitting apps.
This is currently not quite as functional as I would like it.
It doesn't **really** take effect until the next restart of the app. For example, the dive list and the last few dives that you looked at will stay in the previous unit system... I wonder if we could force the app to evict all pages so they indeed get recreated (and not just reused).
This is close, though.
I'll merge my edited version from my laptop.

**Pull request closed without merging**
