### PR TITLE
Mobile: location autocomplete

### LINKED ISSUE #546: [idea] Mobile - Location Selection
I'd love to see the location on the mobile app allow you to reuse your saved locations like the desktop app does.   Currently the process for me when downloading dives from the mobile app is to sync to the cloud and modify on the desktop later.   Not the most inconvenient but would definitely add polish to the app.

### PR DESCRIPTION
**Pull request by janmulder**
### Describe the pull request:

- [ ] Bug fix
- [x] Functional change
- [x] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:
Add the capability to select the location name from a list, constructed from the known dive sites in the logbook. As now the location is possibly known, we need to populate the GPS coordinate of the entered dive location as well. When the user enters a new site name (ie. currently unknown), the GPS coordinate stays empty.

### Changes made:
See individual commits

### Related issues:
Fixes: #546

### Additional information:
While relatively simple, please review and test. I will be afk the coming days and after that 2 weeks with limited internet presence. But this is very nice functionality to test on a dive trip :-)

### Release note:
Yes, will push a line for the Release notes.

### CODE REVIEW

**Comment by dirkhh** [comment]
Yay. That looks promising. I'll wait for the CI to build an Android APK for me (getting lazy).
Have fun diving. We'll miss your contributions. I will admit that one of the best things that happened in the past year is that you and some others have **really** stepped up and as a consequence I feel a lot less overwhelmed with the backlog of things that I feel I need to look at.
Thank you for that.
(hey, it's Thanksgiving in the US... I'm feeling thankful)

**Review by dirkhh — CHANGES_REQUESTED** [review]
Finally finished my testing, making sure that the crashes that I was seeing weren't weird side effects or unrelated to this, but I now have done A/B testing on the same device, same data file, where without this patch Subsurface works just fine, with this patch when I tap on a dive to see dive details Subsurface crashes.

**Comment by janmulder** [comment]
Hmm, do you know where it crashes? Could not reproduce upto now.

**Comment by dirkhh** [comment]
Yesterday being a holiday I didn't spend much time on this.
For me it crashes the moment I tap on a dive to go to DiveDetailsView
Every single time.
But I don't think I've ever managed to get a debugger running and connect to the device so I could get a stack trace or something.

**Comment by dirkhh** [comment]
So this patch prevents the crash for me:
```
commit 1aa11efcea7c6d09d813b38a7df7ef0d3f1eb4c5 (HEAD -> master)
Author: Dirk Hohndel <dirk@hohndel.org>
Date:   Fri Nov 24 19:10:59 2017 -0800

    Fix crash when dives have no dive site
    
    get_dive_site_by_uuid() returns a NULL pointer in that case.
    
    Signed-off-by: Dirk Hohndel <dirk@hohndel.org>

diff --git a/core/subsurface-qt/DiveObjectHelper.cpp b/core/subsurface-qt/DiveObjectHelper.cpp
index 7a376740946f..8ea8b6370c2e 100644
--- a/core/subsurface-qt/DiveObjectHelper.cpp
+++ b/core/subsurface-qt/DiveObjectHelper.cpp
@@ -433,10 +433,11 @@ QStringList DiveObjectHelper::locationList() const
        struct dive_site *ds;
        int i = 0;
        for_each_dive (i, d) {
-               ds = get_dive_site_by_uuid(d->dive_site_uuid);
-               QString temp = ds->name;
-               if (!temp.isEmpty())
-                       locations << temp;
+               if ((ds = get_dive_site_by_uuid(d->dive_site_uuid)) != NULL) {
+                       QString temp = ds->name;
+                       if (!temp.isEmpty())
+                               locations << temp;
+               }
        }
        locations.removeDuplicates();
        locations.sort();
```
But even with this I don't get a dropdown as I expected but a slightly odd to navigate interaction with "markers" around the autocompleted parts of the dive site name...

**Comment by janmulder** [comment]
My internet here is pure crap, and struggling with something very weird. I suddenly get autogroup activated in the mobile version on import. And that is not activated in the desktop (and has never been, exept for some try out to see how it works) ... fully unsure this has any relation. I know that there are some issues on autogroup, but am not aware that any recent work is done on it.

That the "markers and no dropdown". Yes, is how all autocomplete field are currently working (I believe). Like suit, buddy, etc. And agree some kind of dropdown would be much nicer.

**Comment by janmulder** [comment]
And that patch looks sane to me.

**Comment by dirkhh** [comment]
autogroup should be completely unrelated. Should be triggered by autogroup being set in your git repo. Can you check if that's the case for some reason? That will tell us whether we need to look for a bug in it getting set on desktop or for a bug in it being used to init the setting on mobile...

**Comment by janmulder** [comment]
Ok, off topic here... But no sign of autogroup in the cloud config data...

**Comment by dirkhh** [comment]
I figured it out. Someone should beat me with a stick I'm such an idiot sometimes...

**Comment by dirkhh** [comment]
going back to the autocomplete... I swear we used to have drop-downs. I am clearly going insane here...
Given that I never edit anything on Subsurface-mobile, I have completely missed when we lost them.
So with that, I think this one is good to go :-/

**Review by dirkhh — APPROVED** [review]

**Comment by janmulder** [comment]
We use our home grown: HintsTextEdit.qml ... With indeed a fix from Marco from Combobox to TextEdit with hints. Sure there was a reason for this.

**Comment by dirkhh** [comment]
And I have no recollection what it was. I MUCH prefer comboboxes (as you can see from the download dialog)

**Comment by janmulder** [comment]
Agree, something on the growing to-do-list.

**Pull request merged**
