### PR TITLE
Correct, cleanup, translate and unify file filters

### PR DESCRIPTION
**Pull request by sfuchs79**
### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Started to correct many of the file filters all over the tool because there are a few real mistakes there today.

There are a few questions open before I can finalize this:
- Shall I change it even further and avoid to give any real filters stuff part of the strings like "(*.xyz *.XYZ)" to translation via Transifex? We know that with such stuff mistakes can happen easily. Or is there any need to translate these filters?
- Up to now we had "Subsurface files", "Log files", "Firmware files" and e.g. "Datatrak/Wlog files" but many others like "Cochran", "Divesoft",... Do we want to have the "files" suffix text everywhere or not?
- If I want to translate the name of the filter like "Subsurface files" or "OSTCtools files" shall I give the full name to Transifex or just the string "files"?

Yeah, boring stuff but also important to make the tool look very, very professional ;-)

### CODE REVIEW

**Comment by mturkia** [comment]
No need to translate the file suffix. Software name I am not sure of, but it should not ve a big problem to include it. Might be useful in cyrillic or other ”weird” letters...

**Comment by dirkhh** [comment]
This looks nice. I wonder about @mturkia 's comment... should the suffixes be excluded from the translated strings? I'm rather certain that they are unchanged across all languages. But I don't know which way gives us the lower risk of things going wrong here...

**Comment by neolit123** [comment]
@sfuchs79 

> Shall I change it even further and avoid to give any real filters stuff part of the strings like "(*.xyz *.XYZ)" to translation via Transifex? We know that with such stuff mistakes can happen easily. Or is there any need to translate these filters?

the Qt docs suggest that we should translate the whole filter string, but in reality we don't have to.
ideally it should look something like this to avoid any translation errors:
```
QString("HTML ") + tr("files") + QString(" (*.html)"));`
```
note the spaces after `HTML` and before `(*.html)...`

**BTW, we need to remove** all uppercase upper case extensions everywhere.
these are not needed. the Qt filter handles that for you on case-sensitive FSes like on Linux (i've just tried it!) and on Windows it doesn't matter. so, all filter extensions should be lowercase only and you don't need to handle special cases like "XYZ", "Xyz", "xyZ", etc...only "xyz".

> Up to now we had "Subsurface files", "Log files", "Firmware files" and e.g. "Datatrak/Wlog files" but many others like "Cochran", "Divesoft",... Do we want to have the "files" suffix text everywhere or not?

i would say, the changes you've made to "files" are mostly fine. there are extensions following something like `Divesoft` so it's clear that these are files.

as a rule of thumb, only add "files" at the start of a list of extensions for this dialog.
i can place inline reviews after you amend your changes.

> If I want to translate the name of the filter like "Subsurface files" or "OSTCtools files" shall I give the full name to Transifex or just the string "files"?

comments in the first quotation.

this is optimal for us and will avoid translating things like `Liquivision`, `Suunto` and `XML` - nobody would translate these, as these are **abbreviations or brand names!**
```
QString("HTML ") + tr("files") + QString(" (*.html)"));`
```
note that this deliberately avoids using `QString::arg()` with `%1`.

**Comment by sfuchs79** [comment]
Ok, thanks for the feedback.

I think we collected a few clear decisions and very useful information:
- Don't include this real filter part like "(*.html)" into the translations
- Remove all this upper case extensions - great, makes life easier!!!

For one other item I'm still not sure - please someone should make a decision :-)
- Translate tool/file type names: "Brand names" argument vs. "Cyrillic/other ”weird” letters" argument!

**Comment by neolit123** [comment]
i would say, do not translate brand names.
can you provide examples of "weird" Cyrillic letters and such?

**Comment by sfuchs79** [comment]
Please don't ask me about the Cyrillic letters but ask @mturkia ;-)
Beside the jokes:
I don't know exactly but I think it's possible that for some languages the translator(s) really want to translate also brand names especially if the language is using different letters. Russian, Chinese,...!?

**Comment by neolit123** [comment]
ok, my vote then becomes - let's translate everything but the extensions.
if you don't get any more feedback from others, just go for it.

**Comment by sfuchs79** [comment]
@neolit123 
The file filter PR is ready for review! :-)

**Review by neolit123 — COMMENTED** [review]
LGTM

let's wait for the CI and hope that tr() won't break this way.
comments by others @mturkia @dirkhh ?

**Review by neolit123 — APPROVED** [review]

**Comment by neolit123** [comment]
merging this.

**Pull request merged**
