### PR TITLE
Add a messageHandler to take care of qDebug & friends on QML

### PR DESCRIPTION
**Pull request by tcanabrava**
all qDebug / qCDebug and friends now will be properly
logged into developer -> log, on QML.

Signed-off-by: Tomaz Canabrava <tcanabrava@kde.org>

### CODE REVIEW

**Comment by janmulder** [comment]
Maybe I do not fully understand the functionality, but I tried this PR and it surprises me that the console debug print (adding ... to the model) contains far more lines that the data in the mobile app (mobile-on-desktop).

Further, tried it on Android phone as well. Almost no logging any more in the logcat, and it seems that the data in the mobile app is also not complete (as in mobile-on-desktop).

**Comment by tcanabrava** [comment]
On Tue, Jun 6, 2017 at 3:58 PM, janmulder <notifications@github.com> wrote:

> Maybe I do not fully understand the functionality, but I tried this PR and
> it surprises me that the console debug print (adding ... to the model)
> contains far more lines that the data in the mobile app (mobile-on-desktop).
>

Not to be surprised, the data() function is called whenever Qt thinks it
should display data, so any refresh on the screen will print it.


> Further, tried it on Android phone as well. Almost no logging any more in
> the logcat, and it seems that the data in the mobile app is also not
> complete (as in mobile-on-desktop).
>

it's not complete (because I didn't ported the old style of logging on
mobile to the new style).
as soon everything is ported, I would assume that we would lose the logcat
debugs (because the output is being redirected to the mobile ui). I could
try to add it in both directions (ui and logcat).

tougths?

Tomaz

**Comment by mturkia** [comment]
> On 7 Jun 2017, at 16.54, Tomaz Canabrava <notifications@github.com> wrote:
> 
> On Tue, Jun 6, 2017 at 3:58 PM, janmulder <notifications@github.com> wrote:
> 
> > Maybe I do not fully understand the functionality, but I tried this PR and
> > it surprises me that the console debug print (adding ... to the model)
> > contains far more lines that the data in the mobile app (mobile-on-desktop).
> >
> 
> Not to be surprised, the data() function is called whenever Qt thinks it
> should display data, so any refresh on the screen will print it.
> 
> 
> > Further, tried it on Android phone as well. Almost no logging any more in
> > the logcat, and it seems that the data in the mobile app is also not
> > complete (as in mobile-on-desktop).
> >
> 
> it's not complete (because I didn't ported the old style of logging on
> mobile to the new style).
> as soon everything is ported, I would assume that we would lose the logcat
> debugs (because the output is being redirected to the mobile ui). I could
> try to add it in both directions (ui and logcat).
> 
> tougths?

I would think that logcat is very useful for devs. It allows grepping and copy-pasting instead of screenshots from the device. Even in "realtime".

If the app log is long, there should be an easy way for normal users to send it either as long screenshot or preferably as text... And it might be good to have the app log in two modes/displays, compact and verbose. Easier to spot stuff if it is not in a cluttered log.

miika

**Comment by janmulder** [comment]
Agree with Miika on the logcat. Essential for on-device work. Maybe hidden behind a compile time option, to avoid cluttering the logcat on production versions.

**Comment by janmulder** [comment]
And @tcanabrava. I assume that you are aware that @dirkhh started a branch forTomaz where he already pushed something related to logcat.

**Comment by dirkhh** [comment]
@tcanabrava is aware of this, @janmulder
he's helping me debug something in there. I'm traveling with terrible internet today - I hope I'll be able to pull / deal with the PRs later this weel

**Pull request closed without merging**
