### PR TITLE
Mobile copy ui

### PR DESCRIPTION
**Pull request by mturkia**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [x] New feature
- [ ] Code cleanup
- [ ] Build system change
- [x] Documentation change
- [ ] Language translation

### Pull request long description:

UI for the mobile copy-paste functionality.
### Release note:

added
### Documentation change:

added
### Mentions:

@dirkhh @janmulder

### CODE REVIEW

**Comment by janmulder** [comment]
Tried this. I like the way things are "hidden" in the UI. No cluttering for non interested users, but you need to read the user manual to see all the possibilities of the copy/paste capability. Obviously, some developers and users might think the opposite (the UI should show all capabilities and the user shall be guided by intuition, and not needing a manual ever, but whatever. I like this hidden style).

I believe that the chosen copy/paste preferences need to be stored and retrieved on next sessions. For users that like a different than default copy/paste behavior, not storing them is a nuisance.

It does not seem to paste the location. Did not investigate why, but this seems a bug to me.

**Comment by mturkia** [comment]
I just tested the copy of divesite / location and it seems to be working for me. However, there are two peculiarities.
- Location on divelist is not updated
- I was not able to manually edit the location of an existing dive (not related to this patch). Neither selecting an existing site nor modifying the text worked.

**Comment by janmulder** [comment]
Ok, next test. Its getting confusing ... tested on device. My first Qt 5.12, clang and arm64 build, including this PR (obviously). 

All is copy/pasted (that is selected, so also the location + gps data). But, non is shown. Not on the divelist, not in the details. Scrolling away (and thus invalidating QML cached data), reveals finally all data pasted. But please keep in mind ... a very experimental build context.

**Comment by dirkhh** [comment]
Haha, talk about hard to discover UI. I figured I'd just try it. Nope, couldn't figure it out. Read the code. Yeah, that makes sense...
Locations aren't copied for me. Cached QML pages stay unmodified - so user experience is really unexpected.
@mturkia are you actively working on this? Are you looking for help with some of this?

**Comment by mturkia** [comment]
I have tried a couple of times to get the info updated on screen automatically and failed. So a bit of help would be appreciated.

**Comment by janmulder** [comment]
When I add the following code, automatic updating of the divelist does work for me (both on mobile-on-desktop, and own Android build), notice, I rebased this PR first on current master first, so not sure that the line numbers below are correct. This code is at the end of `pasteDiveData`.

```
------------------------ mobile-widgets/qmlmanager.cpp ------------------------
index 775305698..425c29ad2 100644
@@ -1440,0 +1441,4 @@ void QMLManager::pasteDiveData(int id)
+
+	DiveListModel *dm = DiveListModel::instance();
+	int modelIdx = dm->getDiveIdx(d->id);
+	DiveListModel::instance()->updateDive(modelIdx, d);
```

This said. There is still something weird left. The `what` data used in `pasteDiveData` does not always correspond to the setting in the UI. Did not invesitigate this further. Furthermore, my earlier remark "I believe that the chosen copy/paste preferences need to be stored and retrieved on next sessions. For users that like a different than default copy/paste behavior, not storing them is a nuisance." is also still valid.

**Comment by mturkia** [comment]
> When I add the following code, automatic updating of the divelist does work for me

Thanks, I'll take a look at this next week.

I agree that it would be convenient if the selection what to copy-paste was saved. The desktop version does not save it either, instead it presents the selection dialog whenever someone is copying data.

**Comment by mturkia** [comment]
The update of divelist seems to be working now with Jan's trick.

I am wondering about the defaults. The desktop version does not save what one wants to copy-paste over sessions. It instead shows a dialog with nothing selected when one does the copy operation. Would this option be actually feasible for the mobile as well? This would, at least, be easy to find unlike the long press on copy button apparently is. Or should this memory be implemented in both versions?

**Comment by janmulder** [comment]
Wrt. the defaults. I'm not sure on this either. I think that saving the list of fields in the preferences on mobile only (and leave desktop as it is) is acceptable. One could argue that this is inconsistent, but I can easily point out 100 other things things that are different in mobile and desktop. The difference in processing power, screen real-estate, and way of interfacing with the application (no mouse of mobile) makes this valid: it are simply different apps, that use a common code base (as much as possible).

I think that I would opt for stored in preferences on mobile.

**Comment by dirkhh** [comment]
I feel bad that this has been sitting for a month. Between a crazy travel schedule, hurting my foot and being in quite a bit of pain when sitting (which cut down on the time I was willing to spend sitting at my computer in the evening), and then getting one heck of a cold... I just haven't spent nearly as much time on Subsurface in the past six weeks than I really wanted.

I think giving the more challenging interaction with the UI on mobile, having mobile remember the choice does make more sense. But I'll admit that I'm slightly lost where we are overall with this PR...

**Comment by janmulder** [comment]
> Why is Travis failing?

I kicked the builds, and all went well. That "mac" build is very close to the max job length (50 min) of Travis. And its fully unclear to me why that build takes so long.

I'm happy to get this merged.

**Pull request merged**
