### PR TITLE
Desktop cloud UI changes

### PR DESCRIPTION
**Pull request by bstoeger**
### Describe the pull request:

- [ ] Bug fix
- [x] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

These are changes to the cloud desktop UI. In an attempt to make it possible to access non-cloud remote git repositories, a few adaptations to the UI were made. I think it will be easier to introduce these changes now and get feedback along the way. My problem is that I access dives from only one device, so I cannot really experience the cloud UI.

The changes here mostly concern the online/offline status. Firstly, I thought it was weird that "take cloud online" would not give any feedback. So this is changed to actually try to sync with the cloud. If this doesn't work, the user is informed. If it does work, the window title is changed to reflect the change.

Secondly, the preferences flag "sync with cloud in the background" (which does not do what it says) is replaced by a "take cloud offline" menu entry. This gives a symmetric interface (take cloud online/offline). More importantly, this can be used for arbitrary git repositories.

Thirdly, the options "take cloud online/offline" are now only enabled if the current file is the cloud. This can in the future simply be replaced by the condition "current file is remote git repository", with an appropriate renaming of the options.

Thanks for feedback / testing.

### CODE REVIEW

**Review by neolit123 — APPROVED** [review]
the commit `Enable take-cloud-online/offline only if connected to cloud` touches lines (e.g. the `setEnabled()` calls for the action) which were touched in the previous commit too, but i guess both commits follow your train of though so i would leave this as a nitpick.

the changes LGTM.

**Comment by neolit123** [comment]
@bstoeger this would need a `CHANGELOG.md` bump.

i've also added `needs-documentation-change` too, if the docs team follows these.

**Comment by janmulder** [comment]
Tested this, and my normal workflow works just fine (both desktop and mobile). Only one remark regarding the menu UI change. Would it be an option to change the two on/offline into one line with a radio button, like we have for autogroup, for example? Looks nicer IMHO.

**Comment by bstoeger** [comment]
> Only one remark regarding the menu UI change. Would it be an option to change the two on/offline into one line with a radio button, like we have for autogroup, for example? Looks nicer IMHO.

I made this change as an additional commit, so that it is easy to switch between both variants. If a decision is made, I will simplify the commit history (and add a CHANGELOG.md line).

**Comment by janmulder** [comment]
LGTM

**Comment by dirkhh** [comment]
I like the checkbox better. Otherwise LGTM

**Comment by bstoeger** [comment]
Respun this taking into account the preference for the checkbox version. Hopefully nothing broke. It survived light testing.

**Comment by janmulder** [comment]
Tested it again, and see (now) one thing that made me wonder. Not sure I tested the same scenario related to this PR before, so I can't tell (easily) if there is a difference between phase 1 and 2.

Ok, I see this. On mobile (on device, so fully independent local storage, as you might get fooled when running mobile-on-desktop), make a small edit, the local cache is updated, and select "manual sync with cloud". Now check on the internet cloud view if the small change has landed online, and yes, it has.

Now on the desktop, open Subsurface, and my default local git stored logbook opens. The mobile edit is not here, obviously. Now, open cloud storage, and the edit is not there. And that is correct as we are offline. Now select the toggle and go online. I see the message "fetch from remote", so I expect the change to become visible on the desktop. It does **not**. Now restart Subsurface. Same as before, the changes are not in my local logbook: correct. Now open cloud storage. And the local store does contain the edit. Going online does not change this. They are in sync.

It seems that in the UI, the divelist is not updated when going online, after the sync is done.

**Comment by bstoeger** [comment]
Your observation is correct - this was also the case for the first iteration. When "going online", the remote and the local repository are synced. But the dive data in the application is neither loaded nor saved from the local repository. Because what should happen if you have local changes? At some point the user will have to decide whether they want to overwrite the cloud with the local changes or vice-versa, isn't it?

To be honest, I'm really struggling with the cloud code. Not so much because the code is particularly messy, but rather owing to its conceptual complexity.

**Comment by janmulder** [comment]
Hmm. Lets not mix-up 2 subjects 1) the issue I pointed out (lets call it, divelist is not updated when going online, after the sync is done, with the divelist defined as the UI list of dives, not any background storage), and 2) the relation between any local storage (git or ssrf/xml file), and the cloud storage (which has a local git repo, and a bare repo at Dirk's storage). 

1) seems something to fix, as it will confuse the hell out of users working on 2 platforms (desktop and mobile).

2) Is indeed related to your remark: 

> But the dive data in the application is neither loaded nor saved from the local repository. Because what should happen if you have local changes? At some point the user will have to decide whether they want to overwrite the cloud with the local changes or vice-versa, isn't it?

Yes, when a user wants a local store (in git or ssrf/xml) and wants to use a cloud account as well, the user is currently at his own. There is no application support (other than "store in cloud", and "Save as"), to keep them in sync. I believe that this situation is perfectly fine. When the user want a hassle free online storage, the current cloud account is the way to go. All the logic is there to keep things in sync.

Personally, I like to have a local git repo as storage for my dives. And when traveling, I use a mobile and desktop in cloud setup. And when back home, I just pull and merge manually from the git storage used by the cloud to my local git repo (command line) to get my local store in sync again. I understand that this is not a useful procedure for anybody, but for that we have the normal cloud only setup.

**Comment by bstoeger** [comment]
I see your point concerning user-confusion. I just don't know how to resolve this bar a message box saying "Succesfully synced local and remote repository. To load/save dive-list select load or save in file menu".

What do you suggest should happen on "go online"? Load / Save / Try to merge / Ask user?

**Comment by janmulder** [comment]
I do not want any new message when going online. You can only go online after "Open cloud storage", so it is clear that we are talking only about the cloud (with its 2 ways of storage, locally and on the server). I only want to see my divelist updated to the storage state after the sync is none.

There is nothing a user can choose when going online. It is just: go online and sync, and after that the application needs to show the state after the sync. That is the only part that seems missing.

**Comment by bstoeger** [comment]
I understand you. But I don't see how to do that. We have three dive lists:
> [ui] <---1---> [local repo] <---2---> [remote repo].

What the "go online" code in this PR does (or rather is supposed to do) is sync the arrow marked with 2. I don't understand how it works - but apparently the git code manages to do this.

You also want the arrow marked with 1 synced. Is there already code to do this? What should happen in the following case:
1) Open cloud storage without network connection [cloud is offline]
2) Edit a dive in the ui
3) Go online [overwrite local changes with cloud or commit local changes to cloud?]

Maybe refuse going online as long as there are unsaved changes?

**Comment by janmulder** [comment]
Without answering all your questions, a quick answer. In the current PR, when going online, the local, and remote cloud storage are correctly synced (your magic arrow 2). Then you see a dive list in the application (a 4th form of storage besides the ones you mention). Now, select "Open cloud storage" again. When the previous go-online action brought in new changes, the changes are now visible (and stored in local/remote repos, as they are just synced). So, simply calling open cloud storage from the end of going online does the job (but with too much flashing of cloud messages).

I will try to come up with a fix.

**Comment by bstoeger** [comment]
What about this:
1) There are no unsaved changes -> simply load online cloud storage.
2) There are unsaved changes -> sync repositories and inform the user that the cloud is online, but since they have unsaved changes, they have to either load or save from the cloud.

?

**Comment by janmulder** [comment]
> There are no unsaved changes -> simply load online cloud storage.

This a a little ambiguous. Unsaved as in not stored in the local cloud store, or no newer commits in the local cloud store than in online cloud store? Newer commits shall be pushed to the online cloud store, but unsaved edits shall be saved first, and then pushed to remote. 

> There are unsaved changes -> sync repositories and inform the user that the cloud is online, but since they have unsaved changes, they have to either load or save from the cloud.

Partially already answered. And, in fact, going to remote cloud is equivalent to closing the application with respect to unsaved changes. When not saved, they are lost.

**Comment by dirkhh** [comment]
Wow, so much confusion.

remote repo going online implies that the local repo and remote repo are synced. And the local repo is opened. So any changes to the dive list are now synchronized. All you need to do is tell the UI to show those changes.

You didn't anything new in functionality - you just decided to implicitly trigger a certain action (open) when the user takes the cloud connection online.

All the talk about local XML files and unsaved changes is a distraction - this is all no different from before.

**Comment by janmulder** [comment]
> All you need to do is tell the UI to show those changes.

Thanks Dirk :-) That it the only thing that I am missing.

**Comment by bstoeger** [comment]
> This a a little ambiguous. Unsaved as in not stored in the local cloud store, or no newer commits in the local cloud store than in online cloud store? Newer commits shall be pushed to the online cloud store, but unsaved edits shall be saved first, and then pushed to remote.

I'm talking about changes that are not saved to the cloud. As in: The window title has an asterisk in it. So what you suggest here is that "going online" is equivalent to "Save to cloud storage".

> Partially already answered. And, in fact, going to remote cloud is equivalent to closing the application with respect to unsaved changes. When not saved, they are lost.

And now you suggest that "going online" is equivalent to "Open cloud storage". See where my confusion comes from? In any case, we can't simply dump the user's unsaved changes without asking.

> Wow, so much confusion.

Oh, yes..

> remote repo going online implies that the local repo and remote repo are synced. And the local repo is opened. So any changes to the dive list are now synchronized. All you need to do is tell the UI to show those changes.
>
> You didn't anything new in functionality - you just decided to implicitly trigger a certain action (open) when the user takes the cloud connection online.

That's probably what you want the PR to do, but that's *not* what it does. At least to my understanding.

Consider the following scenario (with current master or this PR):
1) Select "Open cloud storage"
2) Edit a dive
3) Select "Open cloud storage"

You will get a warning that your changes will be overwritten if you continue.

Alternative scenario (with this PR):
1) Select "Open cloud storage" without network
2) Edit a dive
3) Select "Go online"

The local and remote repositories will be synced. But the dive list will not be touched - your changes are still there. It's up to you to decide if you want to save them or overwrite them with data from the cloud. The PR as-is concerns only arrow 2 above, not arrow 1. I'm all ears for alternative suggestions.

**Comment by dirkhh** [comment]
My assumption was that the intent here is to combine "go online" and "open cloud storage".
That's why I didn't understand the discussion.
I don't think it is smart to sync with the remote repo (i.e., actually connect to the remote server via libgit2 vs just saying "hey, next time try to connect to the remote repo again" (as we used to do)) without first asking the user to commit all of their information to the local repo (i.e. the same checks we do now before a "save" or "open").

**Comment by bstoeger** [comment]
I think you're right - I'll try to come up with something more sensible.

**Comment by bstoeger** [comment]
Ok, next attempt.

1. No unsaved changes -> do a standard "Open cloud"
2. Unsaved changes -> Ask user if they want to commit changes.
2a. Yes -> do a standard "Save to cloud".
2b. No -> just update window title.

I'm not very happy about 2b. :/

**Comment by janmulder** [comment]
Yes, in general, I like what I see. I'm impressed Berthold that you come up with this after the convoluted discussion earlier. 

Two remarks. Commit message of 68c71d4 needs some rewording, not referencing the separate on/offline buttons. And still a small bug: edit a dive in offline cloud mode (the blue bar is visible), and try to switch to online. The dialog is shown (please save or cancel before going online), and close this. Now the window title says offline, and the menu button is online.

**Comment by bstoeger** [comment]
Thanks for testing!

> Commit message of 68c71d4 needs some rewording

Done.

> And still a small bug: edit a dive in offline cloud mode (the blue bar is visible), and try to switch to online. The dialog is shown (please save or cancel before going online), and close this. Now the window title says offline, and the menu button is online.

Good catch. Fixed.

**Comment by janmulder** [comment]
Did a quick review and LGTM. I believe ready to merge, but lets have @dirkhh have the final say in this.

**Comment by dirkhh** [comment]
Looks good. This fixes a number of subtle inconsistencies. well done.

**Pull request merged**
