### PR TITLE
mobile ui layout improvements

### PR DESCRIPTION
**Pull request by sebasje**
Various layout, alignment and dpi-corrections, basically. Comments welcome.
- add a units object to base sizing on, this object uses the rendered font size to provide a base units for sizing. units.gridUnit provides a dpi-corrected base-value for all UI elements.
- add a theme object which provides a color theme, I've filled this in with the blue from the subsurface icon and chose a matching light grey as background and a darker grey for text, looks pretty smooth, and can be further adjusted to taste
- port a whole bunch of hard-coded sizes to units.gridUnit, and colors to theme
- some layouting changes to what seems more convenient (Row, vs. RowLayout vs. anchors)
- various cleanups in object dependencies

I've only tested this on my desktop machine (180dpi), I'd be interested in screenshots of other dpi screens, especially Android devices. I'll be away for a week starting this weekend, so my next response may take a while.

Here's a screenshot: http://imgur.com/n0DnAjp

### CODE REVIEW

**Comment by pypingou** [comment]
You probably want to check https://github.com/torvalds/subsurface/blob/master/README#L71-L114

**Comment by neolit123** [comment]
the Signed-off-by line is very important - use "git commit -s" for that!

form there, "git format-patch" your branch locally against maser, register to the mailing list and send the patches as attachments in an email with [PATCH] in the title and the same explanation from above as the email body.

**Comment by sebasje** [comment]
Cool, thanks, will do that.

In the meantime, any comments on the approach or implementation and of course testing on more platforms would be most welcome.

**Comment by dirkhh** [comment]
On Fri, Oct 09, 2015 at 06:23:35AM -0700, Sebastian Kügler wrote:

> Cool, thanks, will do that.
> 
> In the meantime, any comments on the approach or implementation and of course testing on more platforms would be most welcome.

I will look at the changes later today and provide feedback on the code.
As for submission style / contributions, yes, all the things in the link
Pierre provided are valid.

I /really/ dislike the feedback system (so the ridiculous email addresses
you see in this email for example). I would strongly prefer the
conversation to happen on our developer mailing list.

We REQUIRE that patches have a Signed-Off-By: line (I think Lubomir
already pointed that out).

All that said, without even having looked at your code, just the commit
messages... YAY!!! I'm so happy that you are working on this. We really
need more people to work on the Android app / QML UI so any help in this
area is truly welcome.

Thanks and you'll hear more from me later. On the Subsurface mailing list
:-)

/D

**Comment by sebasje** [comment]
I saw the signed-off by in the git logs, but was pretty sure you'd point me at the right document for that. It was either read that document or get the patches submitted.

The requirement is not a problem, I'll rebase the patches once I'm back home, add the signed-off-by line, and will also address reviewers' comments then.

As I said, I'll be off for a week (Egypt's red sea), and I'm not taking my laptop, so no hurry with the review. I'm happy that I got at least some stuff done before I leave. I've some more changes planned, but I think this patchset provides a good base for feedback (and it's quite a nice improvement in itself).

**Comment by dirkhh** [comment]
Have you signed up to our mailing list, yet? That way we can move this
conversation there :-)

Thanks

/D

**Comment by sebasje** [comment]
I just did. See you there.

**Pull request closed without merging**
