### PR TITLE
Test-PR

### PR DESCRIPTION
**Pull request by bstoeger**
Copy of #2316 to see whether the test builds work.

### CODE REVIEW

**Comment by bstoeger** [comment]
@dirkhh: only 2 tests..?

Please close if this PR is pointless.

**Comment by dirkhh** [comment]
Oh. OH. I know what's wrong.
It's because it's a PR from YOUR account.
We only run the tests if it is a push to the Subsurface-divelog/subsurface repository. And since you are a Collaborator you can do that. There are privacy/security reasons for that - otherwise anyone who can open a PR can steel the secret tokens...
So please push this into a branch in the main repo and you'll get all the tests. Sorry I didn't notice this earlier.

**Comment by bstoeger** [comment]
Understood, but doesn't this mean that we don't get tests on non-collaborator submitted PRs, which somewhat defeats the purpose?

Moreover, last time I (inadvertently) cloned the main repository I pushed a garbage commit into master and I'd like to avoid such mishaps in the future. Is there a way to push from my copy into the main repository?

**Comment by dirkhh** [comment]
Right. Not sure why I'm so stupid this week.
We need to run these actions on push and pull_request
My bad

**Comment by glance-** [comment]
> Secrets are not passed to workflows that are triggered by a pull request from a fork of this repository.

**Comment by dirkhh** [comment]
Look at (and merge) #2337 (once it passes the builds), please

**Pull request closed without merging**
