### PR TITLE
Grammar: replaces 'indexes' by 'indices'

### PR DESCRIPTION
**Pull request by atdotde**
Feel free to close this if inappropriate!

Grammar-nazi ran

git grep -l 'indexes' | xargs sed -i '' -e 's/indexes/indices/g'

to prevent future wincing when reading the source code.

Signed-off-by: Robert C. Helling <helling@atdotde.de>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### CODE REVIEW

**Comment by dirkhh** [comment]
(a) I didn't know we had a 'grammar' label
(b) this commit is not wrong
(c) I am not convinced that this is the most pressing thing to fix
(d) I am idly wondering if there is a similar movement to "besser als" vs "besser wie" in English that is displacing "indices"... https://writingexplained.org/indexes-or-indices-difference so far it appears that at least for technical English this isn't the case.

**Review by dirkhh — APPROVED** [review]
since it doesn't affect any strings and since it doesn't appear to break anything... approved

**Comment by atdotde** [comment]
Sorry, but this had been bugging me since a while and I came across it today once more when I was implementing a new actual feature, which in the end I didn't as it was already there and I wasn't aware of it. #sohneinerdeutschlehrerin

**Comment by atdotde** [comment]
Is there anything urgent I should/could look into? Ideally something that does not involve mobile.

**Comment by dirkhh** [comment]
**snort**

Yeah, I just tagged you on the cylinder undo PR.

That's core code and reasonably close to things that I believe you are very familiar with.

I know that you are not a huge fan of the undo code, but from working on the mobile UI I can tell you that I am now completely converted and love the undo code. This has made extending the mobile UI so easy, it's embarrassing.

**Pull request merged**
