### PR TITLE
[WIP - EXPERIMENTAL] MTP support for the Garmin Descent Mk2

### PR DESCRIPTION
**Pull request by dirkhh**
### Describe the pull request:

- [x] Functional change
- [x] New feature
- [x] Build system change

### Pull request long description:

This brings in libdc changes that haven't been merged in that repo
Mostly this PR is here to test if this compiles on the various platforms (Windows still missing)

### Changes made:

1) update libdivecomputer to bring in the MTP support / Garmin Descent Mk2 code
2) build Subsurface against libmtp
3) add libmtp development packages for Linux and macOS for the CI builds
 
4) ditch the MXE Docker creation via GitHub Action and instead do it offline again in a single Dockerfile
5) switch the MXE build to 64 bit (I couldn't get libmtp to work with the 32 bit MXE tool chain and a quick look in our server logs seems to imply that we have basically no users on recent Subsurface version with 32 bit machines)

### CODE REVIEW

**Comment by dirkhh** [comment]
Ahhh, of course... older distros, older version of `libmtp`. So now we'll need to add conditional code to deal with that...

**Comment by dirkhh** [comment]
The Windows build will fail because I haven't pushed the new container to Docker Hub, yet.
This needs a tiny bit more work, but I wanted to have this code ready for review

**Review by torvalds — COMMENTED** [review]
No real comments. I wonder how rare 32-bit windows really is, but it's not like _I_ would care.

Looks pretty straightforward to me.

**Comment by dirkhh** [comment]
the iOS issue has nothing to do with this PR, so let's merge it and look at that later.

**Pull request merged**
