### PR TITLE
Show coordinates if no tags from reverse geolookup

### PR DESCRIPTION
**Pull request by mturkia**
Signed-off-by: Miika Turkia <miika.turkia@gmail.com>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [x] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

This will display the dive site coordinates after the Location label if
there are no associated tags from reverse geolookup. Thus it'll be
clearer for users that we do have GPS location stored for the dive, and
might be able to see more easily if the recorded coordinates are
correct.

### CODE REVIEW

**Comment by dirkhh** [comment]
I think it's fair to say that Travis isn't a fan of this PR...

**Comment by bstoeger** [comment]
28e3413ff66552f392fecee25068d634cdfe59fc replaced latitude / longitude pairs by location_t.

Note that it also introduced a `has_location()` helper, which might be of use for this PR.

**Comment by mturkia** [comment]
should have pulled the latest master, 2 days old repo seems to be ancient in Subsurface. Force pushed a commit that should be ok. And uses the has_location()

**Review by dirkhh — APPROVED** [review]
I like it

**Pull request merged**
