### PR TITLE
Gasdensity

### PR DESCRIPTION
**Pull request by atdotde**
In the Google forum, a user pointed out https://www.youtube.com/watch?v=QBajM3xmOtc which highlights the importance of the breathing gas density.

These patches compute this density and shows it in the infobox and, in the planner, as the color of the cylinder pressure line.

### CODE REVIEW

**Comment by janmulder** [comment]
I tried the PR and like the functionality. 

Some (small) remarks:
- I would write density in the info box as Density, just looks better IMHO in the list of items.
- First, I was confused where the new density was supposed to show. Looking trough the code I realized that my EAD preference was not activated. This brings me to a more general remark. As this is something new, which is definitely not known by a lot of (even technical) divers, a new section to the user manual is required to explain the the idea of density and its dangers. I think it would be nice that the software change is combined with a user manual change. It is too easy to forget the (relevant) addition to the manual in these cases.
- Not sure why diving with air does not show a density. Ok, the recreational diver is bothered with something new, but as long a the deep air diver is not extinct, it seems relevant to me for air dives as well.

**Comment by glance-** [comment]
How does this differ from the EADD we already have in the info box?

**Comment by atdotde** [comment]
EADD and gas density are the same thing expressed once as depth and once as density. With the latest patches they are displayed together.

**Comment by sfuchs79** [comment]
I also like this feature.

I have one doubt:
You changed gas density for N2 only. According to the first reference I found on the web you changed it from value at STP=0°C to NTP=20°C. Shouldn't we use values for 0°C or 20°C consistently for all gases? Maybe the 20°C value is really the better choice because the divers body will heat up the gas.
http://www.engineeringtoolbox.com/gas-density-d_158.html

**Comment by atdotde** [comment]
I meant to do that but got confused by the very same table mixing up footnote one and two. On the phone now, will send updated patch later.

**Pull request merged**
