### PR TITLE
Correct CMake to no do "cp -a" for missing QML parts.

### PR DESCRIPTION
**Pull request by janiversen**
The "cp -a" gives a "cannot overwrite" error because macdeployqt
is doing the job.

only copy if Qt version is between 5.11.0 and 5.12.5

Signed-off-by: Jan Iversen <jan@casacondor.com>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [x ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

This patch have been tested with Qt 5.12.5 and Qt 5.13.2

### Changes made:

see commit

### CODE REVIEW

**Review by dirkhh — COMMENTED** [review]
I simply need to test this on the platforms that I usually build.
Usually the trade-off "annoying error message that doesn't hurt" vs "I need to make sure this still works for all the different ways I build this" makes me lean towards ignoring annoying errors...

**Comment by janiversen** [comment]
Your POW is very understandable, feel free to close this PR if you feel it does not help the project.

**Comment by janiversen** [comment]
On a second thought lets all save some work, since this do not have any influence on the work I have made.

**Comment by dirkhh** [comment]
As you know, I always want to respect the work that contributors do.
And of course what you were trying to do was correct in the sense that it fixed a bug.
The real challenge is the complexity of all the different platforms and the various versions against which I end up building - so in the end the issue is that this project still relies way too much on ME doing so many different things. And every time we manage to automate another piece (thanks to @glance- for the work on liberating the building of containers from being dependent on me), overall things get easier to change.
So hopefully it won't be long before PRs like this will feel far less daunting to me.
Thanks for your understanding

**Pull request closed without merging**
