### PR TITLE
Filter invalidate version 2

### PR DESCRIPTION
**Pull request by janmulder**
### Describe the pull request:

- [x] Possible bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup/maintenance
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:
I could have force pushed, the work described in PR #986, but decided not to, and open this new one. Basically, the 2nd commit is changed as a result of the review comment of Berthold.

This "bug" is found using Qt 5.10 compiled in developer mode. Access the filters, click a little around here, close the filters. Almost every time the following assert is triggered:

```
ASSERT failure in QPersistentModelIndex::~QPersistentModelIndex:
"persistent model indexes corrupted", file itemmodels/qabstractitemmodel.cpp, line 643
```

This is relatively deep down in Qt, and it is triggered by clearing the filters. Trying to force a crash when using the same scenario in Qt 5.10 compiled for production (so no active asserts) did not result in a crash. So, up to this time, it is unclear if the Qt assert points out a real problem, or it is some false alarm (for whatever reason).

Further investigation shows that the assert can be solved by changing the invalidate() to an invalidateFilter(). Indeed, the last variant is a little more lightweight, and does seem to do the same job from a functional point of view (in this case).

Unfortunately, a well known problem was introduced. Incorrect width setting for the spanning trip lines. And as there is even a specific function for that, just call this. The reason the mentioned commit introduces this, is that invalidate() causes layoutChanged signals, and invalidateFilter() does not.

Signed-off-by: Jan Mulder <jlmulder@xs4all.nl>

### Changes made:
Carefully read the individual commits

### Additional information:
Original problem can only be seen when running Qt 5.10 from source with enabled asserts, and see (abandoned) PR #986, for the earlier review comment.

### Mentions:
@dirkhh, @bstoeger

### CODE REVIEW

**Comment by bstoeger** [comment]
I still believe that there must be a more fundamental problem with the sorting leading to the assert.
Apart from that - lgtm.

**Comment by janmulder** [comment]
I believe that too, but I'm still unsure if it is something that can be contributed to our code, or somewhere external like Qt. And as Thiago correctly said on the mailing list => fix Subsurface or show/prove that it is Qt. The simple fact that there is a function with the name fixMessyQtModelBehaviour() in our code shows that proving Qt is wrong can be too difficult or time consuming to attempt.

**Comment by dirkhh** [comment]
I agree that proving Qt wrong is often harder than one would think :-)
I think this looks all reasonable. Any reason not to merge it?

**Comment by janmulder** [comment]
Can be merged. Just left it open as this hacking around developer only asserts feels a little unchartered territory for me, so a second look is preferred (as is done now).

**Pull request merged**
