### PR TITLE
More selection speed improvements [contains #2785]

### PR DESCRIPTION
**Pull request by bstoeger**
### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

This selects all dives at once, which is a further improvement. Contains #2785. Posting as an extra PR, because the changes are becoming more and more "experimental".

For discussion see #2785, #2776 and the commit message.

### Mentions:

@janmulder, @atdotde.

### CODE REVIEW

**Comment by bstoeger** [comment]
Another one which gives quite a boost in some cases, though not all. I will have to think about the trip-selection problem.

**Review by dirkhh — APPROVED** [review]
That is quite a series of changes to the very innards of our code.
A week before a release is not my preferred time for something like this to go in, but frankly, the only way we'll find issues is if people test this - so having it sit on GitHub with zero users and bit rot is the wrong direction.

Are you still adding more changes, or is this a good point to merge, @bstoeger ?

**Comment by bstoeger** [comment]
> Are you still adding more changes

Not here and not today. Fixing the dive-trip disaster is probably much more tricky and should be done separately.

**Comment by dirkhh** [comment]
OK. Then I'll merge this and see if we are closer to having working binaries for all platforms.
I believe the update macOS binaries should now populate (this merge will be the test). The various Linux builds seem to be all working and getting some testing.
The Windows binary is the one where I'm debating whether I should keep it as is (as that is relatively well tested) or whether I should update the Qt version. Right now (given the ridiculous amount of pain and wasted time this has caused on the other platforms) I'm leaning towards updating to a newer Qt after the release...

**Pull request merged**
