### PR TITLE
[WIP] just doing a build check on my work on preferences so far, will be removed.

### PR DESCRIPTION
**Pull request by janiversen**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### CODE REVIEW

**Comment by dirkhh** [comment]
Cool - I'm curious where you are going with this. I'm just about to head for the airport, again, so I won't be able to actually read through the code - but I'd love quick peek into what you are working on!

**Comment by janiversen** [comment]
the base idea is to have qPref act as struct pref does for C code. qPref will be the central place to read/store pref. data on disk (currently it is quite distributed). The implementation of qPref is also using the same pattern for all data in struct pref.

I will add a "pref" screen so developers can see all the variables (and possibly change them).

**Comment by janiversen** [comment]
SettingsObjectWrapper contains a lot of the base code, but e.g. loading from disk is separated from storing (and do miss some preferences) and both planner and qmlmanager have handling local.

**Comment by janiversen** [comment]
got what I need for now so closing the PR. 

Choose close instead of removing the branch, giving @dirkhh a chance to read my reply :-)

**Comment by dirkhh** [comment]
Thanks - I know that @tcanabrava had thought about prefs and how to encapsulate them.
I'd be interested in his take - maybe it's useful to get his input before you have spent too much time on a specific implementation - but that's up to you. And with Tomaz it's often hard to predict how much time he has to look at thing. But it might not hurt to ask - he's in the same time zone as you are

**Comment by janiversen** [comment]
I will contact him, as soon as I have the min. required for merging it. I have already spent 100+ hours collecting and refactoring the information so a couple of hours more does not really matter.

**Comment by dirkhh** [comment]
Side note - I always worry when people spend 100+ hours on something without posting to the mailing list to discuss their ideas... you don't always get great feedback, but sometimes you get feedback that is crucial and changes the direction of the work. 100+ hours is a lot of investment and makes it very hard to change fundamental parts of what you intend to do.
Not implying that this is required, just worried about the potential for frustration.

**Comment by janiversen** [comment]
??? I have actually said that I am working on making all structure prefs variables available for qml, as part of my "scaleable" mobile version. But I have not received any feedback, actually I am disappointed with the list because nearly all my emails remain unanswered, that is potential for frustration :-)

Apart from that it is hard to discuss an actual implementation idea, before at least I have a clear picture in my head.

**Comment by janiversen** [comment]
ooh forgot the change qmlPrefs to qPrefs was to signalize the classes are not only for qml, but lets keep the existing name.

**Pull request closed without merging**
