### PR TITLE
French documentation updates

### PR DESCRIPTION
**Pull request by philmassart**
Sections about manually added dives, connection with PC, Location, Equipment

Signed-off-by: Philippe Massart <philippe@philmassart.net>

### CODE REVIEW

**Comment by dirkhh** [comment]
This pull request has quite a few merge conflicts with master - and since I don't speak French, I'm not sure I can fix them. Is there a chance you could rebase this on top of current master? It looks to me that maybe you made changes to a commit that I already took...

**Comment by philmassart** [comment]
Yes of course. It's the best to do. I will Check on my soir what occured 

Philippe

**Comment by dirkhh** [comment]
it's been a while... just checking with you. Are you still working on this? I don't want to lose the work that you did here!

**Comment by philmassart** [comment]
Yes, still working, but had some busy days ;-)

I’ll be back in a few days with updates translations

Philippe

**Comment by philmassart** [comment]
I was able to remove the conflicts, this time!

**Comment by dirkhh** [comment]
So github still claims a conflict. I'll once again try to pull it manually to see if I can resolve this (but last time I tried the conflicts were in the French text which I cannot read and therefore cannot resolve)

**Pull request closed without merging**
