### PR TITLE
[RFC] Remove useless getters in QMLManager

### PR DESCRIPTION
**Pull request by bstoeger**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Background: The more I learn about QML, the more I dislike it. This patch simplifies the properties code of QMLManager by removing redundant getter functions. It is, of course, merely a drop in the bucket.

According to my understanding of a mailing list discussion (though I hope that I'm mistaken), the setter functions cannot be removed, because the emitting of the signal is crucial. So one has to define the signal twice, once in the Q_PROPERTY macro, once in the setter function. An error will only be detected by misbehaving runtime. :(

In a further step, the `m_`-prefixes of the member variables could be removed. I'm not sure what the policy is in this regard though.

### CODE REVIEW

**Comment by neolit123** [comment]
@bstoeger 

> Background: The more I learn about QML, the more I dislike it. This patch simplifies the properties code of QMLManager by removing redundant getter functions. It is, of course, merely a drop in the bucket.

it's OK to remove the getters if they don't have any other operation other than return a local member.
`MEMBER` can be used as a replacement. 

> According to my understanding of a mailing list discussion (though I hope that I'm mistaken), the setter functions cannot be removed, because the emitting of the signal is crucial. So one has to define the signal twice, once in the Q_PROPERTY macro, once in the setter function. An error will only be detected by misbehaving runtime. :(

from the Qt docs:
http://doc.qt.io/qt-5/properties.html
```
A NOTIFY signal is optional. If defined, it should specify one existing signal in that class that is emitted
 whenever the value of the property changes. NOTIFY signals for MEMBER variables must take zero or
 one parameter, which must be of the same type as the property. The parameter will take the new
 value of the property. The NOTIFY signal should only be emitted when the property has really been 
changed, to avoid bindings being unnecessarily re-evaluated in QML, for example. [2] Qt emits 
automatically that signal when needed for MEMBER properties that do not have an explicit setter.

```
highlighting in the context of this PR:
[2] so it should work automatically without a setter and `MEMBER` only, but i think i've tested this at some point and couldn't get it to work with QML and my use case - i.e. it needed a `MEMBER` (or READ) + `NOTIFY` + `WRITE` to work.

on the other hand some of the these setters aren't exactly plain - e.g.:
```
void QMLManager::setCloudUserName(const QString &cloudUserName)
{
	m_cloudUserName = cloudUserName.toLower();
	emit cloudUserNameChanged();
}
...
void QMLManager::setTimeThreshold(int time)
{
	m_timeThreshold = time;
	locationProvider->setGpsTimeThreshold(m_timeThreshold * 60);
	emit timeThresholdChanged();
}
...
```

so `MEMBER` only will not work for them.

> In a further step, the m_-prefixes of the member variables could be removed. I'm not sure what the policy is in this regard though.

our code base has them mixed as we do not have a rule for them. i'm usually leaning towards having `m_` for members. so leave them as is, in this patch.

the patch seems good to me. but it's best if it's tested on the mobile build even if the CI succeeds. you can build the mobile version on the desktop with:
https://github.com/Subsurface-divelog/subsurface/blob/master/CMakeLists.txt#L46

**Comment by bstoeger** [comment]
> on the other hand some of the these setters aren't exactly plain

Yes, I think it is mandatory to emit the signal to let the QML frontend know that the field has changed. So all the setters are necessary.

I don't understand why they didn't go the template way:
```
Property<type, signal,...optional arguments...> property;
```
Which overwrites `operator=()`. I guess that would be too straight-forward to use.

> the patch seems good to me. but it's best if it's tested on the mobile build even if the CI succeeds. you can build the mobile version on the desktop with

I did that and at least superficially it seems to work - but of course I couldn't test all the cloud-connection things.

BTW: My mobile-on-desktop version segfaults on exit - is that expected?

**Comment by neolit123** [comment]
> I don't understand why they didn't go the template way:

i don't know. probably they though MOC is the better choice here.

> I did that and at least superficially it seems to work - but of course I couldn't test all the cloud-connection things.

ok. using `MEMBER` should be a harmless replacement for `READ` given we keep `WRITE` and `NOTIFY`.

> BTW: My mobile-on-desktop version segfaults on exit - is that expected?

i don't remember it crashing the last time i've tested the mobile build. but i do recall users reporting a crash on exit. could be Qt version related.

**Review by neolit123 — APPROVED** [review]

**Comment by janmulder** [comment]
Tested this on device, and LGTM. Made a new cloud account, and all is just working. So, merging.

A little word of warning when messing with the mobile stuff. As most of the settings in preferences are not shared between desktop and mobile, code that depends on preferences cannot be properly tested on mobile-on-desktop. When running mobile-on-desktop (what most developers obviously prefer) the same set of preferences are used as in the normal desktop app.

**Pull request merged**
