### PR TITLE
a bit translations

### PR DESCRIPTION
**Pull request by theundefined**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [x] Language translation

### Pull request long description:

A bit translation to polish.

### CODE REVIEW

**Comment by PeterZaal** [comment]
Shouldn't translations be done in Transifex?

Peter

**Comment by dirkhh** [comment]
We do track our translations in Transifex - you can join the Subsurface team there.
I will figure out how to take your contribution here, though. :-)

Thanks for making Subsurface better!

**Comment by theundefined** [comment]
Ops :-) I saw typo in translation, so i just try to fix it. And then i did few more translations... I didn't read that it's in another system :-) In the free time i'll try to check transifex :-)

**Comment by dirkhh** [comment]
It's really simple and I think the user interface is quite nice.
Sign up for a free account at https://www.transifex.com (I think these days you can simply use your GitHub account) and then join the Subsurface team.
https://www.transifex.com/subsurface/
Once I approve you as translator you can directly edit the translations. And you'll get notified when the source strings change.
Again, thank you for your contribution!
Please email me (dirk@hohndel.org) if you run into any problems - I really want to make this easy for translators.

**Pull request closed without merging**
