### PR TITLE
[RFC] Change control-flow when resetting core data

### PR DESCRIPTION
**Pull request by bstoeger**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

The way the application is reset on loading / closing irked me for quite some time. This tries to disentangle inter-module dependencies by creating a "data reset" signal that is emitted by the core. The various modules should then reset themselves.

On desktop at least a quick test seemed to work fine.
### Changes made:

1) Use common signal to reset models.
2) Call into core directly to reset data. Don't go via models.

### CODE REVIEW

**Review by dirkhh — COMMENTED** [review]
Talk about an invasive change... :-)
Yeah, I think this is the right thing to do, it will need a lot of testing - usually the only way to get this is to merge it. But with this I want to do at least some testing on mobile (and especially on device) to be at least somewhat confident that this doesn't completely break things...
BTW: I don't think it's related at all, but have you seen #2814 ? That's another place where apparently a change in the core isn't propagating to a widget...

**Comment by bstoeger** [comment]
> BTW: I don't think it's related at all, but have you seen #2814 

#2815

**Review by dirkhh — APPROVED** [review]
Spent more time staring at this. I believe this is the right thing to do.

**Comment by dirkhh** [comment]
happy to merge this as well - can do the merge locally if you want.

**Comment by bstoeger** [comment]
rebase on master

**Comment by dirkhh** [comment]
GitHub is unwell - I need to reach out to them again. This is happening more and more frequently. Source checkout fails with a bogus error that the SHA isn't a tree

**Pull request merged**
