### PR TITLE
[WIP] (planner 7) first version of diveplanner pages

### PR DESCRIPTION
**Pull request by janiversen**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [x ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

add diveplanner pages as placeholders and integrate into globalDrawer

add setup page with real values.
add CHANGELOG.md line

### CODE REVIEW

**Comment by dirkhh** [comment]
I'm about ready to merge all this, up and including this PR into master.
Quick question - some of the commits appear to have your apache.org email address as Author (all are signed off with your new address). Would you want me to fix this as I handle them?
And small comment, in case you care - because of the way I process these, they all will have a second signed-off-by from me - all that is signfied by that is that I have touched them in the process of committing - this obviously isn't any claim of authorship - it's just part of the way my tools are set up...

**Comment by janiversen** [comment]
Apache is an alias, but if it does not take extra time then please correct it. I do not have any problem with a second signoff, as long as I stay author.

some of these are cherry-pick from commits I made last year, I assume that is the reason the apache addr.

**Comment by janiversen** [comment]
thanks for handling all in one go.

**Comment by dirkhh** [comment]
it's 30 seconds of work. And yes - this being older commits would explain what I see.

**Comment by dirkhh** [comment]
they also have author dates in February :-)

**Comment by dirkhh** [comment]
manually merged

**Comment by janiversen** [comment]
Do you close PR planner1-6 ? I can also do it.

**Pull request closed without merging**
