### PR TITLE
Don't show cylinder pressure graph for wrong dc for merged dives

### PR DESCRIPTION
**Pull request by sfuchs79**
### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

When merging a logged dive from a dive computer and a planned dive
the cylinders are not always merged. They are e.g. not merged if we
have manually entered pressure values. So we correctly end up with
a doubled set of cylinders.
When now plotting the pressure graphs we need to make sure to only
plot graphs for the cylinders which really belong to the displayed dc.
This PR introduces this behavior.

### Related issues:

This fixes part of what is reported in #697 (but not everything yet)

### Mentions:

@willemferguson once had a example for such a situation. Can you please test this?

### CODE REVIEW

**Comment by sfuchs79** [comment]
@willemferguson 
Ah, found Willems example file. Looks way better with this fix :-)

grafik

**Comment by dirkhh** [comment]
Seems reasonable. It would be good to have Linus look at it as well.

**Comment by neolit123** [comment]
hi, @sfuchs79  can you please ping Linus and the ML about this?

**Comment by torvalds** [comment]
I don't think this is necessarily wrong, but I posted a syntactically different but logically equivalent (hopefully) series as patches on the mailing list.

**Comment by sfuchs79** [comment]
Closed because we have the better solution #826

**Pull request closed without merging**
