### PR TITLE
Planner creating dive from plan: No pressure for 1st sample with new gas

### LINKED ISSUE #603: Vertical lines in pressure graphs under very specific conditions in planner
Created this as a spin-off from #562 to seperate items which do not really belong together and to keep the discussion and latest status from mailing list.

There was already a fix e94af2c0b7ce0dd0e61e25b717829543120c4d33 done which improved the situation a lot but there is still one situation where this issue can be seen:

I can still create one interesting situation where I finally will have the vertical lines in the pressure graph:
- I plan a new dive of the specific kind (deco gas used as first gas and then used later again) with the planner and save it to a new XML file
  --> Everything ok, no vertical line in graph, in XML at time of gas change 43:35 there is no pressure value. This is as @torvalds  said it should be.
- I close Subsurface, restart, open XML
  --> Everything ok, no vertical line in graph
- Replan dive in planner
  --> Vertical line at ~43min appears and if I now save this and look in the XML a pressure value was added at 43:35 which is incorrect.

[Test_Dives.zip](https://github.com/Subsurface-divelog/subsurface/files/1327279/Test_Dives.zip)

The question is now: Why does the planner (or whatever) does the thing correctly when creating the dive but then does a mistake when replanning the same dive?

### PR DESCRIPTION
**Pull request by sfuchs79**
### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

In the planner when a dive is created from the diveplan every first
sample with a new gas shouldn't have a pressure value added.
Otherwise the interpolation code for the pressure graph in the profile
will draw the pressure graph incorrectly.

### Related issues:

This is my proposal to fix #603 
Closes #603 

### Mentions:

@torvalds (did the first part of a fix for this: e94af2c0b7ce0dd0e61e25b717829543120c4d33)
@atdotde

### CODE REVIEW

**Comment by dirkhh** [comment]
Is there a test that we could add? Can you show the before / after picture?

**Comment by sfuchs79** [comment]
Before / not OK picture (can be also found here #562):
grafik

After / OK picture, even after doing the steps described here #603:
grafik

Tests, hmm... no clue how difficult this would be.

More important from my point of view would be that s.o. confirms that the logic behind this change is the right one. Linus would be a good candidate because he explained in details on the mailinglist where the issue in the pressure graph comes from.

**Comment by dirkhh** [comment]
This looks good. Thanks for the pics. @atdotde - any comments?

**Comment by atdotde** [comment]
As @torvalds commented on the mailing list, you should probably remove the two other places in the same function as well, i.e. line 292 and 346.

**Comment by sfuchs79** [comment]
I'm not against removing all but I think that there is a difference between first and last place of adding sample pressure in the code and the middle case I removed:
1st and last case: unnecessary in our use case (planner)
middle case: unnecessary, incorrect and harmful (creates the incorrect vertical lines)

Are you sure that we never will call this function in a situation where we want to have the sample pressures added?

**Comment by sfuchs79** [comment]
Oh-oh... here I'm somehow lost meanwhile.
I tested with removing all the sample pressures. This is clearly the correct idea.
But then I found another hidden issue with one of my test dives: For one of the cylinders the end pressure is not stored in the cylinder struct at all while the sample pressures had been ok. I see this because it's also not in the XML (see file).
This issue was always there but was compensated by the sample pressures being available up to now. If I now remove all the sample pressures the formerly hidden issue shows the effect that for this cylinder we clearly can't display a pressure graph at all.

@atdotde Any idea why the end pressure of this specific cylinder with this specific dive is not populated?

[test.zip](https://github.com/Subsurface-divelog/subsurface/files/1366703/test.zip)

Another thing: I pushed 2 more commits here fixing things I found when debuging. The dump plan change is harmless but the change in create_dive_from_plan() needs careful review.

**Comment by sfuchs79** [comment]
Update here from my side:
I reviewed and tested this now multiple times and this current version of the fix gives the best results for my example cases and also the risk is not so high that this breakes s.th.
I would suggest to merge this.

**Comment by atdotde** [comment]
@sfuchs79 Honestly, I have no clue. Can you reproduce this "end pressure is not set" behaviour? Using Qt Creator, I tried to identify the places in the code, where cylinder.end.mbar is set at all and from what I can tell, the only place is in cylihdermodel.cpp line 376 which gets executed when the value of the cylihdermodel changes. So, maybe we need to trigger that before we walk away with the end pressure. But to investigate that, I would need to know how to trigger this behaviour. The rest looks good, so I will merge it.

**Pull request merged**
