### PR TITLE
planner: fix deco calculation

### PR DESCRIPTION
**Pull request by bstoeger**
In 9bfc6d252, testing of the planner was changed to use the
planner_ds parameter instead of a global variable.

Unfortunately, two conditionals were inverted, leading to
an erroneous ceiling calculation when in the planner.

Restore the proper conditions. Moreover, instead of testing
the planner_ds parameter, use the already existing in_planner
flag, which is derived from said parameter.

Signed-off-by: Berthold Stoeger <bstoeger@mail.tuwien.ac.at>

### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Fixes bug introduced by 9bfc6d252.

### Changes made:

1) Restore conditionals.
2) Use flag instead of pointer for code clarity.
### Related issues:

See discussion in #3186.

### Release note:

No, bug not in release.

### CODE REVIEW

**Comment by atdotde** [comment]
Looks good. I added a PR relative to this that should find such regressions in the future (so far this was missed because the profile test used only Bühlmann)

**Comment by dirkhh** [comment]
So this is part of #3206 and should be merged with that one?

**Comment by dirkhh** [comment]
So I apparently walked away in mid conversation.
Sucky maintainer. So should I merge #3206 before cutting 5.0?

**Comment by atdotde** [comment]
Yes, please.

**Comment by dirkhh** [comment]
merged via local merge of #3206

**Comment by dirkhh** [comment]
And with this in master, tests fail.

Which reminds Dirk to never, ever, ever, ever do a quick merge if he has a few hours to do a release.

**Comment by atdotde** [comment]
Is it the modified profile test that fails? Here, locally, for me it passes. in tests/testprofile.cpp there is an explanation how to make this test pass (by copying a file to dives and committing it). I forgot to update that comment to include also the VPMB versions of the files, dives/exportprofilereferenceVPMB.csv and exportprofileVPMB.csv . I cannot do it here, as the files agree here.

**Comment by dirkhh** [comment]
fixed in master - see last commit there.
in the middle of rushing out 5.0 before I run out of steam :)

**Pull request closed without merging**
