### PR TITLE
[TEST] For CI: generate redundant functions using template magic

### PR DESCRIPTION
**Pull request by bstoeger**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

This PR is only to run CI. I faintly remember that clang doesn't stomach the simple constructor delegation with the `using` directive as used in this PR. If it runs I will write a longer description.

### CODE REVIEW

**Comment by dirkhh** [comment]
Looks like the compilers liked it

**Comment by dirkhh** [comment]
clearly removes a lot of code, so that's neat. And I don't immediately hate the use of templates here (which, as you know, is high praise from me when it comes to C++-isms).

**Comment by dirkhh** [comment]
Is this something that should be merged? Or is this just something you posted for compile testing?

**Comment by bstoeger** [comment]
Yes, if you feel that the gained brevity outweighs the pointer-to-member obscurity.

**Comment by dirkhh** [comment]
This may sound bad from the maintainer. But I really don't care. I assumed you wrote the code because you felt it was better. And on that I will certainly trust you more than I trust myself.
So if you feel this should go in, please merge it. If you feel this isn't an improvement, please close it.

**Comment by bstoeger** [comment]
*shrug*
I guess it makes implementing simple dive-edit-commands by copy&paste easier.

**Pull request merged**
