### PR TITLE
Icons cleanup 1st stage

### PR DESCRIPTION
**Pull request by merinsky**
### Describe the pull request:
- [* ] Code cleanup

### Pull request long description:
This is first part of my work. To have nicer icons in Subsurface. Till now almost everything should work as before.

### CODE REVIEW

**Comment by neolit123** [comment]
i would much rather preferred if we go with `<widget>-icon-<name>` or `icon-<widget>-<name>`- where `widget` optionally describes in what widget this asset is used, and `icon` which describes the type of the asset. i don't like putting `icon` last and not specifying where this asset is used. we need some sort of grouping, not renaming all icons and placing them in the same sorted context.

also, i don't like `dive-spot` that you've used in the map-widget. :)
it should be either `dive site` and `dive location`, `dive marker`.
technically it should be a `dive location ` as that's the underlying C++ type that wraps the `dive site` C type.

the map type are also called `street` not `roadmap` in the underlying C++. not sure why you've decided to rename this.

i'm tempted to suggest a revert for this patch as this can be done better.

@tcanabrava and @merinsky 
CC @dirkhh

**Comment by merinsky** [comment]
> &lt;widget&gt;-icon-&lt;name&gt; or icon-&lt;widget&gt;-&lt;name&gt;

This is absolutely incorrect. Icon names has nothing to do with widgets. Same icons may be used in several widgets. I'm aiming to use standard naming scheme according to Freedesktop Icon Naming Specification. 

There is question, whether to use `-icon` suffix in `qrc` and code. But it is matter of one search &amp; replace (easy to do one way, difficult the other). Using standard icon themes is the way to go.

`dive-spot` might not be the best name, I agree. I found names `poi-marker` and `mark-location` in GNOME, Adwaita and HighContrast icon sets. So I vote for `dive-location-marker`. I can change this and send pull request if agreed.

I did a small research and chose **roadmap** because **street** doesn't say anything about what it is. No matter how the underlying C++ calls it. Google calls it **Satellite** and **Map**. en.mapy.cz calls it **Aerial** and **Base**. Bing calls it **Aerial** and **Road** with explanation "A standard road map." bingo ;-) I found this the most explantory. Google search _streetmap_ versus _roadmap_, **roadmap** wins. But I have no strong feelings about this.

**Comment by neolit123** [comment]
we shouldn't care much about `Freedesktop Icon Naming Specification` or `GNOME` to be quite honest.

>This is absolutely incorrect.

please, read the `widget` proposal more in the lines of `context`, `location`, `grouping`.
some of the icons don't have that and they have no context, so maybe it's a good idea to give them context?

this is good:
```
        <file alias="gaschange-air-icon">icons/Air_change.png</file>
        <file alias="gaschange-ean-icon">icons/Nx_change.png</file>
        <file alias="gaschange-oxy-icon">icons/Oxy_change.png</file>
        <file alias="gaschange-tmx-icon">icons/Tmx_change.png</file>
```

this is also good:
```
        <file alias="preferences-desktop-locale-icon">icons/language.png</file>
        <file alias="preferences-other-icon">icons/defaults.png</file>
        <file alias="preferences-system-network-icon">icons/network.png</file>
```

this isn't:
```
        <file alias="pphe-icon">icons/he.png</file>
        <file alias="ppn2-icon">icons/n2.png</file>
        <file alias="ppo2-icon">icons/o2.png</file>
```

the above icons are sorted by molecules.

why `context-resourcetype-name` works? in the alphabetical order this would group all resources by `context` then by `resourcetype` and finally by name.

for instance with your change you have separated the zoom icons from the map widget at the end of the icon list, yet they are not re-used anywhere else:
```
        <file alias="zoom-in-icon">map-widget/qml/icons/mapwidget-zoom-in.png</file>
        <file alias="zoom-out-icon">map-widget/qml/icons/mapwidget-zoom-out.png</file>
```

> I did a small research and chose roadmap because street doesn't say anything about what it is. No matter how the underlying C++ calls it. Google calls it Satellite and Map. en.mapy.cz calls it Aerial and Base. Bing calls it Aerial and Road with explanation "A standard road map." bingo ;-) I found this the most explantory. Google search streetmap versus roadmap, roadmap wins. But I have no strong feelings about this.

it's all about the underlying code, because the resources are for Subsurface developers not for GNOME icon people. the icon should be called to be meaningful and reflect a connection with the underlying source code. the google maps plugin we are using has a map type `STREET` not `ROADMAP`.

**NAK** for this change from me, as it need to be done in a better way...one problem is that it's already in master.

**Comment by merinsky** [comment]
> we shouldn't care much about Freedesktop Icon Naming Specification or GNOME to be quite honest.

This is pretty strong statement. It is not GNOME thing, it works for KDE as well.

Why I want standardized icon names? Because I don't want Subsurface icons. I don't want Subsurface to look other way than the rest of my desktop. I want all applications on my computer to use the same icons for the common things. And I want to be able to switch icon theme at will.

> the above icons are sorted by molecules.

Yes, because molecules are the only thing that is different there.

> for instance with your change you have separated the zoom icons from the map widget at the end of the icon list, yet they are not re-used anywhere else:

Correct. They could be. Zooming is not exclusive for map.

In this case alphabetical order works pretty well. Better than current state.

Do you seriously(?!) think current mess is better than this merge? It didn't bother anyone for a long, long time.

If you want to see, whrere my works leads see my branch [icons_3](https://github.com/merinsky/subsurface/tree/icons_3).

**Comment by dirkhh** [comment]
I'm very unhappy to see this merged without more review. @tcanabrava - I don't think that was the right decision. Let's revert this.
I completely agree with Lubomir. Gnome standards (and frankly, KDE standards) are entirely irrelevant on the platforms where Subsurface has a substantial user base. Randomly ordering things alphabetically and take them out of context is not a good idea.
NAK and revert.

**Pull request merged**
