### PR TITLE
Consistent strings3

### PR DESCRIPTION
**Pull request by merinsky**
Last string changes on my list. Some of these might be a little bit controversial. If so, please feel free to cherry-pick whatever you like.

### CODE REVIEW

**Comment by Ghalr** [comment]
I would keep divemode, divelog, divespot, such as setpoint.. This is because, divers have learned with those english words.. In my opinion, some words should not be translated. 
For French we will have:
- Mode de plongée
- Journal de plongée
- Lieu de plongée

Also maybe another french can check about that "setpoint" translation.
We should have also "low setpoint" and "high setpoint". Setpoint will be more understandable, shorter than any other custom translation.

**Comment by dirkhh** [comment]
Can we have that conversation on the mailing list. I very much appreciate the push for consistency, but I thing @Ghalr raises some good points.

**Comment by Ghalr** [comment]
I will try to setup mailing list right now, but I have no idea how it works.
For example, here is a famous  website (in french) who explain what is setpoints for CCR
http://recycleur.free.fr/index.php/pratique
Even our french manual for Inspiration CCR do not translate setpoints, and I am not sure if Dive Computer do translate this either.
http://www.plongeesout.com/articles%20publication/recycleur/inspiration/Inspiration_Vision_%20manuel%20d'utilisation%200107.pdf    - CTRL+F Setpoint

To be honest, I have no idea how to translate correctly "setpoint(s)".

**Comment by Ghalr** [comment]
I have a concern also about : EAD, END, EADD, MOD
Those letters should not be translated. This is what we share to divemaster when we do make travel who is not our native language. Any of those terms can be understood by anyone.

**Comment by merinsky** [comment]
Big thanks for looking at this. :-)

I would like to say, that this pull request has nothing to do with question whether to translate something or not. For the record, I wouldn't translate setpoint to Czech. But this has nothing to do with translations.

As @Ghair pointed out, "Setpoint" is used most often as one word. We use "Setpoint" in UI, so I only suggest to use it as one word everywhere.

"Setpoint" has nothing common with "Dive mode", "Dive log" or "Dive spot". These terms can be considered separately.

Subsurface now uses both "Dive mode" and "Divemode" (the same for "Dive log" and "Dive spot"). My intention is to use only one variant.

I agree with @Ghair, that many divers use some terms in english. But these terms should be spelled correctly. 

PADI uses "dive log", not "divelog":
http://www2.padi.com/blog/tag/dive-log/

Let's have a look at number of Google search results:

"dive mode" 48,700
"divemode"   2,120

"dive log" 235,000
"divelog"   68,000

"dive spot" 237,000
"divespot"   26,000

I belive that two-words versions are the correct ones.

**Comment by Ghalr** [comment]
Good point about "dive mode, dive log, dive spot" google result. But some languages requiert like a lot of characters and space left can be a problem. Also let's imagine that you are using Subsurface with your buddy who do not speak your language, it would be much better if specific terms are in english (not translated). I mean specific term like MOD/END where Open Water divers learnt at school. I do believe then that Subsurface is switch to english language when you met new friends ^^.

Divers understand these words regardless of their nationality.
I will never put anything else than MOD inscription on my tanks when I'll dive abroad.

**Comment by dirkhh** [comment]
So we could decide not to translate some terms. But what about non Latin scripts? Would you leave these terms in Russian, Hebrew, or Chinese?



-------- Original Message --------

**Comment by Ghalr** [comment]
Totally. Any divers will clearly understand what's going on even if they dive with russian or chinese divers who speak with understandable terms. Writing down MOD/END (or anything else) on their tanks will help to understand/communicate a lot more faster and easier than having a translated term. Communication is really important to have a better dive without any issues. This would be the same when filling a tank in a fill station, we do use MOD/END terms.


I also found some Dive Computer  vs   Dive computer.

**Comment by dirkhh** [comment]
I really, really, really doubt that.
No, let me be more clear.
I think you are dead wrong.
I know quite a few German divers who's have no idea what you are talking about.


-------- Original Message --------

**Comment by Ghalr** [comment]
About MOD/END terms ?

**Comment by dirkhh** [comment]
Yep

⁣


-------- Original Message --------

**Comment by Ghalr** [comment]
I'm just sharing my point of view here.
In my country we learnt and do use and understand those terms.
I personally use english subsurface so this is not a problem for me, maybe some other users can give their point of view too.

**Comment by ghost** [comment]
I agree with Martin, the 2 word variants of those strings make more sense to me.
Regarding translation of technical terms, would the best course be to mark them for translation anyway? then in countries that use their own term they can be translated, and in countries where the English term is used that English word can be set as the translation.

**Pull request merged**
