### PR TITLE
[TESTING] Play videos in profile plot

### PR DESCRIPTION
**Pull request by bstoeger**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [x] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Note! This is only for testing, not an actual pull request.

The point of this PR is to let people test if my approach for playing videos in the profile widget works. A few comments:
1) The code here is quite verbose, since using a `QGraphicsVideoItem` did not work on my setup. Therefore, video frames are shown by hand.
2) Extracting stills as thumbnails is not yet implemented owing to a Qt bug discussed in #359 (this must be performed in the main thread or an external library must be used). This will need some refactoring of the thumbnail code.
3) To mark a file as a video, a null QImage is added to a new video-thumbnail-cache. This is for forward-compatibility: Once thumbnail-extraction is supported, actual images will be written to this cache.
4) At the moment, when a null-image is found in the video-thumbnail-cache, a dummy "video" icon is shown. A proper icon is needed.
5) Since at the moment there is no extraction of stills, videos are identified by file extensions. Since Qt provides no list of supported file formats, this is hard-coded. 

To test:
1) Go to dive picture tab
2) Upload an mp4 or mpeg.
3) Switch to different dive and back [so that the proper thumbnail is loaded].
4) Move video onto profile graph.
5) Hover mouse over video in profile graph.

Please let me know if this works for you.

### CODE REVIEW

**Comment by bstoeger** [comment]
Ok - this needs some Travis CI magic. And conditional compilation on mobile.

NB.: the `list(APPEND QT_EXTRA_LIBRARIES Qt5::MultimediaWidgets)` is probably not even needed in the current version, since projection of images is done by hand.

**Comment by sfuchs79** [comment]
@bstoeger 
Hey, first thing I have to say: I'm a big fan of this video support feature idea! :-)

Finally I managed to do some testing (on Windows 10). Maybe the result is not what you would like to hear but I see some very positive aspects:
- Adding a video file works
- Dragging it to the profile works
- (Double-)Clicking it in the tab or the profile does open the external viewer
- But: NO video playback in the profile! I guess that should happen on mouse-over?
There is this on stdout:
`defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.mediaplayer"`

The question I would like to raise is: Is Subsurface internal video playback really prio A? For me I see these three steps of implementation:
1. Be able to add a video (w/o thumbnail) and be able to open it in external viewer
2. Same as 1. but with thumbnail
3. Same as 2. but also with internal playback

Your implementation is already close to 1.
Only focusing on step 1. there are these findings:
- Video icon doesn't show up instantly (you know this based on your comments)
- It doesn't make sense to show the "adjust time" dialog for the video as long as we can never extract a date/time from a video file
BTW: Is there a possible way to do this?

**Comment by bstoeger** [comment]
Thanks for testing. That's a pity. :( I fear I can't do anything about that. There's a rather long thread here: https://forum.qt.io/topic/28620/solved-qtmultimedia-defaultserviceprovider-requestservice-no-service-found-for-org-qt-project-qt-mediaplayer/16 but I can't really follow it. Maybe you can extract some useful information out of it? Sounds like a Qt build/installation problem?

The problem is that still-extraction in Qt works by starting a video and intercepting a frame. So 2 (thumbnail extraction) will not work if 3 (video replay) doesn't work. We could use an external library, but I feel getting video-replay running in Qt will be more fruitful in the long run.

> Video icon doesn't show up instantly (you know this based on your comments)

I have fixed that - will push in due course.

> It doesn't make sense to show the "adjust time" dialog for the video as long as we can never extract a date/time from a video file

What about the file timestamp?

**Comment by sfuchs79** [comment]
@bstoeger 
Regarding playback: I will read the discussion more carefully. Maybe we simply need to install an additional DLL?
But as I was saying already step 1 "be able to add a video (w/o thumbnail) and be able to open it in external viewer" would be a really nice new feature :-)
Let's go step by step...

Yes, using the file timestamp may work in many cases. I'm not an expert in file timestamps at all. I guess that the file timestamp can change when editing the video (or picture) file. This is why for pictures it is nicer to use the EXIF date/time. But as long as we don't have s.th. similar as EXIF for video files it would be also ok to use the file timestamp.

**Comment by sfuchs79** [comment]
@bstoeger 
I figured out one thing: Most probably we need to install dsengine.dll and qtmedia...dll in /plugins/mediaservice

That removes the old error but unfortunately still no playback but a new error:
DirectShowPlayerService::doRender: Unresolved error code 0x80040266 ()

I will continue to investigate later...

**Comment by sfuchs79** [comment]
@bstoeger 
Getting the DLLs installed if afaik easy: Just one line here:
https://github.com/Subsurface-divelog/subsurface/blob/master/packaging/windows/mxe-based-build.sh#L222
Path is .../mediaservice

Your updated code now fails to build for Windows. For Travis and for me with same error - no need to copy it here, please have a look at the Travis log! ;-)

**Comment by sfuchs79** [comment]
@bstoeger 
Guess what?
Video playback in profile works! We need to discuss the details but at least it's not impossible.

**Comment by sfuchs79** [comment]
Here is the info how I fixed this one for me:
DirectShowPlayerService::doRender: Unresolved error code 0x80040266 ()

The related discussion I found:
https://bugreports.qt.io/browse/QTBUG-51692

What I then did is to install the "k lite codec pack". Not a very nice solution but as far as I read in the discussion it is really needed to install a proper codec because Qt won't use the wmf backend but only the DirectShow backend.

**Comment by bstoeger** [comment]
Gah - a few seconds after I pushed the previous changes I lost my internet connection. Thanks, Leipzig/Halle Airport. :/

Thank you very much @sfuchs79 for figuring this out. Unfortunately I have no idea what the consequences for subsurface are. Is Qt bundled with the Windows executable? Will it be possible to ship the needed codecs?

The offensive code should not be there anymore in my newest update. Though I guess an intermediate commit which needs a rather new compiler version is not acceptable, right?

The current state is still *very* rough, but perhaps you can have a look at it. Adding videos should now extract the first still. Also, loading images from the web should produce a thumbnail without switching dives.

The way this works is by doing event-driven IO. At first a "generic image" icon is shown. This is replaced by a thumbnail on success or by an "error" icon on failure. Stills are extracted with a "pipeline" through the main UI thread. It's a royal mess using the Qt signal/slot system and pretty brittle. Testing all failure modes (e.g. download a corrupted video from the web) will be a nightmare.

This means that currently we need two icons: "Not yet loaded" and "Failed loading", preferably in SVG? Also a marker placed on top of videos would be nice.

**Comment by sfuchs79** [comment]
> Thank you very much @sfuchs79 for figuring this out. Unfortunately I have no idea what the consequences for subsurface are. Is Qt bundled with the Windows executable? Will it be possible to ship the needed codecs?

For the moment don't worry too much about the codec thing! Maybe my Windows 10 installation was a kind of mess in terms of video codecs before installing the codec pack. The installer of the codec pack claimed that it had to fixup various broken things. I would wait for the feedback from other Windows users.

> The offensive code should not be there anymore in my newest update. Though I guess an intermediate commit which needs a rather new compiler version is not acceptable, right?

Don't know exactly how to answer this. If it would mean for example for me to recompile MXE with gcc6 or gcc7 support -> not a big fan. I once tried this and failed.

Some more comments:
- It would be right if you add a commit with the MXE build script change to your PR. See my comment above: Just add a line to copy ".../mediaservice" plugins. Otherwise any Windows user will struggle when trying to test this.
- A minor item: We already should thing about how to rename "Pictures" in the tab name, the dive list and the menu entries. Currently I vote for simply calling it "Media".
- I'll go to bed now and continue testing tomorrow... ;-)

**Comment by sfuchs79** [comment]
Ok, I did do another test:
- For me it compiles now again. But please look at Travis! There is some error coming from some side effect to linking that small smtk... tool.
- The functionality is already really impressing: Thumbnails work, drag&drop works, playback works,...
- Reading the file timestamp for video files (as a replacement for EXIF) is not implemented yet?
- There is one bad thing but I have to be very precise about this: I see some sporadic crashes. But not only with the latest version but they where already there with the one version before from today (the one which compiled). My feeling is that the crashes are NOT related to video playback itself. It may come from any of your more basic changes - some of the first commits. I have the feeling the crashes happen when I switch in the dive list between different dives with pictures attached. Crash backtrace attached...


subsurface.exe caused an Access Violation at location 0000000066B94B5F in module Qt5Core.dll Reading from location 0000000000000024.

Registers:
eax=00000000 ebx=00a2d4a4 ecx=66e44cb4 edx=00000001 esi=22736600 edi=277ee730
eip=66b94b5f esp=00a2d3f0 ebp=00a2d478 iopl=0         nv up ei pl nz na pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00210202

AddrPC   Params
66B94B5F 277EE730 00000005 6C0912A0  Qt5Core.dll!QObject::setUserData
66B95260 00A2D4EC 277EE8F8 00000000  Qt5Core.dll!QObject::disconnectImpl
66B9AF4A 6C00186F 00A2D520 00000008  Qt5Core.dll!QObject::~QObject
74517084 C7000000 02082444 C7000000  msvcrt.dll!_free
000C2444 C7000000 A0042444 896C0912
02082444 A0042444 896C0912 15FF240C
C7000000 896C0912 15FF240C 6C0CB690
A0042444 15FF240C 6C0CB690 C31CC483
896C0912 6C0CB690 C31CC483 26B48D90
15FF240C C31CC483 26B48D90 00000000
6C0CB690 26B48D90 00000000 8B2CEC83  Qt5Multimedia.dll!QMediaMetaData::Title
C31CC483 66B8E170 66B92530 66B8E170
66B9A260 66A72EC0 66A76820 66A74420  Qt5Core.dll!QObjectPrivate::moveToThread_helper
66A78570 66B78B60 669EF360 6697F270  Qt5Core.dll!QIODevice::setOpenMode
66B789A0 669E6EE0 669DE450 669DE5A0  Qt5Core.dll!QMetaObject::invokeMethod
669E4EE0 669DE450 669DE5A0 669E0440  Qt5Core.dll!QString::arg
669E6EE0 669DE5A0 669E0440 669DDE30  Qt5Core.dll!QStringRef::mid
669DE450 669E0440 669DDE30 6696F540  Qt5Core.dll!QString::indexOf
669DE5A0 669DDE30 6696F540 66BABB40  Qt5Core.dll!QString::remove
669E0440 6696F540 66BABB40 66BAC580  Qt5Core.dll!QString::startsWith
669DDE30 6D42FEB0 6D42FF00 6D42C600  Qt5Core.dll!operator==
6D46D8C0 76EFBA20 76EEA190 74815CA0  Qt5Network.dll!QNetworkConfiguration::bearerTypeName
7486D03F 76EEA190 74815CA0 74816620  KERNEL32.DLL!_AslHashFree@4
76EFBA1F 74815CA0 74816620 74816660  ntdll.dll!CountUTF8ToUnicode
76EEA18F 74816620 74816660 748166E0  ntdll.dll!LdrpGetFileSizeFromLoadAsDataTable
74815C9F 74816660 748166E0 74816750  KERNEL32.DLL!_QueryMemoryResourceNotificationStub@8
7481661F 748166E0 74816750 748167D0  KERNEL32.DLL!_SetThreadStackGuaranteeStub@4
7481665F 74816750 748167D0 74816930  KERNEL32.DLL!_SizeofResourceStub@8
748166DF 748167D0 74816930 74816970  KERNEL32.DLL!_SystemTimeToTzSpecificLocalTimeStub@12
7481674F 74816930 74816970 00000000  KERNEL32.DLL!_TlsFreeStub@4
748167CF 74816970 00000000 74526970  KERNEL32.DLL!_TzSpecificLocalTimeToSystemTimeStub@12
7481692F 00000000 74526970 74566E80  KERNEL32.DLL!_VirtualLockStub@8
7481696F 74526970 74566E80 74535C20  KERNEL32.DLL!_VirtualProtectExStub@20

**Comment by bstoeger** [comment]
Yes, this multi-threaded code, with objects belonging to different threads being passed through Qt's signal/slot-system, is very hairy. I fixed a bug, but that was in a new commit, so probably not the cause of your crash.

Is there any way to get line numbers with the backtrace? Especially the location of the `invokeMethod` call would be very interesting. I don't understand where all that string-handling stuff, `setUserData`, etc. comes from...?

**Comment by bstoeger** [comment]
> It would be right if you add a commit with the MXE build script change to your PR. See my comment above: Just add a line to copy ".../mediaservice" plugins. Otherwise any Windows user will struggle when trying to test this.

I think it would be best if you post such a patch with your Signed-Off line. I will then incorporate it into this PR.

**Comment by sfuchs79** [comment]
@bstoeger 
Can you please grab it from here:
https://github.com/sfuchs79/subsurface/tree/add_mediaservice_plugins

**Comment by sfuchs79** [comment]
> Yes, this multi-threaded code, with objects belonging to different threads being passed through Qt's signal/slot-system, is very hairy. I fixed a bug, but that was in a new commit, so probably not the cause of your crash.

Unfortunately the crash is still there.

> Is there any way to get line numbers with the backtrace? Especially the location of the invokeMethod call would be very interesting. I don't understand where all that string-handling stuff, setUserData, etc. comes from...?

I'll try to generate a debug build including debug Qt DLLs. Maybe this gives more detailed info.

**Comment by bstoeger** [comment]
Added your commit and it should now extract the timestamp from the file creation date. This looks like such a triviality that I wonder why this wasn't done previously? Any side effects that I'm missing?

I'm not happy about the EXIF code - it loads the whole video into memory just to fail afterwards. This will have to be fixed.

Still no progress on the crash - hopefully I find some time tomorrow to have a look at it. Unfortunately so far I'm unable to reproduce it. :(

**Comment by sfuchs79** [comment]
> Added your commit 

Nice, thanks! Going to remove my branch already again.

> and it should now extract the timestamp from the file creation date. This looks like such a triviality that I wonder why this wasn't done previously? Any side effects that I'm missing?

I don't know. I also won't expect anything harmful.

> I'm not happy about the EXIF code - it loads the whole video into memory just to fail afterwards. This will have to be fixed.

Yeah, especially because we still don't have a progress bar it would be nice to limit the situations where the UI doesn't react to a minimum. Maybe simply call the EXIF code for supported image formats only?

> Still no progress on the crash - hopefully I find some time tomorrow to have a look at it. Unfortunately so far I'm unable to reproduce it. :(

Also no progress on my side. Ugly thing: My MXE debug build crashes immediately on startup. I guess s.th. completely unrelated. You wanna have a look? But I won't post it here but I'm going to open a separate issue.

**Comment by bstoeger** [comment]
> My MXE debug build crashes immediately on startup. I guess s.th. completely unrelated.

It's very possible that it's related to this PR. On startup, the first dive is selected and the thumbnails are populated. I have experienced some crashes there with older versions of this PR.

**Comment by bstoeger** [comment]
Rebased and added a mark for flagging video thumbnails.

The thumbnail-extraction code is really scary. But I'm not sure what will be more painful: getting this work or including an external library such as OpenCV?

**Comment by bstoeger** [comment]
Refactored this to use only one `QMediaPlayer` and one `QAbstractVideoSurface` at a time. At least the out-of-memory errors are gone. Still, this behaves very erratically:

1) `present()` is called *after* receiving a state-change to stopped signal.
2) State is changed to stopped *before* `present()` is called.
3) Often, the message "Failed to start video surface due to main thread blocked." is shown.

I have no idea if I'm doing something wrong or if this whole Qt-media business is broken. I think I give up for now - this needs a Qt expert.

**Pull request closed without merging**
