### PR TITLE
Move filtering closer to the core

### PR DESCRIPTION
**Pull request by bstoeger**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

To avoid ProxyModel-Lasagna, Dirk suggested filtering the dives directly at the core. Indeed, the DiveTripModels have to handle filtering anyway. We hope that this helps in unifying the desktop and mobile models.

This is an attempt at doing so. It is only very lightly tested though, so it *will* break widely. Testing would be very welcome. Note that this is not as easy as one might think. The interesting parts are when modifying dives changes the filter-criterion; when whole trips are hidden and the interaction with the undo-system.

The main commit is admittedly a tad big and should probably be split up.

### Changes made:

1) Move filtering to the DiveTripModels.
2) Remove filtering from the MultiFilterProxyModel (which now has an inappropriate name, btw).
3) Remove some now unused code.

### Release note:

No.
### Documentation change:

No.
### Mentions:

@dirkhh @neolit123

### CODE REVIEW

**Comment by dirkhh** [comment]
Conceptual question. If a dive is hidden, then how does a change make it unhidden?
Maybe some undo or something? Just trying to figure out if we are making our lives too hard?
For example, wouldn't it be much easier to do this:
- connect to the "something changed in the divelist" signal
- remove filter and add filter with same criterion
- prosper

**Comment by bstoeger** [comment]
> Conceptual question. If a dive is hidden, then how does a change make it unhidden?
Maybe some undo or something?

Precisely.
1) Change buddy "A" to "B".
2) Filter for buddy "B".
3) Undo. <- dive has to disappear

Or:

1) Filter for buddy "A".
2) Change buddy "A" to "B" <- dive has to disappear
3) Undo <- dive has to appear

> remove filter and add filter with same criterion

I reckon you suggest to fully reload the filter after every change to dives? I'm not sure it is that simple, but I will think about it.

**Comment by bstoeger** [comment]
Also note, that's pretty much what the code attempts to do anyway:
```
	ShownChange shownChange = updateShown(dives);
	divesShown(trip, shownChange.newShown);
	divesHidden(trip, shownChange.newHidden);
```
For all changed dives, recalculate the filter and add if newly shown, remove if newly hidden. That's in principle the same as when the whole filter is reset, just limited to the changed dives.

That brings me to another complication when testing: tree vs flat mode. :-P

**Comment by dirkhh** [comment]
Here are some of the tests I tried (all on desktop, of course)
(1) tree view, filter by rating
- change rating of currently shown dive
-- dive list updates (dive is now hidden), including the totals for the trip
-- dive itself stays shown (it's debatable if that's a bug)
- undo
-- dive list updates
-- dive is still shown

(2) same thing in flat view (sort by date)
- same results

(3) tree view, filter by tag
- delete a dive that is shown
-- dive is deleted, count is updated, next dive is shown
- undo
- dive returns, counts are updated, un-deleted dive is selected

(4) filter for different tag which makes the deleted dive hidden
- undo / redo sequence
-- no visible changes, as it should be

(5) filter by temperature
- currently visible dive is one that gets hidden, but stays visible (same as above)
-- deleting that dives via redo now changes things so that the first visible dive is selected
-- undo keeps that visible dive selected (that seems like the correct behavior)

(6) now add filter by person
-- correct dives stay visible
- invert the filter
-- different dive becomes visible, but its trip isn't expanded in the dive list (that's a bug, but it seems like a corner case and not really an issue)

So by and large it seems like this is on the right track, @bstoeger

**Comment by dirkhh** [comment]
iOS builds are having timeout issues right now.
Funnily enough, in a completely different context I have been talking to GitHub management about some of the concerns around GitHub Actions that run on macOS environments (like the iOS builds) and I understand their pain.
Right now I'm selectively restarting these to ensure that we don't break iOS by mistake, but I realize that this may be an issue for a while

**Comment by bstoeger** [comment]
First of all, thanks for testing!

> dive itself stays shown (it's debatable if that's a bug)

Since we *do* hide dives when the filter is edited, I consider this as a bug. Should be fixed now.

> different dive becomes visible, but its trip isn't expanded in the dive list (that's a bug, but it seems like a corner case and not really an issue)

Yes, the whole trip-expansion business. I have to admit that I haven't really thought about it up to now.

**Comment by dirkhh** [comment]
Where are we with this? More testing needed? Consider for merging?

**Comment by bstoeger** [comment]
Depends on how important the trip-expansion is to you. Also, if you could double-check that the current dive is now set correctly, that would be great (I'm already quite tired for today).

**Comment by dirkhh** [comment]
not super important :-)
And yes,will test some more
Get some sleep

**Comment by bstoeger** [comment]
Added a small code-reshuffling commit: Loop in the actual filter code, not the model. This makes the way we filter more flexible (think fulltext index) and also is, arguably, more logically organized.

**Review by dirkhh — APPROVED** [review]
Did some more testing - I think this looks good.
If you feel this is ready to merge, please change the Subject. After that I'll read through the changes one more time (because I really did a poor job with reviews, lately) and then hopefully merge

**Comment by dirkhh** [comment]
I guess @bstoeger is enjoying a weekend with family... but I'm hesitant to merge this without him chiming in :-)

@atdotde , did you have a chance to test this? Anyone else?

**Comment by bstoeger** [comment]
Sorry - I was distracted. Merge in principle fine with me, I just improved the last commit. Therefore, let's wait for CI. If you have doubts concerning the last commit, feel free to leave it out. Thanks.

**Comment by dirkhh** [comment]
So this could already be merged in order to make #2625 smaller? Because I think this one is certainly fine...

**Comment by bstoeger** [comment]
> So this could already be merged in order to make #2625 smaller? Because I think this one is certainly fine...

It *is* somewhat scary, but yes - from my side it's ready to go.

**Pull request merged**
