### PR TITLE
Icons 3

### PR DESCRIPTION
**Pull request by merinsky**
Please do NOT merge this. This work in progress is RFC.

I don't consider these icons finished. Many of them are rather placeholders. I'm willing to improve them according to Subsurface developers and users comments. Pleae, give it a chance and tell me what you would like to improve.

Things to come:
* Fix and improve profile background image scaling.
* Use your current theme icons by default.
* More dive events have icon.

### CODE REVIEW

**Comment by sfuchs79** [comment]
@merinsky 
Could you please add a few screenshots showing the new look?
This would give everyone a hint how this finally could look like w/o the need to merge and build this.

**Comment by merinsky** [comment]
Up to this point, it is more about icons management than change of the look. Change of the look is done only because currently we don't have all icons in scalable format and our icons are a little bit messy.

**Comment by sfuchs79** [comment]
Ok, misunderstanding on my side...

**Comment by merinsky** [comment]
I appreciate your interest. It needs a little bit more work. After that, I will definitely post screenshots.

**Review by dirkhh — CHANGES_REQUESTED** [review]
NAK on this PR.
This mixes completely unrelated things into one PR:
- cleanup of icon use, removal of unused icons (I'm ok with that)
- change to the UI layout (that needs it's own PR, I want to see the before/after, and it requires a commit message that explains why this is better; in general the burden of proof goes up when making changes to something that a lot of people have used and have gotten used to, even if maybe it isn't ideal) 
- changes to the SVG, merging of icons: I see no reason to do that
- random reorganization of icons paths that are likely to break many of our platforms (and as the CI points out, already does break those)
- random renaming of icons for some random spec on the least interesting and relevant of our platforms
- introduction of new icons to replace existing ones (happy to look at those, but again, that is a separate PR with before and after picture and an explanation why this is better)

**Pull request closed without merging**
