### PR TITLE
Add a comment on building option -mobile

### PR DESCRIPTION
**Pull request by atdotde**
...to explain the difference between building the mobile
version to run on desktop and crossbuild for a mobile OS.

This should address #1247

Signed-off-by: Robert C. Helling <helling@atdotde.de>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [x] Documentation change
- [ ] Language translation

### CODE REVIEW

**Comment by janiversen** [comment]
Adding documentation is always a good thing, just wonder how many new developers read comments in build.sh. Added PR #1249, to (also) put the information in INSTALL

**Comment by atdotde** [comment]
How did you find out about the -mobile option if not reading build.sh?

**Comment by janiversen** [comment]
Well I was actually told, when I started to make my dev. environment. But does it hurt to put it in text ?

**Comment by mfbernardes** [comment]
Didn’t I point directly to packaging/ios?

**Comment by janiversen** [comment]
You did, which helped me a lot, but that was not the only info. I have been trying to understand the difference for a while (documented as comments in some of my PR as well as mails), but it was not until now, that I understood the difference. 

I have absolutely no problem with this PR and recommend it to be merged.

I personally would have preferred it to be in INSTALL as well, assuming if I get confused others can as well, but abandoned in respects of the comments received.

**Pull request merged**
