### PR TITLE
Cleanup of android build infrastructure

### PR DESCRIPTION
**Pull request by glance-**
- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

This is a bunch of small cleanups of the android build infrastructure.

### CODE REVIEW

**Comment by glance-** [comment]
It was basically newer cmake/linker which caused things to behave differently. Now when we use the right linker it behaves correctly, no matter cmake version.

**Comment by janiversen** [comment]
I just tested your pr against mine, and yes there are conflicts but they are easy to solve, so not a real problem.

**Review by neolit123 — APPROVED** [review]
great, thanks @glance- 
at some point we need to get clang and the latest NDK working too.

**Comment by dirkhh** [comment]
@janiversen I'll merge this one and then look at maybe finishing yours?

**Pull request merged**
