### PR TITLE
RFC: Move and split match() function

### PR DESCRIPTION
**Pull request by bstoeger**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

This is a tiny first step to make the parser reentrant. Some match-functions have side-effects and therefore need to be passed parser-context. But they are the exception. Therefore split out the name comparison for these cases, whereas the old `match()` function can still be used for the common case.
### Changes made:

1) Move `match()` to `parse-xml.c`. It seems awfully XML specific
2) Split `match()` in two parts. One only for comparison, the other for comparison and calling the callback for matches.
### Release note:

No.
### Documentation change:

No.

### CODE REVIEW

**Comment by dirkhh** [comment]
I think this looks right, but this is @torvalds code, so I'll ping him on email...

**Review by torvalds — DISMISSED** [review]
No, this is wrong. 

The reason that plen parameter exists is that the pattern is basically always a constant string, and doing the strlen() in the MATCH() macro means that it ends up being just a constant integer at compile time. 

Moving the 'strlen()' into the called function makes the compiler now generate a 'strlen()' call, which basically makes the matching cost about twice as high.

The XML parsing is slow as is - and yes, it's noticeable if you have thousands of dives.

Of course, if you have thousands of dives, you hopefully don't use the XML format and instead use the git format, but still..

**Comment by bstoeger** [comment]
> The reason that plen parameter exists is that the pattern is basically always a constant string, and doing the strlen() in the MATCH() macro means that it ends up being just a constant integer at compile time.

Ok, I understand. The reason I changed the code is that it looked fishy [access beyond end of name], but now I see that name is inside a `static buffer[MAXNAME]`, so I guess it is fine.

> The XML parsing is slow as is - and yes, it's noticeable if you have thousands of dives.

Is there a (realistic) thousands of dives XML for testing purposes? Not that I don't trust you - I'm just interested in how much these kind of changes affect the parse time.

I will close this for now.

**Comment by dirkhh** [comment]
I created a 3000 dive file a while ago... I'm traveling and don't have it on this machine... but it should be easy enough to anonymize a file like that.
I remember one user who had more than 7000 dives in his dive file and who had performance issues with parsing - some of our optimizations followed his reports...

**Comment by bstoeger** [comment]
> I created a 3000 dive file a while ago... I'm traveling and don't have it on this machine... but it should be easy enough to anonymize a file like that.

If that's not too much work for you - that would be great as it would allow me to performance-test my changes to the parser. But no hurry - at the moment new places to work on pop up at a much faster rate than I'm able to address them. :( Keeping this PR open as a reminder.

**Comment by henrik242** [comment]
> I created a 3000 dive file a while ago... I'm traveling and don't have it on this machine... but it should be easy enough to anonymize a file like that.

That could be perfect for a unit test: Make it fail if parsing takes more than x seconds.

**Comment by dirkhh** [comment]
Performance on Travis isn't consistent... so I'm not quite sure how we'd do this and have it be a reasonable test. I guess I'll have to play with that and find out how big the variability is...
But overall that's a great idea @henrik242  :-)

**Comment by bstoeger** [comment]
Harumpf. I made a divelog with 10 000 dives by simple concatenation and when I try to open it I get a `SIGKILL`. I reckon that means out of memory? That's inacceptable. It's not like 10 000 is some outrageous number...!?

**Comment by dirkhh** [comment]
I am in the process of making an anonymized 2000 dive dive log available for testing. This is based on a real dive log so will likely present rather useful test data. The problem is that even compressed it's almost 7MB, so I'm not sure I want to have this in our main repo. Right now I'm thinking of having a test data repo that cleverly makes that same data available both as .ssrf file and as git storage (that way we can test "flavors").
I am going to see if I can push this a lot further in size without too much additional effort. I'm surprised that 10000 dives would already cause us to run out of memory on a modern system...

**Comment by bstoeger** [comment]
Systematic performance testing is a good idea - but let's better wait for @dirkhh [or other person with real-world data] to come up with a sensible dive log. I just concatenated the same dives a few hundreds of times, so it is no good for actual testing. This is only useful for a very silly micro-benchmark.

In any case, I quickly produced a few numbers with
```
static void test_parse_file()
{
        clear_dive_file_data();
        struct timeval tv;
        gettimeofday(&tv, NULL);
        int64_t micro_before = tv.tv_sec*1000000LL+tv.tv_usec;
        parse_file("dummy5.xml", &dive_table);
        gettimeofday(&tv, NULL);
        int64_t micro_after = tv.tv_sec*1000000LL+tv.tv_usec;
        printf("parse_file(): %lf\n", (micro_after-micro_before) / 1000.0);
}
```
on a 2600 dives xml.

This PR gives:
```
parse_file(): 6409.373000
parse_file(): 6665.275000
parse_file(): 6634.164000
parse_file(): 6612.200000
parse_file(): 6620.620000
parse_file(): 6632.807000
parse_file(): 6614.933000
parse_file(): 6625.508000
parse_file(): 6630.469000
parse_file(): 6639.583000
```

vs. master:

```
parse_file(): 6643.414000
parse_file(): 7053.812000
parse_file(): 6807.438000
parse_file(): 6817.118000
parse_file(): 6838.187000
parse_file(): 6860.524000
parse_file(): 6824.466000
parse_file(): 6858.325000
parse_file(): 6840.823000
parse_file(): 6848.964000
```
Times are in msec. Note how this PR is actually 3% *faster* than current master [not perfectly comparable, since in master we can parse into arbitrary table]. So moving the `match()` function to the same translation unit as the caller, thus allowing the compiler to inline it, has more positive impact than removing the `plen` argument has negative impact.

Now I will try to move the thing in the same translation unit and keep the `plen` parameter.

**Comment by bstoeger** [comment]
OK, just moving the `match()` function (and not splitting into name function as in this PR):
```
parse_file(): 6453.011000
parse_file(): 6813.681000
parse_file(): 6660.701000
parse_file(): 6567.585000
parse_file(): 6575.625000
parse_file(): 6591.155000
parse_file(): 6571.472000
parse_file(): 6615.782000
parse_file(): 6594.871000
parse_file(): 6689.932000
```
Average this PR: 6608.5
Average master with function moved to same translation unit: 6613.4

That seems to be inside measurement-error.

So how to proceed? If there is interest I can try to optimize the name-parsing, but I doubt that it's more than a few %.

**Comment by dirkhh** [comment]
Cool. I'm about ready to give you somewhat more 'real' data... slow network here at the hotel :-(
If we can verify this with realistic data, let's poke Linus again :-)

**Comment by dirkhh** [comment]
See my email on the mailing list: https://github.com/Subsurface-divelog/large-anonymous-sample-data
Have fun with that :-)

**Comment by bstoeger** [comment]
That file gives me a too large variance for being of any use. With master I get for a 3-iteration loop:
```
parse_file(): 309542.222000
parse_file(): 219133.808000
parse_file(): 279553.564000
```
I guess it depends on when my laptop decides to go in some sort of energy-saving mode..

**Comment by dirkhh** [comment]
>That file gives me a too large variance for being of any use. With
>master I get for a 3-iteration loop:
>
>parse_file(): 309542.222000
>parse_file(): 219133.808000
>parse_file(): 279553.564000

Wait. What? Parsing this file takes maybe 11 or 12 seconds on mine, I think...
200-310 seconds? I need to redo my testing...

>I guess it depends on when my laptop decides to go in some sort of
>energy-saving mode..

What are the specs of your laptop?

**Comment by bstoeger** [comment]
Heh.. I guess it's thrashing. That would explain the volatility of the results and why the fan doesn't run. I will try on a freshly rebooted machine.

Specs:
```
$ sudo lshw -short
[sudo] password for bs: 
H/W path         Device     Class          Description
======================================================
                            system         W840SU Series (Not Applicable)
/0                          bus            W840SU Series
/0/0                        memory         64KiB BIOS
/0/14                       processor      Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
/0/14/15                    memory         512KiB L2 cache
/0/14/16                    memory         128KiB L1 cache
/0/14/17                    memory         3MiB L3 cache
/0/18                       memory         4GiB System Memory
/0/18/0                     memory         DIMM [empty]
/0/18/1                     memory         DIMM [empty]
/0/18/2                     memory         4GiB SODIMM DDR3 Synchronous 1600 MHz (0.6 ns)
/0/18/3                     memory         DIMM [empty]
/0/100                      bridge         Haswell-ULT DRAM Controller
/0/100/2                    display        Haswell-ULT Integrated Graphics Controller
/0/100/3                    multimedia     Haswell-ULT HD Audio Controller
/0/100/14                   bus            8 Series USB xHCI HC
/0/100/14/0      usb2       bus            xHCI Host Controller
/0/100/14/0/5               communication  Bluetooth wireless interface
/0/100/14/1      usb3       bus            xHCI Host Controller
/0/100/16                   communication  8 Series HECI #0
/0/100/1b                   multimedia     8 Series HD Audio Controller
/0/100/1c                   bridge         8 Series PCI Express Root Port 1
/0/100/1c.2                 bridge         8 Series PCI Express Root Port 3
/0/100/1c.2/0    wlp2s0     network        Wireless 7260
/0/100/1c.3                 bridge         8 Series PCI Express Root Port 4
/0/100/1c.3/0               generic        RTL8411B PCI Express Card Reader
/0/100/1c.3/0.1  enp3s0f1   network        RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
/0/100/1d                   bus            8 Series USB EHCI #1
/0/100/1d/1      usb1       bus            EHCI Host Controller
/0/100/1d/1/1               bus            USB hub
/0/100/1f                   bridge         8 Series LPC Controller
/0/100/1f.2                 storage        8 Series SATA Controller 1 [AHCI mode]
/0/100/1f.3                 bus            8 Series SMBus Controller
/0/1             scsi0      storage        
/0/1/0.0.0       /dev/sda   disk           250GB Samsung SSD 850
/0/1/0.0.0/1     /dev/sda1  volume         228GiB EXT4 volume
/0/1/0.0.0/2     /dev/sda2  volume         3987MiB Extended partition
/0/1/0.0.0/2/5   /dev/sda5  volume         3987MiB Linux swap volume
```

**Comment by bstoeger** [comment]
Large file still thrashing. :(

When cutting out the first 1 000 000 lines of the XML, I get:
```
master:
parse_file(): 3137.065000
parse_file(): 2876.695000
parse_file(): 2875.133000
parse_file(): 2883.446000
parse_file(): 2862.299000
parse_file(): 2895.273000
parse_file(): 2916.774000
parse_file(): 2901.471000
parse_file(): 2920.576000
parse_file(): 2939.794000

master, match() moved into parse-xml.c:
parse_file(): 3111.426000
parse_file(): 2866.961000
parse_file(): 2817.796000
parse_file(): 2805.461000
parse_file(): 2849.112000
parse_file(): 2814.476000
parse_file(): 2840.180000
parse_file(): 2827.660000
parse_file(): 2892.215000
parse_file(): 2862.881000

branch parse2, rebased on master:
parse_file(): 3053.937000
parse_file(): 2750.070000
parse_file(): 2741.009000
parse_file(): 2749.121000
parse_file(): 2768.907000
parse_file(): 2755.807000
parse_file(): 2794.451000
parse_file(): 2765.955000
parse_file(): 2816.375000
parse_file(): 2807.887000
```

Average without the first run (always slower - "cold" cache?):
```
master: 2896.8 (±0 %)
master, match() moved into parse-xml.c: 2841.9 (-1.9 %)
branch parse2, rebased on master: 2772.2 (-4.3 %)
```

So nothing really noticeable, but still hmmmm...??

**Comment by dirkhh** [comment]
Cool. Let's see what Linus thinks now 🙄
I guess the big difference is that my laptop has 32G memory 
I still would like to make sure this works well on a 4G machine... Easy enough to simulate with a VM.

**Comment by bstoeger** [comment]
> Average without the first run (always slower - "cold" cache?):

Another plausible explanation: it doesn't have to `realloc()` the dive table once it has the appropriate size.

**Comment by torvalds** [comment]
Numbers talk, so hey, if it speeds things up then go right ahead.

**Comment by dirkhh** [comment]
with that ringing endorsement... I'll dismiss @torvalds review and ask... @bstoeger - is this still good to go? Or any modifications before I merge?

**Comment by bstoeger** [comment]
I rebased on master and it still loads my divelog, so I think it's good to go.

**Pull request merged**
