### PR TITLE
(2) update plannerShared and correct bug in desktop version.

### PR DESCRIPTION
**Pull request by janiversen**
### Describe the pull request:

- [ x] Bug fix
- [ ] Functional change
- [ ] New feature
- [x ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

There was an error in the desktop version. setting of ascent/descent rates was connected both
to diveplannermodel and plannershared, both doing the same conversion and saving the
calculated value in qPrefDivePlanner. Removed second connect.

Diveplannermodel already contained set_ functions for ascent/descent rates, with conversion from screen values. Added get functions also with conversions. This allows the conversions to be in 1
place (for both desktop and mobile version), which ensures there are no differences.

Cleaned plannerShared and updated QML to use backend.

This conversion was possible partly due to the new pure interface.

### CODE REVIEW

**Comment by dirkhh** [comment]
so this looks like it was supposed to be the next in the series?
Can you confirm? Or should I look at something else, next.
The conflicts stem from the way I merged things, that's no big deal and easy to deal with when I merge this locally - so no need for you to deal with rebasing - just let me know where to look next.

**Comment by janiversen** [comment]
Yes this is the second in the series. I started numbering the (1) .... just to make life easier for you.

**Comment by janiversen** [comment]
Please observe there is a rename, so please start with (1) then (2) .. (3) or of course (3) includes the 2 others.

**Comment by janiversen** [comment]
it is late here....I see you already did (1) and (3) still sits on my disk because I am not satisfied with some of the commits.

**Comment by dirkhh** [comment]
manually merged

**Pull request closed without merging**
