### PR TITLE
fix bug in MapItemView and add new markers

### PR DESCRIPTION
**Pull request by neolit123**
### Describe the pull request:

- [x] Bug fix
- [x] Functional change
- [ ] New feature
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

**First patch:**

The QML map uses MapItemView. MapItemView needs a delagate
in the form of a MapQuickItem. The MapQuickItem needs a
'sourceItem' which would be used as the visual (e.g. marker)
on the map.

If the root sourceItem is of type Item, the marker becomes
non-clickable. If the root sourceItem is an Image, the clicks
work.

This patch removes the root Item, which makes the code
less organized, but at the same time it fixes the bug.

Bug reproduced on the following Qt versions on Ubuntu:
5.5.x, 5.7.x

Bug cannot be reproduced on Qt 5.9.x on Windows.

**The two other patches**

- Update the "dark" dive location flag to be slightly darker
- Add and use a new de-saturated marker when editing a dive location

### Changes made:
1) remove Item container from QML file
2) updated a PNG file
3) added a new PNG file and make use of it in QML

### Related issues:

http://lists.subsurface-divelog.org/pipermail/subsurface/2017-October/030282.html

### Additional information:

Seems like a bug in older Qt, but the strange thing is that it worked for me on Ubuntu a couple of days ago. The QML hasn't been touched recently, so it seems that something else might have triggered that...

### Mentions:
@sfuchs79 @willemferguson @dirkhh  

please test, so that we can include this in the next version...

### CODE REVIEW

**Comment by neolit123** [comment]
ready to merge.
confirmed by @willemferguson and @sfuchs79 that it works in the same linked ML thread.

separate issues were reported.

**Comment by neolit123** [comment]
added two new patches.
first post updated to reflect the PR changes.

**Comment by dirkhh** [comment]
LGTM

**Comment by sfuchs79** [comment]
The new markers are nice and a real improvement!

**Pull request merged**
