### PR TITLE
Add HP117 to the cylinder list

### PR DESCRIPTION
**Pull request by briangweber**
Reported-by: Brian Weber
Signed-off-by: weber311@gmail.com

Just got an HP117 and wanted to add it for my own convenience.

### CODE REVIEW

**Comment by neolit123** [comment]
hello,
for pull requests to be accepted they need to be submitted to the mailing list.
you can also send this change as a single patch.
thanks

**Comment by briangweber** [comment]
OK - so just email the mailing list with a description of the change and a patch file?

**Comment by neolit123** [comment]
yes, you can have the patch as an email attachment.

the patch format:

```
Title
Description

Reported-by: ...
Signed-off-by: ...
```

**Comment by neolit123** [comment]
it seems to make a white-space change at this line. make sure you exclude that:

```
+// Clang has a bug on zero-initialization of C structs.
```

thanks

**Comment by Subsurface-divelog** [comment]
this was applied as a patch (of course, ironically, now I have finally come around to the conclusion that I'll make it easier for people if I accept pull requests...)

**Pull request closed without merging**
