### PR TITLE
New mobile divelist

### PR DESCRIPTION
**Pull request by dirkhh**
### Describe the pull request:

- [X] Bug fix
- [X] Functional change
- [X] New feature
- [X] Code cleanup

### Pull request long description:

Yeah, this is a bit hefty... the result of four months of work - most of the credit for the hard stuff goes to @bstoeger - I did the easy things and kept annoying him

### Changes made:

1) implement new models for the mobile dive list that use the same base models as desktop
2) implement a new dive list on top of that
3) fix dive edits, etc
4) first part of real undo support for mobile
5) first glimpse at the context menu

### Related issues:

This fixes many, many issues in the current version.
Significant performance improvement of the dive list.
No more (knock on wood) issues with the dive list getting messed up after edits, deletes, or downloads from dive computers
Better filter

### Release note:

There are a couple of entries

### Documentation change:

Yes, this will require changes to the user manual including new pictures. There will be a follow-up PR that brings in a lot more of dive list management features (moving dives between trips for example), it would make sense to wait with the documentation update until that is in as well, but I of course need to flag that yes, this needs documentation updates.

### Mentions:

@bstoeger @willemferguson @atdotde

### CODE REVIEW

**Comment by dirkhh** [comment]
oops, never built this on iOS before it turns out... force push coming up :-)

**Comment by bstoeger** [comment]
Resolved the conflict in case that's what you were waiting for...?

**Comment by bstoeger** [comment]
...and fixed a typo in a commit message...

**Comment by dirkhh** [comment]
this has been manually merged

**Pull request closed without merging**
