### PR TITLE
Uemis: remove trip deletion on dive deletion [+additional minor cleanups]

### PR DESCRIPTION
**Pull request by bstoeger**
Since ff9506b21bbb9910256841dcb577bcb2e19047e8 the downloaders don't
add dives to a new trip, but the import code does. Remove the
code in the Uemis downloader that would remove a dive from the trip.
The code has been broken recently anyway (instead of testing for trip,
it tested for the notrip flag, which make no sense whatsoever).

Signed-off-by: Berthold Stoeger <bstoeger@mail.tuwien.ac.at>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

A tiny cleanup that fixes a fallout of the import-undo code: The downloaders don't add dives to trips anymore, so there is no point in the uemis downloader removing a dive from a trip, should the dive be deleted.

### Changes made:

1) Remove (hopefully) dead code.
### Release note:

No.
### Documentation change:

No.

### CODE REVIEW

**Comment by bstoeger** [comment]
Added a further small cleanup: remove an unnecessary struct field.

**Comment by bstoeger** [comment]
And another one.

**Comment by bstoeger** [comment]
...and another one. Starting to wonder if these should be squashed..? @dirkhh: feel free to squash on commit.

**Review by dirkhh — APPROVED** [review]
All good, all unrelated. Merging as is.

**Pull request merged**
