### PR TITLE
build-system: add check for tar files in get-dep-lib

### PR DESCRIPTION
**Pull request by janiversen**
Complemented the git check with a similar tar check.
check if the correct download file is present if not download and expand it

Signed-off-by: Jan Iversen <jani@apache.org>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [x ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

@mfbernardes made a nice enhancement of get-dep-lib.sh, this PR completes it by
also handling tar files.

It is checked that the lib<foo><version> is present in src/ if not it is downloaded and expanded

### CODE REVIEW

**Comment by mfbernardes** [comment]
I have a different approach for this at #1392.

**Comment by dirkhh** [comment]
I like #1392 @mfbernardes did - except that something is wrong with ftdi - see the Android Travis failure...

**Comment by janiversen** [comment]
No hard feeling here, if you prefer that. #1392 is nice because it makes a function, but my patch does without an extra file. Best thing would be if @mfbernardes would use the tar file test I do.

**Comment by janiversen** [comment]
Duplicate to #1392, which uses a better approach (functions)

**Pull request closed without merging**
