### PR TITLE
core: qPref, remove inline and ; for inline functions

### PR DESCRIPTION
**Pull request by janiversen**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

I would have preferred to wait with this, since it affects all the branches (one for each non-merged class) that are being updated.

Now its done, but please bear over with me if I forget to remove it in one of the next PR in this restructuring series.

### CODE REVIEW

**Comment by janiversen** [comment]
@dirkhh I am currently trying to understand the reasoning for some strange structs, like e.g. depth_t

I can only see disadvantages by having it in a struct (you need to address the variable within), would you be against converting these to a typedef, which seems to provide the same type of security against accidential mixing types ?

**Comment by dirkhh** [comment]
changing this would be a MASSIVE change to the code base for no actual benefit.
This is a very common way to ensure in C that you handle data structures correctly.
I recommend against trying to change this.

**Comment by dirkhh** [comment]
in C code with a decent compiler it doesn't

**Review by bstoeger — APPROVED** [review]

**Comment by bstoeger** [comment]
It depends on the structure layout. On my system
```
struct test2 {
    int16_t t1;
    int16_t t3;
    int32_t t2;
};
```
is 8 bytes, whereas
```
struct test1 {
    int16_t t1;
    int32_t t2;
    int16_t t3;
};
```
is 12 bytes.

But since C programmers usually are low-level programmers I reckon that they have though about this.

**Comment by dirkhh** [comment]
which is why our struct entries used to be carefully ordered.
Of course, since, a few C++ programmers have made everything better by ordering them logically and then alphabetically, types be darned. And a lazy maintainer accepted those changes instead of arguing byte counts...

**Pull request merged**
