### PR TITLE
cleanup: break out event-related code into event.[c|h]

### PR DESCRIPTION
**Pull request by bstoeger**
In an effort to reduce the size of dive.h and dive.c, break out
the event related functions. Moreover event-names were handled
by the profile-code, collect that also in the new source files.

Signed-off-by: Berthold Stoeger <bstoeger@mail.tuwien.ac.at>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

More dive.c shrinking - see commit message.

### Changes made:

1) Move event functions from dive.c and profile.c to new event.c source file.

### CODE REVIEW

**Comment by bstoeger** [comment]
...and more include reshuffling...

**Comment by dirkhh** [comment]
I'm happy that the new test setup shows us why this is failing. The first check to see if this is a remote repo fails in unexpected ways. I need to figure out what to do when that happens, but this is much more encouraging then other failure modes I was worried about.

**Review by dirkhh — APPROVED** [review]
excellent cleanups. they will mess with my "muscle memory" of where to find stuff, but that's ok. `git grep` is my friend. But I really appreciate that the result is more logical and more structured.

**Comment by bstoeger** [comment]
Attention - some more header-reshuffling incoming.

**Comment by dirkhh** [comment]
I'll hold back on merging then :-)

**Review by dirkhh — APPROVED** [review]
lgtm

**Comment by dirkhh** [comment]
merged locally

**Pull request closed without merging**
