### PR TITLE
Update android build

### PR DESCRIPTION
**Pull request by dirkhh**
### Describe the pull request:

- [x] Build system change

### Pull request long description:

This does a few small tweaks to our Android build.
- update to Qt 5.13.2 (but not Qt 5.14 - which is a disaster for Android)
- different method of installing Qt
- no longer use a Docker image built via GitHub as that results in a much bigger image

The biggest outcome is a Docker image that's 1.1G smaller (20%) and that hopefully will no longer cause our Android CI builds to all fail.

### CODE REVIEW

**Comment by dirkhh** [comment]
Eh - forgot to disable the on GitHub build of the Docker image. Which promptly failed...

**Comment by dirkhh** [comment]
Finally.
Now I need to go back and fix the Docker container so I no longer need the stupid hacks in the .yml, rev the versions, and start this whole thing again.
Oh how I LOVE, LOVE, LOVE working on these things. They are so productive and so totally not a complete and utter waste of time...
:shrug:

**Comment by dirkhh** [comment]
manually merged

**Comment by glance-** [comment]
I can't find install-qt.sh , did you forgot to add it?

**Comment by dirkhh** [comment]
> On Apr 27, 2020, at 12:48 AM, Anton Lundin <notifications@github.com> wrote:
> 
> 
> I can't find install-qt.sh , did you forgot to add it?
> 
> 

That does seem like something I'd do... I'll add it

/D

**Pull request closed without merging**
