### PR TITLE
Split dive computer into distinct dive

### PR DESCRIPTION
**Pull request by bstoeger**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [x] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

This is a first stab at implementing splitting out of dive computer. I'm not a fan of this extreme code-reuse by sub classing, but it was the most efficient thing to do.

Moreover it turned out that saving the insertion index in the undo-command is quite painful. This premature optimization should be removed in a clean-up commit. But only after the huge undo changes!

This is based on code by @torvalds.

### Changes made:

1) Implement splitting out of dive computer.

### Release note:

Done.
### Documentation change:

Probably, yes...?
### Mentions:

@torvalds

### CODE REVIEW

**Comment by bstoeger** [comment]
Currently, the split dives are in random order (based on the generated id). This raises the question: should the dives be sorted by dive-computers? For example alphabetically?

**Review by dirkhh — APPROVED** [review]
The expected density of code... but I think I got all the parts and they seem to look good.
To get a review from @torvalds you need to ping him on email - for somewhat obvious reasons he has GitHub notifications turned off...

**Comment by torvalds** [comment]
Looks all fine - but I'm not really competent to judge the subclassing. But sharing code is good.

**Comment by dirkhh** [comment]
OK, I'll merge this locally to deal with CHANGELOG.md

**Pull request closed without merging**
