### PR TITLE
don't try to create a version on pull requests

### PR DESCRIPTION
**Pull request by dirkhh**
The necessary keys to do so aren't available (and of course we don't try to post a release on pull requests, anyway).

### Describe the pull request:

- [x] Bug fix
- [x] Build system change

### Pull request long description:

That was a silly oversight on my part.

### CODE REVIEW

**Comment by dirkhh** [comment]
I haven't looked at the AppImage in years... @probonopd - hate to ping you, but it's highly likely that you'll be 10x faster telling us what's going on here than one of us trying to figure it out the hard way...

**Comment by probonopd** [comment]
@dirkhh happy to help. Looks like the AppImage is created successfully but a subsequent step fails.

https://github.com/subsurface/subsurface/actions/runs/7225153956/job/19687975458#step:6:32

> ##[debug]Running JavaScript Action with default external tool: node20
> __e/node20/bin/node: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /__e/node20/bin/node)

This looks to me like one of the GitHub actions, `actions/upload-artifact@master`, is using a binary of `node` that was built on a system newer than the one it is being run on.

Looking into it now.

**Comment by probonopd** [comment]
Changing
https://github.com/subsurface/subsurface/actions/runs/7225153956/workflow#L38
to `uses: actions/upload-artifact@v3` fixes this.

**Comment by dirkhh** [comment]
Thank you so much!
I really appreciate the instant support!

**Comment by dirkhh** [comment]
I have updated this PR accordingly :)

**Review by mikeller — APPROVED** [review]

**Pull request merged**
