### PR TITLE
Change resolution of fN2, fHe from 0.01% to 0.1% in plannernotes.c

### PR DESCRIPTION
**Pull request by willemferguson**
In icd information table of planner output:
Resolution of 0.01% is too fine for gas percentages that are
normally measured in full percent values. Change the resolution
of gas fractions to 0.1%.

Signed-off-by: Willem Ferguson <willemferguson@zoology.up.ac.za>

### Describe the pull request:

- [ ] Bug fix
- [x] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### CODE REVIEW

**Comment by sfuchs79** [comment]
Yep, that's exactly how I think it should be 👍

**Comment by RickMWalsh** [comment]
The proposed change is in the right direction but I'm a bit concerned that adopting a precision of 0.1 is giving false confidence in a crude rule if thumb? Gas input is in whole percentages, so why not the delta-fraction?

**Comment by willemferguson** [comment]
Rick, I perfectly understand your point of view. But keep in mind for oxygen, Max PO2 is considered as 1.4 or 1.6. (i.e. a reasonably high precision). For nitrogen, the Workman/Bühlmann M-line has highly precise coefficients even though it is also a subjective criterion. For that reason I propose that we keep it as is. ok?

**Comment by atdotde** [comment]
I would second @RickMWalsh: It's about relative precision. For partial pressures, one digit after the decimal point is about 7%, that's fine (as for OC when blending cylinders that corresponds to 10ths of bar. This is something one should get right. But for gas fractions, the relative error is much smaller and even our UI does do allow to enter fractions of a percent (and I have never seen a diver tasing about EAN30.3 for example). So (even when we internally treat these number as per mille), they are always integer percent and so are their differences. Even if we print the additional digit, it will always be 0.

For the deco calculations, the tissue partial pressures need a lot of precision, since we keep adding very small amounts (and that often) and would otherwise totally screw up the final sum. I agree that the a and b coefficients have far too many digits (in particular taking into account how they were initially measured). But there, I would say we keep them for historical reasons and also since they don't hurt: They are never presented to the user and are only used internally to compare pressures (and buy keeping them as in the literature we also make sure we reproduce know results even with rounding).

**Comment by willemferguson** [comment]
Where I was trained, we take icd seriously. If the rule-of-fifths requires a maximal deltaN2 of 3.6% and my deltaN2 is 4.1%, I want to know the exact magnitude of these differences. If everything is rounded to the nearest percent, then I am compliant. Taken to one decimal, I am not compliant. The expectation is that one applies exactly the same diligence in all aspects of dive safety, whether it is in deco depths and timing, or whether it is in respect to gas changes. The majority of these rules are arbitrary, but one cannot be interpreted in a more arbitrary way than another. A 0.1% gas difference may very well constitute 5% of the maximal degree of deltaN2 before icd-related decompression sickness. Who is prepared to specify the maximal safety margin *above* max-deltaN2 before icd is highly likely?  People get injured by not taking these things seriously. I have some literature on South African icd-related DCS and I will send that to Robert when I manage to get my hands on it. I personally feel so serious about the issue that, if you guys decrease the resolution of the icd calculations, I will keep my own private branch that satisfies my own requirements.

My suggestion is, let's agree for the moment, to reduce the resolution to 0.1 so that it does not stay at 0.01. Pending further discussions we can then decide on a more long term approach. Does this make sense at all?

**Comment by janmulder** [comment]
> Where I was trained, we take icd seriously. 

Interestingly, where I was trained we hardly discussed this subject. Assumed to be a non-issue when diving standard gasses. I only dive CCR now (for TX depths), but I checked a few dives of mine during my OC TX period. And to my surprise, a 18/45 switch to EAN50 at 21m is now an ICD warning. And let me say that I did this switch hundreds of time.

Simple: it can't both not be right.

**Comment by willemferguson** [comment]
I have no problem with this. We all know that any dive malady (there are at least a dozen of them) is largely dependent on the individual diver (often on the state of the diver during a specific dive). Perhaps you are more robust than many other divers in this respect. The question is: would this be a totally safe gas switch for ALL divers? We have no way of knowing. Therefore rather err on the cautious side.

**Comment by janmulder** [comment]
I have no problem with this either, but I do not believe the 1:5 rule of thumb is relevant to me, so it clutters the profile with red exclamation marks for non-issues. For example, like Anton already said on the mailing list, there are more ways calculate ICD risk (like the one used in V-Planner/Multideco). That rule simply accepts my 18/45 to EAN50 switches, which is more in line with what I see in the field.

This is a nicely applicable post by Simon Mitchell: https://www.scubaboard.com/community/threads/icd-and-switch-to-nx38-from-normoxic-trimix.498748/page-6#post-7312650

**Comment by willemferguson** [comment]
I think we have now come to the core of the issue. Funnily enough, I was not aware of warning icons on my profile until you mentioned it and I saw the red exclamation marks on the gas change icons. I would strongly prefer these to be removed. 

We need to treat the deltaN2 values in exactly the same way as a PO2 warning. I almost always have PO2 warnings, because I plan on PO2=1.6 (or close to it) at each deco gas change, this being standard practice in our group. A PO2 of 1.62 does not generate a red exclamation mark on the profile, hopefully because in real life, slight excess of 1.6 in deco frequently occurs and deco with oxygen is mostly calculated with PO2 at 1.6 = 6m.  Deco with oxygen in the sea at 6m gives PO2=1.62. I do not need a red exclamation for that. In a similar way I often slightly exceed the fifth-rule in planning because I have to juggle the gases for 100% deco gas redundancy (i.e. knock out any individual deco cylinder and you can still safely do the ascent on your own within deco and icd limits). The important point is that, if we do this in planning, we just need to *be aware* then we are exceeding the 1.6 PO2 limit or the icd limit. That is the essential function of a good dive planning program. We may adjust the dive plan on this basis or we may decide that the warning reflects a risk that minimises other risks. Multideco is quite primitive in this sense because one has to specify arbitrary maxdPHe and maxdPN2, but the significance of dPHe of 1.2 bar at 20m is vastly different from at 70m.

But to have exclamation marks on the profile is not promoting what the warning messages are for.

I am aware of Simon Mitchell's point of view. I keep a sharp eye on what he writes and talks because he is one of a tiny handful of active researchers dealing with technical dive safety and I highly respect him. But his points of view are sometimes controversial.

Apologies for a long, meandering argument.

Is it possible to get some consensus about the icd issue? Can we at least agree that the red exclamation marks should be removed and that (at least as a first step) the resolution for icd information in the dive plan is reduced from 0.01 to 0.1?

**Comment by sfuchs79** [comment]
I have doubts that there is anything I could add which could be of any help ;-)
Two items:
- Today we in fact can enter gas fractions in the cylinder tab and the planner with a precision of 0.1%.
- Roberts new gas change items are really nice BUT today in the planner we also don't add a warning icon for pO2 exceeded in the profile.

**Comment by RickMWalsh** [comment]
On 24 Jan. 2018 05:21, "Stefan Fuchs" <notifications@github.com> wrote:

I have doubts that there is anything I could add which could be of any help
;-)
Two items:

   - Today we in fact can enter gas fractions in the cylinder tab and the
   planner with a precision of 0.1%.

With that being the case, and sorry I missed it, the patch looks good to me.

**Comment by sfuchs79** [comment]
@willemferguson 
I think you now have to rebase your branch on master again to get rid of the merge commit.

Beside this I (again) vote for taking this patch because it changes the precision in the right direction and now also fixes some real mistakes :-)

**Comment by atdotde** [comment]
Now I am really confused. Do you want to be warned about ICD or not? If yes, then in to should be in the profile (as it is something that happens at a gas switch at a certain point in the dive (i.e. it has a time). The way it is listed in the dive notes adds a lot of information to be parsed by the user but to be useful, she has to read the runtime value from the table then go up to the profile to see where this time is and then identify the gas switch. I strongly believe this should be aided by a visual clue. For this I came up with the exclamation mark. If you don't like it because it is too string, please go ahead and replace it with a different icon. But please give a visual clue.

But if you don't want the warning, we should rip out the whole ICD thing again. After all, nobody seems to be really sure what the criterium should really be. I even asked on Scubaboard and the only person to reply was Simon Mitchell (https://www.scubaboard.com/community/threads/icd-and-gas-swaps.554986/page-7#post-8193662) basically saying "nah, don't bother".

Why don't we do the following compromise: We add a preference for this, where the user can say when she wants to be warned about ICD (replaying the 1/5 rule by 10%, 20%, 30%, 50%, 100% and never). And then I would opt for the default value being "never".

**Comment by janmulder** [comment]
@atdotde: I understand your confusion :-) And as can be read above, I'm a non-believer of ICD in real live, for the diving I do (max 100m on mCCR). So, I like the answer of Simon Mitchell. But that said, @willemferguson strongly believes in ICD (and the need for countering the issue).

> Why don't we do the following compromise: We add a preference for this, where the user can say when she wants to be warned about ICD.

Yes, that would solve "everything", at the cost of another preference.

**Comment by willemferguson** [comment]
May I request, please, lets us focus on one issue at a time. Would it be ok if, for the moment, just focus on the PR that deals with the resolution of calculations and the display of these calculations at the appropriate resolution?  Once this has been pulled into master, then we can do whatever else you would want. I am in favour of keeping Robert's icons in cases where the calculations do not fit the 20% rule. Let's do this one step at a time, otherwise the discussion will continue for ever and we waste effort that could be put to better use for Subsurface.

Please see the icd issue as a corner case. It only applies to hypoxic OC trimix dives. That is almost a negligible fraction of all the dives being logged in Subsurface. It is not necessary to spend a huge amount of effort in developing this because only a small number of individuals will ever encounter this in working with Subsurface.

Can I sort out the merge conflict and submit a final PR that deals with the resolution part only?

**Comment by janmulder** [comment]
> Can I sort out the merge conflict and submit a final PR that deals with the resolution part only?

Please do not close this PR and open a new one, but just rebase this (to get rid of the merge commit: we do not like these in our git history).

```
git checkout precision
git rebase -i master
```
you will now get the merge conflict
so fix this
```
git add profile-widget/diveeventitem.cpp  (there is the merge conflict in)
git rebase --continue
```

now you are all set to push (--force) it to GitHub again.

And sorry for bringing up the usefulness of ICD here (as this PR has nothing to do with that aspect).

**Comment by willemferguson** [comment]
This is what I get:

~/src/subsurface$ checkout precision
Already on 'precision' [not suprisingly]
~/src/subsurface$ git rebase -i master
Successfully rebased and updated refs/heads/precision.
~/src/subsurface$ git add profile-widget/diveeventitem.cpp
~/src/subsurface$ git rebase --continue
No rebase in progress?
~/src/subsurface$ git push -f upstream precision
Username for 'https://github.com':
Password for 'https://willemferguson@github.com': 
Everything up-to-date

[no need to push. merge conflict remains :-((((( ]

**Comment by janmulder** [comment]
@willemferguson: now I messed up myself ...  and somehow created a merge commit myself (from the brouwser @ github).

Can you now force push your precision branch again, to resolve this?

**Comment by willemferguson** [comment]
I've pushed it. Cannot see it on this page.

~/src/subsurface$ git push -f upstream precision
Counting objects: 6, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 1.00 KiB | 0 bytes/s, done.
Total 6 (delta 5), reused 0 (delta 0)
remote: Resolving deltas: 100% (5/5), completed with 5 local objects.
To https://github.com/willemferguson/subsurface.git
 + f285972...34e7fca precision -> precision (forced update)

**Comment by willemferguson** [comment]
Is there anything I should do about this conflicting file? Looks like the rebase does not do much in this case.

~/src/subsurface$ git checkout precision
Switched to branch 'precision'
~/src/subsurface$ git rebase -i master
Successfully rebased and updated refs/heads/precision.

~/src/subsurface$ git push -f upstream precision
Username for 'https://github.com': willemferguson
Password for 'https://willemferguson@github.com': 
Everything up-to-date

**Comment by janmulder** [comment]
The reason that your rebase is `Successfully rebased and updated refs/heads/precision` without conflict is that your own master is (3 commits) behind the current master (of upstream, ie. the official repo). So you first need to get your (local and remote) repo in sync with the official one (as you normally do when pulling in all changes that have been added to upstream)

If I would know how to manually push the rebase, I would do that for you, but as I'm not 100% sure how to do this (and having all powers to mess things up) is is best you rebase yourself.

**Pull request merged**
