### PR TITLE
Clear undo stack on file close

### PR DESCRIPTION
**Pull request by michaelandreen**
The undo stack is only relevant to the dives that were loaded at the
time the command was executed. If a file is closed, by specifically
closing it or opening another file, then the undo commands will
reference dives that aren't available anymore. Clearing the undo stack
ensures that we don't crash or accidentally do some undefined
modifications to the currently open file.

Signed-off-by: Michael Andreen <michael@andreen.dev>

### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### CODE REVIEW

**Review by dirkhh — APPROVED** [review]
That seems very reasonable.

@bstoeger - any thoughts?

**Comment by bstoeger** [comment]
Yes, this is reasonable. The `setClean()` call should probably be removed as an empty undo-list should be clean by definition.

Note that the `clear()` call was removed in fb6210a99a1eda0f7f7197ed57f3c61a82132dff, so mobile is probably also affected.

Which makes me wonder whether this should be moved to `clear_dive_file_data`. On the other hand, calling C++ from C is so painful...

**Comment by dirkhh** [comment]
> Yes, this is reasonable. The `setClean()` call should probably be removed as an empty undo-list should be clean by definition.
> 
> Note that the `clear()` call was removed in [fb6210a](https://github.com/subsurface/subsurface/commit/fb6210a99a1eda0f7f7197ed57f3c61a82132dff), so mobile is probably also affected.
> 
> Which makes me wonder whether this should be moved to `clear_dive_file_data`. On the other hand, calling C++ from C is so painful...

So we have several `setClean()` calls in that file. And I'm not entire sure what you are saying here...
That `setClean()` in general makes no sense and should be removed?
Or that it should be removed here (which it is in the patch)?

I'd just hate for me to try to follow the logic (or what I think I read in your comment) and then make things worse...

**Comment by michaelandreen** [comment]
It would be fairly easy to add an extern "C" wrapper in qthelper.h/cpp or similar. There are currently no dependencies from core to commands and adding something like this would introduce circular dependencies between the libs. I don't know if that is something we care about.

**Comment by michaelandreen** [comment]
> So we have several `setClean()` calls in that file. And I'm not entire sure what you are saying here...
> That `setClean()` in general makes no sense and should be removed?
> Or that it should be removed here (which it is in the patch)?

setClean() seems to be a way to say that the current state has been saved. The cases where it's used are save, save_as and save to cloud, so that seems reasonable.

**Comment by bstoeger** [comment]
I'm saying that `setClean` and `clear` is redundant, so the new version should be correct.

> It would be fairly easy to add an extern "C" wrapper in qthelper.h/cpp or similar. There are currently no dependencies from core to commands and adding something like this would introduce circular dependencies between the libs. I don't know if that is something we care about.

There is precedence. For example, core calls into the C++ fulltext code.

I have no preference in this particular case. There are three calls to `clear_dive_file_data` in `qmlmanager.cpp`

> setClean() seems to be a way to say that the current state has been saved. The cases where it's used are save, save_as and save to cloud, so that seems reasonable.

Correct. This marks the "clean" state for which the asterisk next to the filename is removed.

**Comment by dirkhh** [comment]
I posted an alternative PR that simply (Ha!) calls `Command::clear()` from the C routine `clear_dive_file_data()`

What it is missing is the `CHANGELOG` entry as well as the removal of `Command::setClean()` calls after we call `clear_dive_file_data()` -- I was simply trying to be quick to catch @bstoeger before he signs off for today :)

**Comment by michaelandreen** [comment]
Since `clear_dive_file_data` emits `diveListNotifier.dataReset` we can just connect that to clear. Seems cleaner and avoids the circular dependency.

**Comment by bstoeger** [comment]
LGTM. Ultimately, the `clean` function could be made local. I'm also fine with Dirk's version. Both have things going for and against them.

**Review by bstoeger — APPROVED** [review]

**Comment by dirkhh** [comment]
I liked the logical clarity of my solution. This way you still have to remember to do this. Remind me, is this problem fixed now for mobile as well, or does it still need to be fixed there?

Anyway, I'll merge this.

**Comment by michaelandreen** [comment]
> Remind me, is this problem fixed now for mobile as well, or does it still need to be fixed there?

I would assume that it is fixed for mobile as well, since it calls Command::init().

**Pull request merged**
