### PR TITLE
Desktop: ensure cloud storage email address is all lower case

### PR DESCRIPTION
**Pull request by dirkhh**
We already do that on mobile and I was certain we used to do this for
desktop as well, but apparently that got lost somewhere...

This should solve the problems we are seeing for people with mixed case
email addresses.

### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Changes made:

Simply force the email string to contain no upper case letters

### Release note:

done

### Documentation change:

not needed

### CODE REVIEW

**Comment by dirkhh** [comment]
I'd appreciate if one of the other Collaborators would do a sanity check and merge this

**Review by atdotde — COMMENTED** [review]
Shall we enforce that everywhere before sending? Like converting also stored addresses to lower and even more on the receiving end?

**Comment by dirkhh** [comment]
We are already forcing things to be lower case of the server.
The problem is the branch name is derived from the email. And that's why people can't read their data.

**Comment by dirkhh** [comment]
So this is converting the address to lower as it is extracted from the UI.
Maybe I'm not understanding your comment, @atdotde - where else would you want to make sure that we convert it?

**Comment by atdotde** [comment]
I wasn't really aware of how this is handled: I meant, we take cloud_storage_email and cloud_storage_email_encoded from the preferences (in particular in getCloudUrl() in qthelper.c) and thought it might be a good idea to force lower case in those places as well. But I am no longer sure this is such a good idea as it might collide with branch names of checked out repositories.

**Comment by dirkhh** [comment]
I don't want to risk breaking things for people who have working setups. So this is designed to only behave differently if someone adds new cloud credentials.
I have looked through this again and am reasonably certain it's correct.
Merging.

**Pull request merged**
