### PR TITLE
Android BLE update

### LINKED ISSUE #2974: Cannot find shearwater peregrine on Android
### Describe the issue:

- [x ] Bug

### Issue long description:
My Shearwater Peregrine is not found on Android. I have already tried to turn on 'Show all bluetooth devices' toggle in the Advanced settings but still don't see my DC.

### Operating system:
Android

### Subsurface version:
Subsurface version 3.0.15 (4.9.6.111) official release

### Steps to reproduce:
1) Turn on bluetooth connection on DC
2) Try to find DC in subsurface

### Current behavior:
My DC is not found in the app

### Expected behavior:
DC is found in the app

### PR DESCRIPTION
**Pull request by dirkhh**
### Describe the pull request:

- [x] Bug fix
- [x] Functional change

### Pull request long description:

a couple of cleanups
better debugging information
use the discovery agent to find BLE devices that can't be bonded/paried

### Related issues:

Fixes #2974 

### Mentions:

@torvalds

### CODE REVIEW

**Comment by dirkhh** [comment]
RIGHT, Dirk. You KNOW not to do edits to make it look better just before pushing the branch.
GRMBL.
Yeah, will fix.
But what matters is the core idea, not the couple of typos.

**Comment by vondwater** [comment]
Great! My issue will be fixed then :-) Thanks!

When will there be a release?

**Comment by dirkhh** [comment]
Should become available within a day or two (Google reviews slow things down).
If you want to side-load the apk directly (signed with the same certificate as the apk from the play store), you can find a test binary here: https://subsurface-divelog.org/downloads/test/Subsurface-mobile-4.9.7.50-arm64.apk

**Comment by vondwater** [comment]
> Should become available within a day or two (Google reviews slow things down).
> If you want to side-load the apk directly (signed with the same certificate as the apk from the play store), you can find a test binary here: https://subsurface-divelog.org/downloads/test/Subsurface-mobile-4.9.7.50-arm64.apk

Thanks! Now it works 👌

**Comment by dirkhh** [comment]
excellent. thanks for the confirmation

**Pull request merged**
