### PR TITLE
When removing a cylinder completely fill the mapping table

### PR DESCRIPTION
**Pull request by sfuchs79**
### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

When deleting a cylinder the mapping was not filled with all
necessary values. Values for cylinders before deleted cylinder were
missing.

Potentially fixes a crash reported on the ML when removing a cylinder.

This is up to now for testing for the people reported the crash. Needs more testing by myself.

### CODE REVIEW

**Comment by ggardet** [comment]
No crash anymore for me. Tested on top of daily 4.6.4-1031 on openSUSE Leap 42.3

**Comment by dirkhh** [comment]
This looks sane, but I don't have prior problems, so it's hard for me to test if this works.

**Comment by sfuchs79** [comment]
No, I'm not happy yet.
There is still s.th. odd. In my code is one clear typo in the new line 566.
And then there is s.th. else odd. Difficult to explain. Need to understand it first.

**Comment by sfuchs79** [comment]
NOW that's ready.

Wow, that killed my nerves...
I was haunted by zombie cylinders apparently because the endRemoveRows was in the wrong position.

**Pull request merged**
