### PR TITLE
Typo of celsius

### PR DESCRIPTION
**Pull request by jb2cool**
Just a typo for the comment regarding celsius, no functional code change

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Just a typo in a comment, no 'live' code change

### Changes made:

Changed the word celcius to celsius in a comment, no functional change

### CODE REVIEW

**Comment by dirkhh** [comment]
You closed all three of them. Sorry this is so frustrating.

What the bot complains about actually even contains a way to fix it.
In your own tree, simply issue this command (assuming you have user and email set up - if you don't, git tells you how to fix THAT):
`git commit -s --amend`
this will sign off on the last commit. Then you can push that to github (may need a new branch of `git push -f`) and create a PR for it :-)

If there's anything else I can do to help with this process, please let me know!

**Comment by jb2cool** [comment]
I had done my initial edits just using the browser so not really the proper way. I have since followed the contribution guidance and should have created a proper signed off ‘patch’.

There are still some references to celcius in csv files but didn’t want to touch then in case it caused parsing errors.

Jb

**Comment by dirkhh** [comment]
I don't see an open PR from you... did you close that one by mistake? Or did you not submit it, yet?

**Comment by jb2cool** [comment]
Didn't submit one, i just sent the patch file (attached) to the dev mailing
list. I thought this was one of the accepted procedures for pulls. I'm
pretty new to git (I know how to pull, commit to my own code and puch but
don't really know much about PRs and merge requests when it comes to
someone else's code.

JB

**Comment by dirkhh** [comment]
My mistake, I had missed the attached patch.
We have pretty much moved away from patches in email, but I will happily add that to our code.
Doing all this on GitHub is actually quite easy - if you want to do more work on Subsurface, I'll be happy to walk you through it.

**Comment by jb2cool** [comment]
Thanks Dirk,
I'm ok on the command line so long as i know what i'm doing, i just need an
example to work to. The contribution page talks me through pulling the code
and creating a branch and even doing the commit but doesn't tell me how to
do the PR from the command line. If that's because you don't do it via the
command line but you instead pick up the commit up from the website and do
the PR there then that could explain it.

I've certainly no coder/programmer but can fix small things like typos as i
see them or even slightly more complex things when someone has shown me how
it works. For example I was helping to update the Flatpak install of
Subsurface at one point when i was using that on Linux Mint but when i
switched to using the PPA (I think you suggested this to me) then i stopped
doing the Flatpak one, i was only selfishly doing it for my own benefit. I
did look over the code at one point to see if i could be of any use and
frankly i can't understand any of it.

Regards
Jason

**Comment by dirkhh** [comment]
So from the command line you push this to your fork of Subsurface on github. 
So first fork the repo (I see that you haven't done that, yet). There's a fork button at the top of this very page (assuming you are looking at this on the website).
Now you have your own copy (which should be `https://github.com/jb2cool/subsurface`).
You can push a new branch into that copy (the next depends on many things - for simplicity I assume that you have ssh keys set up for GitHub... you can also do this with https and then authenticate on the command line):
`git push git@github.com:jb2cool/subsurface <branch-name>`
(sorry, there was a typo here - fixed it)
When you now go back to `https://github.com/jb2cool` you'll see an option to create a pull request (i.e., that last step is done on the website). And detailed steps how to do this will be printed as a result of the `push` command above.

Happy to tell you more about each of the steps in case I went to fast somewhere.

**Comment by jb2cool** [comment]
Perfect, thanks. I'll give that a try next time i do something.

I did actually have a fork of Subsurface until earlier today but it was
very out of date so i cleaned up my repositories and removed anything that
was redundant. I guess i could have looked at how to update that (a quick
Google suggests git fetch and git rebase is the way to go here) but i had
nothing of value in my fork so i just ditched it.

This is why i like Subsurface so much, firstly it's an application that
does exactly what i want and in the past when i'd requested features
they've been implemented but the developer community is friendly too.

Regards
Jason

**Pull request closed without merging**
