### PR TITLE
core: split proper divecomputer in split_divecomputer()

### PR DESCRIPTION
**Pull request by bstoeger**
split_divecomputer() is passed a dive and a divecomputer number.
However, it accesses the currently visible dc!

This would be a nasty bug if it werent for the fact that it is
called when placing an undo command and there it is passed the
current dive and divecomputer anyway.

Nevertheless, fix this.

Signed-off-by: Berthold Stoeger <bstoeger@mail.tuwien.ac.at>

### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

This fixes a bug in a function, that should not be user visible.
Completely untested, but looks rather logical...?
### Changes made:

1) Access the correct divecomputer when splitting dives.

### CODE REVIEW

**Comment by bstoeger** [comment]
Added a second commit that removes an ominous access to the global "dc_number" variable.

**Comment by bstoeger** [comment]
And more commits to move handling of the global `dc_number` variable from core to desktop. It makes no sense on mobile, where multiple profiles are active at the same time.

**Review by dirkhh — APPROVED** [review]
the number of these stupid silly misunderstandings that we have everywhere... just bad

thanks for your diligence in fixing them over time.

**Comment by dirkhh** [comment]
This looks very nice. The last commit has a typo in the commit message (plot/plit) - and I kinda agree with the question posed... I think it would be more logical to have a pointer back to the profile and use that to access the plot_info. Any reason you didn't do that in the end?

**Comment by dirkhh** [comment]
and I'll take this one as well - and fix up the commit message

**Pull request closed without merging**
