### PR TITLE
User manual 4.8.2

### PR DESCRIPTION
**Pull request by janmulder**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [x] Documentation change
- [ ] Language translation

### Pull request long description:
User manual changes for 4.8.2. Split in 3 commits. 2 non-controversial  one and a relatively big one stripping out all text related to the Companion app. 

### Changes made:
See commits

### Additional information:
2 screendumps from Willem added to this PR

### CODE REVIEW

**Comment by willemferguson** [comment]
Here is the image. Jan, I made a terrible mess with a PR 'Manual-figures-V4.8' I cannot delete it, it hangs above the Pull request panel. Woould you be prepared to kill that thing, please?
pref5_f23

**Comment by janmulder** [comment]
@willemferguson: I do not think I can delete that for you. That branch is sitting in your github account.

**Comment by janmulder** [comment]
@willemferguson: added your Preferences/Network screendump to this PR.

**Comment by dirkhh** [comment]
OK, this looks good. I might have phrased this slightly differently, but I can of course always address that when manually merging :-)
No point in waiting for travis as this isn't compiled code, anyway. So I'll pull this.

**Comment by dirkhh** [comment]
Oh, that last commit should be authored by Willem, I'll fix that as well.

**Comment by janmulder** [comment]
Yes, your right. Screendumps by Willem.

**Comment by dirkhh** [comment]
Please check if you like my modifications. Pushed to master now.

**Pull request closed without merging**
