### PR TITLE
Add/update preference screen icons

### PR DESCRIPTION
**Pull request by ssttaarr**
Defaults and language icons were missing, and graph/profile
icon was not readable.

All icons except "language.png" were taken from Google's
Material Design Icon pack which is distributed under Apache 2.0 license
(see https://github.com/google/material-design-icons)

Language icon is from http://languageicon.org site. If their
license isn't permissive enough, then we can switch to a language icon
from Material Design pack (globe).

Signed-off-by: Sergey Starosek <sergey.starosek@gmail.com>

### CODE REVIEW

**Comment by dirkhh** [comment]
Technically Apache2 and GPLv2 are not compatible. Admittedly, in this circumstance the "technicality" that makes them incompatible (the patent grant provisions) isn't relevant as there are no patents involved in art work, but this makes me somewhat uncomfortable.
The three icons that you use from Material design are incredibly basic. I wonder if there aren't very similar icons available elsewhere under a GPLv2 compatible license.

The language icon is beautiful and I want to use it, but that means that we need to credit the creator in our About box (which we should extend anyway to credit all the other libraries and their authors that we rely upon).
For 4.6.2 I'm not sure we can get this done (new strings for the About box that need to be translated, etc).

**Comment by ssttaarr** [comment]
Hi Dirk,

On Tue, Feb 14, 2017 at 6:37 PM, Dirk Hohndel <notifications@github.com>
wrote:

> The three icons that you use from Material design are incredibly basic. I
> wonder if there aren't very similar icons available elsewhere under a GPLv2
> compatible license.
>
I'll look for icons with GPL-friendly license, np.

> The language icon is beautiful and I want to use it, but that means that
> we need to credit the creator in our About box (which we should extend
> anyway to credit all the other libraries and their authors that we rely
> upon).
>
For 4.6.2 I'm not sure we can get this done (new strings for the About box
> that need to be translated, etc).
>
I also like it very much. Let's wait for the next release for this patch.

Sergey

**Comment by ssttaarr** [comment]
Seems that Google has switched to Apache 2.0 license since v3.0.0 of Material Design Icon pack. Before they used CC-BY 4.0 license which is compatible with GPLv2 according to https://www.gnu.org/licenses/license-list.en.html

**Comment by dirkhh** [comment]
And those icons where unchanged from before v3.0.0? That would make this easy :-)
All I need to do is add the attributions...

**Comment by dirkhh** [comment]
@ssttaarr Have you been able to verify that the icons are unchanged from before v3.0.0? So can we use these under CC-BY 4.0?

**Comment by ssttaarr** [comment]
Those three icons haven't been changed since v2.2.3 (CC BY 4.0 license).
No changes to the icons, just renaming.

**Comment by dirkhh** [comment]
@ssttaarr I thought about this (and you saw that I even created the Credits page to prep for this), but in the end decided to delay this past 4.6.2. The user manual would have to be updated. And even though it is "just icons" that change, it would have no testing whatsoever before a release. That would be just bad engineering practice on my part.
I'll pull it after the release (and I expect to do a 4.6.3 reasonably soon).
Thanks

**Comment by dirkhh** [comment]
Would you please add the appropriate credits to our credits page on subsurface-website?

Thanks

**Pull request merged**
