### PR TITLE
Git storage testing

### PR DESCRIPTION
**Pull request by dirkhh**
### Describe the pull request:

- [x] Bug fix
- [x] Functional change
- [x] Code cleanup
- [x] Build system change

### Pull request long description:

This should fix the core issue of why TestGitStorage kept failing for us
The code implicitly relied on `.git/HEAD` pointing to the user's branch in the local cache, yet whether that was the case depended on how / when the local cache was created. And if this was wrong, the user could in fact lose data.

### Changes made:

1) ensure that `.git/HEAD` points to our branch
2) create ten test accounts and use random branch names
3) clean up after the test runs
4) re-enable the test

### Related issues:

need to see if we have some that relate to this

### Release note:

Given that this fixes a potentially bad user visible problem, yes, I should add that

### Mentions:

Not sure who'd be brave enough to look at this...
I guess @torvalds for the git changes
@bstoeger to look at the test (if you are bored)

### CODE REVIEW

**Comment by dirkhh** [comment]
Ahh. `QRandomGenerator` is Qt 5.10 or newer. And Ubuntu 18.04 is on 5.9.
So I'll need an alternative implementation until we can stop supporting Qt 5.9
lovely

**Comment by glance-** [comment]
rand() or just if-def the test case for qt >= 5.10 , and ignore old bionic. focal is coming on the 23rd and it isn't far until we can bionic users to the app image instead.

**Comment by dirkhh** [comment]
> rand() or just if-def the test case for qt >= 5.10 , and ignore old bionic. focal is coming on the 23rd and it isn't far until we can bionic users to the app image instead.

yeah, I will do an ifdef'ed `rand()` based implementation and keep what I have for Qt >= 5.10
I really like using Qt functionality for things like this as I then know that it's expected to work consistently on all platforms. But I'll do another one until we can use that more broadly.

Even with Focal coming out next week, I expect people to keep using Bionic for at least another year. I seem to remember that people were mad at me when I killed Trusty support in right after Bionic was released... based on that I would say we should expect to keep Bionic support around for another couple of years :-)

**Comment by bstoeger** [comment]
> @bstoeger to look at the test (if you are bored)

Way over my head, sorry. If it works for you, then excellent.

**Pull request merged**
