### PR TITLE
CICD: Update the Runner for macOS to macos-13.

### PR DESCRIPTION
**Pull request by mikeller**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [x] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Update the runner used for macOS builds to macos-13 because the macos-12 runner is no longer supported by GitHub.

### CODE REVIEW

**Comment by mikeller** [comment]
@dirkhh: As expected this isn't working, but I am really just taking stabs in the dark here as I am not set up to test this locally. Do you have bandwidth to help?
(Getting this resolved will probably also move us forward in the quest to get CICD builds for the iOS emulator working again...)

**Comment by dirkhh** [comment]
> @dirkhh: As expected this isn't working, but I am really just taking stabs in the dark here as I am not set up to test this locally. Do you have bandwidth to help? (Getting this resolved will probably also move us forward in the quest to get CICD builds for the iOS emulator working again...)

I mean the errors that I'm seeing appear to be in the git checkout trying (and failing) to use http/2 - this has nothing to do with the build. Possibly we need a newer version of some github action module? I can try to look into this, but given my load at work that will take a few days.

**Comment by mikeller** [comment]
@dirkhh: Ha, took me a while to find what you are referring to. It looks like the latest build of this pull request (after I had rebased the branch) ran into something like network issues.
Have a look at https://github.com/subsurface/subsurface/actions/runs/11899873615/job/33159467208?pr=4374, which is the first run on this branch, and went fine all the way until the build failed.
Update: After re-running the failed jobs in the latest run it now fails at the same place in the build.

**Comment by dirkhh** [comment]
> @dirkhh: Ha, took me a while to find what you are referring to. It looks like the latest build of this pull request (after I had rebased the branch) ran into something like network issues. Have a look at https://github.com/subsurface/subsurface/actions/runs/11899873615/job/33159467208?pr=4374, which is the first run on this branch, and went fine all the way until the build failed.

Cool. The error is actually in `googlemaps`:
```
 + /Users/runner/work/subsurface/subsurface/qt-mac/Qt5.15.15/lib/cmake/../../bin/qmake INCLUDEPATH=/Users/runner/work/subsurface/install-root/include CONFIG+=release ../googlemaps.pro
 Info: creating stash file /Users/runner/work/subsurface/googlemaps/build/.qmake.stash
 Project ERROR: failed to parse default search paths from compiler output
```

I know that I had that building on macOS 14. My first guess would be to not use our branch upstream again. After abandoning the project for a while it seems the maintainer is back...

**Comment by mikeller** [comment]
I've had a look at the googlemaps plugin, but unfortunately the latest changes include a breaking API change, so an update to upstream or a rebase on upstream won't be a straightforward thing (see https://github.com/subsurface/subsurface/actions/runs/11902387958/job/33167293409?pr=4374).

On the other hand the googlemaps plugin is building and working fine everywhere but macOS, and the error on macOS seems to be caused by pathing on macOS 13 being different, so the easiest way to the fix might be to update the expected pathing in the googlemaps plugin build.

**Comment by mikeller** [comment]
@dirkhh: Looks like the unwillingness of GitHub to run workflows on macos-12 runners was a temporary glitch / reminder, and our macOS builds are running again.
But we should probably try to get this resolved soon-ish anyway, as `macos-12` is slated for permanent retirement on 3 Dec 2024: https://github.com/actions/runner-images/issues/10721

**Comment by dirkhh** [comment]
> @dirkhh: Looks like the unwillingness of GitHub to run workflows on macos-12 runners was a temporary glitch / reminder, and our macOS builds are running again. But we should probably try to get this resolved soon-ish anyway, as `macos-12` is slated for permanent retirement on 3 Dec 2024: [actions/runner-images#10721](https://github.com/actions/runner-images/issues/10721)

we need to upgrade to Qt 5.15.16
it's so frustrating to consider how much time is wasted on chasing dependencies (and random changes in the underlying OS)

**Comment by mikeller** [comment]
> we need to upgrade to Qt 5.15.16 it's so frustrating to consider how much time is wasted on chasing dependencies (and random changes in the underlying OS)

 😣

Yeah - it looks like the macOS-12 GitHub runners are gone permanently now.

**Comment by dirkhh** [comment]
> > we need to upgrade to Qt 5.15.16 it's so frustrating to consider how much time is wasted on chasing dependencies (and random changes in the underlying OS)
> 
> 😣
> 
> Yeah - it looks like the macOS-12 GitHub runners are gone permanently now.

I'm working on building this. Which of course takes for ever and if something fails just restarting is like another hour lost... I'll get there...

**Comment by dirkhh** [comment]
this has been superseded by #4393

**Pull request closed without merging**
