### PR TITLE
Make SmartTrak import tool buildable again

### PR DESCRIPTION
**Pull request by salvadorcunat**
Last rework of source tree left smtk-import tool unbuildable.  This should make it buildable again.

### CODE REVIEW

**Comment by salvadorcunat** [comment]
Well not really 4 commits, just two.  The user-manual_es.txt one was applied some days ago and the other is a merge from upstream.  It seems I screwed my fork yesterday. If this don't apply on master I will blow it away and will re-fork the project.

**Comment by Subsurface-divelog** [comment]
Yep, worked as just as straight forward as I thought.

**Comment by salvadorcunat** [comment]
Thanks Dirk.  I'll blow away the fork, make a new one and follow your instructions in the mailing list.

**Comment by Subsurface-divelog** [comment]
Maybe you misunderstood. I pulled this - just not using the GitHub UI. So please test latest master to see if this is functional.

**Pull request closed without merging**
