### PR TITLE
Desktop: Load the Dive Computer List in 'Configure Dive Computer' Dynamically.

### PR DESCRIPTION
**Pull request by mikeller**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Load the dive computer list in the 'Change Settings on Dive Computer' dialog dynamically.
Also incorporate suggestions from
https://github.com/subsurface/subsurface/pull/3925#issuecomment-1595784076.

### Changes made:

1. use constant array for dive computer list;
2. load the dive computer list in the 'Change Settings on Dive Computer' dialog dynamically.

### Mentions:

Suggested-by: Berthold Stoeger <bstoeger@mail.tuwien.ac.at>

### CODE REVIEW

**Comment by glance-** [comment]
I don't see the upside with this. I've been working with the ui in designer, and not having the selection panel there will just be a pita.

So, no, I don't like moving this out of the ui files.

**Comment by bstoeger** [comment]
> I don't see the upside with this. I've been working with the ui in designer, and not having the selection panel there will just be a pita.
> 
> So, no, I don't like moving this out of the ui files.

The point is - the data is now found in two places. If you edit the ui file, you must edit the C++ file. This change makes it so that you only have to edit the C++ file. Seems reasonable to me.

**Comment by glance-** [comment]
For changes in all ui components you need to change both the .ui files, and plumb up the values to the c++ code to make anything happen. This only changes this for a small fraction of the ui logic, with the downside of making testing of this directly in the qt-designer harder because the computer switcher/chooser thingie isn't there any longer.


There are 4 computers supported, and that haven't changed in ages, since I added the Ostc4 like... 5? years ago. It won't change that much in the future either. Shure, if it where code that was changed every week or so, fine. then it would get out of sync often enough but this is really low traffic code who now is changed the first time in 5 years.

So, slight inconvenience in keeping ui and cpp in sync, which they need to be for _everything else_ already is a tiny price for making the ui still testable standalone in qt-designer.

**Comment by bstoeger** [comment]
Ok, to me that's a very foreign way of doing things, but fair enough. In fact, I stopped using QtCreator and edit these XML-files by hand. Since I'll never use this part of the code, it's not my call.

**Comment by dirkhh** [comment]
I'm leaning towards @glance- 's argument here. There really are only four supported dive computers and it's not likely to change. This is such an odd, rarely used feature... I don't think it's worth making his workflow harder - and he's the main person working on this...

**Comment by mikeller** [comment]
Ok, tried to salvage the improvements from this, and added a warning about the reliance on matching indices across multiple files.

**Comment by glance-** [comment]
I'd suggest you break out the forcedFirmwareUpgradeSupported changes to a separate commit, but other than that, it LGTM.

**Comment by mikeller** [comment]
@glance-: Done.

**Review by glance- — APPROVED** [review]

**Review by dirkhh — APPROVED** [review]
looks good

**Pull request merged**
