### PR TITLE
Import: Update libdivecomputer to the Latest Version.

### PR DESCRIPTION
**Pull request by mikeller**
### Describe the pull request:

- [ ] Bug fix
- [x] Functional change
- [x] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Update `libdivecomputer` to the latest upstream version.

### Changes made:

1. update `libdivecomputer` to the latest upstream version;
2. add support for the new dive computer models that have been added in the
latest version of libdivecomputer;

### CODE REVIEW

**Review by dirkhh — APPROVED** [review]
I haven't tested this, of course, but the changes look good.

**Comment by dirkhh** [comment]
I'll leave it to you to pull the trigger on the merge.
I will create another "current" release with the changes before this merge so we have something for people to use that aren't as adventurous... I hope I'll have time this evening to do so.

**Comment by mikeller** [comment]
Hi Dirk.

> I will create another "current" release with the changes before this merge so we have something for people to use that aren't as adventurous...

Good idea!

**Comment by dirkhh** [comment]
So should we merge this? 😁

**Pull request merged**
