### PR TITLE
Turn off optimization while debugging

### PR DESCRIPTION
**Pull request by atdotde**
With the optimizer eliminating local variables the debugger
becomes useless.

This reverses 0f3bda4c44

Signed-off-by: Robert C. Helling <helling@atdotde.de>

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [x] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

I found that with optimisation, the debugger is pretty much unusable since it loses access to local variables. Since debug builds should allow debugging, turned it off again.

### CODE REVIEW

**Comment by neolit123** [comment]
@dirkhh @atdotde @bstoeger 

i guess @bstoeger 's observation is that `-O2` generates more readable assembly.

on the other what @atdotde reports:
> the debugger is pretty much unusable since it loses access to local variables

i think out weights the previous problem and the commit should be indeed reverted.

instead of hard coding the optimization level we should remove all `-Oxxxx` flags from CMake and leave it to the user to specify them via the command line.

**Comment by bstoeger** [comment]
Perhaps the more important point was that some warnings depend on data-analysis that is only performed with -O2. Another point is that it seems like a good idea to test code that is as close as possible to release builds.

> the debugger is pretty much unusable since it loses access to local variables

This is only partially true (test program, compiled with -O3):
```
(gdb) next
7               for (int i = 0; i < 100; ++i)
(gdb) next
8                       printf("= %d =\n", i);
(gdb) next
= 2 =
7               for (int i = 0; i < 100; ++i)
(gdb) print i
$1 = 3
```
But yes, with SIMD-vectorization, copy-elision, inlining, etc I can see how stepping through an optimized program might become a nightmare.

Even though debuggers were never very central to my work-flow, I really would like to have builds with -O2 *and* debug-symbols for the odd use-case. Strategic `printf`s have always been more how I operate.

I think this should be discussed on the mailing list.

**Comment by bstoeger** [comment]
PS: This is the original mail leading to the referenced PR:
http://lists.subsurface-divelog.org/pipermail/subsurface/2017-December/031248.html

**Comment by neolit123** [comment]
i remember local variable working from gdb with optimization flags in other projects.
@atdotde can you provide an example of where this breaks for you in Subsurface?

**Comment by atdotde** [comment]
I didn't do this out of aesthetic considerations. I was actually trying to find a bug (and found it, #1222 is the fix for it). I was single stepping though code in profile.c dive.c and planner.c in particular tissues_at_end() in planner.c where t0 and t1 didn't have useful values in the debugger and also entry in plot_data() in profile.c was optimised away (taking with it all interesting state variables). As I said, the debugger was useless.

We could make this a cmake variable that can be set using ccmake according to one preferences for looking at assembly, looking for data analysis warnings or actual debugging.

**Comment by neolit123** [comment]
@atdotde 
> We could make this a cmake variable 

i was able to reproduce the `t1` being optimized out in `tissue_at_end`. `t0` was not optimized out for me, but i guess this still makes a valid point that using `-O2` all the time is not desired.

have a look at:
https://github.com/Subsurface-divelog/subsurface/pull/1224

following your suggestion, this PR adds the option to control the GCC optimization flags for debug builds.
by default we use `-O2` so if you want to disable that use `-DGCC_OPTIMIZATION_FLAGS:STRING=-O0` or set it via the GUI.

**Comment by dirkhh** [comment]
The problem with having the Travis build be different from what we do for production builds should be obvious... I'd much rather make sure that we keep those consistent.

**Pull request closed without merging**
