### PR TITLE
cmake: make sure to only handle objcopy from MXE

### PR DESCRIPTION
**Pull request by neolit123**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

The native Windows build does not use the MXE tools
and call such as `i686-w64-mingw32.shared-objcopy`
can fail.

Attempt to first find if the program exists using
`find_program()` and only then call it.

Signed-off-by: Lubomir I. Ivanov <neolit123@gmail.com>

### Mentions:

@dirkhh

### CODE REVIEW

**Comment by neolit123** [comment]
first approach failed. waiting to see if the CI is happy with the second one.

**Comment by neolit123** [comment]
i've been waiting in line for Stefan's PR to get checked first. o_o

**Comment by sfuchs79** [comment]
I'm sooo sorry ;-)

**Comment by sfuchs79** [comment]
BTW Lubomir, will this here also fix the following issue I saw a few minutes before:
If I locally rebuild the subsurface.exe by not calling the mxe-based-build.sh again but by going into the .../win32/subsurface directory and just type "make" this currently fails because in this case objcopy is not found.

**Comment by neolit123** [comment]
> BTW Lubomir, will this here also fix the following issue I saw a few minutes before:

i think so, yes. but also, it will not generate the separate `.debug` file.

**Comment by neolit123** [comment]
alright, this one should be good to go. waiting on the CI and merging it.

**Comment by neolit123** [comment]
@sfuchs79 you can give this one a try.

**Pull request merged**
