### PR TITLE
[WIP] Final and annoying part of the statistics: the UI

### PR DESCRIPTION
**Pull request by bstoeger**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [x] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

This is the third and last installment of the statistics PR. Here comes the annoying part: the UI.

Reversing the hierarchy: binning determines chart makes things much more complicated. Before, every combination of variables gave a valid chart. This is no longer the case and makes things quite hairy.

Therefore, please do not merge yet - it's probably easy to get to inconsistent states or even crash the thing. I'll have to audit and rewrite this with a fresh mind.

That said, please test as much as you can. @dirkhh: Feel free to force push over the icons and other UI problems. I will try to make this mergeable tomorrow.

### Related issues:

Last part of #3052.

### Release note:

Will do.
### Documentation change:

Probably still needs some stabilization.
### Mentions:

@willemferguson: please comment on the new chart-selection scheme.

### CODE REVIEW

**Review by dirkhh — COMMENTED** [review]
8e56086e0cd099eb1b351066a51239733781321c
This wasn't nearly as painful as I feared.
I can't wait to see @willemferguson 's comments on the new combo box / chart selection logic. I can see the arguments for both thought processes - and yes, the code for this one is a lot more gnarly.
Random comments:
- one thing that puzzles me is why `Count` turned into `none` for the `Data` variable. That seems strange.
- there are other things that feel... off. For example if I use Date as my base and chart the Max.Depth. Binning and Operations are kinda 'orthogonal' you can do either one or the other. That felt weird. And the `sum` operation for Max.Depth is, err, not exactly useful?
- in a stacked horizontal charts the labels in the histogram provide the absolute number and percentage with just a space between them - that looks bad, you need a `/` or something between the values

From the code standpoint I didn't find anything that I disagree merging with, but mostly I need to do more testing to figure out if there is anything in the chart logic that I can get to fail. In my half hour of testing it all seemed to make sense.

You asked me to help with the UI especially the icons...
- the icons are ugly, but I can't put my finger on _why_ they are ugly. I'm about to push a change that at least makes them slightly rounded on the outside, which is at least somewhat better, but I want to spend some quality time with them to see if I can't make them overall more appealing
- I rather dislike the warning triangle to indicate _Undesired_ charts. There has got to be a better way - again, something I want to spend more time on tonight
Overall - remarkably well done!

**Comment by dirkhh** [comment]
Ok, added two tiny commits with marginal improvements of the UI.
I still want to replace the warning triangle with something better, but the family is asking me to stop staring at my computer, so I doubt I'll get to that tonight.

**Comment by bstoeger** [comment]
> one thing that puzzles me is why Count turned into none for the Data variable. That seems strange.

"None" better reflects the internal representation. In the future we might want to plot multiple variables and then none is a natural extension of 0, 1, 2, etc. variables

> there are other things that feel... off. For example if I use Date as my base and chart the Max.Depth. Binning and Operations are kinda 'orthogonal' you can do either one or the other.

Yes they are - if the first variable is binned, you can either have a count-based chart (binning on the second variable) or a value based chart ("operation" on the second variable). Extending to multiple variables will be fun!

> And the sum operation for Max.Depth is, err, not exactly useful?

Yes - it's not really useful. It's one of those "fun" options: In total I dove with buddy XY down to the Mariana trench.

> in a stacked horizontal charts the labels in the histogram provide the absolute number and percentage with just a space between them - that looks bad, you need a / or something between the values

Originally, the percentage was in parentheses, but that took too much space in vertical bar chart. I'll re-add this for horizontal bar charts.

> From the code standpoint I didn't find anything that I disagree merging with, but mostly I need to do more testing to figure out if there is anything in the chart logic that I can get to fail. In my half hour of testing it all seemed to make sense.

I improved the code somewhat. Feel free to merge if you are fine with it.

**Comment by bstoeger** [comment]
> in a stacked horizontal charts the labels in the histogram provide the absolute number and percentage with just a space between them - that looks bad, you need a / or something between the values

See last commit. Feel free to adapt to your tastes.

**Comment by dirkhh** [comment]
I am surprised that the iOS build completed - you didn't add the `roundrectitem.cpp` to the `Subsurface-mobile.pro` file and the Android build stumbled over that:
```
armeabi-v7a/moc_divetooltipitem.o:moc_divetooltipitem.cpp:vtable for ToolTipItem: error: undefined reference to 'RoundRectItem::paint(QPainter*, QStyleOptionGraphicsItem const*, QWidget*)'
```
Now a good question for me to look into later (have an appointment this morning) is why we are building the tooltip on Android... but at least for now this prevents me from merging this

**Comment by dirkhh** [comment]
This is looking really good. I've been playing with getting this to actually run on the various platforms (i.e., including all the necessary dependencies to not only build it but to run it) which has been slowing me down since we support WAY too many platforms for a single person to maintain... but yeah, I think I'll merge this today.

One issue that I noticed is that sometimes labels aren't printed in histograms. For example the default date/none chart that opens... no labels in the bars.

But that's all stuff we can fix after merging.

It will take me a little longer to get all the build stuff right (and I bet even when I think I'm done I really won't be), so if you have stuff in your tree, feel free to still push. Or if you are done for today, please let me know so I don't wait for you :-)

**Comment by dirkhh** [comment]
> One issue that I noticed is that sometimes labels aren't printed in histograms. For example the default date/none chart that opens... no labels in the bars.

I figured this one out... The width of the bars was so that single digit percentages fit, but double digit percentages didn't fit. That was subtle and unexpected - but not necessarily wrong. So I'd argue it's not a bug, it's just a well designed feature that ends up behaving in somewhat unexpected ways :-)

**Comment by dirkhh** [comment]
did some rewording of commit messages, added a changelog, did a last minute change to rename the old statistics tab to be 'Summary'... will merge my local branch

**Comment by dirkhh** [comment]
A huge, huge DANKE to both of you, @willemferguson and @bstoeger 

I just announced this on the mailing list, just in time for the folks in the "near UTC" time zones to head to bed.
But at least it's in people's hand starting Monday. We'll see how many actually provide feedback...

**Pull request closed without merging**
