### PR TITLE
Quick-fix for #1002

### PR DESCRIPTION
**Pull request by bstoeger**
### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

This is a quick-fix for #1002. It also does a work-around should an invalid device name have found its way into the preferences (as happened in one of my tests). I'm planning to do a more appropriate fix when I'm back (always initialize the BT selection dialog).

### CODE REVIEW

**Comment by janmulder** [comment]
Tested and lgtm. 

A little unsure about the announcement of "always initialize the BT selection dialog". Initialize looks fine to me, but the use case of not accessing this dialog and using previous data from settings (that worked) should be possible.

**Comment by bstoeger** [comment]
Initializing the dialog object doesn't mean showing the dialog. Let's discuss this when I'm back from holidays (5th of Jan.)

Still amazed how I managed to not hit this during testing. :(

**Comment by janmulder** [comment]
Don't worry Berthold, things like this happen. Happy holidays. And thanks for the quick fix. I will wait for Dirk to give his opinion on merging. At least we can point users now to this issue and PR when they hit downloading issues.

**Comment by dirkhh** [comment]
Actually, if this fixes an issue that people run into, we should consider doing a 4.7.7
On the flip side, this had already been the case with 4.7.5 so I don't think a lot of people have run into it (which kinda surprises me - but then, as we've learned there aren't a ton of BT dive computers...)

**Comment by janmulder** [comment]
It is a little weird problem. A user that never accesses the select BT device, still has its earlier plain address sitting there (from the preferences), and than you do not hit this issue. That is one other reason that users did not complain already. I know at least 3 Shearwater BT/BLE users, and they did not notice this bug.

**Pull request merged**
