### PR TITLE
Cleanups concerning the pressure values on the profile

### PR DESCRIPTION
**Pull request by bstoeger**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [x] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

These are a few cleanups in preparation of making the whole thing more dynamic (see #2140). That in turn is preparation for undo of equipment editing actions.

Usage of inline functions makes this somewhat more verbose than the macros before. Sadly, C doesn't know references that can be returned from functions, so a setter function is introduced.

### CODE REVIEW

**Comment by dirkhh** [comment]
Amy idea why the LGTM build would fail?
Also, I assume this is post-4.9, just like #2140 ?

**Comment by bstoeger** [comment]
I don't understand, no - it warns about an undefined inlined function which would mean that the proper include-file was not included. By why then does Travis pass...?

**Comment by dirkhh** [comment]
Is it possible that LGTM builds with a combination of settings that we don't test on Travis? I need to stare a bit more at that build output


-- 
From my phone

**Comment by bstoeger** [comment]
Seems like making the inline functions `static inline` did the trick. Is this a C thing? I don't think I ever had to do this in C++. We also have a number of non-static inline functions in the C++ part.

It appears backward to me: wouldn't `static inline` mean that if the compiler decides to not inline then the function is repeated for every translation unit? I always thought that inline means that the compiler is free to inline or not but the linker will not complain about multiple definitions. Weird.

**Comment by bstoeger** [comment]
Well, according to a quick Internet search, it appears that `inline` has indeed different meanings in C and C++. Good to know.

**Review by dirkhh — APPROVED** [review]
These all look good

**Pull request merged**
