### PR TITLE
Nordic uart ble service

### PR DESCRIPTION
**Pull request by torvalds**
### Describe the pull request:

- [ ] Bug fix
- [x] Functional change
- [x] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

This just adds a special case for the Nordic UART service name, which should make us pick it preferentially over other random services.

That should fix the confusion we have with the complicated services of the Cressi BLE dongle.

### CODE REVIEW

**Comment by dirkhh** [comment]
Your pull request is relative to your previously merged and rebased branch, so the commit 75ad9e5 shows up in this PR, even though it's the same as https://github.com/Subsurface-divelog/subsurface/commit/6df46a25a38fab167b0cd378c2ee563b6ea8f65a in master...
I can of course easily fix this when merging manually.

**Comment by dirkhh** [comment]
I assume that we are waiting to hear back from Martin before merging this, correct?

**Comment by pausad** [comment]
Tråkigt att du inte svarar. Hoppas du inte är död. Jag är inte död iallafall. Hursomhelst kommer BankID bli sams med Linux Operativsystem ?

En del av dem använder https://www.meetup.com/

is it true that its written in:
C, assembler

Nu när man är inlåst ska man skratta eller gråta eller få ngn sjukdom?


or just c

**Comment by dirkhh** [comment]
The test failed as the protocol appears to be different for BLE. We are waiting for the necessary information to be able to implement this - as such, I have no idea when this will be resolved. This PR by itself doesn't help.

**Comment by pausad** [comment]
Fler sånna människor finns ju överallt typ vården o polisen.

**Review by pausad — COMMENTED** [review]
Is this for bluetooth ?

**Comment by dirkhh** [comment]
This is outdated

**Pull request closed without merging**
